#pragma once
#include "syscall/win/Type.hpp"

namespace cmn::syscall::win
{
    NTSTATUS nt_accept_connect_port(PHANDLE _portHandle, PVOID _portContext, PPORT_MESSAGE _connectionRequest, BOOLEAN _acceptConnection, PPORT_VIEW _serverView, PREMOTE_PORT_VIEW _clientView);
    NTSTATUS nt_access_check(PSECURITY_DESCRIPTOR _securityDescriptor, HANDLE _clientToken, ACCESS_MASK _desiredAccess, PGENERIC_MAPPING _genericMapping, PPRIVILEGE_SET _privilegeSet, PULONG _privilegeSetLength, PACCESS_MASK _grantedAccess, PNTSTATUS _accessStatus);
    NTSTATUS nt_access_check_and_audit_alarm(PCUNICODE_STRING _subsystemName, PVOID _handleId, PCUNICODE_STRING _objectTypeName, PCUNICODE_STRING _objectName, PSECURITY_DESCRIPTOR _securityDescriptor, ACCESS_MASK _desiredAccess, PGENERIC_MAPPING _genericMapping, BOOLEAN _objectCreation, PACCESS_MASK _grantedAccess, PNTSTATUS _accessStatus, PBOOLEAN _generateOnClose);
    NTSTATUS nt_access_check_by_type(PSECURITY_DESCRIPTOR _securityDescriptor, PSID _principalSelfSid, HANDLE _clientToken, ACCESS_MASK _desiredAccess, POBJECT_TYPE_LIST _objectTypeList, ULONG _objectTypeListLength, PGENERIC_MAPPING _genericMapping, PPRIVILEGE_SET _privilegeSet, PULONG _privilegeSetLength, PACCESS_MASK _grantedAccess, PNTSTATUS _accessStatus);
    NTSTATUS nt_access_check_by_type_and_audit_alarm(PCUNICODE_STRING _subsystemName, PVOID _handleId, PCUNICODE_STRING _objectTypeName, PCUNICODE_STRING _objectName, PSECURITY_DESCRIPTOR _securityDescriptor, PSID _principalSelfSid, ACCESS_MASK _desiredAccess, AUDIT_EVENT_TYPE _auditType, ULONG _flags, POBJECT_TYPE_LIST _objectTypeList, ULONG _objectTypeListLength, PGENERIC_MAPPING _genericMapping, BOOLEAN _objectCreation, PACCESS_MASK _grantedAccess, PNTSTATUS _accessStatus, PBOOLEAN _generateOnClose);
    NTSTATUS nt_access_check_by_type_result_list(PSECURITY_DESCRIPTOR _securityDescriptor, PSID _principalSelfSid, HANDLE _clientToken, ACCESS_MASK _desiredAccess, POBJECT_TYPE_LIST _objectTypeList, ULONG _objectTypeListLength, PGENERIC_MAPPING _genericMapping, PPRIVILEGE_SET _privilegeSet, PULONG _privilegeSetLength, PACCESS_MASK _grantedAccess, PNTSTATUS _accessStatus);
    NTSTATUS nt_access_check_by_type_result_list_and_audit_alarm(PCUNICODE_STRING _subsystemName, PVOID _handleId, PCUNICODE_STRING _objectTypeName, PCUNICODE_STRING _objectName, PSECURITY_DESCRIPTOR _securityDescriptor, PSID _principalSelfSid, ACCESS_MASK _desiredAccess, AUDIT_EVENT_TYPE _auditType, ULONG _flags, POBJECT_TYPE_LIST _objectTypeList, ULONG _objectTypeListLength, PGENERIC_MAPPING _genericMapping, BOOLEAN _objectCreation, PACCESS_MASK _grantedAccess, PNTSTATUS _accessStatus, PBOOLEAN _generateOnClose);
    NTSTATUS nt_access_check_by_type_result_list_and_audit_alarm_by_handle(PCUNICODE_STRING _subsystemName, PVOID _handleId, HANDLE _clientToken, PCUNICODE_STRING _objectTypeName, PCUNICODE_STRING _objectName, PSECURITY_DESCRIPTOR _securityDescriptor, PSID _principalSelfSid, ACCESS_MASK _desiredAccess, AUDIT_EVENT_TYPE _auditType, ULONG _flags, POBJECT_TYPE_LIST _objectTypeList, ULONG _objectTypeListLength, PGENERIC_MAPPING _genericMapping, BOOLEAN _objectCreation, PACCESS_MASK _grantedAccess, PNTSTATUS _accessStatus, PBOOLEAN _generateOnClose);
    NTSTATUS nt_acquire_cross_vm_mutant(HANDLE _crossVmMutant, PLARGE_INTEGER _timeout);
    NTSTATUS nt_acquire_process_activity_reference(PHANDLE _activityReferenceHandle, HANDLE _parentProcessHandle, ULONG _processActivityType);
    NTSTATUS nt_add_atom(PCWSTR _atomName, ULONG _length, PRTL_ATOM _atom);
    NTSTATUS nt_add_atom_ex(PCWSTR _atomName, ULONG _length, PRTL_ATOM _atom, ULONG _flags);
    NTSTATUS nt_add_boot_entry(PBOOT_ENTRY _bootEntry, PULONG _id);
    NTSTATUS nt_add_driver_entry(PEFI_DRIVER_ENTRY _driverEntry, PULONG _id);
    NTSTATUS nt_adjust_groups_token(HANDLE _tokenHandle, BOOLEAN _resetToDefault, PTOKEN_GROUPS _newState, ULONG _bufferLength, PTOKEN_GROUPS _previousState, PULONG _returnLength);
    NTSTATUS nt_adjust_privileges_token(HANDLE _tokenHandle, BOOLEAN _disableAllPrivileges, PTOKEN_PRIVILEGES _newState, ULONG _bufferLength, PTOKEN_PRIVILEGES _previousState, PULONG _returnLength);
    NTSTATUS nt_adjust_token_claims_and_device_groups(HANDLE _tokenHandle, BOOLEAN _userResetToDefault, BOOLEAN _deviceResetToDefault, BOOLEAN _deviceGroupsResetToDefault, PTOKEN_SECURITY_ATTRIBUTES_INFORMATION _newUserState, PTOKEN_SECURITY_ATTRIBUTES_INFORMATION _newDeviceState, PTOKEN_GROUPS _newDeviceGroupsState, ULONG _userBufferLength, PTOKEN_SECURITY_ATTRIBUTES_INFORMATION _previousUserState, ULONG _deviceBufferLength, PTOKEN_SECURITY_ATTRIBUTES_INFORMATION _previousDeviceState, ULONG _deviceGroupsBufferLength, PTOKEN_GROUPS _previousDeviceGroups, PULONG _userReturnLength, PULONG _deviceReturnLength, PULONG _deviceGroupsReturnBufferLength);
    NTSTATUS nt_alert_multiple_thread_by_thread_id(PHANDLE _multipleThreadId, ULONG _count, PPS_ALERT_THREAD_EXTENDED_PARAMETER _extendedParameters, ULONG _extendedParameterCount);
    NTSTATUS nt_alert_resume_thread(HANDLE _threadHandle, PULONG _previousSuspendCount);
    NTSTATUS nt_alert_thread(HANDLE _threadHandle);
    NTSTATUS nt_alert_thread_by_thread_id(HANDLE _threadId);
    NTSTATUS nt_alert_thread_by_thread_id_ex(HANDLE _threadId, PRTL_SRWLOCK _lock);
    NTSTATUS nt_allocate_locally_unique_id(PLUID _luid);
    NTSTATUS nt_allocate_reserve_object(PHANDLE _memoryReserveHandle, PCOBJECT_ATTRIBUTES _objectAttributes, MEMORY_RESERVE_TYPE _type);
    NTSTATUS nt_allocate_user_physical_pages(HANDLE _processHandle, PSIZE_T _numberOfPages, PULONG_PTR _userPfnArray);
    NTSTATUS nt_allocate_user_physical_pages_ex(HANDLE _processHandle, PULONG_PTR _numberOfPages, PULONG_PTR _userPfnArray, PMEM_EXTENDED_PARAMETER _extendedParameters, ULONG _extendedParameterCount);
    NTSTATUS nt_allocate_uuids(PULARGE_INTEGER _time, PULONG _range, PULONG _sequence, PCHAR _seed);
    NTSTATUS nt_allocate_virtual_memory(HANDLE _processHandle, PVOID* _baseAddress, ULONG_PTR _zeroBits, PSIZE_T _regionSize, ULONG _allocationType, ULONG _pageProtection);
    NTSTATUS nt_allocate_virtual_memory_ex(HANDLE _processHandle, PVOID* _baseAddress, PSIZE_T _regionSize, ULONG _allocationType, ULONG _pageProtection, PMEM_EXTENDED_PARAMETER _extendedParameters, ULONG _extendedParameterCount);
    NTSTATUS nt_alpc_accept_connect_port(PHANDLE _portHandle, HANDLE _connectionPortHandle, ULONG _flags, POBJECT_ATTRIBUTES _objectAttributes, PALPC_PORT_ATTRIBUTES _portAttributes, PVOID _portContext, PPORT_MESSAGE _connectionRequest, PALPC_MESSAGE_ATTRIBUTES _connectionMessageAttributes, BOOLEAN _acceptConnection);
    NTSTATUS nt_alpc_cancel_message(HANDLE _portHandle, ULONG _flags, PALPC_CONTEXT_ATTR _messageContext);
    NTSTATUS nt_alpc_connect_port(PHANDLE _portHandle, PCUNICODE_STRING _portName, POBJECT_ATTRIBUTES _objectAttributes, PALPC_PORT_ATTRIBUTES _portAttributes, ULONG _flags, PSID _requiredServerSid, PPORT_MESSAGE _connectionMessage, PSIZE_T _bufferLength, PALPC_MESSAGE_ATTRIBUTES _outMessageAttributes, PALPC_MESSAGE_ATTRIBUTES _inMessageAttributes, PLARGE_INTEGER _timeout);
    NTSTATUS nt_alpc_connect_port_ex(PHANDLE _portHandle, POBJECT_ATTRIBUTES _connectionPortObjectAttributes, POBJECT_ATTRIBUTES _clientPortObjectAttributes, PALPC_PORT_ATTRIBUTES _portAttributes, ULONG _flags, PSECURITY_DESCRIPTOR _serverSecurityRequirements, PPORT_MESSAGE _connectionMessage, PSIZE_T _bufferLength, PALPC_MESSAGE_ATTRIBUTES _outMessageAttributes, PALPC_MESSAGE_ATTRIBUTES _inMessageAttributes, PLARGE_INTEGER _timeout);
    NTSTATUS nt_alpc_create_port(PHANDLE _portHandle, POBJECT_ATTRIBUTES _objectAttributes, PALPC_PORT_ATTRIBUTES _portAttributes);
    NTSTATUS nt_alpc_create_port_section(HANDLE _portHandle, ULONG _flags, HANDLE _sectionHandle, SIZE_T _sectionSize, PALPC_HANDLE _alpcSectionHandle, PSIZE_T _actualSectionSize);
    NTSTATUS nt_alpc_create_resource_reserve(HANDLE _portHandle, ULONG _flags, SIZE_T _messageSize, PULONG _resourceId);
    NTSTATUS nt_alpc_create_section_view(HANDLE _portHandle, ULONG _flags, PALPC_DATA_VIEW_ATTR _viewAttributes);
    NTSTATUS nt_alpc_create_security_context(HANDLE _portHandle, ULONG _flags, PALPC_SECURITY_ATTR _securityAttribute);
    NTSTATUS nt_alpc_delete_port_section(HANDLE _portHandle, ULONG _flags, ALPC_HANDLE _sectionHandle);
    NTSTATUS nt_alpc_delete_resource_reserve(HANDLE _portHandle, ULONG _flags, ULONG _resourceId);
    NTSTATUS nt_alpc_delete_section_view(HANDLE _portHandle, ULONG _flags, PVOID _viewBase);
    NTSTATUS nt_alpc_delete_security_context(HANDLE _portHandle, ULONG _flags, ALPC_HANDLE _contextHandle);
    NTSTATUS nt_alpc_disconnect_port(HANDLE _portHandle, ULONG _flags);
    NTSTATUS nt_alpc_impersonate_client_container_of_port(HANDLE _portHandle, PPORT_MESSAGE _message, ULONG _flags);
    NTSTATUS nt_alpc_impersonate_client_of_port(HANDLE _portHandle, PPORT_MESSAGE _message, PVOID _flags);
    NTSTATUS nt_alpc_open_sender_process(PHANDLE _processHandle, HANDLE _portHandle, PPORT_MESSAGE _portMessage, ULONG _flags, ACCESS_MASK _desiredAccess, POBJECT_ATTRIBUTES _objectAttributes);
    NTSTATUS nt_alpc_open_sender_thread(PHANDLE _threadHandle, HANDLE _portHandle, PPORT_MESSAGE _portMessage, ULONG _flags, ACCESS_MASK _desiredAccess, POBJECT_ATTRIBUTES _objectAttributes);
    NTSTATUS nt_alpc_query_information(HANDLE _portHandle, ALPC_PORT_INFORMATION_CLASS _portInformationClass, PVOID _portInformation, ULONG _length, PULONG _returnLength);
    NTSTATUS nt_alpc_query_information_message(HANDLE _portHandle, PPORT_MESSAGE _portMessage, ALPC_MESSAGE_INFORMATION_CLASS _messageInformationClass, PVOID _messageInformation, ULONG _length, PULONG _returnLength);
    NTSTATUS nt_alpc_revoke_security_context(HANDLE _portHandle, ULONG _flags, ALPC_HANDLE _contextHandle);
    NTSTATUS nt_alpc_send_wait_receive_port(HANDLE _portHandle, ULONG _flags, PPORT_MESSAGE _sendMessageW, PALPC_MESSAGE_ATTRIBUTES _sendMessageAttributes, PPORT_MESSAGE _receiveMessage, PSIZE_T _bufferLength, PALPC_MESSAGE_ATTRIBUTES _receiveMessageAttributes, PLARGE_INTEGER _timeout);
    NTSTATUS nt_alpc_set_information(HANDLE _portHandle, ALPC_PORT_INFORMATION_CLASS _portInformationClass, PVOID _portInformation, ULONG _length);
    NTSTATUS nt_apphelp_cache_control(AHC_SERVICE_CLASS _serviceClass, PVOID _serviceContext);
    NTSTATUS nt_are_mapped_files_the_same(PVOID _file1MappedAsAnImage, PVOID _file2MappedAsFile);
    NTSTATUS nt_assign_process_to_job_object(HANDLE _jobHandle, HANDLE _processHandle);
    NTSTATUS nt_associate_wait_completion_packet(HANDLE _waitCompletionPacketHandle, HANDLE _ioCompletionHandle, HANDLE _targetObjectHandle, PVOID _keyContext, PVOID _apcContext, NTSTATUS _ioStatus, ULONG_PTR _ioStatusInformation, PBOOLEAN _alreadySignaled);
    NTSTATUS nt_call_enclave(PENCLAVE_ROUTINE _routine, PVOID _reserved, ULONG _flags, PVOID* _routineParamReturn);
    NTSTATUS nt_callback_return(PVOID _outputBuffer, ULONG _outputLength, NTSTATUS _status);
    NTSTATUS nt_cancel_io_file(HANDLE _fileHandle, PIO_STATUS_BLOCK _ioStatusBlock);
    NTSTATUS nt_cancel_io_file_ex(HANDLE _fileHandle, PIO_STATUS_BLOCK _ioRequestToCancel, PIO_STATUS_BLOCK _ioStatusBlock);
    NTSTATUS nt_cancel_synchronous_io_file(HANDLE _threadHandle, PIO_STATUS_BLOCK _ioRequestToCancel, PIO_STATUS_BLOCK _ioStatusBlock);
    NTSTATUS nt_cancel_timer(HANDLE _timerHandle, PBOOLEAN _currentState);
    NTSTATUS nt_cancel_timer2(HANDLE _timerHandle, PT2_CANCEL_PARAMETERS _parameters);
    NTSTATUS nt_cancel_wait_completion_packet(HANDLE _waitCompletionPacketHandle, BOOLEAN _removeSignaledPacket);
    NTSTATUS nt_change_process_state(HANDLE _processStateChangeHandle, HANDLE _processHandle, PROCESS_STATE_CHANGE_TYPE _stateChangeType, PVOID _extendedInformation, SIZE_T _extendedInformationLength, ULONG _reserved);
    NTSTATUS nt_change_thread_state(HANDLE _threadStateChangeHandle, HANDLE _threadHandle, THREAD_STATE_CHANGE_TYPE _stateChangeType, PVOID _extendedInformation, SIZE_T _extendedInformationLength, ULONG _reserved);
    NTSTATUS nt_clear_event(HANDLE _eventHandle);
    NTSTATUS nt_close(HANDLE _handle);
    NTSTATUS nt_close_object_audit_alarm(PCUNICODE_STRING _subsystemName, PVOID _handleId, BOOLEAN _generateOnClose);
    NTSTATUS nt_commit_complete(HANDLE _enlistmentHandle, PLARGE_INTEGER _tmVirtualClock);
    NTSTATUS nt_commit_enlistment(HANDLE _enlistmentHandle, PLARGE_INTEGER _tmVirtualClock);
    NTSTATUS nt_commit_registry_transaction(HANDLE _registryTransactionHandle, ULONG _flags);
    NTSTATUS nt_commit_transaction(HANDLE _transactionHandle, BOOLEAN _wait);
    NTSTATUS nt_compact_keys(ULONG _count, HANDLE _keyArray[]);
    NTSTATUS nt_compare_objects(HANDLE _firstObjectHandle, HANDLE _secondObjectHandle);
    NTSTATUS nt_compare_signing_levels(SE_SIGNING_LEVEL _firstSigningLevel, SE_SIGNING_LEVEL _secondSigningLevel);
    NTSTATUS nt_compare_tokens(HANDLE _firstTokenHandle, HANDLE _secondTokenHandle, PBOOLEAN _equal);
    NTSTATUS nt_complete_connect_port(HANDLE _portHandle);
    NTSTATUS nt_compress_key(HANDLE _keyHandle);
    NTSTATUS nt_connect_port(PHANDLE _portHandle, PCUNICODE_STRING _portName, PSECURITY_QUALITY_OF_SERVICE _securityQos, PPORT_VIEW _clientView, PREMOTE_PORT_VIEW _serverView, PULONG _maxMessageLength, PVOID _connectionInformation, PULONG _connectionInformationLength);
    NTSTATUS nt_continue(PCONTEXT _contextRecord, BOOLEAN _testAlert);
    NTSTATUS nt_continue_ex(PCONTEXT _contextRecord, PVOID _continueArgument);
    NTSTATUS nt_convert_between_auxiliary_counter_and_performance_counter(BOOLEAN _convertAuxiliaryToPerformanceCounter, PULONG64 _performanceOrAuxiliaryCounterValue, PULONG64 _convertedValue, PULONG64 _conversionError);
    NTSTATUS nt_copy_file_chunk(HANDLE _sourceHandle, HANDLE _destinationHandle, HANDLE _eventHandle, PIO_STATUS_BLOCK _ioStatusBlock, ULONG _length, PLARGE_INTEGER _sourceOffset, PLARGE_INTEGER _destOffset, PULONG _sourceKey, PULONG _destKey, ULONG _flags);
    NTSTATUS nt_create_cpu_partition(PHANDLE _cpuPartitionHandle, ACCESS_MASK _desiredAccess, POBJECT_ATTRIBUTES _objectAttributes);
    NTSTATUS nt_create_cross_vm_event(PHANDLE _crossVmEvent, ACCESS_MASK _desiredAccess, POBJECT_ATTRIBUTES _objectAttributes, ULONG _crossVmEventFlags, LPCGUID _vMID, LPCGUID _serviceID);
    NTSTATUS nt_create_cross_vm_mutant(PHANDLE _eventHandle, ACCESS_MASK _desiredAccess, POBJECT_ATTRIBUTES _objectAttributes, ULONG _crossVmEventFlags, LPCGUID _vMID, LPCGUID _serviceID);
    NTSTATUS nt_create_debug_object(PHANDLE _debugObjectHandle, ACCESS_MASK _desiredAccess, POBJECT_ATTRIBUTES _objectAttributes, ULONG _flags);
    NTSTATUS nt_create_directory_object(PHANDLE _directoryHandle, ACCESS_MASK _desiredAccess, POBJECT_ATTRIBUTES _objectAttributes);
    NTSTATUS nt_create_directory_object_ex(PHANDLE _directoryHandle, ACCESS_MASK _desiredAccess, POBJECT_ATTRIBUTES _objectAttributes, HANDLE _shadowDirectoryHandle, ULONG _flags);
    NTSTATUS nt_create_enclave(HANDLE _processHandle, PVOID* _baseAddress, ULONG_PTR _zeroBits, SIZE_T _size, SIZE_T _initialCommitment, ULONG _enclaveType, PVOID _enclaveInformation, ULONG _enclaveInformationLength, PULONG _enclaveError);
    NTSTATUS nt_create_enlistment(PHANDLE _enlistmentHandle, ACCESS_MASK _desiredAccess, HANDLE _resourceManagerHandle, HANDLE _transactionHandle, POBJECT_ATTRIBUTES _objectAttributes, ULONG _createOptions, NOTIFICATION_MASK _notificationMask, PVOID _enlistmentKey);
    NTSTATUS nt_create_event(PHANDLE _eventHandle, ACCESS_MASK _desiredAccess, POBJECT_ATTRIBUTES _objectAttributes, EVENT_TYPE _eventType, BOOLEAN _initialState);
    NTSTATUS nt_create_event_pair(PHANDLE _eventPairHandle, ACCESS_MASK _desiredAccess, PCOBJECT_ATTRIBUTES _objectAttributes);
    NTSTATUS nt_create_file(PHANDLE _fileHandle, ACCESS_MASK _desiredAccess, PCOBJECT_ATTRIBUTES _objectAttributes, PIO_STATUS_BLOCK _ioStatusBlock, PLARGE_INTEGER _allocationSize, ULONG _fileAttributes, ULONG _shareAccess, ULONG _createDisposition, ULONG _createOptions, PVOID _eaBuffer, ULONG _eaLength);
    NTSTATUS nt_create_i_r_timer(PHANDLE _timerHandle, PULONG _timerId, ACCESS_MASK _desiredAccess);
    NTSTATUS nt_create_io_completion(PHANDLE _ioCompletionHandle, ACCESS_MASK _desiredAccess, PCOBJECT_ATTRIBUTES _objectAttributes, ULONG _numberOfConcurrentThreads);
    NTSTATUS nt_create_io_ring(PHANDLE _ioRingHandle, ULONG _createParametersLength, PVOID _createParameters, ULONG _outputParametersLength, PVOID _outputParameters);
    NTSTATUS nt_create_job_object(PHANDLE _jobHandle, ACCESS_MASK _desiredAccess, PCOBJECT_ATTRIBUTES _objectAttributes);
    NTSTATUS nt_create_job_set(ULONG _numJob, PJOB_SET_ARRAY _userJobSet, ULONG _flags);
    NTSTATUS nt_create_key(PHANDLE _keyHandle, ACCESS_MASK _desiredAccess, POBJECT_ATTRIBUTES _objectAttributes, ULONG _titleIndex, PCUNICODE_STRING _class, ULONG _createOptions, PULONG _disposition);
    NTSTATUS nt_create_key_transacted(PHANDLE _keyHandle, ACCESS_MASK _desiredAccess, POBJECT_ATTRIBUTES _objectAttributes, ULONG _titleIndex, PCUNICODE_STRING _class, ULONG _createOptions, HANDLE _transactionHandle, PULONG _disposition);
    NTSTATUS nt_create_keyed_event(PHANDLE _keyedEventHandle, ACCESS_MASK _desiredAccess, PCOBJECT_ATTRIBUTES _objectAttributes, ULONG _flags);
    NTSTATUS nt_create_low_box_token(PHANDLE _tokenHandle, HANDLE _existingTokenHandle, ACCESS_MASK _desiredAccess, POBJECT_ATTRIBUTES _objectAttributes, PSID _packageSid, ULONG _capabilityCount, PSID_AND_ATTRIBUTES _capabilities, ULONG _handleCount, HANDLE* _handles);
    NTSTATUS nt_create_mailslot_file(PHANDLE _fileHandle, ACCESS_MASK _desiredAccess, PCOBJECT_ATTRIBUTES _objectAttributes, PIO_STATUS_BLOCK _ioStatusBlock, ULONG _createOptions, ULONG _mailslotQuota, ULONG _maximumMessageSize, PLARGE_INTEGER _readTimeout);
    NTSTATUS nt_create_mutant(PHANDLE _mutantHandle, ACCESS_MASK _desiredAccess, PCOBJECT_ATTRIBUTES _objectAttributes, BOOLEAN _initialOwner);
    NTSTATUS nt_create_named_pipe_file(PHANDLE _fileHandle, ACCESS_MASK _desiredAccess, PCOBJECT_ATTRIBUTES _objectAttributes, PIO_STATUS_BLOCK _ioStatusBlock, ULONG _shareAccess, ULONG _createDisposition, ULONG _createOptions, ULONG _namedPipeType, ULONG _readMode, ULONG _completionMode, ULONG _maximumInstances, ULONG _inboundQuota, ULONG _outboundQuota, PLARGE_INTEGER _defaultTimeout);
    NTSTATUS nt_create_paging_file(PCUNICODE_STRING _pageFileName, PLARGE_INTEGER _minimumSize, PLARGE_INTEGER _maximumSize, ULONG _priority);
    NTSTATUS nt_create_partition(HANDLE _parentPartitionHandle, PHANDLE _partitionHandle, ACCESS_MASK _desiredAccess, PCOBJECT_ATTRIBUTES _objectAttributes);
    NTSTATUS nt_create_port(PHANDLE _portHandle, POBJECT_ATTRIBUTES _objectAttributes, ULONG _maxConnectionInfoLength, ULONG _maxMessageLength, ULONG _maxPoolUsage);
    NTSTATUS nt_create_private_namespace(PHANDLE _namespaceHandle, ACCESS_MASK _desiredAccess, POBJECT_ATTRIBUTES _objectAttributes, POBJECT_BOUNDARY_DESCRIPTOR _boundaryDescriptor);
    NTSTATUS nt_create_process(PHANDLE _processHandle, ACCESS_MASK _desiredAccess, PCOBJECT_ATTRIBUTES _objectAttributes, HANDLE _parentProcess, BOOLEAN _inheritObjectTable, HANDLE _sectionHandle, HANDLE _debugPort, HANDLE _tokenHandle);
    NTSTATUS nt_create_process_ex(PHANDLE _processHandle, ACCESS_MASK _desiredAccess, PCOBJECT_ATTRIBUTES _objectAttributes, HANDLE _parentProcess, ULONG _flags, HANDLE _sectionHandle, HANDLE _debugPort, HANDLE _tokenHandle, ULONG _reserved);
    NTSTATUS nt_create_process_state_change(PHANDLE _processStateChangeHandle, ACCESS_MASK _desiredAccess, PCOBJECT_ATTRIBUTES _objectAttributes, HANDLE _processHandle, ULONG _reserved);
    NTSTATUS nt_create_profile(PHANDLE _profileHandle, HANDLE _process, PVOID _profileBase, SIZE_T _profileSize, ULONG _bucketSize, PULONG _buffer, ULONG _bufferSize, KPROFILE_SOURCE _profileSource, KAFFINITY _affinity);
    NTSTATUS nt_create_profile_ex(PHANDLE _profileHandle, HANDLE _process, PVOID _profileBase, SIZE_T _profileSize, ULONG _bucketSize, PULONG _buffer, ULONG _bufferSize, KPROFILE_SOURCE _profileSource, USHORT _groupCount, PGROUP_AFFINITY _groupAffinity);
    NTSTATUS nt_create_registry_transaction(HANDLE* _registryTransactionHandle, ACCESS_MASK _desiredAccess, POBJECT_ATTRIBUTES _objAttributes, ULONG _createOptions);
    NTSTATUS nt_create_resource_manager(PHANDLE _resourceManagerHandle, ACCESS_MASK _desiredAccess, HANDLE _tmHandle, LPGUID _rmGuid, POBJECT_ATTRIBUTES _objectAttributes, ULONG _createOptions, PCUNICODE_STRING _description);
    NTSTATUS nt_create_section(PHANDLE _sectionHandle, ACCESS_MASK _desiredAccess, PCOBJECT_ATTRIBUTES _objectAttributes, PLARGE_INTEGER _maximumSize, ULONG _sectionPageProtection, ULONG _allocationAttributes, HANDLE _fileHandle);
    NTSTATUS nt_create_section_ex(PHANDLE _sectionHandle, ACCESS_MASK _desiredAccess, PCOBJECT_ATTRIBUTES _objectAttributes, PLARGE_INTEGER _maximumSize, ULONG _sectionPageProtection, ULONG _allocationAttributes, HANDLE _fileHandle, PMEM_EXTENDED_PARAMETER _extendedParameters, ULONG _extendedParameterCount);
    NTSTATUS nt_create_semaphore(PHANDLE _semaphoreHandle, ACCESS_MASK _desiredAccess, PCOBJECT_ATTRIBUTES _objectAttributes, LONG _initialCount, LONG _maximumCount);
    NTSTATUS nt_create_symbolic_link_object(PHANDLE _linkHandle, ACCESS_MASK _desiredAccess, POBJECT_ATTRIBUTES _objectAttributes, PCUNICODE_STRING _linkTarget);
    NTSTATUS nt_create_thread(PHANDLE _threadHandle, ACCESS_MASK _desiredAccess, PCOBJECT_ATTRIBUTES _objectAttributes, HANDLE _processHandle, PCLIENT_ID _clientId, PCONTEXT _threadContext, PINITIAL_TEB _initialTeb, BOOLEAN _createSuspended);
    NTSTATUS nt_create_thread_ex(PHANDLE _threadHandle, ACCESS_MASK _desiredAccess, PCOBJECT_ATTRIBUTES _objectAttributes, HANDLE _processHandle, PUSER_THREAD_START_ROUTINE _startRoutine, PVOID _argument, ULONG _createFlags, SIZE_T _zeroBits, SIZE_T _stackSize, SIZE_T _maximumStackSize, PPS_ATTRIBUTE_LIST _attributeList);
    NTSTATUS nt_create_thread_state_change(PHANDLE _threadStateChangeHandle, ACCESS_MASK _desiredAccess, PCOBJECT_ATTRIBUTES _objectAttributes, HANDLE _threadHandle, ULONG _reserved);
    NTSTATUS nt_create_timer(PHANDLE _timerHandle, ACCESS_MASK _desiredAccess, PCOBJECT_ATTRIBUTES _objectAttributes, TIMER_TYPE _timerType);
    NTSTATUS nt_create_timer2(PHANDLE _timerHandle, PULONG _timerId, PCOBJECT_ATTRIBUTES _objectAttributes, ULONG _attributes, ACCESS_MASK _desiredAccess);
    NTSTATUS nt_create_token(PHANDLE _tokenHandle, ACCESS_MASK _desiredAccess, POBJECT_ATTRIBUTES _objectAttributes, TOKEN_TYPE _type, PLUID _authenticationId, PLARGE_INTEGER _expirationTime, PTOKEN_USER _user, PTOKEN_GROUPS _groups, PTOKEN_PRIVILEGES _privileges, PTOKEN_OWNER _owner, PTOKEN_PRIMARY_GROUP _primaryGroup, PTOKEN_DEFAULT_DACL _defaultDacl, PTOKEN_SOURCE _source);
    NTSTATUS nt_create_token_ex(PHANDLE _tokenHandle, ACCESS_MASK _desiredAccess, POBJECT_ATTRIBUTES _objectAttributes, TOKEN_TYPE _type, PLUID _authenticationId, PLARGE_INTEGER _expirationTime, PTOKEN_USER _user, PTOKEN_GROUPS _groups, PTOKEN_PRIVILEGES _privileges, PTOKEN_SECURITY_ATTRIBUTES_INFORMATION _userAttributes, PTOKEN_SECURITY_ATTRIBUTES_INFORMATION _deviceAttributes, PTOKEN_GROUPS _deviceGroups, PTOKEN_MANDATORY_POLICY _mandatoryPolicy, PTOKEN_OWNER _owner, PTOKEN_PRIMARY_GROUP _primaryGroup, PTOKEN_DEFAULT_DACL _defaultDacl, PTOKEN_SOURCE _source);
    NTSTATUS nt_create_transaction(PHANDLE _transactionHandle, ACCESS_MASK _desiredAccess, POBJECT_ATTRIBUTES _objectAttributes, LPGUID _uow, HANDLE _tmHandle, ULONG _createOptions, ULONG _isolationLevel, ULONG _isolationFlags, PLARGE_INTEGER _timeout, PCUNICODE_STRING _description);
    NTSTATUS nt_create_transaction_manager(PHANDLE _tmHandle, ACCESS_MASK _desiredAccess, POBJECT_ATTRIBUTES _objectAttributes, PCUNICODE_STRING _logFileName, ULONG _createOptions, ULONG _commitStrength);
    NTSTATUS nt_create_user_process(PHANDLE _processHandle, PHANDLE _threadHandle, ACCESS_MASK _processDesiredAccess, ACCESS_MASK _threadDesiredAccess, PCOBJECT_ATTRIBUTES _processObjectAttributes, PCOBJECT_ATTRIBUTES _threadObjectAttributes, ULONG _processFlags, ULONG _threadFlags, PRTL_USER_PROCESS_PARAMETERS _processParameters, PPS_CREATE_INFO _createInfo, PPS_ATTRIBUTE_LIST _attributeList);
    NTSTATUS nt_create_wait_completion_packet(PHANDLE _waitCompletionPacketHandle, ACCESS_MASK _desiredAccess, PCOBJECT_ATTRIBUTES _objectAttributes);
    NTSTATUS nt_create_waitable_port(PHANDLE _portHandle, POBJECT_ATTRIBUTES _objectAttributes, ULONG _maxConnectionInfoLength, ULONG _maxMessageLength, ULONG _maxPoolUsage);
    NTSTATUS nt_create_wnf_state_name(PWNF_STATE_NAME _stateName, WNF_STATE_NAME_LIFETIME _nameLifetime, WNF_DATA_SCOPE _dataScope, BOOLEAN _persistData, PCWNF_TYPE_ID _typeId, ULONG _maximumStateSize, PSECURITY_DESCRIPTOR _securityDescriptor);
    NTSTATUS nt_create_worker_factory(PHANDLE _workerFactoryHandleReturn, ACCESS_MASK _desiredAccess, PCOBJECT_ATTRIBUTES _objectAttributes, HANDLE _completionPortHandle, HANDLE _workerProcessHandle, PVOID _startRoutine, PVOID _startParameter, ULONG _maxThreadCount, SIZE_T _stackReserve, SIZE_T _stackCommit);
    NTSTATUS nt_debug_active_process(HANDLE _processHandle, HANDLE _debugObjectHandle);
    NTSTATUS nt_debug_continue(HANDLE _debugObjectHandle, PCLIENT_ID _clientId, NTSTATUS _continueStatus);
    NTSTATUS nt_delay_execution(BOOLEAN _alertable, PLARGE_INTEGER _delayInterval);
    NTSTATUS nt_delete_atom(RTL_ATOM _atom);
    NTSTATUS nt_delete_boot_entry(ULONG _id);
    NTSTATUS nt_delete_driver_entry(ULONG _id);
    NTSTATUS nt_delete_file(PCOBJECT_ATTRIBUTES _objectAttributes);
    NTSTATUS nt_delete_key(HANDLE _keyHandle);
    NTSTATUS nt_delete_object_audit_alarm(PCUNICODE_STRING _subsystemName, PVOID _handleId, BOOLEAN _generateOnClose);
    NTSTATUS nt_delete_private_namespace(HANDLE _namespaceHandle);
    NTSTATUS nt_delete_value_key(HANDLE _keyHandle, PCUNICODE_STRING _valueName);
    NTSTATUS nt_delete_wnf_state_data(PCWNF_STATE_NAME _stateName, PCSID _explicitScope);
    NTSTATUS nt_delete_wnf_state_name(PCWNF_STATE_NAME _stateName);
    NTSTATUS nt_device_io_control_file(HANDLE _fileHandle, HANDLE _event, PIO_APC_ROUTINE _apcRoutine, PVOID _apcContext, PIO_STATUS_BLOCK _ioStatusBlock, ULONG _ioControlCode, PVOID _inputBuffer, ULONG _inputBufferLength, PVOID _outputBuffer, ULONG _outputBufferLength);
    NTSTATUS nt_direct_graphics_call(ULONG _inputBufferLength, PVOID _inputBuffer, ULONG _outputBufferLength, PVOID _outputBuffer, PULONG _returnLength);
    NTSTATUS nt_disable_last_known_good();
    NTSTATUS nt_display_string(PCUNICODE_STRING _string);
    NTSTATUS nt_draw_text(PCUNICODE_STRING _text);
    NTSTATUS nt_duplicate_object(HANDLE _sourceProcessHandle, HANDLE _sourceHandle, HANDLE _targetProcessHandle, PHANDLE _targetHandle, ACCESS_MASK _desiredAccess, ULONG _handleAttributes, ULONG _options);
    NTSTATUS nt_duplicate_token(HANDLE _existingTokenHandle, ACCESS_MASK _desiredAccess, POBJECT_ATTRIBUTES _objectAttributes, BOOLEAN _effectiveOnly, TOKEN_TYPE _type, PHANDLE _newTokenHandle);
    NTSTATUS nt_enable_last_known_good();
    NTSTATUS nt_enumerate_boot_entries(PVOID _buffer, PULONG _bufferLength);
    NTSTATUS nt_enumerate_driver_entries(PVOID _buffer, PULONG _bufferLength);
    NTSTATUS nt_enumerate_key(HANDLE _keyHandle, ULONG _index, KEY_INFORMATION_CLASS _keyInformationClass, PVOID _keyInformation, ULONG _length, PULONG _resultLength);
    NTSTATUS nt_enumerate_system_environment_values_ex(ULONG _informationClass, PVOID _buffer, PULONG _bufferLength);
    NTSTATUS nt_enumerate_transaction_object(HANDLE _rootObjectHandle, KTMOBJECT_TYPE _queryType, PKTMOBJECT_CURSOR _objectCursor, ULONG _objectCursorLength, PULONG _returnLength);
    NTSTATUS nt_enumerate_value_key(HANDLE _keyHandle, ULONG _index, KEY_VALUE_INFORMATION_CLASS _keyValueInformationClass, PVOID _keyValueInformation, ULONG _length, PULONG _resultLength);
    NTSTATUS nt_extend_section(HANDLE _sectionHandle, PLARGE_INTEGER _newSectionSize);
    NTSTATUS nt_filter_boot_option(FILTER_BOOT_OPTION_OPERATION _filterOperation, ULONG _objectType, ULONG _elementType, PVOID _data, ULONG _dataSize);
    NTSTATUS nt_filter_token(HANDLE _existingTokenHandle, ULONG _flags, PTOKEN_GROUPS _sidsToDisable, PTOKEN_PRIVILEGES _privilegesToDelete, PTOKEN_GROUPS _restrictedSids, PHANDLE _newTokenHandle);
    NTSTATUS nt_filter_token_ex(HANDLE _existingTokenHandle, ULONG _flags, PTOKEN_GROUPS _sidsToDisable, PTOKEN_PRIVILEGES _privilegesToDelete, PTOKEN_GROUPS _restrictedSids, ULONG _disableUserClaimsCount, PCUNICODE_STRING _userClaimsToDisable, ULONG _disableDeviceClaimsCount, PCUNICODE_STRING _deviceClaimsToDisable, PTOKEN_GROUPS _deviceGroupsToDisable, PTOKEN_SECURITY_ATTRIBUTES_INFORMATION _restrictedUserAttributes, PTOKEN_SECURITY_ATTRIBUTES_INFORMATION _restrictedDeviceAttributes, PTOKEN_GROUPS _restrictedDeviceGroups, PHANDLE _newTokenHandle);
    NTSTATUS nt_find_atom(PCWSTR _atomName, ULONG _length, PRTL_ATOM _atom);
    NTSTATUS nt_flush_buffers_file(HANDLE _fileHandle, PIO_STATUS_BLOCK _ioStatusBlock);
    NTSTATUS nt_flush_buffers_file_ex(HANDLE _fileHandle, ULONG _flags, PVOID _parameters, ULONG _parametersSize, PIO_STATUS_BLOCK _ioStatusBlock);
    NTSTATUS nt_flush_install_u_i_language(LANGID _installUILanguage, ULONG _setComittedFlag);
    NTSTATUS nt_flush_instruction_cache(HANDLE _processHandle, PVOID _baseAddress, SIZE_T _regionSize);
    NTSTATUS nt_flush_key(HANDLE _keyHandle);
    NTSTATUS nt_flush_process_write_buffers();
    NTSTATUS nt_flush_virtual_memory(HANDLE _processHandle, PVOID* _baseAddress, PSIZE_T _regionSize, PIO_STATUS_BLOCK _ioStatus);
    NTSTATUS nt_flush_write_buffer();
    NTSTATUS nt_free_user_physical_pages(HANDLE _processHandle, PULONG_PTR _numberOfPages, PULONG_PTR _userPfnArray);
    NTSTATUS nt_free_virtual_memory(HANDLE _processHandle, PVOID* _baseAddress, PSIZE_T _regionSize, ULONG _freeType);
    NTSTATUS nt_freeze_registry(ULONG _timeOutInSeconds);
    NTSTATUS nt_freeze_transactions(PLARGE_INTEGER _freezeTimeout, PLARGE_INTEGER _thawTimeout);
    NTSTATUS nt_fs_control_file(HANDLE _fileHandle, HANDLE _event, PIO_APC_ROUTINE _apcRoutine, PVOID _apcContext, PIO_STATUS_BLOCK _ioStatusBlock, ULONG _fsControlCode, PVOID _inputBuffer, ULONG _inputBufferLength, PVOID _outputBuffer, ULONG _outputBufferLength);
    NTSTATUS nt_get_cached_signing_level(HANDLE _file, PULONG _flags, PSE_SIGNING_LEVEL _signingLevel, PUCHAR _thumbprint, PULONG _thumbprintSize, PULONG _thumbprintAlgorithm);
    NTSTATUS nt_get_complete_wnf_state_subscription(PWNF_STATE_NAME _oldDescriptorStateName, ULONG64* _oldSubscriptionId, ULONG _oldDescriptorEventMask, ULONG _oldDescriptorStatus, PWNF_DELIVERY_DESCRIPTOR _newDeliveryDescriptor, ULONG _descriptorSize);
    NTSTATUS nt_get_context_thread(HANDLE _threadHandle, PCONTEXT _threadContext);
    ULONG nt_get_current_processor_number();
    ULONG nt_get_current_processor_number_ex(PPROCESSOR_NUMBER _processorNumber);
    NTSTATUS nt_get_device_power_state(HANDLE _device, PDEVICE_POWER_STATE _state);
    NTSTATUS nt_get_m_u_i_registry_info(ULONG _flags, PULONG _dataSize, PVOID _data);
    NTSTATUS nt_get_next_process(HANDLE _processHandle, ACCESS_MASK _desiredAccess, ULONG _handleAttributes, ULONG _flags, PHANDLE _newProcessHandle);
    NTSTATUS nt_get_next_thread(HANDLE _processHandle, HANDLE _threadHandle, ACCESS_MASK _desiredAccess, ULONG _handleAttributes, ULONG _flags, PHANDLE _newThreadHandle);
    NTSTATUS nt_get_nls_section_ptr(ULONG _sectionType, ULONG _sectionData, PVOID _contextData, PVOID* _sectionPointer, PULONG _sectionSize);
    NTSTATUS nt_get_notification_resource_manager(HANDLE _resourceManagerHandle, PTRANSACTION_NOTIFICATION _transactionNotification, ULONG _notificationLength, PLARGE_INTEGER _timeout, PULONG _returnLength, ULONG _asynchronous, ULONG_PTR _asynchronousContext);
    ULONG nt_get_tick_count();
    ULONGLONG nt_get_tick_count64();
    NTSTATUS nt_get_write_watch(HANDLE _processHandle, ULONG _flags, PVOID _baseAddress, SIZE_T _regionSize, PVOID* _userAddressArray, PULONG_PTR _entriesInUserAddressArray, PULONG _granularity);
    NTSTATUS nt_impersonate_anonymous_token(HANDLE _threadHandle);
    NTSTATUS nt_impersonate_client_of_port(HANDLE _portHandle, PPORT_MESSAGE _message);
    NTSTATUS nt_impersonate_thread(HANDLE _serverThreadHandle, HANDLE _clientThreadHandle, PSECURITY_QUALITY_OF_SERVICE _securityQos);
    NTSTATUS nt_initialize_enclave(HANDLE _processHandle, PVOID _baseAddress, PVOID _enclaveInformation, ULONG _enclaveInformationLength, PULONG _enclaveError);
    NTSTATUS nt_initialize_nls_files(PVOID* _baseAddress, PLCID _defaultLocaleId, PLARGE_INTEGER _defaultCasingTableSize, PULONG _currentNLSVersion);
    NTSTATUS nt_initialize_registry(USHORT _bootCondition);
    NTSTATUS nt_initiate_power_action(POWER_ACTION _systemAction, SYSTEM_POWER_STATE _lightestSystemState, ULONG _flags, BOOLEAN _asynchronous);
    NTSTATUS nt_is_process_in_job(HANDLE _processHandle, HANDLE _jobHandle);
    BOOLEAN nt_is_system_resume_automatic();
    NTSTATUS nt_is_u_i_language_comitted();
    NTSTATUS nt_listen_port(HANDLE _portHandle, PPORT_MESSAGE _connectionRequest);
    NTSTATUS nt_load_driver(PCUNICODE_STRING _driverServiceName);
    NTSTATUS nt_load_enclave_data(HANDLE _processHandle, PVOID _baseAddress, PVOID _buffer, SIZE_T _bufferSize, ULONG _protect, PVOID _pageInformation, ULONG _pageInformationLength, PSIZE_T _numberOfBytesWritten, PULONG _enclaveError);
    NTSTATUS nt_load_key(POBJECT_ATTRIBUTES _targetKey, POBJECT_ATTRIBUTES _sourceFile);
    NTSTATUS nt_load_key2(POBJECT_ATTRIBUTES _targetKey, POBJECT_ATTRIBUTES _sourceFile, ULONG _flags);
    NTSTATUS nt_load_key3(POBJECT_ATTRIBUTES _targetKey, POBJECT_ATTRIBUTES _sourceFile, ULONG _flags, PCM_EXTENDED_PARAMETER _extendedParameters, ULONG _extendedParameterCount, ACCESS_MASK _desiredAccess, PHANDLE _rootHandle, PVOID _reserved);
    NTSTATUS nt_load_key_ex(POBJECT_ATTRIBUTES _targetKey, POBJECT_ATTRIBUTES _sourceFile, ULONG _flags, HANDLE _trustClassKey, HANDLE _event, ACCESS_MASK _desiredAccess, PHANDLE _rootHandle, PVOID _reserved);
    NTSTATUS nt_lock_file(HANDLE _fileHandle, HANDLE _event, PIO_APC_ROUTINE _apcRoutine, PVOID _apcContext, PIO_STATUS_BLOCK _ioStatusBlock, PLARGE_INTEGER _byteOffset, PLARGE_INTEGER _length, ULONG _key, BOOLEAN _failImmediately, BOOLEAN _exclusiveLock);
    NTSTATUS nt_lock_product_activation_keys(ULONG* _pPrivateVer, ULONG* _pSafeMode);
    NTSTATUS nt_lock_registry_key(HANDLE _keyHandle);
    NTSTATUS nt_lock_virtual_memory(HANDLE _processHandle, PVOID* _baseAddress, PSIZE_T _regionSize, ULONG _mapType);
    NTSTATUS nt_make_permanent_object(HANDLE _handle);
    NTSTATUS nt_make_temporary_object(HANDLE _handle);
    NTSTATUS nt_manage_hot_patch(HOT_PATCH_INFORMATION_CLASS _hotPatchInformationClass, PVOID _hotPatchInformation, ULONG _hotPatchInformationLength, PULONG _returnLength);
    NTSTATUS nt_manage_partition(HANDLE _targetHandle, HANDLE _sourceHandle, PARTITION_INFORMATION_CLASS _partitionInformationClass, PVOID _partitionInformation, ULONG _partitionInformationLength);
    NTSTATUS nt_map_c_m_f_module(ULONG _what, ULONG _index, PULONG _cacheIndexOut, PULONG _cacheFlagsOut, PULONG _viewSizeOut, PVOID* _baseAddress);
    NTSTATUS nt_map_user_physical_pages(PVOID _virtualAddress, SIZE_T _numberOfPages, PULONG_PTR _userPfnArray);
    NTSTATUS nt_map_user_physical_pages_scatter(PVOID* _virtualAddresses, SIZE_T _numberOfPages, PULONG_PTR _userPfnArray);
    NTSTATUS nt_map_view_of_section(HANDLE _sectionHandle, HANDLE _processHandle, PVOID* _baseAddress, ULONG_PTR _zeroBits, SIZE_T _commitSize, PLARGE_INTEGER _sectionOffset, PSIZE_T _viewSize, SECTION_INHERIT _inheritDisposition, ULONG _allocationType, ULONG _pageProtection);
    NTSTATUS nt_map_view_of_section_ex(HANDLE _sectionHandle, HANDLE _processHandle, PVOID* _baseAddress, PLARGE_INTEGER _sectionOffset, PSIZE_T _viewSize, ULONG _allocationType, ULONG _pageProtection, PMEM_EXTENDED_PARAMETER _extendedParameters, ULONG _extendedParameterCount);
    NTSTATUS nt_modify_boot_entry(PBOOT_ENTRY _bootEntry);
    NTSTATUS nt_modify_driver_entry(PEFI_DRIVER_ENTRY _driverEntry);
    NTSTATUS nt_notify_change_directory_file(HANDLE _fileHandle, HANDLE _event, PIO_APC_ROUTINE _apcRoutine, PVOID _apcContext, PIO_STATUS_BLOCK _ioStatusBlock, PVOID _buffer, ULONG _length, ULONG _completionFilter, BOOLEAN _watchTree);
    NTSTATUS nt_notify_change_directory_file_ex(HANDLE _fileHandle, HANDLE _event, PIO_APC_ROUTINE _apcRoutine, PVOID _apcContext, PIO_STATUS_BLOCK _ioStatusBlock, PVOID _buffer, ULONG _length, ULONG _completionFilter, BOOLEAN _watchTree, DIRECTORY_NOTIFY_INFORMATION_CLASS _directoryNotifyInformationClass);
    NTSTATUS nt_notify_change_key(HANDLE _keyHandle, HANDLE _event, PIO_APC_ROUTINE _apcRoutine, PVOID _apcContext, PIO_STATUS_BLOCK _ioStatusBlock, ULONG _completionFilter, BOOLEAN _watchTree, PVOID _buffer, ULONG _bufferSize, BOOLEAN _asynchronous);
    NTSTATUS nt_notify_change_multiple_keys(HANDLE _masterKeyHandle, ULONG _count, OBJECT_ATTRIBUTES _subordinateObjects[], HANDLE _event, PIO_APC_ROUTINE _apcRoutine, PVOID _apcContext, PIO_STATUS_BLOCK _ioStatusBlock, ULONG _completionFilter, BOOLEAN _watchTree, PVOID _buffer, ULONG _bufferSize, BOOLEAN _asynchronous);
    NTSTATUS nt_notify_change_session(HANDLE _sessionHandle, ULONG _changeSequenceNumber, PLARGE_INTEGER _changeTimeStamp, IO_SESSION_EVENT _event, IO_SESSION_STATE _newState, IO_SESSION_STATE _previousState, PVOID _payload, ULONG _payloadSize);
    NTSTATUS nt_open_cpu_partition(PHANDLE _cpuPartitionHandle, ACCESS_MASK _desiredAccess, POBJECT_ATTRIBUTES _objectAttributes);
    NTSTATUS nt_open_directory_object(PHANDLE _directoryHandle, ACCESS_MASK _desiredAccess, POBJECT_ATTRIBUTES _objectAttributes);
    NTSTATUS nt_open_enlistment(PHANDLE _enlistmentHandle, ACCESS_MASK _desiredAccess, HANDLE _resourceManagerHandle, LPGUID _enlistmentGuid, POBJECT_ATTRIBUTES _objectAttributes);
    NTSTATUS nt_open_event(PHANDLE _eventHandle, ACCESS_MASK _desiredAccess, POBJECT_ATTRIBUTES _objectAttributes);
    NTSTATUS nt_open_event_pair(PHANDLE _eventPairHandle, ACCESS_MASK _desiredAccess, PCOBJECT_ATTRIBUTES _objectAttributes);
    NTSTATUS nt_open_file(PHANDLE _fileHandle, ACCESS_MASK _desiredAccess, PCOBJECT_ATTRIBUTES _objectAttributes, PIO_STATUS_BLOCK _ioStatusBlock, ULONG _shareAccess, ULONG _openOptions);
    NTSTATUS nt_open_io_completion(PHANDLE _ioCompletionHandle, ACCESS_MASK _desiredAccess, PCOBJECT_ATTRIBUTES _objectAttributes);
    NTSTATUS nt_open_job_object(PHANDLE _jobHandle, ACCESS_MASK _desiredAccess, PCOBJECT_ATTRIBUTES _objectAttributes);
    NTSTATUS nt_open_key(PHANDLE _keyHandle, ACCESS_MASK _desiredAccess, POBJECT_ATTRIBUTES _objectAttributes);
    NTSTATUS nt_open_key_ex(PHANDLE _keyHandle, ACCESS_MASK _desiredAccess, POBJECT_ATTRIBUTES _objectAttributes, ULONG _openOptions);
    NTSTATUS nt_open_key_transacted(PHANDLE _keyHandle, ACCESS_MASK _desiredAccess, POBJECT_ATTRIBUTES _objectAttributes, HANDLE _transactionHandle);
    NTSTATUS nt_open_key_transacted_ex(PHANDLE _keyHandle, ACCESS_MASK _desiredAccess, POBJECT_ATTRIBUTES _objectAttributes, ULONG _openOptions, HANDLE _transactionHandle);
    NTSTATUS nt_open_keyed_event(PHANDLE _keyedEventHandle, ACCESS_MASK _desiredAccess, PCOBJECT_ATTRIBUTES _objectAttributes);
    NTSTATUS nt_open_mutant(PHANDLE _mutantHandle, ACCESS_MASK _desiredAccess, PCOBJECT_ATTRIBUTES _objectAttributes);
    NTSTATUS nt_open_object_audit_alarm(PCUNICODE_STRING _subsystemName, PVOID _handleId, PCUNICODE_STRING _objectTypeName, PCUNICODE_STRING _objectName, PSECURITY_DESCRIPTOR _securityDescriptor, HANDLE _clientToken, ACCESS_MASK _desiredAccess, ACCESS_MASK _grantedAccess, PPRIVILEGE_SET _privileges, BOOLEAN _objectCreation, BOOLEAN _accessGranted, PBOOLEAN _generateOnClose);
    NTSTATUS nt_open_partition(PHANDLE _partitionHandle, ACCESS_MASK _desiredAccess, PCOBJECT_ATTRIBUTES _objectAttributes);
    NTSTATUS nt_open_private_namespace(PHANDLE _namespaceHandle, ACCESS_MASK _desiredAccess, POBJECT_ATTRIBUTES _objectAttributes, POBJECT_BOUNDARY_DESCRIPTOR _boundaryDescriptor);
    NTSTATUS nt_open_process(PHANDLE _processHandle, ACCESS_MASK _desiredAccess, PCOBJECT_ATTRIBUTES _objectAttributes, PCLIENT_ID _clientId);
    NTSTATUS nt_open_process_token(HANDLE _processHandle, ACCESS_MASK _desiredAccess, PHANDLE _tokenHandle);
    NTSTATUS nt_open_process_token_ex(HANDLE _processHandle, ACCESS_MASK _desiredAccess, ULONG _handleAttributes, PHANDLE _tokenHandle);
    NTSTATUS nt_open_registry_transaction(HANDLE* _registryTransactionHandle, ACCESS_MASK _desiredAccess, POBJECT_ATTRIBUTES _objAttributes);
    NTSTATUS nt_open_resource_manager(PHANDLE _resourceManagerHandle, ACCESS_MASK _desiredAccess, HANDLE _tmHandle, LPGUID _resourceManagerGuid, POBJECT_ATTRIBUTES _objectAttributes);
    NTSTATUS nt_open_section(PHANDLE _sectionHandle, ACCESS_MASK _desiredAccess, PCOBJECT_ATTRIBUTES _objectAttributes);
    NTSTATUS nt_open_semaphore(PHANDLE _semaphoreHandle, ACCESS_MASK _desiredAccess, PCOBJECT_ATTRIBUTES _objectAttributes);
    NTSTATUS nt_open_session(PHANDLE _sessionHandle, ACCESS_MASK _desiredAccess, POBJECT_ATTRIBUTES _objectAttributes);
    NTSTATUS nt_open_symbolic_link_object(PHANDLE _linkHandle, ACCESS_MASK _desiredAccess, POBJECT_ATTRIBUTES _objectAttributes);
    NTSTATUS nt_open_thread(PHANDLE _threadHandle, ACCESS_MASK _desiredAccess, PCOBJECT_ATTRIBUTES _objectAttributes, PCLIENT_ID _clientId);
    NTSTATUS nt_open_thread_token(HANDLE _threadHandle, ACCESS_MASK _desiredAccess, BOOLEAN _openAsSelf, PHANDLE _tokenHandle);
    NTSTATUS nt_open_thread_token_ex(HANDLE _threadHandle, ACCESS_MASK _desiredAccess, BOOLEAN _openAsSelf, ULONG _handleAttributes, PHANDLE _tokenHandle);
    NTSTATUS nt_open_timer(PHANDLE _timerHandle, ACCESS_MASK _desiredAccess, PCOBJECT_ATTRIBUTES _objectAttributes);
    NTSTATUS nt_open_transaction(PHANDLE _transactionHandle, ACCESS_MASK _desiredAccess, POBJECT_ATTRIBUTES _objectAttributes, LPGUID _uow, HANDLE _tmHandle);
    NTSTATUS nt_open_transaction_manager(PHANDLE _tmHandle, ACCESS_MASK _desiredAccess, POBJECT_ATTRIBUTES _objectAttributes, PCUNICODE_STRING _logFileName, LPGUID _tmIdentity, ULONG _openOptions);
    NTSTATUS nt_plug_play_control(PLUGPLAY_CONTROL_CLASS _pnPControlClass, PVOID _pnPControlData, ULONG _pnPControlDataLength);
    NTSTATUS nt_power_information(ULONG _informationLevel, PVOID _inputBuffer, ULONG _inputBufferLength, PVOID _outputBuffer, ULONG _outputBufferLength);
    NTSTATUS nt_pre_prepare_complete(HANDLE _enlistmentHandle, PLARGE_INTEGER _tmVirtualClock);
    NTSTATUS nt_pre_prepare_enlistment(HANDLE _enlistmentHandle, PLARGE_INTEGER _tmVirtualClock);
    NTSTATUS nt_prepare_complete(HANDLE _enlistmentHandle, PLARGE_INTEGER _tmVirtualClock);
    NTSTATUS nt_prepare_enlistment(HANDLE _enlistmentHandle, PLARGE_INTEGER _tmVirtualClock);
    NTSTATUS nt_privilege_check(HANDLE _clientToken, PPRIVILEGE_SET _requiredPrivileges, PBOOLEAN _result);
    NTSTATUS nt_privilege_object_audit_alarm(PCUNICODE_STRING _subsystemName, PVOID _handleId, HANDLE _clientToken, ACCESS_MASK _desiredAccess, PPRIVILEGE_SET _privileges, BOOLEAN _accessGranted);
    NTSTATUS nt_privileged_service_audit_alarm(PCUNICODE_STRING _subsystemName, PCUNICODE_STRING _serviceName, HANDLE _clientToken, PPRIVILEGE_SET _privileges, BOOLEAN _accessGranted);
    NTSTATUS nt_propagation_complete(HANDLE _resourceManagerHandle, ULONG _requestCookie, ULONG _bufferLength, PVOID _buffer);
    NTSTATUS nt_propagation_failed(HANDLE _resourceManagerHandle, ULONG _requestCookie, NTSTATUS _propStatus);
    NTSTATUS nt_protect_virtual_memory(HANDLE _processHandle, PVOID* _baseAddress, PSIZE_T _regionSize, ULONG _newProtection, PULONG _oldProtection);
    NTSTATUS nt_pss_capture_va_space_bulk(HANDLE _processHandle, PVOID _baseAddress, PNTPSS_MEMORY_BULK_INFORMATION _bulkInformation, SIZE_T _bulkInformationLength, PSIZE_T _returnLength);
    NTSTATUS nt_pulse_event(HANDLE _eventHandle, PLONG _previousState);
    NTSTATUS nt_query_attributes_file(PCOBJECT_ATTRIBUTES _objectAttributes, PFILE_BASIC_INFORMATION _fileInformation);
    NTSTATUS nt_query_auxiliary_counter_frequency(PULONG64 _auxiliaryCounterFrequency);
    NTSTATUS nt_query_boot_entry_order(PULONG _ids, PULONG _count);
    NTSTATUS nt_query_boot_options(PBOOT_OPTIONS _bootOptions, PULONG _bootOptionsLength);
    NTSTATUS nt_query_debug_filter_state(ULONG _componentId, ULONG _level);
    NTSTATUS nt_query_default_locale(BOOLEAN _userProfile, PLCID _defaultLocaleId);
    NTSTATUS nt_query_default_u_i_language(LANGID* _defaultUILanguageId);
    NTSTATUS nt_query_directory_file(HANDLE _fileHandle, HANDLE _event, PIO_APC_ROUTINE _apcRoutine, PVOID _apcContext, PIO_STATUS_BLOCK _ioStatusBlock, PVOID _fileInformation, ULONG _length, FILE_INFORMATION_CLASS _fileInformationClass, BOOLEAN _returnSingleEntry, PCUNICODE_STRING _fileName, BOOLEAN _restartScan);
    NTSTATUS nt_query_directory_file_ex(HANDLE _fileHandle, HANDLE _event, PIO_APC_ROUTINE _apcRoutine, PVOID _apcContext, PIO_STATUS_BLOCK _ioStatusBlock, PVOID _fileInformation, ULONG _length, FILE_INFORMATION_CLASS _fileInformationClass, ULONG _queryFlags, PCUNICODE_STRING _fileName);
    NTSTATUS nt_query_directory_object(HANDLE _directoryHandle, PVOID _buffer, ULONG _length, BOOLEAN _returnSingleEntry, BOOLEAN _restartScan, PULONG _context, PULONG _returnLength);
    NTSTATUS nt_query_driver_entry_order(PULONG _ids, PULONG _count);
    NTSTATUS nt_query_ea_file(HANDLE _fileHandle, PIO_STATUS_BLOCK _ioStatusBlock, PVOID _buffer, ULONG _length, BOOLEAN _returnSingleEntry, PVOID _eaList, ULONG _eaListLength, PULONG _eaIndex, BOOLEAN _restartScan);
    NTSTATUS nt_query_event(HANDLE _eventHandle, EVENT_INFORMATION_CLASS _eventInformationClass, PVOID _eventInformation, ULONG _eventInformationLength, PULONG _returnLength);
    NTSTATUS nt_query_full_attributes_file(PCOBJECT_ATTRIBUTES _objectAttributes, PFILE_NETWORK_OPEN_INFORMATION _fileInformation);
    NTSTATUS nt_query_information_atom(RTL_ATOM _atom, ATOM_INFORMATION_CLASS _atomInformationClass, PVOID _atomInformation, ULONG _atomInformationLength, PULONG _returnLength);
    NTSTATUS nt_query_information_by_name(PCOBJECT_ATTRIBUTES _objectAttributes, PIO_STATUS_BLOCK _ioStatusBlock, PVOID _fileInformation, ULONG _length, FILE_INFORMATION_CLASS _fileInformationClass);
    NTSTATUS nt_query_information_cpu_partition(HANDLE _cpuPartitionHandle, ULONG _cpuPartitionInformationClass, PVOID _cpuPartitionInformation, ULONG _cpuPartitionInformationLength, PULONG _returnLength);
    NTSTATUS nt_query_information_enlistment(HANDLE _enlistmentHandle, ENLISTMENT_INFORMATION_CLASS _enlistmentInformationClass, PVOID _enlistmentInformation, ULONG _enlistmentInformationLength, PULONG _returnLength);
    NTSTATUS nt_query_information_file(HANDLE _fileHandle, PIO_STATUS_BLOCK _ioStatusBlock, PVOID _fileInformation, ULONG _length, FILE_INFORMATION_CLASS _fileInformationClass);
    NTSTATUS nt_query_information_job_object(HANDLE _jobHandle, ULONG _jobObjectInformationClass, PVOID _jobObjectInformation, ULONG _jobObjectInformationLength, PULONG _returnLength);
    NTSTATUS nt_query_information_port(HANDLE _portHandle, PORT_INFORMATION_CLASS _portInformationClass, PVOID _portInformation, ULONG _length, PULONG _returnLength);
    NTSTATUS nt_query_information_process(HANDLE _processHandle, PROCESSINFOCLASS _processInformationClass, PVOID _processInformation, ULONG _processInformationLength, PULONG _returnLength);
    NTSTATUS nt_query_information_resource_manager(HANDLE _resourceManagerHandle, RESOURCEMANAGER_INFORMATION_CLASS _resourceManagerInformationClass, PVOID _resourceManagerInformation, ULONG _resourceManagerInformationLength, PULONG _returnLength);
    NTSTATUS nt_query_information_thread(HANDLE _threadHandle, THREADINFOCLASS _threadInformationClass, PVOID _threadInformation, ULONG _threadInformationLength, PULONG _returnLength);
    NTSTATUS nt_query_information_token(HANDLE _tokenHandle, TOKEN_INFORMATION_CLASS _tokenInformationClass, PVOID _tokenInformation, ULONG _tokenInformationLength, PULONG _returnLength);
    NTSTATUS nt_query_information_transaction(HANDLE _transactionHandle, TRANSACTION_INFORMATION_CLASS _transactionInformationClass, PVOID _transactionInformation, ULONG _transactionInformationLength, PULONG _returnLength);
    NTSTATUS nt_query_information_transaction_manager(HANDLE _transactionManagerHandle, TRANSACTIONMANAGER_INFORMATION_CLASS _transactionManagerInformationClass, PVOID _transactionManagerInformation, ULONG _transactionManagerInformationLength, PULONG _returnLength);
    NTSTATUS nt_query_information_worker_factory(HANDLE _workerFactoryHandle, WORKERFACTORYINFOCLASS _workerFactoryInformationClass, PVOID _workerFactoryInformation, ULONG _workerFactoryInformationLength, PULONG _returnLength);
    NTSTATUS nt_query_install_u_i_language(LANGID* _installUILanguageId);
    NTSTATUS nt_query_interval_profile(KPROFILE_SOURCE _profileSource, PULONG _interval);
    NTSTATUS nt_query_io_completion(HANDLE _ioCompletionHandle, IO_COMPLETION_INFORMATION_CLASS _ioCompletionInformationClass, PVOID _ioCompletionInformation, ULONG _ioCompletionInformationLength, PULONG _returnLength);
    NTSTATUS nt_query_io_ring_capabilities(SIZE_T _ioRingCapabilitiesLength, PVOID _ioRingCapabilities);
    NTSTATUS nt_query_key(HANDLE _keyHandle, KEY_INFORMATION_CLASS _keyInformationClass, PVOID _keyInformation, ULONG _length, PULONG _resultLength);
    NTSTATUS nt_query_license_value(PCUNICODE_STRING _valueName, PULONG _type, PVOID _data, ULONG _dataSize, PULONG _resultDataSize);
    NTSTATUS nt_query_multiple_value_key(HANDLE _keyHandle, PKEY_VALUE_ENTRY _valueEntries, ULONG _entryCount, PVOID _valueBuffer, PULONG _bufferLength, PULONG _requiredBufferLength);
    NTSTATUS nt_query_mutant(HANDLE _mutantHandle, MUTANT_INFORMATION_CLASS _mutantInformationClass, PVOID _mutantInformation, ULONG _mutantInformationLength, PULONG _returnLength);
    NTSTATUS nt_query_object(HANDLE _handle, OBJECT_INFORMATION_CLASS _objectInformationClass, PVOID _objectInformation, ULONG _objectInformationLength, PULONG _returnLength);
    NTSTATUS nt_query_open_sub_keys(POBJECT_ATTRIBUTES _targetKey, PULONG _handleCount);
    NTSTATUS nt_query_open_sub_keys_ex(POBJECT_ATTRIBUTES _targetKey, ULONG _bufferLength, PVOID _buffer, PULONG _requiredSize);
    NTSTATUS nt_query_performance_counter(PLARGE_INTEGER _performanceCounter, PLARGE_INTEGER _performanceFrequency);
    LOGICAL nt_query_port_information_process();
    NTSTATUS nt_query_quota_information_file(HANDLE _fileHandle, PIO_STATUS_BLOCK _ioStatusBlock, PVOID _buffer, ULONG _length, BOOLEAN _returnSingleEntry, PVOID _sidList, ULONG _sidListLength, PSID _startSid, BOOLEAN _restartScan);
    NTSTATUS nt_query_section(HANDLE _sectionHandle, SECTION_INFORMATION_CLASS _sectionInformationClass, PVOID _sectionInformation, SIZE_T _sectionInformationLength, PSIZE_T _returnLength);
    NTSTATUS nt_query_security_attributes_token(HANDLE _tokenHandle, PCUNICODE_STRING _attributes, ULONG _numberOfAttributes, PVOID _buffer, ULONG _length, PULONG _returnLength);
    NTSTATUS nt_query_security_object(HANDLE _handle, SECURITY_INFORMATION _securityInformation, PSECURITY_DESCRIPTOR _securityDescriptor, ULONG _length, PULONG _lengthNeeded);
    NTSTATUS nt_query_security_policy(PCUNICODE_STRING _policy, PCUNICODE_STRING _keyName, PCUNICODE_STRING _valueName, SECURE_SETTING_VALUE_TYPE _valueType, PVOID _value, PULONG _valueSize);
    NTSTATUS nt_query_semaphore(HANDLE _semaphoreHandle, SEMAPHORE_INFORMATION_CLASS _semaphoreInformationClass, PVOID _semaphoreInformation, ULONG _semaphoreInformationLength, PULONG _returnLength);
    NTSTATUS nt_query_symbolic_link_object(HANDLE _linkHandle, PUNICODE_STRING _linkTarget, PULONG _returnedLength);
    NTSTATUS nt_query_system_environment_value(PCUNICODE_STRING _variableName, PWSTR _variableValue, USHORT _valueLength, PUSHORT _returnLength);
    NTSTATUS nt_query_system_environment_value_ex(PCUNICODE_STRING _variableName, PCGUID _vendorGuid, PVOID _buffer, PULONG _bufferLength, PULONG _attributes);
    NTSTATUS nt_query_system_information(SYSTEM_INFORMATION_CLASS _systemInformationClass, PVOID _systemInformation, ULONG _systemInformationLength, PULONG _returnLength);
    NTSTATUS nt_query_system_information_ex(SYSTEM_INFORMATION_CLASS _systemInformationClass, PVOID _inputBuffer, ULONG _inputBufferLength, PVOID _systemInformation, ULONG _systemInformationLength, PULONG _returnLength);
    NTSTATUS nt_query_system_time(PLARGE_INTEGER _systemTime);
    NTSTATUS nt_query_timer(HANDLE _timerHandle, TIMER_INFORMATION_CLASS _timerInformationClass, PVOID _timerInformation, ULONG _timerInformationLength, PULONG _returnLength);
    NTSTATUS nt_query_timer_resolution(PULONG _maximumTime, PULONG _minimumTime, PULONG _currentTime);
    NTSTATUS nt_query_value_key(HANDLE _keyHandle, PCUNICODE_STRING _valueName, KEY_VALUE_INFORMATION_CLASS _keyValueInformationClass, PVOID _keyValueInformation, ULONG _length, PULONG _resultLength);
    NTSTATUS nt_query_virtual_memory(HANDLE _processHandle, PVOID _baseAddress, MEMORY_INFORMATION_CLASS _memoryInformationClass, PVOID _memoryInformation, SIZE_T _memoryInformationLength, PSIZE_T _returnLength);
    NTSTATUS nt_query_volume_information_file(HANDLE _fileHandle, PIO_STATUS_BLOCK _ioStatusBlock, PVOID _fsInformation, ULONG _length, FSINFOCLASS _fsInformationClass);
    NTSTATUS nt_query_wnf_state_data(PCWNF_STATE_NAME _stateName, PCWNF_TYPE_ID _typeId, PCSID _explicitScope, PWNF_CHANGE_STAMP _changeStamp, PVOID _buffer, PULONG _bufferLength);
    NTSTATUS nt_query_wnf_state_name_information(PCWNF_STATE_NAME _stateName, WNF_STATE_NAME_INFORMATION _nameInfoClass, PCSID _explicitScope, PVOID _buffer, ULONG _bufferLength);
    NTSTATUS nt_queue_apc_thread(HANDLE _threadHandle, PPS_APC_ROUTINE _apcRoutine, PVOID _apcArgument1, PVOID _apcArgument2, PVOID _apcArgument3);
    NTSTATUS nt_queue_apc_thread_ex(HANDLE _threadHandle, HANDLE _reserveHandle, PPS_APC_ROUTINE _apcRoutine, PVOID _apcArgument1, PVOID _apcArgument2, PVOID _apcArgument3);
    NTSTATUS nt_queue_apc_thread_ex2(HANDLE _threadHandle, HANDLE _reserveHandle, ULONG _apcFlags, PPS_APC_ROUTINE _apcRoutine, PVOID _apcArgument1, PVOID _apcArgument2, PVOID _apcArgument3);
    NTSTATUS nt_raise_exception(PEXCEPTION_RECORD _exceptionRecord, PCONTEXT _contextRecord, BOOLEAN _firstChance);
    NTSTATUS nt_read_file(HANDLE _fileHandle, HANDLE _event, PIO_APC_ROUTINE _apcRoutine, PVOID _apcContext, PIO_STATUS_BLOCK _ioStatusBlock, PVOID _buffer, ULONG _length, PLARGE_INTEGER _byteOffset, PULONG _key);
    NTSTATUS nt_read_file_scatter(HANDLE _fileHandle, HANDLE _event, PIO_APC_ROUTINE _apcRoutine, PVOID _apcContext, PIO_STATUS_BLOCK _ioStatusBlock, PFILE_SEGMENT_ELEMENT _segmentArray, ULONG _length, PLARGE_INTEGER _byteOffset, PULONG _key);
    NTSTATUS nt_read_only_enlistment(HANDLE _enlistmentHandle, PLARGE_INTEGER _tmVirtualClock);
    NTSTATUS nt_read_request_data(HANDLE _portHandle, PPORT_MESSAGE _message, ULONG _dataEntryIndex, PVOID _buffer, SIZE_T _bufferSize, PSIZE_T _numberOfBytesRead);
    NTSTATUS nt_read_virtual_memory(HANDLE _processHandle, PVOID _baseAddress, PVOID _buffer, SIZE_T _numberOfBytesToRead, PSIZE_T _numberOfBytesRead);
    NTSTATUS nt_read_virtual_memory_ex(HANDLE _processHandle, PVOID _baseAddress, PVOID _buffer, SIZE_T _numberOfBytesToRead, PSIZE_T _numberOfBytesRead, ULONG _flags);
    NTSTATUS nt_recover_enlistment(HANDLE _enlistmentHandle, PVOID _enlistmentKey);
    NTSTATUS nt_recover_resource_manager(HANDLE _resourceManagerHandle);
    NTSTATUS nt_recover_transaction_manager(HANDLE _transactionManagerHandle);
    NTSTATUS nt_register_protocol_address_information(HANDLE _resourceManager, PCRM_PROTOCOL_ID _protocolId, ULONG _protocolInformationSize, PVOID _protocolInformation, ULONG _createOptions);
    NTSTATUS nt_register_thread_terminate_port(HANDLE _portHandle);
    NTSTATUS nt_release_keyed_event(HANDLE _keyedEventHandle, PVOID _keyValue, BOOLEAN _alertable, PLARGE_INTEGER _timeout);
    NTSTATUS nt_release_mutant(HANDLE _mutantHandle, PLONG _previousCount);
    NTSTATUS nt_release_semaphore(HANDLE _semaphoreHandle, LONG _releaseCount, PLONG _previousCount);
    NTSTATUS nt_release_worker_factory_worker(HANDLE _workerFactoryHandle);
    NTSTATUS nt_remove_io_completion(HANDLE _ioCompletionHandle, PVOID* _keyContext, PVOID* _apcContext, PIO_STATUS_BLOCK _ioStatusBlock, PLARGE_INTEGER _timeout);
    NTSTATUS nt_remove_io_completion_ex(HANDLE _ioCompletionHandle, PFILE_IO_COMPLETION_INFORMATION _ioCompletionInformation, ULONG _count, PULONG _numEntriesRemoved, PLARGE_INTEGER _timeout, BOOLEAN _alertable);
    NTSTATUS nt_remove_process_debug(HANDLE _processHandle, HANDLE _debugObjectHandle);
    NTSTATUS nt_rename_key(HANDLE _keyHandle, PCUNICODE_STRING _newName);
    NTSTATUS nt_rename_transaction_manager(PCUNICODE_STRING _logFileName, LPGUID _existingTransactionManagerGuid);
    NTSTATUS nt_replace_key(POBJECT_ATTRIBUTES _newFile, HANDLE _targetHandle, POBJECT_ATTRIBUTES _oldFile);
    NTSTATUS nt_replace_partition_unit(PCUNICODE_STRING _targetInstancePath, PCUNICODE_STRING _spareInstancePath, ULONG _flags);
    NTSTATUS nt_reply_port(HANDLE _portHandle, PPORT_MESSAGE _replyMessage);
    NTSTATUS nt_reply_wait_receive_port(HANDLE _portHandle, PVOID* _portContext, PPORT_MESSAGE _replyMessage, PPORT_MESSAGE _receiveMessage);
    NTSTATUS nt_reply_wait_receive_port_ex(HANDLE _portHandle, PVOID* _portContext, PPORT_MESSAGE _replyMessage, PPORT_MESSAGE _receiveMessage, PLARGE_INTEGER _timeout);
    NTSTATUS nt_reply_wait_reply_port(HANDLE _portHandle, PPORT_MESSAGE _replyMessage);
    NTSTATUS nt_request_port(HANDLE _portHandle, PPORT_MESSAGE _requestMessage);
    NTSTATUS nt_request_wait_reply_port(HANDLE _portHandle, PPORT_MESSAGE _requestMessage, PPORT_MESSAGE _replyMessage);
    NTSTATUS nt_reset_event(HANDLE _eventHandle, PLONG _previousState);
    NTSTATUS nt_reset_write_watch(HANDLE _processHandle, PVOID _baseAddress, SIZE_T _regionSize);
    NTSTATUS nt_restore_key(HANDLE _keyHandle, HANDLE _fileHandle, ULONG _flags);
    NTSTATUS nt_resume_process(HANDLE _processHandle);
    NTSTATUS nt_resume_thread(HANDLE _threadHandle, PULONG _previousSuspendCount);
    NTSTATUS nt_revert_container_impersonation();
    NTSTATUS nt_rollback_complete(HANDLE _enlistmentHandle, PLARGE_INTEGER _tmVirtualClock);
    NTSTATUS nt_rollback_enlistment(HANDLE _enlistmentHandle, PLARGE_INTEGER _tmVirtualClock);
    NTSTATUS nt_rollback_registry_transaction(HANDLE _registryTransactionHandle, ULONG _flags);
    NTSTATUS nt_rollback_transaction(HANDLE _transactionHandle, BOOLEAN _wait);
    NTSTATUS nt_rollforward_transaction_manager(HANDLE _transactionManagerHandle, PLARGE_INTEGER _tmVirtualClock);
    NTSTATUS nt_save_key(HANDLE _keyHandle, HANDLE _fileHandle);
    NTSTATUS nt_save_key_ex(HANDLE _keyHandle, HANDLE _fileHandle, ULONG _format);
    NTSTATUS nt_save_merged_keys(HANDLE _highPrecedenceKeyHandle, HANDLE _lowPrecedenceKeyHandle, HANDLE _fileHandle);
    NTSTATUS nt_secure_connect_port(PHANDLE _portHandle, PCUNICODE_STRING _portName, PSECURITY_QUALITY_OF_SERVICE _securityQos, PPORT_VIEW _clientView, PSID _requiredServerSid, PREMOTE_PORT_VIEW _serverView, PULONG _maxMessageLength, PVOID _connectionInformation, PULONG _connectionInformationLength);
    NTSTATUS nt_serialize_boot();
    NTSTATUS nt_set_boot_entry_order(PULONG _ids, ULONG _count);
    NTSTATUS nt_set_boot_options(PBOOT_OPTIONS _bootOptions, ULONG _fieldsToChange);
    NTSTATUS nt_set_cached_signing_level(ULONG _flags, SE_SIGNING_LEVEL _inputSigningLevel, PHANDLE _sourceFiles, ULONG _sourceFileCount, HANDLE _targetFile);
    NTSTATUS nt_set_cached_signing_level2(ULONG _flags, SE_SIGNING_LEVEL _inputSigningLevel, PHANDLE _sourceFiles, ULONG _sourceFileCount, HANDLE _targetFile, SE_SET_FILE_CACHE_INFORMATION* _cacheInformation);
    NTSTATUS nt_set_context_thread(HANDLE _threadHandle, PCONTEXT _threadContext);
    NTSTATUS nt_set_debug_filter_state(ULONG _componentId, ULONG _level, BOOLEAN _state);
    NTSTATUS nt_set_default_hard_error_port(HANDLE _defaultHardErrorPort);
    NTSTATUS nt_set_default_locale(BOOLEAN _userProfile, LCID _defaultLocaleId);
    NTSTATUS nt_set_default_u_i_language(LANGID _defaultUILanguageId);
    NTSTATUS nt_set_driver_entry_order(PULONG _ids, ULONG _count);
    NTSTATUS nt_set_ea_file(HANDLE _fileHandle, PIO_STATUS_BLOCK _ioStatusBlock, PVOID _buffer, ULONG _length);
    NTSTATUS nt_set_event(HANDLE _eventHandle, PLONG _previousState);
    NTSTATUS nt_set_event_boost_priority(HANDLE _eventHandle);
    NTSTATUS nt_set_event_ex(HANDLE _threadId, PRTL_SRWLOCK _lock);
    NTSTATUS nt_set_high_event_pair(HANDLE _eventPairHandle);
    NTSTATUS nt_set_high_wait_low_event_pair(HANDLE _eventPairHandle);
    NTSTATUS nt_set_i_r_timer(HANDLE _timerHandle, PLARGE_INTEGER _dueTime);
    NTSTATUS nt_set_information_cpu_partition(HANDLE _cpuPartitionHandle, ULONG _cpuPartitionInformationClass, PVOID _cpuPartitionInformation, ULONG _cpuPartitionInformationLength);
    NTSTATUS nt_set_information_debug_object(HANDLE _debugObjectHandle, DEBUGOBJECTINFOCLASS _debugObjectInformationClass, PVOID _debugInformation, ULONG _debugInformationLength, PULONG _returnLength);
    NTSTATUS nt_set_information_enlistment(HANDLE _enlistmentHandle, ENLISTMENT_INFORMATION_CLASS _enlistmentInformationClass, PVOID _enlistmentInformation, ULONG _enlistmentInformationLength);
    NTSTATUS nt_set_information_file(HANDLE _fileHandle, PIO_STATUS_BLOCK _ioStatusBlock, PVOID _fileInformation, ULONG _length, FILE_INFORMATION_CLASS _fileInformationClass);
    NTSTATUS nt_set_information_io_ring(HANDLE _ioRingHandle, ULONG _ioRingInformationClass, ULONG _ioRingInformationLength, PVOID _ioRingInformation);
    NTSTATUS nt_set_information_job_object(HANDLE _jobHandle, ULONG _jobObjectInformationClass, PVOID _jobObjectInformation, ULONG _jobObjectInformationLength);
    NTSTATUS nt_set_information_key(HANDLE _keyHandle, KEY_SET_INFORMATION_CLASS _keySetInformationClass, PVOID _keySetInformation, ULONG _keySetInformationLength);
    NTSTATUS nt_set_information_object(HANDLE _handle, OBJECT_INFORMATION_CLASS _objectInformationClass, PVOID _objectInformation, ULONG _objectInformationLength);
    NTSTATUS nt_set_information_process(HANDLE _processHandle, PROCESSINFOCLASS _processInformationClass, PVOID _processInformation, ULONG _processInformationLength);
    NTSTATUS nt_set_information_resource_manager(HANDLE _resourceManagerHandle, RESOURCEMANAGER_INFORMATION_CLASS _resourceManagerInformationClass, PVOID _resourceManagerInformation, ULONG _resourceManagerInformationLength);
    NTSTATUS nt_set_information_symbolic_link(HANDLE _linkHandle, SYMBOLIC_LINK_INFO_CLASS _symbolicLinkInformationClass, PVOID _symbolicLinkInformation, ULONG _symbolicLinkInformationLength);
    NTSTATUS nt_set_information_thread(HANDLE _threadHandle, THREADINFOCLASS _threadInformationClass, PVOID _threadInformation, ULONG _threadInformationLength);
    NTSTATUS nt_set_information_token(HANDLE _tokenHandle, TOKEN_INFORMATION_CLASS _tokenInformationClass, PVOID _tokenInformation, ULONG _tokenInformationLength);
    NTSTATUS nt_set_information_transaction(HANDLE _transactionHandle, TRANSACTION_INFORMATION_CLASS _transactionInformationClass, PVOID _transactionInformation, ULONG _transactionInformationLength);
    NTSTATUS nt_set_information_transaction_manager(HANDLE _tmHandle, TRANSACTIONMANAGER_INFORMATION_CLASS _transactionManagerInformationClass, PVOID _transactionManagerInformation, ULONG _transactionManagerInformationLength);
    NTSTATUS nt_set_information_virtual_memory(HANDLE _processHandle, VIRTUAL_MEMORY_INFORMATION_CLASS _vmInformationClass, SIZE_T _numberOfEntries, PMEMORY_RANGE_ENTRY _virtualAddresses, PVOID _vmInformation, ULONG _vmInformationLength);
    NTSTATUS nt_set_information_worker_factory(HANDLE _workerFactoryHandle, WORKERFACTORYINFOCLASS _workerFactoryInformationClass, PVOID _workerFactoryInformation, ULONG _workerFactoryInformationLength);
    NTSTATUS nt_set_interval_profile(ULONG _interval, KPROFILE_SOURCE _source);
    NTSTATUS nt_set_io_completion(HANDLE _ioCompletionHandle, PVOID _keyContext, PVOID _apcContext, NTSTATUS _ioStatus, ULONG_PTR _ioStatusInformation);
    NTSTATUS nt_set_io_completion_ex(HANDLE _ioCompletionHandle, HANDLE _ioCompletionPacketHandle, PVOID _keyContext, PVOID _apcContext, NTSTATUS _ioStatus, ULONG_PTR _ioStatusInformation);
    NTSTATUS nt_set_ldt_entries(ULONG _selector0, ULONG _entry0Low, ULONG _entry0Hi, ULONG _selector1, ULONG _entry1Low, ULONG _entry1Hi);
    NTSTATUS nt_set_low_event_pair(HANDLE _eventPairHandle);
    NTSTATUS nt_set_low_wait_high_event_pair(HANDLE _eventPairHandle);
    NTSTATUS nt_set_quota_information_file(HANDLE _fileHandle, PIO_STATUS_BLOCK _ioStatusBlock, PVOID _buffer, ULONG _length);
    NTSTATUS nt_set_security_object(HANDLE _handle, SECURITY_INFORMATION _securityInformation, PSECURITY_DESCRIPTOR _securityDescriptor);
    NTSTATUS nt_set_system_environment_value(PCUNICODE_STRING _variableName, PCUNICODE_STRING _variableValue);
    NTSTATUS nt_set_system_environment_value_ex(PCUNICODE_STRING _variableName, PCGUID _vendorGuid, PVOID _buffer, ULONG _bufferLength, ULONG _attributes);
    NTSTATUS nt_set_system_information(SYSTEM_INFORMATION_CLASS _systemInformationClass, PVOID _systemInformation, ULONG _systemInformationLength);
    NTSTATUS nt_set_system_power_state(POWER_ACTION _systemAction, SYSTEM_POWER_STATE _lightestSystemState, ULONG _flags);
    NTSTATUS nt_set_system_time(PLARGE_INTEGER _systemTime, PLARGE_INTEGER _previousTime);
    NTSTATUS nt_set_thread_execution_state(EXECUTION_STATE _newFlags, EXECUTION_STATE* _previousFlags);
    NTSTATUS nt_set_timer(HANDLE _timerHandle, PLARGE_INTEGER _dueTime, PTIMER_APC_ROUTINE _timerApcRoutine, PVOID _timerContext, BOOLEAN _resumeTimer, LONG _period, PBOOLEAN _previousState);
    NTSTATUS nt_set_timer2(HANDLE _timerHandle, PLARGE_INTEGER _dueTime, PLARGE_INTEGER _period, PT2_SET_PARAMETERS _parameters);
    NTSTATUS nt_set_timer_ex(HANDLE _timerHandle, TIMER_SET_INFORMATION_CLASS _timerSetInformationClass, PVOID _timerSetInformation, ULONG _timerSetInformationLength);
    NTSTATUS nt_set_timer_resolution(ULONG _desiredTime, BOOLEAN _setResolution, PULONG _actualTime);
    NTSTATUS nt_set_uuid_seed(PCHAR _seed);
    NTSTATUS nt_set_value_key(HANDLE _keyHandle, PCUNICODE_STRING _valueName, ULONG _titleIndex, ULONG _type, PVOID _data, ULONG _dataSize);
    NTSTATUS nt_set_volume_information_file(HANDLE _fileHandle, PIO_STATUS_BLOCK _ioStatusBlock, PVOID _fsInformation, ULONG _length, FSINFOCLASS _fsInformationClass);
    NTSTATUS nt_set_wnf_process_notification_event(HANDLE _notificationEvent);
    NTSTATUS nt_shutdown_system(SHUTDOWN_ACTION _action);
    NTSTATUS nt_shutdown_worker_factory(HANDLE _workerFactoryHandle, LONG* _pendingWorkerCount);
    NTSTATUS nt_signal_and_wait_for_single_object(HANDLE _signalHandle, HANDLE _waitHandle, BOOLEAN _alertable, PLARGE_INTEGER _timeout);
    NTSTATUS nt_single_phase_reject(HANDLE _enlistmentHandle, PLARGE_INTEGER _tmVirtualClock);
    NTSTATUS nt_start_profile(HANDLE _profileHandle);
    NTSTATUS nt_stop_profile(HANDLE _profileHandle);
    NTSTATUS nt_submit_io_ring(HANDLE _ioRingHandle, ULONG _flags, ULONG _waitOperations, PLARGE_INTEGER _timeout);
    NTSTATUS nt_subscribe_wnf_state_change(PCWNF_STATE_NAME _stateName, WNF_CHANGE_STAMP _changeStamp, ULONG _eventMask, PULONG64 _subscriptionId);
    NTSTATUS nt_suspend_process(HANDLE _processHandle);
    NTSTATUS nt_suspend_thread(HANDLE _threadHandle, PULONG _previousSuspendCount);
    NTSTATUS nt_system_debug_control(SYSDBG_COMMAND _command, PVOID _inputBuffer, ULONG _inputBufferLength, PVOID _outputBuffer, ULONG _outputBufferLength, PULONG _returnLength);
    NTSTATUS nt_terminate_enclave(PVOID _baseAddress, ULONG _flags);
    NTSTATUS nt_terminate_job_object(HANDLE _jobHandle, NTSTATUS _exitStatus);
    NTSTATUS nt_terminate_process(HANDLE _processHandle, NTSTATUS _exitStatus);
    NTSTATUS nt_terminate_thread(HANDLE _threadHandle, NTSTATUS _exitStatus);
    NTSTATUS nt_test_alert();
    NTSTATUS nt_thaw_registry();
    NTSTATUS nt_thaw_transactions();
    NTSTATUS nt_trace_control(ETWTRACECONTROLCODE _functionCode, PVOID _inputBuffer, ULONG _inputBufferLength, PVOID _outputBuffer, ULONG _outputBufferLength, PULONG _returnLength);
    NTSTATUS nt_trace_event(HANDLE _traceHandle, ULONG _flags, ULONG _fieldSize, PVOID _fields);
    NTSTATUS nt_translate_file_path(PFILE_PATH _inputFilePath, ULONG _outputType, PFILE_PATH _outputFilePath, PULONG _outputFilePathLength);
    NTSTATUS nt_ums_thread_yield(PVOID _schedulerParam);
    NTSTATUS nt_unload_driver(PCUNICODE_STRING _driverServiceName);
    NTSTATUS nt_unload_key(POBJECT_ATTRIBUTES _targetKey);
    NTSTATUS nt_unload_key2(POBJECT_ATTRIBUTES _targetKey, ULONG _flags);
    NTSTATUS nt_unload_key_ex(POBJECT_ATTRIBUTES _targetKey, HANDLE _event);
    NTSTATUS nt_unlock_file(HANDLE _fileHandle, PIO_STATUS_BLOCK _ioStatusBlock, PLARGE_INTEGER _byteOffset, PLARGE_INTEGER _length, ULONG _key);
    NTSTATUS nt_unlock_virtual_memory(HANDLE _processHandle, PVOID* _baseAddress, PSIZE_T _regionSize, ULONG _mapType);
    NTSTATUS nt_unmap_view_of_section(HANDLE _processHandle, PVOID _baseAddress);
    NTSTATUS nt_unmap_view_of_section_ex(HANDLE _processHandle, PVOID _baseAddress, ULONG _flags);
    NTSTATUS nt_unsubscribe_wnf_state_change(PCWNF_STATE_NAME _stateName);
    NTSTATUS nt_update_wnf_state_data(PCWNF_STATE_NAME _stateName, void* _buffer, ULONG _length, PCWNF_TYPE_ID _typeId, PCSID _explicitScope, WNF_CHANGE_STAMP _matchingChangeStamp, LOGICAL _checkStamp);
    LOGICAL nt_user_allow_foreground_activation();
    LOGICAL nt_user_allow_set_foreground_window(ULONG _processId);
    ULONG nt_user_arrange_iconic_windows(HWND _hwnd);
    NTSTATUS nt_user_attach_thread_input(ULONG _idAttach, ULONG _idAttachTo, BOOL _attach);
    HDWP nt_user_begin_defer_window_pos(ULONG _numWindowsHint);
    HDC nt_user_begin_paint(HWND _windowHandle, LPPAINTSTRUCT _lpPaint);
    BOOL nt_user_block_input(BOOL _blockInput);
    BOOL nt_user_bring_window_to_top(HWND _windowHandle);
    LOGICAL nt_user_broadcast_ime_show_status_change(HWND _ime, LOGICAL _show);
    NTSTATUS nt_user_build_hwnd_list(HANDLE _desktopHandle, HWND _parentWindowHandle, BOOL _includeChildren, BOOL _excludeImmersive, ULONG _threadId, ULONG _hwndListInformationLength, PVOID _hwndListInformation, PULONG _returnLength);
    NTSTATUS nt_user_build_name_list(HWINSTA _windowStationHandle, ULONG _nameListInformationLength, PVOID _nameListInformation, PULONG _returnLength);
    NTSTATUS nt_user_build_prop_list(HWINSTA _windowStationHandle, ULONG _propListInformationLength, PVOID _propListInformation, PULONG _returnLength);
    BOOL nt_user_calculate_popup_window_position(POINT* _anchorPoint, SIZE* _windowSize, ULONG _flags, RECT* _excludeRect, RECT* _popupWindowPosition);
    ULONG_PTR nt_user_call_hwnd(HWND _hwnd, ULONG _xpfnProc);
    ULONG_PTR nt_user_call_hwnd_lock(HWND _hwnd, ULONG _xpfnProc);
    ULONG_PTR nt_user_call_hwnd_lock_safe(HWND _hwnd, ULONG _xpfnProc);
    ULONG_PTR nt_user_call_hwnd_opt(HWND _hwnd, ULONG _xpfnProc);
    ULONG_PTR nt_user_call_hwnd_param(HWND _hwnd, ULONG_PTR _param, ULONG _xpfnProc);
    ULONG_PTR nt_user_call_hwnd_param_lock(HWND _hwnd, ULONG_PTR _param, ULONG _xpfnProc);
    ULONG_PTR nt_user_call_hwnd_param_lock_safe(HWND _hwnd, ULONG_PTR _param, ULONG _xpfnProc);
    ULONG_PTR nt_user_call_hwnd_safe(HWND _hwnd, ULONG _xpfnProc);
    ULONG_PTR nt_user_call_no_param(ULONG _xpfnProc);
    ULONG_PTR nt_user_call_one_param(ULONG_PTR _param, ULONG _xpfnProc);
    ULONG_PTR nt_user_call_two_param(ULONG_PTR _param1, ULONG_PTR _param2, ULONG _xpfnProc);
    BOOL nt_user_can_current_thread_change_foreground();
    LOGICAL nt_user_cancel_queue_event_completion_packet();
    LOGICAL nt_user_change_window_message_filter(ULONG _message, ULONG _flag);
    NTSTATUS nt_user_check_access_for_integrity_level(ULONG _processIdFirst, ULONG _processIdSecond, PBOOLEAN _grantedAccess);
    LOGICAL nt_user_check_ime_show_status_in_thread(HWND _ime);
    NTSTATUS nt_user_check_process_for_clipboard_access(ULONG _processId, PULONG _grantedAccess);
    HWND nt_user_child_window_from_point_ex(HWND _windowHandle, POINT _pt, ULONG _flags);
    NTSTATUS nt_user_cit_set_info(ULONG_PTR _infoFlags, ULONG_PTR _info);
    LOGICAL nt_user_clear_wake_mask();
    LOGICAL nt_user_clear_window_state(HWND _hwnd, ULONG _flag);
    BOOL nt_user_clip_cursor(RECT* _lpRect);
    BOOL nt_user_close_desktop(HDESK _desktopHandle);
    BOOL nt_user_close_window_station(HWINSTA _windowStationHandle);
    NTSTATUS nt_user_console_control(CONSOLECONTROL _command, PVOID _consoleInformation, ULONG _consoleInformationLength);
    LONG nt_user_copy_accelerator_table(HACCEL _hAccelSrc, LPACCEL _lpAccelDst, LONG _cAccelEntries);
    HACCEL nt_user_create_accelerator_table(LPACCEL _paccel, LONG _cAccel);
    HMENU nt_user_create_menu();
    HMENU nt_user_create_popup_menu();
    LOGICAL nt_user_create_system_threads();
    NTSTATUS nt_user_create_window_station(POBJECT_ATTRIBUTES _objectAttributes, ACCESS_MASK _desiredAccess, HANDLE _keyboardLayoutHandle, PVOID _keyboardLayoutOffset, PVOID _nlsTableOffset, PVOID _keyboardDescriptor, PCUNICODE_STRING _languageIdString, ULONG _keyboardLocale);
    LOGICAL nt_user_cs_dde_uninitialize(HANDLE _hInst);
    ULONG_PTR nt_user_d_w_p__get_enabled_popup_offset(HWND _hwnd);
    ULONG_PTR nt_user_deferred_desktop_rotation();
    BOOL nt_user_delete_menu(HMENU _menuHandle, ULONG _position, ULONG _flags);
    LOGICAL nt_user_deregister_shell_hook_window(HWND _hwnd);
    LOGICAL nt_user_destroy_caret();
    BOOL nt_user_destroy_menu(HMENU _menuHandle);
    BOOL nt_user_destroy_window(HWND _windowHandle);
    BOOL nt_user_disable_process_window_filtering();
    LOGICAL nt_user_disable_process_windows_ghosting();
    LOGICAL nt_user_do_init_message_pump_hook();
    LOGICAL nt_user_do_uninit_message_pump_hook();
    BOOL nt_user_drag_detect(HWND _windowHandle, POINT _pt);
    ULONG nt_user_drag_object(HWND _windowHandleParent, HWND _windowHandleFrom, ULONG _fmt, ULONG_PTR _data, HCURSOR _hcur);
    LOGICAL nt_user_drain_thread_core_messaging_completions();
    BOOL nt_user_draw_animated_rects(HWND _windowHandle, int _idAni, RECT* _lprcFrom, RECT* _lprcTo);
    LOGICAL nt_user_draw_menu_bar(HWND _hwnd);
    ULONG_PTR nt_user_dwm_lock_screen_updates(LOGICAL _lockUpdates);
    LOGICAL nt_user_enable_modern_app_window_keyboard_intercept(HWND _hwnd, LOGICAL _enable);
    LOGICAL nt_user_enable_mouse_in_pointer_for_thread();
    LOGICAL nt_user_enable_per_monitor_menu_scaling();
    ULONG_PTR nt_user_enable_session_for_m_m_c_s_s(LOGICAL _enable);
    LOGICAL nt_user_enable_shell_window_management_behavior(ULONG_PTR _param1, ULONG_PTR _param2);
    LOGICAL nt_user_enable_window(HWND _hwnd, LOGICAL _enable);
    BOOL nt_user_end_menu();
    BOOL nt_user_end_paint(HWND _windowHandle, PAINTSTRUCT* _lpPaint);
    LOGICAL nt_user_ensure_dpi_dep_sys_met_cache_for_plateau(ULONG _dpi);
    ULONG nt_user_enum_clipboard_formats(ULONG _format);
    BOOL nt_user_enum_display_monitors(HDC _hdc, LPCRECT _lprcClip, MONITORENUMPROC _lpfnEnum, LPARAM _dwData);
    HRGN nt_user_exclude_update_rgn(HDC _hDC, HWND _windowHandle);
    HWND nt_user_find_window_ex(HWND _hwndParent, HWND _hwndChild, PCUNICODE_STRING _className, PCUNICODE_STRING _windowName, ULONG _type);
    BOOL nt_user_flash_window_ex(PFLASHWINFO _pfwi);
    UINT_PTR nt_user_force_enable_numpad_translation(LOGICAL _forceNumlockTranslation);
    HWND nt_user_get_ancestor(HWND _windowHandle, ULONG _gaFlags);
    ULONG nt_user_get_caret_blink_time();
    BOOL nt_user_get_caret_pos(LPPOINT _lpPoint);
    HCURSOR nt_user_get_class_ico_cur(HWND _hwnd, ULONG _index);
    ULONG nt_user_get_class_name(HWND _windowHandle, BOOL _realClassName, PUNICODE_STRING _className);
    BOOL nt_user_get_clip_cursor(LPRECT _lpRect);
    BOOL nt_user_get_combo_box_info(HWND _windowHandleCombo, PCOMBOBOXINFO _pcbi);
    BOOL nt_user_get_current_input_message_source(INPUT_MESSAGE_SOURCE* _inputMessageSource);
    HCURSOR nt_user_get_cursor();
    BOOL nt_user_get_cursor_info(PCURSORINFO _pci);
    LOGICAL nt_user_get_cursor_pos(PPOINT _point, ULONG _cursorPosType);
    HDC nt_user_get_d_c_ex(HWND _windowHandle, HRGN _hrgnClip, ULONG _flags);
    ULONG nt_user_get_device_change_info();
    BOOL nt_user_get_display_auto_rotation_preferences(ORIENTATION_PREFERENCE* _pOrientation);
    ULONG nt_user_get_double_click_time();
    HWND nt_user_get_foreground_window();
    BOOL nt_user_get_g_u_i_thread_info(ULONG _idThread, PGUITHREADINFO _pgui);
    ULONG nt_user_get_gui_resources(HANDLE _processHandle, ULONG _flags);
    LOGICAL nt_user_get_i_m_e_show_status();
    BOOL nt_user_get_icon_info(HICON _iconOrCursorHandle, PICONINFO _iconinfo, PUNICODE_STRING _name, PUNICODE_STRING _resourceId, PULONG _colorBits, LOGICAL _isCursorHandle);
    BOOL nt_user_get_icon_size(HGDIOBJ _iconOrCursorHandle, LOGICAL _isCursorHandle, PULONG _xX, PULONG _yY);
    HDESK nt_user_get_input_desktop();
    HANDLE nt_user_get_input_event(ULONG _wakeMask);
    ULONG nt_user_get_keyboard_type(ULONG _typeFlag);
    BOOL nt_user_get_layered_window_attributes(HWND _windowHandle, COLORREF* _key, PBYTE _alpha, PULONG _flags);
    ULONG nt_user_get_list_box_info(HWND _windowHandle);
    BOOL nt_user_get_menu_bar_info(HWND _windowHandle, LONG _idObject, LONG _idItem, PMENUBARINFO _pmbi);
    BOOL nt_user_get_menu_item_rect(HWND _windowHandle, HMENU _menuHandle, ULONG _menuIndex, PRECT _menuRect);
    ULONG nt_user_get_message_pos();
    HWND nt_user_get_modern_app_window(HWND _shellFrame);
    LONG nt_user_get_mouse_move_points_ex(ULONG _mouseMovePointsSize, LPMOUSEMOVEPOINT _inputBuffer, LPMOUSEMOVEPOINT _outputBuffer, LONG _outputBufferCount, ULONG _resolution);
    BOOL nt_user_get_object_information(HANDLE _objectHandle, LONG _index, PVOID _vInfo, ULONG _length, PULONG _lengthNeeded);
    LOGICAL nt_user_get_process_default_layout(PULONG _defaultLayout);
    NTSTATUS nt_user_get_process_u_i_context_information(HANDLE _processHandle, PPROCESS_UICONTEXT_INFORMATION _uIContext);
    HWINSTA nt_user_get_process_window_station();
    HANDLE nt_user_get_prop(HWND _windowHandle, PCWSTR _string);
    HANDLE nt_user_get_prop2(HWND _windowHandle, PCUNICODE_STRING _string);
    ULONG_PTR nt_user_get_queue_iocp();
    ULONG nt_user_get_raw_input_data(HRAWINPUT _rawInputData, ULONG _rawInputCommand, PVOID _rawInputBuffer, PULONG _rawInputBufferSize, ULONG _rawInputHeaderSize);
    ULONG nt_user_get_raw_input_device_list(PRAWINPUTDEVICELIST _rawInputDeviceList, PULONG _rawInputDeviceCount, ULONG _rawInputDeviceSize);
    ULONG nt_user_get_registered_raw_input_devices(PRAWINPUTDEVICE _rawInputDevices, PULONG _rawInputDeviceCount, ULONG _rawInputDeviceSize);
    HWND nt_user_get_send_message_receiver(ULONG _threadIdSender);
    ULONG_PTR nt_user_get_sys_menu_offset(HWND _hwnd);
    HMENU nt_user_get_system_menu(HWND _windowHandle, BOOL _revert);
    HDESK nt_user_get_thread_desktop(ULONG _threadId);
    ULONG_PTR nt_user_get_thread_state(ULONG _userThreadState);
    BOOL nt_user_get_title_bar_info(HWND _windowHandle, PTITLEBARINFO _pti);
    ULONG nt_user_get_unpredicted_message_pos();
    LOGICAL nt_user_get_win_station_info(PWSINFO _wsInfo);
    ULONG nt_user_get_window_context_help_id(HWND _hwnd);
    HDC nt_user_get_window_d_c(HWND _windowHandle);
    BOOL nt_user_get_window_placement(HWND _windowHandle, PWINDOWPLACEMENT _windowPlacement);
    HANDLE nt_user_get_window_process_handle(HWND _windowHandle, ACCESS_MASK _desiredAccess);
    ULONG_PTR nt_user_get_window_track_info_async(HWND _hwnd);
    HWND nt_user_ghost_window_from_hung_window(HWND _windowHandle);
    LOGICAL nt_user_handle_system_thread_creation_failure();
    ULONG_PTR nt_user_hide_cursor_no_capture();
    BOOL nt_user_hilite_menu_item(HWND _windowHandle, HMENU _menuHandle, ULONG _iDHiliteItem, ULONG _hilite);
    HWND nt_user_hung_window_from_ghost_window(HWND _windowHandle);
    LOGICAL nt_user_init_ansi_oem(PCHAR _oemToCharA, PCHAR _charToOemA);
    ULONG_PTR nt_user_init_thread_core_messaging_iocp(HWND _hwnd);
    HICON nt_user_internal_get_window_icon(HWND _windowHandle, ULONG _iconType);
    ULONG nt_user_internal_get_window_text(HWND _windowHandle, LPWSTR _pString, ULONG _cchMaxCount);
    BOOL nt_user_invalidate_rect(HWND _windowHandle, RECT* _rect, BOOL _erase);
    BOOL nt_user_invalidate_rgn(HWND _windowHandle, HRGN _rgnHandle, BOOL _erase);
    LOGICAL nt_user_is_queue_attached();
    BOOL nt_user_is_touch_window(HWND _windowHandle, PULONG _flags);
    LOGICAL nt_user_kill_system_timer(HWND _hwnd, UINT_PTR _iDEvent);
    BOOL nt_user_kill_timer(HWND _windowHandle, ULONG_PTR _iDEvent);
    LOGICAL nt_user_l_w__load_fonts(LOGICAL _remote);
    LOGICAL nt_user_load_cursors_and_icons();
    LOGICAL nt_user_load_user_api_hook();
    LOGICAL nt_user_lock_set_foreground_window(ULONG _lockCode);
    BOOL nt_user_lock_work_station();
    BOOL nt_user_logical_to_physical_point(HWND _windowHandle, LPPOINT _lpPoint);
    PVOID nt_user_map_desktop_object(HANDLE _h);
    LONG nt_user_menu_item_from_point(HWND _windowHandle, HMENU _menuHandle, POINT _ptScreen);
    LOGICAL nt_user_message_beep(ULONG _type);
    BOOL nt_user_move_window(HWND _windowHandle, LONG _x, LONG _y, LONG _width, LONG _height, BOOL _repaint);
    LOGICAL nt_user_nls_kbd_send_i_m_e_notification(ULONG _imeOpen, ULONG _imeConversion);
    LOGICAL nt_user_notify_overlay_window(HWND _hwnd, LOGICAL _enable);
    HANDLE nt_user_open_desktop(PCOBJECT_ATTRIBUTES _objectAttributes, ULONG _flags, ACCESS_MASK _desiredAccess);
    HDESK nt_user_open_input_desktop(ULONG _flags, BOOL _inherit, ACCESS_MASK _desiredAccess);
    HWINSTA nt_user_open_window_station(POBJECT_ATTRIBUTES _objectAttributes, ACCESS_MASK _desiredAccess);
    BOOL nt_user_physical_to_logical_point(HWND _windowHandle, LPPOINT _point);
    LOGICAL nt_user_play_event_sound(ULONG _idSound);
    LOGICAL nt_user_post_quit_message(LONG _exitCode);
    LOGICAL nt_user_prepare_for_logoff();
    BOOL nt_user_print_window(HWND _windowHandle, HDC _hdc, ULONG _flags);
    NTSTATUS nt_user_query_information_thread(HANDLE _threadHandle, USERTHREADINFOCLASS _threadInformationClass, PVOID _threadInformation, PULONG _returnLength);
    BOOL nt_user_query_send_message(PMSG _message);
    ULONG_PTR nt_user_query_window(HWND _windowHandle, WINDOWINFOCLASS _windowInfo);
    NTSTATUS nt_user_raise_lower_shell_window(HWND _windowHandle, BOOLEAN _setWithOptions);
    HWND nt_user_real_child_window_from_point(HWND _windowHandleParent, POINT _ptParentClientCoords);
    ULONG nt_user_realize_palette(HDC _hdc);
    LOGICAL nt_user_reassociate_queue_event_completion_packet();
    LOGICAL nt_user_redraw_frame(HWND _hwnd);
    LOGICAL nt_user_redraw_frame_and_hook(HWND _hwnd);
    LOGICAL nt_user_redraw_title(HWND _hwnd, ULONG _flags);
    BOOL nt_user_redraw_window(HWND _windowHandle, PRECT _lprcUpdate, HRGN _hrgnUpdate, ULONG _flags);
    BOOL nt_user_register_cloaked_notification(HWND _windowHandle, BOOL _register);
    LOGICAL nt_user_register_ghost_window(HWND _ghost, HWND _hung);
    BOOL nt_user_register_hot_key(HWND _windowHandle, LONG _id, ULONG _fsModifiers, ULONG _vk);
    LOGICAL nt_user_register_l_p_k(ULONG _lpkEntryPoints);
    LOGICAL nt_user_register_logon_process(ULONG _processId, PLUID _luidConnect);
    LOGICAL nt_user_register_shell_hook_window(HWND _hwnd);
    LOGICAL nt_user_register_sibling_frost_window(HWND _hwndFrost, HWND _hwnd);
    LOGICAL nt_user_register_system_thread(ULONG _flags);
    LOGICAL nt_user_register_user_hung_app_handlers(PFNW32ET _w32EndTask, HANDLE _eventWowExec);
    LOGICAL nt_user_register_window_arrangement_callout(HWND _hwnd, LOGICAL _register);
    LOGICAL nt_user_release_capture();
    ULONG nt_user_remote_connect_state();
    NTSTATUS nt_user_remote_console_shadow_stop();
    NTSTATUS nt_user_remote_disconnect();
    NTSTATUS nt_user_remote_notify(_DONOTIFYDATA* _doNotifyData);
    NTSTATUS nt_user_remote_passthru_disable();
    NTSTATUS nt_user_remote_passthru_enable();
    NTSTATUS nt_user_remote_reconnect(_DOCONNECTDATA* _doConnectData);
    NTSTATUS nt_user_remote_shadow_cleanup(PVOID _thinwireData, ULONG _thinwireDataLength);
    NTSTATUS nt_user_remote_shadow_setup();
    NTSTATUS nt_user_remote_shadow_start(PVOID _thinwireData, ULONG _thinwireDataLength);
    NTSTATUS nt_user_remote_shadow_stop();
    NTSTATUS nt_user_remote_thinwire_stats(CACHE_STATISTICS* _stats);
    BOOL nt_user_remove_menu(HMENU _menuHandle, ULONG _position, ULONG _flags);
    LOGICAL nt_user_remove_queue_completion();
    LOGICAL nt_user_reply_message(LRESULT _result);
    LOGICAL nt_user_reset_dbl_clk();
    ULONG_PTR nt_user_scale_system_metric_for_d_p_i_without_cache(ULONG _metric, ULONG _toDpi);
    LOGICAL nt_user_schedule_dispatch_notification(HWND _hwnd);
    ULONG nt_user_send_input(ULONG _count, LPINPUT _inputs, LONG _size);
    HWND nt_user_set_active_window(HWND _windowHandle);
    ULONG nt_user_set_additional_foreground_boost_processes(HWND _windowHandle);
    ULONG nt_user_set_additional_power_throttling_process(HWND _windowHandle, ULONG _processHandlesCount, PHANDLE _processHandles);
    LOGICAL nt_user_set_cancel_rotation_delay_hint_window(HWND _hwnd);
    HWND nt_user_set_capture(HWND _windowHandle);
    LOGICAL nt_user_set_caret_blink_time(ULONG _milliseconds);
    LOGICAL nt_user_set_caret_pos(LONG _x, LONG _y);
    NTSTATUS nt_user_set_child_window_no_activate(HWND _windowHandle);
    USHORT nt_user_set_class_word(HWND _windowHandle, LONG _index, USHORT _newWord);
    BOOL nt_user_set_cursor_pos(LONG _x, LONG _y);
    LOGICAL nt_user_set_dialog_pointer(HWND _hwnd, ULONG_PTR _ptr);
    LOGICAL nt_user_set_dialog_system_menu(HWND _hwnd);
    LOGICAL nt_user_set_double_click_time(ULONG _milliseconds);
    HWND nt_user_set_focus(HWND _windowHandle);
    LOGICAL nt_user_set_foreground_window(HWND _hwnd);
    NTSTATUS nt_user_set_foreground_window_for_application(HWND _windowHandle);
    NTSTATUS nt_user_set_information_thread(HANDLE _threadHandle, USERTHREADINFOCLASS _threadInformationClass, PVOID _threadInformation, ULONG _threadInformationLength);
    BOOL nt_user_set_layered_window_attributes(HWND _windowHandle, COLORREF _key, BYTE _alpha, ULONG _flags);
    LPARAM nt_user_set_message_extra_info(LPARAM _param);
    LOGICAL nt_user_set_modern_app_window(HWND _shellFrame, HWND _app);
    LOGICAL nt_user_set_msg_box(HWND _hwnd);
    LOGICAL nt_user_set_process_default_layout(ULONG _defaultLayout);
    NTSTATUS nt_user_set_process_restriction_exemption(BOOL _enableExemption);
    NTSTATUS nt_user_set_process_u_i_access_zorder();
    NTSTATUS nt_user_set_process_win32_capabilities(USER_PROCESS_CAP_ENTRY* _capabilities, ULONG _count);
    BOOL nt_user_set_process_window_station(HWINSTA _windowStationHandle);
    LOGICAL nt_user_set_progman_window(HWND _hwnd);
    LOGICAL nt_user_set_shell_change_notify_h_w_n_d(HWND _hwnd);
    LOGICAL nt_user_set_sys_menu(HWND _hwnd);
    LOGICAL nt_user_set_t_s_f_event_state(ULONG _stateFlags);
    LOGICAL nt_user_set_taskman_window(HWND _hwnd);
    BOOL nt_user_set_thread_desktop(HDESK _desktopHandle);
    LOGICAL nt_user_set_thread_queue_merge_setting(ULONG _threadId, ULONG _flags);
    ULONG_PTR nt_user_set_timer(HWND _windowHandle, ULONG_PTR _iDEvent, ULONG _elapse, TIMERPROC _timerFunc, ULONG _toleranceDelay);
    LOGICAL nt_user_set_visible(HWND _hwnd, ULONG _flags);
    LOGICAL nt_user_set_wait_for_queue_attach(LOGICAL _waiting);
    LOGICAL nt_user_set_watermark_strings(PCUNICODE_STRING _stringTable);
    LOGICAL nt_user_set_window_context_help_id(HWND _hwnd, ULONG _contextId);
    BOOL nt_user_set_window_placement(HWND _windowHandle, WINDOWPLACEMENT* _lpwndpl);
    BOOL nt_user_set_window_pos(HWND _windowHandle, HWND _windowHandleInsertAfter, LONG _x, LONG _y, LONG _cx, LONG _cy, ULONG _flags);
    LOGICAL nt_user_set_window_state(HWND _hwnd, ULONG _flag);
    BOOL nt_user_set_window_station_user(HWINSTA _windowStationHandle, PLUID _userLogonId, PSID _userSid, ULONG _userSidLength);
    USHORT nt_user_set_window_word(HWND _windowHandle, LONG _index, USHORT _newWord);
    HWND nt_user_shell_foreground_boost_process(HANDLE _processHandle, HWND _windowHandle);
    LONG nt_user_show_cursor(BOOL _show);
    LOGICAL nt_user_show_owned_popups(HWND _owner, LOGICAL _show);
    LOGICAL nt_user_show_start_glass(ULONG _timeout);
    BOOL nt_user_show_window(HWND _windowHandle, LONG _cmdShow);
    BOOL nt_user_show_window_async(HWND _windowHandle, LONG _cmdShow);
    BOOL nt_user_shutdown_block_reason_query(HWND _windowHandle, PWSTR _buffer, PULONG _bufferCount);
    BOOL nt_user_shutdown_reason_destroy(HWND _windowHandle);
    LOGICAL nt_user_swap_mouse_button(LOGICAL _swapButtons);
    BOOL nt_user_switch_desktop(HDESK _desktopHandle, ULONG _flags, ULONG _fadeTime);
    LOGICAL nt_user_switch_to_this_window(HWND _hwnd, LOGICAL _altTab);
    NTSTATUS nt_user_test_for_interactive_user(PLUID _authenticationId);
    LOGICAL nt_user_thread_message_queue_attached(ULONG _threadId);
    BOOL nt_user_track_mouse_event(LPTRACKMOUSEEVENT _eventTrack);
    BOOL nt_user_track_popup_menu_ex(HMENU _menuHandle, ULONG _flags, LONG _x, LONG _y, HWND _windowHandle, LPTPMPARAMS _lptpm);
    BOOL nt_user_unhook_win_event(HWINEVENTHOOK _winEventHookHandle);
    LOGICAL nt_user_unhook_windows_hook(LONG _filterType, HOOKPROC _filterProc);
    BOOL nt_user_unregister_hot_key(HWND _windowHandle, LONG _id);
    LOGICAL nt_user_update_client_rect(HWND _hwnd);
    LOGICAL nt_user_update_per_user_imm_enabling();
    LOGICAL nt_user_update_window(HWND _hwnd);
    LOGICAL nt_user_update_windows(HWND _hwnd, HRGN _hrgn);
    BOOL nt_user_user_handle_grant_access(HANDLE _userHandle, HANDLE _job, BOOL _grant);
    LOGICAL nt_user_user_power_callout_worker();
    BOOL nt_user_validate_rect(HWND _windowHandle, RECT* _rect);
    LOGICAL nt_user_validate_rgn(HWND _hwnd, HRGN _hrgn);
    LOGICAL nt_user_w_o_w_module_unload(HANDLE _module);
    NTSTATUS nt_user_wake_r_i_t_for_shutdown();
    HWND nt_user_window_from_d_c(HDC _hdc);
    HWND nt_user_window_from_physical_point(POINT _point);
    HWND nt_user_window_from_point(POINT _point);
    LOGICAL nt_user_zap_active_and_focus();
    NTSTATUS nt_vdm_control(VDMSERVICECLASS _service, PVOID _serviceData);
    NTSTATUS nt_wait_for_alert_by_thread_id(PVOID _address, PLARGE_INTEGER _timeout);
    NTSTATUS nt_wait_for_debug_event(HANDLE _debugObjectHandle, BOOLEAN _alertable, PLARGE_INTEGER _timeout, PDBGUI_WAIT_STATE_CHANGE _waitStateChange);
    NTSTATUS nt_wait_for_keyed_event(HANDLE _keyedEventHandle, PVOID _keyValue, BOOLEAN _alertable, PLARGE_INTEGER _timeout);
    NTSTATUS nt_wait_for_multiple_objects(ULONG _count, HANDLE _handles[], WAIT_TYPE _waitType, BOOLEAN _alertable, PLARGE_INTEGER _timeout);
    NTSTATUS nt_wait_for_multiple_objects32(ULONG _count, LONG _handles[], WAIT_TYPE _waitType, BOOLEAN _alertable, PLARGE_INTEGER _timeout);
    NTSTATUS nt_wait_for_single_object(HANDLE _handle, BOOLEAN _alertable, PLARGE_INTEGER _timeout);
    NTSTATUS nt_wait_for_work_via_worker_factory(HANDLE _workerFactoryHandle, PFILE_IO_COMPLETION_INFORMATION _miniPackets, ULONG _count, PULONG _packetsReturned, PVOID _deferredWork);
    NTSTATUS nt_wait_high_event_pair(HANDLE _eventPairHandle);
    NTSTATUS nt_wait_low_event_pair(HANDLE _eventPairHandle);
    NTSTATUS nt_worker_factory_worker_ready(HANDLE _workerFactoryHandle);
    NTSTATUS nt_wow64_get_native_system_information(SYSTEM_INFORMATION_CLASS _systemInformationClass, PVOID _nativeSystemInformation, ULONG _informationLength, PULONG _returnLength);
    NTSTATUS nt_wow64_query_information_process64(HANDLE _processHandle, PROCESSINFOCLASS _processInformationClass, PVOID _processInformation, ULONG _processInformationLength, PULONG _returnLength);
    NTSTATUS nt_wow64_query_virtual_memory64(HANDLE _processHandle, ULONGLONG _baseAddress, MEMORY_INFORMATION_CLASS _memoryInformationClass, PVOID _memoryInformation, ULONGLONG _memoryInformationLength, PULONGLONG _returnLength);
    NTSTATUS nt_wow64_read_virtual_memory64(HANDLE _processHandle, ULONGLONG _baseAddress, PVOID _buffer, ULONGLONG _numberOfBytesToRead, PULONGLONG _numberOfBytesRead);
    NTSTATUS nt_wow64_write_virtual_memory64(HANDLE _processHandle, ULONGLONG _baseAddress, PVOID _buffer, ULONGLONG _numberOfBytesToWrite, PULONGLONG _numberOfBytesWritten);
    NTSTATUS nt_write_file(HANDLE _fileHandle, HANDLE _event, PIO_APC_ROUTINE _apcRoutine, PVOID _apcContext, PIO_STATUS_BLOCK _ioStatusBlock, PVOID _buffer, ULONG _length, PLARGE_INTEGER _byteOffset, PULONG _key);
    NTSTATUS nt_write_file_gather(HANDLE _fileHandle, HANDLE _event, PIO_APC_ROUTINE _apcRoutine, PVOID _apcContext, PIO_STATUS_BLOCK _ioStatusBlock, PFILE_SEGMENT_ELEMENT _segmentArray, ULONG _length, PLARGE_INTEGER _byteOffset, PULONG _key);
    NTSTATUS nt_write_request_data(HANDLE _portHandle, PPORT_MESSAGE _message, ULONG _dataEntryIndex, PVOID _buffer, SIZE_T _bufferSize, PSIZE_T _numberOfBytesWritten);
    NTSTATUS nt_write_virtual_memory(HANDLE _processHandle, PVOID _baseAddress, PVOID _buffer, SIZE_T _numberOfBytesToWrite, PSIZE_T _numberOfBytesWritten);
    NTSTATUS nt_yield_execution();
}