#pragma once

union graft_args;
using graftdmg_args_un = graft_args;
struct shared_file_np;
struct ntptimeval;
struct net_qos_param;
struct ch_info;
struct ch_init;
struct kpersona_info;
struct msghdr_x;
using __uint8_t = unsigned char;
using uint8_t = __uint8_t;
using mach_port_name_t = int;
struct Mac;
struct kevent_qos_s;
struct necp_aggregate_result;
struct kevent64_s;
struct kevent;
struct auditinfo_addr;
using __id_t = unsigned int;
using id_t = __id_t;
struct timeval;
using __caddr_t = char *;
using caddr_t = __caddr_t;
using __u_long = unsigned long;
using u_long = __u_long;
struct rusage;
struct msqid_ds;
using __u_int = unsigned int;
using u_int = __u_int;
struct itimerval;
struct sigaction;
struct fhandle;
struct _posix_spawn_args_desc;
using __pid_t = int;
using pid_t = __pid_t;
using au_asid_t = pid_t;
using __uint32_t = unsigned int;
using u_int32_t = __uint32_t;
struct attrlist;
using size_t = int;
struct sembuf;
struct __sigaction;
struct shmid_ds;
using __uint64_t = unsigned long;
using uint64_t = __uint64_t;
struct msghdr;
struct searchstate;
using uint32_t = __uint32_t;
using __gid_t = unsigned int;
using gid_t = __gid_t;
struct iovec;
using caddr_ut = caddr_t;
struct sigaltstack;
using __uid_t = unsigned int;
using uid_t = __uid_t;
using size_ut = __typeof__(sizeof(int));
using __socklen_t = unsigned int;
using socklen_t = __socklen_t;
struct ucontext;
struct siginfo_t;
enum idtype_t { };
struct sockaddr;
struct statfs64;
struct nxprov_reg;
struct nxctl_init;
struct timespec;
using __off_t = long;
using off_t = __off_t;
using au_id_t = uid_t;
struct statfs;
struct timex;
using fhandle_t = fhandle;
using uuid_t = unsigned char[16];
using __key_t = int;
using key_t = __key_t;
struct rlimit;
struct pollfd;
using sem_t = int;
using __darwin_sigset_t = __uint32_t;
using sigset_t = __darwin_sigset_t;
using __int64_t = long;
using int64_t = __int64_t;
using __int32_t = int;
using int32_t = __int32_t;
struct shared_file_mapping_slide_np_t;
using shared_file_mapping_slide_np_ut = shared_file_mapping_slide_np_t;
typedef __uint32_t sae_associd_t;
struct sa_endpoints;
using sa_endpoints_t = sa_endpoints;
using u_int64_t = __uint64_t;
using user_size_t = u_int64_t;
using user_ssize_t = int64_t;
using user_addr_t = u_int64_t;
struct fssearchblock;
struct sigvec;
struct timezone;
struct sf_hdtr;
using sae_connid_t = __uint32_t;
using guardid_t = __uint64_t;
union semun {
    int             val;            /* value for SETVAL */
    struct semid_ds *buf;           /* buffer for IPC_STAT & IPC_SET */
    unsigned short  *array;         /* array for GETALL & SETALL */
};
typedef union semun semun_t;