#pragma once

union graft_args;
using graftdmg_args_un = union graft_args;
struct shared_file_np;
struct kpersona_info;
struct msghdr_x;
using __uint8_t = unsigned char;
using uint8_t = __uint8_t;
using __uint32_t = unsigned int;
using sae_associd_t = __uint32_t;
struct sa_endpoints;
using sa_endpoints_t = struct sa_endpoints;
using mach_port_name_t = int;
struct mac;
struct kevent_qos_s;
struct kevent;
using int32_t = int;
using caddr_t = char *;
using u_long = unsigned long;
struct rusage;
using u_int = unsigned int;
struct itimerval;
struct sigaction;
struct _posix_spawn_args_desc;
using int64_t = long long;
using user_ssize_t = int64_t;
using __int32_t = int;
using __darwin_pid_t = __int32_t;
using pid_t = __darwin_pid_t;
using au_asid_t = pid_t;
using u_int32_t = unsigned int;
using u_int64_t = unsigned long long;
using user_size_t = u_int64_t;
using user_addr_t = u_int64_t;
struct attrlist;
struct msghdr;
struct searchstate;
using __darwin_size_t = unsigned long;
using size_t = __darwin_size_t;
struct sembuf;
struct __sigaction;
using __uint64_t = unsigned long long;
using uint64_t = __uint64_t;
struct kevent64_s;
using uint32_t = __uint32_t;
using __darwin_gid_t = __uint32_t;
using gid_t = __darwin_gid_t;
struct iovec;
using caddr_ut = caddr_t;
struct sigaltstack;
using __darwin_uid_t = __uint32_t;
using uid_t = __darwin_uid_t;
struct fssearchblock;
using __darwin_socklen_t = __uint32_t;
using socklen_t = __darwin_socklen_t;
struct timeval;
using __darwin_id_t = __uint32_t;
using id_t = __darwin_id_t;
struct __siginfo;
using siginfo_t = struct __siginfo;
struct statfs64;
enum idtype_t { };
struct sockaddr;
struct sf_hdtr;
using sae_connid_t = __uint32_t;
struct timespec;
using __int64_t = long long;
using __darwin_off_t = __int64_t;
using off_t = __darwin_off_t;
using au_id_t = uid_t;
struct statfs;
struct fhandle;
using fhandle_t = struct fhandle;
using __darwin_uuid_t = unsigned char[16];
using uuid_t = __darwin_uuid_t;
using key_t = __int32_t;
struct rlimit;
union semun;
using semun_t = union semun;
using sem_t = int;
using __darwin_sigset_t = __uint32_t;
using sigset_t = __darwin_sigset_t;
