#include "syscall/lin/Call.hh"
#include "syscall/lin/Func.hh"
#include "syscall/lin/ID.hh"
namespace cmn::syscall
{
    #define SYSCALL0(_name, _id                                                                                          ) i64 _name(                                                                                          ) {return syscall(_id                                                                        );}
    #define SYSCALL1(_name, _id, _type0, _arg0                                                                           ) i64 _name(_type0, _type0 _arg0                                                                      ) {return syscall(_id, (i64)_arg0                                                            );}
    #define SYSCALL2(_name, _id, _type0, _arg0, _type1, _arg1                                                            ) i64 _name(_type0, _type0 _arg0, _type1 _arg1                                                        ) {return syscall(_id, (i64)_arg0, (i64)_arg1                                                );}
    #define SYSCALL3(_name, _id, _type0, _arg0, _type1, _arg1, _type2, _arg2                                             ) i64 _name(_type0, _type0 _arg0, _type1 _arg1, _type2 _arg2                                          ) {return syscall(_id, (i64)_arg0, (i64)_arg1, (i64)_arg2                                    );}
    #define SYSCALL4(_name, _id, _type0, _arg0, _type1, _arg1, _type2, _arg2, _type3, _arg3                              ) i64 _name(_type0, _type0 _arg0, _type1 _arg1, _type2 _arg2, _type3 _arg3                            ) {return syscall(_id, (i64)_arg0, (i64)_arg1, (i64)_arg2, (i64)_arg3                        );}
    #define SYSCALL5(_name, _id, _type0, _arg0, _type1, _arg1, _type2, _arg2, _type3, _arg3, _type4, _arg4               ) i64 _name(_type0, _type0 _arg0, _type1 _arg1, _type2 _arg2, _type3 _arg3, _type4 _arg4              ) {return syscall(_id, (i64)_arg0, (i64)_arg1, (i64)_arg2, (i64)_arg3, (i64)_arg4            );}
    #define SYSCALL6(_name, _id, _type0, _arg0, _type1, _arg1, _type2, _arg2, _type3, _arg3, _type4, _arg4, _type5, _arg5) i64 _name(_type0, _type0 _arg0, _type1 _arg1, _type2 _arg2, _type3 _arg3, _type4 _arg4, _type5 _arg5) {return syscall(_id, (i64)_arg0, (i64)_arg1, (i64)_arg2, (i64)_arg3, (i64)_arg4, (i64)_arg5);}

    SYSCALL3(accept_connection                        , ACCEPT_CONNECTION                        , i32, _fileDescriptor, SocketAddress*, _peerSocketAddress, i32*, _peerAddressLength)
    SYSCALL4(accept_connection_with_flags             , ACCEPT_CONNECTION_WITH_FLAGS             , i32, _fileDescriptor, SocketAddress*, _peerSocketAddress, i32*, _peerAddressLength, i32, _flags)
    SYSCALL3(add_inotify_watch                        , ADD_INOTIFY_WATCH                        , i32, _fileDescriptor, const c08*, _pathName, u32, _mask)
    SYSCALL5(add_key_to_keyring                       , ADD_KEY_TO_KEYRING                       , const c08*, _type, const c08*, _description, const void*, _payload, s64, _payloadLength, i32, _keyringId)
    SYSCALL4(add_landlock_rule                        , ADD_LANDLOCK_RULE                        , const i32, _rulesetFileDescriptor, const LandlockRulesetType, _ruleType, const void* const, _ruleAttributes, const u32, _flags)
    SYSCALL2(adjust_clock                             , ADJUST_CLOCK                             , const i32, _clockId, KernelTimeAdjustment*, _timeAdjustment)
    SYSCALL1(adjust_system_clock                      , ADJUST_SYSTEM_CLOCK                      , KernelTimeAdjustment*, _timeAdjustment)
    SYSCALL3(advise_memory                            , ADVISE_MEMORY                            , u64, _startAddress, s64, _length, i32, _behavior)
    SYSCALL5(advise_process_memory                    , ADVISE_PROCESS_MEMORY                    , i32, _processFileDescriptor, const IoVector*, _vectors, s64, _vectorCount, i32, _behavior, u32, _flags)
    SYSCALL4(allocate_file_space                      , ALLOCATE_FILE_SPACE                      , i32, _fileDescriptor, i32, _mode, i64, _offset, i64, _length)
    SYSCALL2(allocate_memory_protection_key           , ALLOCATE_MEMORY_PROTECTION_KEY           , u64, _flags, u64, _initialRights)
    SYSCALL2(apply_landlock_ruleset                   , APPLY_LANDLOCK_RULESET                   , const i32, _rulesetFileDescriptor, const u32, _flags)
    SYSCALL3(attach_shared_memory                     , ATTACH_SHARED_MEMORY                     , i32, _sharedMemoryId, c08*, _sharedMemoryAddress, i32, _flags)
    SYSCALL6(bind_memory_policy                       , BIND_MEMORY_POLICY                       , u64, _startAddress, u64, _length, u64, _mode, const u64*, _nodeMask, u64, _maximumNode, u32, _flags)
    SYSCALL3(bind_socket                              , BIND_SOCKET                              , i32, _fileDescriptor, SocketAddress*, _socketAddress, i32, _addressLength)
    SYSCALL1(brk                                      , BRK                                      , u64, _programBreak)
    SYSCALL3(cancel_async_io                          , CANCEL_ASYNC_IO                          , u64, _contextId, IoControlBlock*, _ioControlBlock, IoCompletionEvent*, _result)
    SYSCALL2(change_file_mode                         , CHANGE_FILE_MODE                         , u32, _fileDescriptor, u16, _mode)
    SYSCALL3(change_file_mode_at                      , CHANGE_FILE_MODE_AT                      , i32, _directoryFileDescriptor, const c08*, _fileName, u16, _mode)
    SYSCALL4(change_file_mode_at_with_flags           , CHANGE_FILE_MODE_AT_WITH_FLAGS           , i32, _directoryFileDescriptor, const c08*, _fileName, u16, _mode, u32, _flags)
    SYSCALL3(change_file_owner                        , CHANGE_FILE_OWNER                        , u32, _fileDescriptor, u32, _userId, u32, _groupId)
    SYSCALL5(change_file_owner_at                     , CHANGE_FILE_OWNER_AT                     , i32, _directoryFileDescriptor, const c08*, _fileName, u32, _userId, u32, _groupId, i32, _flags)
    SYSCALL1(change_root_directory                    , CHANGE_ROOT_DIRECTORY                    , const c08*, _fileName)
    SYSCALL2(change_root_mount                        , CHANGE_ROOT_MOUNT                        , const c08*, _newRoot, const c08*, _oldRootLocation)
    SYSCALL1(change_working_directory                 , CHANGE_WORKING_DIRECTORY                 , const c08*, _fileName)
    SYSCALL1(change_working_directory_from_descriptor , CHANGE_WORKING_DIRECTORY_FROM_DESCRIPTOR , u32, _fileDescriptor)
    SYSCALL3(check_file_access_at                     , CHECK_FILE_ACCESS_AT                     , i32, _directoryFileDescriptor, const c08*, _fileName, i32, _mode)
    SYSCALL4(check_file_access_at_with_flags          , CHECK_FILE_ACCESS_AT_WITH_FLAGS          , i32, _directoryFileDescriptor, const c08*, _fileName, i32, _mode, i32, _flags)
    SYSCALL1(close_file_descriptor                    , CLOSE_FILE_DESCRIPTOR                    , u32, _fileDescriptor)
    SYSCALL3(close_file_descriptor_range              , CLOSE_FILE_DESCRIPTOR_RANGE              , u32, _firstFileDescriptor, u32, _maximumFileDescriptor, u32, _flags)
    SYSCALL5(compare_process_resources                , COMPARE_PROCESS_RESOURCES                , i32, _processId1, i32, _processId2, i32, _type, u64, _index1, u64, _index2)
    SYSCALL4(configure_epoll_watch                    , CONFIGURE_EPOLL_WATCH                    , i32, _epollFileDescriptor, i32, _operation, i32, _fileDescriptor, EpollEventData*, _event)
    SYSCALL5(configure_filesystem_context             , CONFIGURE_FILESYSTEM_CONTEXT             , i32, _fileDescriptor, u32, _command, const c08*, _key, const void*, _value, i32, _auxiliary)
    SYSCALL4(configure_io_uring                       , CONFIGURE_IO_URING                       , u32, _fileDescriptor, u32, _operationCode, void*, _argument, u32, _argumentCount)
    SYSCALL3(configure_message_queue_attributes       , CONFIGURE_MESSAGE_QUEUE_ATTRIBUTES       , i32, _messageQueueDescriptor, const MessageQueueAttributes*, _newAttributes, MessageQueueAttributes*, _oldAttributes)
    SYSCALL2(configure_message_queue_notification     , CONFIGURE_MESSAGE_QUEUE_NOTIFICATION     , i32, _messageQueueDescriptor, const SignalEvent*, _notification)
    SYSCALL1(configure_process_accounting             , CONFIGURE_PROCESS_ACCOUNTING             , const c08*, _fileName)
    SYSCALL1(configure_process_personality            , CONFIGURE_PROCESS_PERSONALITY            , u32, _personality)
    SYSCALL4(configure_process_resource_limit         , CONFIGURE_PROCESS_RESOURCE_LIMIT         , i32, _processId, u32, _resource, const ResourceLimit64*, _newLimit, ResourceLimit64*, _oldLimit)
    SYSCALL4(configure_restartable_sequence           , CONFIGURE_RESTARTABLE_SEQUENCE           , RestartableSequence*, _restartableSequence, u32, _restartableSequenceLength, i32, _flags, u32, _signature)
    SYSCALL4(configure_signal_action                  , CONFIGURE_SIGNAL_ACTION                  , i32, _signal, const SignalAction*, _action, SignalAction*, _oldAction, s64, _signalSetSize)
    SYSCALL4(configure_signal_descriptor              , CONFIGURE_SIGNAL_DESCRIPTOR              , i32, _fileDescriptor, SignalSet*, _signalMask, s64, _signalMaskSize, i32, _flags)
    SYSCALL4(configure_signal_mask                    , CONFIGURE_SIGNAL_MASK                    , i32, _how, SignalSet*, _newSignalSet, SignalSet*, _oldSignalSet, s64, _signalSetSize)
    SYSCALL2(configure_signal_stack                   , CONFIGURE_SIGNAL_STACK                   , const SignalStack*, _newStack, SignalStack*, _oldStack)
    SYSCALL3(configure_syscall_filtering              , CONFIGURE_SYSCALL_FILTERING              , u32, _operation, u32, _flags, void*, _arguments)
    SYSCALL3(connect_socket                           , CONNECT_SOCKET                           , i32, _fileDescriptor, SocketAddress*, _serverAddress, i32, _addressLength)
    SYSCALL3(control_file_descriptor                  , CONTROL_FILE_DESCRIPTOR                  , u32, _fileDescriptor, u32, _command, u64, _argument)
    SYSCALL4(control_filesystem_quota                 , CONTROL_FILESYSTEM_QUOTA                 , u32, _command, const c08*, _specialDevice, u32, _quotaId, void*, _address)
    SYSCALL4(control_filesystem_quota_by_descriptor   , CONTROL_FILESYSTEM_QUOTA_BY_DESCRIPTOR   , u32, _fileDescriptor, u32, _command, u32, _quotaId, void*, _address)
    SYSCALL5(control_kernel_keys                      , CONTROL_KERNEL_KEYS                      , i32, _option, u64, _argument2, u64, _argument3, u64, _argument4, u64, _argument5)
    SYSCALL3(control_kernel_log                       , CONTROL_KERNEL_LOG                       , i32, _type, c08*, _buffer, i32, _length)
    SYSCALL3(control_message_queue                    , CONTROL_MESSAGE_QUEUE                    , i32, _messageQueueId, i32, _command, MessageQueueStatus*, _buffer)
    SYSCALL5(control_process                          , CONTROL_PROCESS                          , i32, _option, u64, _argument2, u64, _argument3, u64, _argument4, u64, _argument5)
    SYSCALL4(control_process_trace                    , CONTROL_PROCESS_TRACE                    , i64, _request, i64, _processId, u64, _address, u64, _data)
    SYSCALL4(control_semaphore_set                    , CONTROL_SEMAPHORE_SET                    , i32, _semaphoreId, i32, _semaphoreNumber, i32, _command, u64, _argument)
    SYSCALL3(control_shared_memory                    , CONTROL_SHARED_MEMORY                    , i32, _sharedMemoryId, i32, _command, SharedMemoryStatus*, _buffer)
    SYSCALL4(control_system_power                     , CONTROL_SYSTEM_POWER                     , i32, _magic1, i32, _magic2, u32, _command, void*, _argument)
    SYSCALL6(copy_file_data                           , COPY_FILE_DATA                           , i32, _inputFileDescriptor, i64*, _inputOffset, i32, _outputFileDescriptor, i64*, _outputOffset, s64, _length, u32, _flags)
    SYSCALL4(copy_file_to_descriptor                  , COPY_FILE_TO_DESCRIPTOR                  , i32, _outputFileDescriptor, i32, _inputFileDescriptor, i64*, _offset, s64, _count)
    SYSCALL2(create_async_io_context                  , CREATE_ASYNC_IO_CONTEXT                  , u32, _eventCount, u64*, _context)
    SYSCALL5(create_child_task                        , CREATE_CHILD_TASK                        , u64, _cloneFlags, u64, _newStackPointer, i32*, _parentThreadId, u64, _threadLocalStorage, i32*, _childThreadId)
    SYSCALL2(create_child_task_with_options           , CREATE_CHILD_TASK_WITH_OPTIONS           , CloneArguments*, _arguments, s64, _size)
    SYSCALL3(create_detached_mount                    , CREATE_DETACHED_MOUNT                    , i32, _fileSystemFileDescriptor, u32, _flags, u32, _attributeFlags)
    SYSCALL3(create_directory_at                      , CREATE_DIRECTORY_AT                      , i32, _directoryFileDescriptor, const c08*, _pathName, u16, _mode)
    SYSCALL1(create_epoll                             , CREATE_EPOLL                             , i32, _flags)
    SYSCALL2(create_event_counter                     , CREATE_EVENT_COUNTER                     , u32, _initialValue, i32, _flags)
    SYSCALL2(create_fanotify_group                    , CREATE_FANOTIFY_GROUP                    , u32, _flags, u32, _eventFileFlags)
    SYSCALL2(create_filesystem_context                , CREATE_FILESYSTEM_CONTEXT                , const c08*, _fileSystemName, u32, _flags)
    SYSCALL4(create_filesystem_node_at                , CREATE_FILESYSTEM_NODE_AT                , i32, _directoryFileDescriptor, const c08*, _fileName, u16, _mode, u32, _device)
    SYSCALL5(create_hard_link_at                      , CREATE_HARD_LINK_AT                      , i32, _oldDirectoryFileDescriptor, const c08*, _oldName, i32, _newDirectoryFileDescriptor, const c08*, _newName, i32, _flags)
    SYSCALL1(create_inotify                           , CREATE_INOTIFY                           , i32, _flags)
    SYSCALL2(create_io_uring                          , CREATE_IO_URING                          , u32, _entries, IoUringParameters*, _parameters)
    SYSCALL3(create_landlock_ruleset                  , CREATE_LANDLOCK_RULESET                  , const LandlockRulesetAttributes* const, _attributes, const u64, _size, const u32, _flags)
    SYSCALL2(create_memory_file                       , CREATE_MEMORY_FILE                       , const c08*, _name, u32, _flags)
    SYSCALL2(create_pipe                              , CREATE_PIPE                              , i32*, _fileDescriptors, i32, _flags)
    SYSCALL0(create_process_session                   , CREATE_PROCESS_SESSION                   )
    SYSCALL3(create_process_timer                     , CREATE_PROCESS_TIMER                     , const i32, _clockId, SignalEvent*, _timerEventSpecification, i32*, _createdTimerId)
    SYSCALL1(create_secret_memory                     , CREATE_SECRET_MEMORY                     , i32, _flags)
    SYSCALL3(create_shadow_stack                      , CREATE_SHADOW_STACK                      , u64, _address, u64, _size, u32, _flags)
    SYSCALL3(create_socket                            , CREATE_SOCKET                            , i32, _family, i32, _type, i32, _protocol)
    SYSCALL4(create_socket_pair                       , CREATE_SOCKET_PAIR                       , i32, _family, i32, _type, i32, _protocol, i32*, _socketDescriptors)
    SYSCALL3(create_symbolic_link_at                  , CREATE_SYMBOLIC_LINK_AT                  , const c08*, _oldName, i32, _newDirectoryFileDescriptor, const c08*, _newName)
    SYSCALL2(create_timer_descriptor                  , CREATE_TIMER_DESCRIPTOR                  , i32, _clockId, i32, _flags)
    SYSCALL1(create_user_fault_descriptor             , CREATE_USER_FAULT_DESCRIPTOR             , i32, _flags)
    SYSCALL1(delete_process_timer                     , DELETE_PROCESS_TIMER                     , i32, _timerId)
    SYSCALL1(destroy_async_io_context                 , DESTROY_ASYNC_IO_CONTEXT                 , u64, _context)
    SYSCALL1(detach_shared_memory                     , DETACH_SHARED_MEMORY                     , c08*, _sharedMemoryAddress)
    SYSCALL1(disable_swap                             , DISABLE_SWAP                             , const c08*, _specialFile)
    SYSCALL1(duplicate_file_descriptor                , DUPLICATE_FILE_DESCRIPTOR                , u32, _fileDescriptor)
    SYSCALL3(duplicate_file_descriptor_to             , DUPLICATE_FILE_DESCRIPTOR_TO             , u32, _oldFileDescriptor, u32, _newFileDescriptor, i32, _flags)
    SYSCALL4(duplicate_pipe_data                      , DUPLICATE_PIPE_DATA                      , i32, _inputFileDescriptor, i32, _outputFileDescriptor, s64, _length, u32, _flags)
    SYSCALL3(duplicate_process_descriptor             , DUPLICATE_PROCESS_DESCRIPTOR             , i32, _processFileDescriptor, i32, _fileDescriptor, u32, _flags)
    SYSCALL2(enable_swap                              , ENABLE_SWAP                              , const c08*, _specialFile, i32, _swapFlags)
    SYSCALL3(execute_bpf_command                      , EXECUTE_BPF_COMMAND                      , i32, _command, union bpf_attr*, _attributes, u32, _size)
    SYSCALL3(execute_program                          , EXECUTE_PROGRAM                          , const c08*, _fileName, const c08* const*, _arguments, const c08* const*, _environment)
    SYSCALL5(execute_program_at                       , EXECUTE_PROGRAM_AT                       , i32, _fileDescriptor, const c08*, _fileName, const c08* const*, _arguments, const c08* const*, _environment, i32, _flags)
    SYSCALL1(exit_process                             , EXIT_PROCESS                             , i32, _errorCode)
    SYSCALL1(exit_thread                              , EXIT_THREAD                              , i32, _errorCode)
    SYSCALL1(free_memory_protection_key               , FREE_MEMORY_PROTECTION_KEY               , i32, _protectionKey)
    SYSCALL5(get_async_io_completions                 , GET_ASYNC_IO_COMPLETIONS                 , u64, _contextId, i64, _minimumEvents, i64, _eventCount, IoCompletionEvent*, _events, KernelTimeSpecification*, _timeout)
    SYSCALL6(get_async_io_completions_with_signal_mask, GET_ASYNC_IO_COMPLETIONS_WITH_SIGNAL_MASK, u64, _contextId, i64, _minimumEvents, i64, _eventCount, IoCompletionEvent*, _events, KernelTimeSpecification*, _timeout, const AioSignalSet*, _signalSet)
    SYSCALL2(get_clock_resolution                     , GET_CLOCK_RESOLUTION                     , const i32, _clockId, KernelTimeSpecification*, _resolution)
    SYSCALL2(get_clock_time                           , GET_CLOCK_TIME                           , const i32, _clockId, KernelTimeSpecification*, _time)
    SYSCALL3(get_cpu_affinity                         , GET_CPU_AFFINITY                         , i32, _processId, u32, _length, u64*, _cpuMask)
    SYSCALL3(get_current_cpu                          , GET_CURRENT_CPU                          , u32*, _cpu, u32*, _node, void*, _unused)
    SYSCALL2(get_descriptor_status                    , GET_DESCRIPTOR_STATUS                    , u32, _fileDescriptor, DescriptorStatus*, _statusBuffer)
    SYSCALL0(get_effective_group_id                   , GET_EFFECTIVE_GROUP_ID                   )
    SYSCALL0(get_effective_user_id                    , GET_EFFECTIVE_USER_ID                    )
    SYSCALL4(get_extended_attribute                   , GET_EXTENDED_ATTRIBUTE                   , i32, _fileDescriptor, const c08*, _name, void*, _value, u64, _size)
    SYSCALL4(get_extended_attribute                   , GET_EXTENDED_ATTRIBUTE                   , const c08*, _pathName, const c08*, _name, void*, _value, u64, _size)
    SYSCALL6(get_extended_attribute_at                , GET_EXTENDED_ATTRIBUTE_AT                , i32, _directoryFileDescriptor, const c08*, _pathName, u32, _lookupFlags, const c08*, _name, ExtendedAttributeArguments*, _arguments, u64, _size)
    SYSCALL4(get_extended_attribute_no_follow         , GET_EXTENDED_ATTRIBUTE_NO_FOLLOW         , const c08*, _pathName, const c08*, _name, void*, _value, u64, _size)
    SYSCALL5(get_extended_file_status                 , GET_EXTENDED_FILE_STATUS                 , i32, _directoryFileDescriptor, const c08*, _fileName, u32, _flags, u32, _mask, ExtendedFileStatus*, _buffer)
    SYSCALL5(get_file_handle_at                       , GET_FILE_HANDLE_AT                       , i32, _directoryFileDescriptor, const c08*, _name, FileHandleInfo*, _fileHandle, void*, _mountId, i32, _flags)
    SYSCALL5(get_filesystem_file_attributes           , GET_FILESYSTEM_FILE_ATTRIBUTES           , i32, _directoryFileDescriptor, const c08*, _fileName, FileAttributes*, _fileAttributes, u64, _size, u32, _lookupFlags)
    SYSCALL2(get_filesystem_statistics                , GET_FILESYSTEM_STATISTICS                , const c08*, _pathName, FilesystemStatistics*, _buffer)
    SYSCALL2(get_filesystem_statistics                , GET_FILESYSTEM_STATISTICS                , u32, _fileDescriptor, FilesystemStatistics*, _buffer)
    SYSCALL3(get_group_credentials                    , GET_GROUP_CREDENTIALS                    , u32*, _realGroupId, u32*, _effectiveGroupId, u32*, _savedGroupId)
    SYSCALL2(get_interval_timer                       , GET_INTERVAL_TIMER                       , i32, _timerType, LegacyIntervalTimerValue*, _value)
    SYSCALL2(get_io_priority                          , GET_IO_PRIORITY                          , i32, _which, i32, _who)
    SYSCALL3(get_local_socket_address                 , GET_LOCAL_SOCKET_ADDRESS                 , i32, _fileDescriptor, SocketAddress*, _socketAddress, i32*, _socketAddressLength)
    SYSCALL1(get_maximum_scheduler_priority           , GET_MAXIMUM_SCHEDULER_PRIORITY           , i32, _policy)
    SYSCALL5(get_memory_policy                        , GET_MEMORY_POLICY                        , i32*, _policy, u64*, _nodeMask, u64, _maximumNode, u64, _address, u64, _flags)
    SYSCALL2(get_message_queue                        , GET_MESSAGE_QUEUE                        , i32, _key, i32, _messageFlags)
    SYSCALL1(get_minimum_scheduler_priority           , GET_MINIMUM_SCHEDULER_PRIORITY           , i32, _policy)
    SYSCALL4(get_mount_information                    , GET_MOUNT_INFORMATION                    , const MountIdentifierRequest*, _request, MountStatistics*, _buffer, s64, _bufferSize, u32, _flags)
    SYSCALL2(get_nice_priority                        , GET_NICE_PRIORITY                        , i32, _which, i32, _who)
    SYSCALL0(get_parent_process_id                    , GET_PARENT_PROCESS_ID                    )
    SYSCALL4(get_path_status_at                       , GET_PATH_STATUS_AT                       , i32, _directoryFileDescriptor, const c08*, _fileName, DescriptorStatus*, _statusBuffer, i32, _flags)
    SYSCALL3(get_peer_socket_address                  , GET_PEER_SOCKET_ADDRESS                  , i32, _fileDescriptor, SocketAddress*, _socketAddress, i32*, _socketAddressLength)
    SYSCALL2(get_pending_signals                      , GET_PENDING_SIGNALS                      , SignalSet*, _signalSet, s64, _signalSetSize)
    SYSCALL1(get_process_group_id                     , GET_PROCESS_GROUP_ID                     , i32, _processId)
    SYSCALL0(get_process_id                           , GET_PROCESS_ID                           )
    SYSCALL2(get_process_timer                        , GET_PROCESS_TIMER                        , i32, _timerId, KernelIntervalTimerSpecification*, _setting)
    SYSCALL1(get_process_times                        , GET_PROCESS_TIMES                        , ProcessTimeStatistics*, _timesBuffer)
    SYSCALL3(get_random_bytes                         , GET_RANDOM_BYTES                         , c08*, _buffer, u64, _length, u32, _flags)
    SYSCALL0(get_real_group_id                        , GET_REAL_GROUP_ID                        )
    SYSCALL0(get_real_user_id                         , GET_REAL_USER_ID                         )
    SYSCALL2(get_resource_limit                       , GET_RESOURCE_LIMIT                       , u32, _resource, ResourceLimit*, _resourceLimit)
    SYSCALL2(get_resource_usage                       , GET_RESOURCE_USAGE                       , i32, _who, ResourceUsage*, _resourceUsage)
    SYSCALL2(get_round_robin_interval                 , GET_ROUND_ROBIN_INTERVAL                 , i32, _processId, KernelTimeSpecification*, _interval)
    SYSCALL4(get_scheduler_attributes                 , GET_SCHEDULER_ATTRIBUTES                 , i32, _processId, SchedulerAttributes*, _attributes, u32, _size, u32, _flags)
    SYSCALL2(get_scheduler_parameters                 , GET_SCHEDULER_PARAMETERS                 , i32, _processId, SchedulerParameters*, _parameters)
    SYSCALL1(get_scheduler_policy                     , GET_SCHEDULER_POLICY                     , i32, _processId)
    SYSCALL4(get_security_attributes                  , GET_SECURITY_ATTRIBUTES                  , u32, _attribute, SecurityModuleContext*, _context, u32*, _size, u32, _flags)
    SYSCALL3(get_semaphore_set                        , GET_SEMAPHORE_SET                        , i32, _key, i32, _semaphoreCount, i32, _flags)
    SYSCALL1(get_session_id                           , GET_SESSION_ID                           , i32, _processId)
    SYSCALL3(get_shared_memory                        , GET_SHARED_MEMORY                        , i32, _key, s64, _size, i32, _flags)
    SYSCALL5(get_socket_option                        , GET_SOCKET_OPTION                        , i32, _fileDescriptor, i32, _level, i32, _optionName, c08*, _optionValue, i32*, _optionLength)
    SYSCALL2(get_supplementary_groups                 , GET_SUPPLEMENTARY_GROUPS                 , i32, _groupSetSize, u32*, _groupList)
    SYSCALL1(get_system_identification                , GET_SYSTEM_IDENTIFICATION                , SystemIdentification*, _systemName)
    SYSCALL1(get_system_information                   , GET_SYSTEM_INFORMATION                   , SystemInformation*, _information)
    SYSCALL2(get_thread_capabilities                  , GET_THREAD_CAPABILITIES                  , cap_user_header_t, _capabilityHeader, cap_user_data_t, _capabilityData)
    SYSCALL0(get_thread_id                            , GET_THREAD_ID                            )
    SYSCALL3(get_thread_robust_futex_list             , GET_THREAD_ROBUST_FUTEX_LIST             , i32, _processId, RobustFutexListHead**, _headPointer, u64*, _lengthPointer)
    SYSCALL2(get_timer_descriptor                     , GET_TIMER_DESCRIPTOR                     , i32, _fileDescriptor, KernelIntervalTimerSpecification*, _currentTimer)
    SYSCALL1(get_timer_overrun_count                  , GET_TIMER_OVERRUN_COUNT                  , i32, _timerId)
    SYSCALL3(get_user_credentials                     , GET_USER_CREDENTIALS                     , u32*, _realUserId, u32*, _effectiveUserId, u32*, _savedUserId)
    SYSCALL2(get_wall_clock_time                      , GET_WALL_CLOCK_TIME                      , LegacyTimeValue*, _timeValue, TimezoneInformation*, _timezone)
    SYSCALL2(get_working_directory                    , GET_WORKING_DIRECTORY                    , c08*, _buffer, u64, _size)
    SYSCALL0(hangup_virtual_terminal                  , HANGUP_VIRTUAL_TERMINAL                  )
    SYSCALL3(issue_memory_barrier                     , ISSUE_MEMORY_BARRIER                     , i32, _command, u32, _flags, i32, _cpuId)
    SYSCALL2(join_namespace                           , JOIN_NAMESPACE                           , i32, _fileDescriptor, i32, _flags)
    SYSCALL3(list_extended_attributes                 , LIST_EXTENDED_ATTRIBUTES                 , i32, _fileDescriptor, c08*, _list, u64, _size)
    SYSCALL3(list_extended_attributes                 , LIST_EXTENDED_ATTRIBUTES                 , const c08*, _pathName, c08*, _list, u64, _size)
    SYSCALL5(list_extended_attributes_at              , LIST_EXTENDED_ATTRIBUTES_AT              , i32, _directoryFileDescriptor, const c08*, _pathName, u32, _lookupFlags, c08*, _list, u64, _size)
    SYSCALL3(list_extended_attributes_no_follow       , LIST_EXTENDED_ATTRIBUTES_NO_FOLLOW       , const c08*, _pathName, c08*, _list, u64, _size)
    SYSCALL4(list_mount_ids                           , LIST_MOUNT_IDS                           , const MountIdentifierRequest*, _request, u64*, _mountIds, u64, _mountIdCount, u32, _flags)
    SYSCALL3(list_security_modules                    , LIST_SECURITY_MODULES                    , u64*, _moduleIds, u32*, _size, u32, _flags)
    SYSCALL2(listen_for_connections                   , LISTEN_FOR_CONNECTIONS                   , i32, _fileDescriptor, i32, _backlog)
    SYSCALL4(load_kernel_image                        , LOAD_KERNEL_IMAGE                        , u64, _entryPoint, u64, _segmentCount, KernelExecutionSegment*, _segments, u64, _flags)
    SYSCALL5(load_kernel_image_from_files             , LOAD_KERNEL_IMAGE_FROM_FILES             , i32, _kernelFileDescriptor, i32, _initialRamdiskFileDescriptor, u64, _commandLineLength, const c08*, _commandLine, u64, _flags)
    SYSCALL3(load_kernel_module_from_descriptor       , LOAD_KERNEL_MODULE_FROM_DESCRIPTOR       , i32, _fileDescriptor, const c08*, _arguments, i32, _flags)
    SYSCALL3(load_kernel_module_from_memory           , LOAD_KERNEL_MODULE_FROM_MEMORY           , void*, _moduleImage, u64, _length, const c08*, _arguments)
    SYSCALL2(lock_memory                              , LOCK_MEMORY                              , u64, _startAddress, s64, _length)
    SYSCALL3(lock_memory_with_flags                   , LOCK_MEMORY_WITH_FLAGS                   , u64, _startAddress, s64, _length, i32, _flags)
    SYSCALL1(lock_process_memory                      , LOCK_PROCESS_MEMORY                      , i32, _flags)
    SYSCALL2(manage_file_lock                         , MANAGE_FILE_LOCK                         , u32, _fileDescriptor, u32, _command)
    SYSCALL6(map_memory                               , MAP_MEMORY                               , u64, _address, u64, _length, u64, _protection, u64, _flags, u64, _fileDescriptor, u64, _offset)
    SYSCALL4(migrate_process_pages                    , MIGRATE_PROCESS_PAGES                    , i32, _processId, u64, _maximumNode, const u64*, _oldNodes, const u64*, _newNodes)
    SYSCALL5(modify_fanotify_mark                     , MODIFY_FANOTIFY_MARK                     , i32, _fanotifyFileDescriptor, u32, _flags, u64, _mask, i32, _directoryFileDescriptor, const c08*, _pathName)
    SYSCALL5(mount_filesystem                         , MOUNT_FILESYSTEM                         , c08*, _deviceName, c08*, _directoryName, c08*, _fileSystemType, u64, _flags, void*, _data)
    SYSCALL5(move_mount                               , MOVE_MOUNT                               , i32, _sourceDirectoryFileDescriptor, const c08*, _sourcePathName, i32, _destinationDirectoryFileDescriptor, const c08*, _destinationPathName, u32, _flags)
    SYSCALL6(move_process_pages                       , MOVE_PROCESS_PAGES                       , i32, _processId, u64, _pageCount, const void**, _pages, const i32*, _nodes, i32*, _status, i32, _flags)
    SYSCALL4(open_file_at                             , OPEN_FILE_AT                             , i32, _directoryFileDescriptor, const c08*, _fileName, i32, _flags, u16, _mode)
    SYSCALL4(open_file_at_with_options                , OPEN_FILE_AT_WITH_OPTIONS                , i32, _directoryFileDescriptor, const c08*, _fileName, OpenOptions*, _openHow, s64, _size)
    SYSCALL3(open_file_by_handle                      , OPEN_FILE_BY_HANDLE                      , i32, _mountDirectoryFileDescriptor, FileHandleInfo*, _fileHandle, i32, _flags)
    SYSCALL4(open_message_queue                       , OPEN_MESSAGE_QUEUE                       , const c08*, _name, i32, _openFlags, u16, _mode, MessageQueueAttributes*, _attributes)
    SYSCALL3(open_mount_configuration                 , OPEN_MOUNT_CONFIGURATION                 , i32, _directoryFileDescriptor, const c08*, _path, u32, _flags)
    SYSCALL3(open_mount_tree                          , OPEN_MOUNT_TREE                          , i32, _directoryFileDescriptor, const c08*, _fileName, u32, _flags)
    SYSCALL5(open_mount_tree_with_attributes          , OPEN_MOUNT_TREE_WITH_ATTRIBUTES          , i32, _directoryFileDescriptor, const c08*, _fileName, u32, _flags, MountAttributes*, _attributes, s64, _size)
    SYSCALL5(open_performance_event                   , OPEN_PERFORMANCE_EVENT                   , PerformanceEventAttributes*, _attributes, i32, _processId, i32, _cpu, i32, _groupFileDescriptor, u64, _flags)
    SYSCALL2(open_process_descriptor                  , OPEN_PROCESS_DESCRIPTOR                  , i32, _processId, u32, _flags)
    SYSCALL6(perform_futex_operation                  , PERFORM_FUTEX_OPERATION                  , u32*, _userAddress, i32, _operation, u32, _value, const KernelTimeSpecification*, _timeout, u32*, _secondaryUserAddress, u32, _value3)
    SYSCALL3(perform_io_control                       , PERFORM_IO_CONTROL                       , u32, _fileDescriptor, u32, _command, u64, _argument)
    SYSCALL3(perform_semaphore_operations             , PERFORM_SEMAPHORE_OPERATIONS             , i32, _semaphoreId, SemaphoreOperation*, _operations, u32, _operationCount)
    SYSCALL4(perform_semaphore_operations_until       , PERFORM_SEMAPHORE_OPERATIONS_UNTIL       , i32, _semaphoreId, SemaphoreOperation*, _operations, u32, _operationCount, const KernelTimeSpecification*, _timeout)
    SYSCALL5(poll_file_descriptors                    , POLL_FILE_DESCRIPTORS                    , PollFileDescriptor*, _fileDescriptors, u32, _fileDescriptorCount, KernelTimeSpecification*, _timeout, const SignalSet*, _signalMask, s64, _signalSetSize)
    SYSCALL3(preload_file_data                        , PRELOAD_FILE_DATA                        , i32, _fileDescriptor, i64, _offset, s64, _count)
    SYSCALL6(process_io_uring_queue                   , PROCESS_IO_URING_QUEUE                   , u32, _fileDescriptor, u32, _submitCount, u32, _minimumCompletions, u32, _flags, const void*, _arguments, u64, _argumentSize)
    SYSCALL3(query_memory_residency                   , QUERY_MEMORY_RESIDENCY                   , u64, _startAddress, s64, _length, u08*, _vector)
    SYSCALL4(query_page_cache                         , QUERY_PAGE_CACHE                         , u32, _fileDescriptor, CacheStatisticsRange*, _cacheStatusRange, CacheStatistics*, _cacheStatus, u32, _flags)
    SYSCALL3(queue_process_signal                     , QUEUE_PROCESS_SIGNAL                     , i32, _processId, i32, _signal, SignalInformation*, _signalInfo)
    SYSCALL4(queue_thread_signal                      , QUEUE_THREAD_SIGNAL                      , i32, _threadGroupId, i32, _processId, i32, _signal, SignalInformation*, _signalInfo)
    SYSCALL3(read_data                                , READ_DATA                                , u32, _fileDescriptor, c08*, _buffer, s64, _count)
    SYSCALL3(read_data_vectors                        , READ_DATA_VECTORS                        , u64, _fileDescriptor, const IoVector*, _vectors, u64, _vectorCount)
    SYSCALL3(read_directory_entries                   , READ_DIRECTORY_ENTRIES                   , u32, _fileDescriptor, LinuxDirectoryEntry*, _directoryEntry, u32, _count)
    SYSCALL4(read_file_at_offset                      , READ_FILE_AT_OFFSET                      , u32, _fileDescriptor, c08*, _buffer, s64, _count, i64, _position)
    SYSCALL5(read_file_vectors_at_offset              , READ_FILE_VECTORS_AT_OFFSET              , u64, _fileDescriptor, const IoVector*, _vectors, u64, _vectorCount, u64, _positionLow, u64, _positionHigh)
    SYSCALL6(read_file_vectors_at_offset_with_flags   , READ_FILE_VECTORS_AT_OFFSET_WITH_FLAGS   , u64, _fileDescriptor, const IoVector*, _vectors, u64, _vectorCount, u64, _positionLow, u64, _positionHigh, i32, _flags)
    SYSCALL6(read_process_memory                      , READ_PROCESS_MEMORY                      , i32, _processId, const IoVector*, _localVectors, u64, _localVectorCount, const IoVector*, _remoteVectors, u64, _remoteVectorCount, u64, _flags)
    SYSCALL4(read_symbolic_link_at                    , READ_SYMBOLIC_LINK_AT                    , i32, _directoryFileDescriptor, const c08*, _pathName, c08*, _buffer, i32, _bufferSize)
    SYSCALL5(receive_message_until                    , RECEIVE_MESSAGE_UNTIL                    , i32, _messageQueueDescriptor, c08*, _messageBuffer, s64, _messageLength, u32*, _messagePriority, const KernelTimeSpecification*, _absoluteTimeout)
    SYSCALL5(receive_queue_message                    , RECEIVE_QUEUE_MESSAGE                    , i32, _messageQueueId, MessageBuffer*, _messageBuffer, s64, _messageSize, i64, _messageType, i32, _messageFlags)
    SYSCALL6(receive_socket_data                      , RECEIVE_SOCKET_DATA                      , i32, _fileDescriptor, void*, _buffer, s64, _size, u32, _flags, SocketAddress*, _address, i32*, _addressLength)
    SYSCALL3(receive_socket_message                   , RECEIVE_SOCKET_MESSAGE                   , i32, _fileDescriptor, UserMessageHeader*, _message, u32, _flags)
    SYSCALL5(receive_socket_messages                  , RECEIVE_SOCKET_MESSAGES                  , i32, _fileDescriptor, MultiMessageHeader*, _messages, u32, _messageCount, u32, _flags, KernelTimeSpecification*, _timeout)
    SYSCALL2(release_process_memory                   , RELEASE_PROCESS_MEMORY                   , i32, _processFileDescriptor, u32, _flags)
    SYSCALL5(remap_file_pages                         , REMAP_FILE_PAGES                         , u64, _startAddress, u64, _size, u64, _protection, u64, _pageOffset, u64, _flags)
    SYSCALL5(remap_memory                             , REMAP_MEMORY                             , u64, _address, u64, _oldLength, u64, _newLength, u64, _flags, u64, _newAddress)
    SYSCALL2(remove_extended_attribute                , REMOVE_EXTENDED_ATTRIBUTE                , const c08*, _pathName, const c08*, _name)
    SYSCALL2(remove_extended_attribute                , REMOVE_EXTENDED_ATTRIBUTE                , i32, _fileDescriptor, const c08*, _name)
    SYSCALL4(remove_extended_attribute_at             , REMOVE_EXTENDED_ATTRIBUTE_AT             , i32, _directoryFileDescriptor, const c08*, _pathName, u32, _lookupFlags, const c08*, _name)
    SYSCALL2(remove_extended_attribute_no_follow      , REMOVE_EXTENDED_ATTRIBUTE_NO_FOLLOW      , const c08*, _pathName, const c08*, _name)
    SYSCALL2(remove_inotify_watch                     , REMOVE_INOTIFY_WATCH                     , i32, _fileDescriptor, i32, _watchDescriptor)
    SYSCALL3(remove_path_at                           , REMOVE_PATH_AT                           , i32, _directoryFileDescriptor, const c08*, _pathName, i32, _flags)
    SYSCALL4(rename_path_at                           , RENAME_PATH_AT                           , i32, _oldDirectoryFileDescriptor, const c08*, _oldName, i32, _newDirectoryFileDescriptor, const c08*, _newName)
    SYSCALL5(rename_path_at_with_flags                , RENAME_PATH_AT_WITH_FLAGS                , i32, _oldDirectoryFileDescriptor, const c08*, _oldName, i32, _newDirectoryFileDescriptor, const c08*, _newName, u32, _flags)
    SYSCALL4(request_kernel_key                       , REQUEST_KERNEL_KEY                       , const c08*, _type, const c08*, _description, const c08*, _calloutInfo, i32, _destinationKeyringId)
    SYSCALL4(requeue_futex_waiters                    , REQUEUE_FUTEX_WAITERS                    , FutexWaitRequest*, _waiters, u32, _flags, i32, _wakeCount, i32, _requeueCount)
    SYSCALL2(resize_file                              , RESIZE_FILE                              , u32, _fileDescriptor, i64, _length)
    SYSCALL2(resize_file_at_path                      , RESIZE_FILE_AT_PATH                      , const c08*, _path, i64, _length)
    SYSCALL0(restart_interrupted_syscall              , RESTART_INTERRUPTED_SYSCALL              )
    SYSCALL0(return_from_signal_handler               , RETURN_FROM_SIGNAL_HANDLER               )
    SYSCALL3(seal_memory                              , SEAL_MEMORY                              , u64, _startAddress, s64, _length, u64, _flags)
    SYSCALL3(seek_file                                , SEEK_FILE                                , i32, _fileDescriptor, i64, _offset, u32, _whence)
    SYSCALL5(send_message_until                       , SEND_MESSAGE_UNTIL                       , i32, _messageQueueDescriptor, const c08*, _messageBuffer, s64, _messageLength, u32, _messagePriority, const KernelTimeSpecification*, _absoluteTimeout)
    SYSCALL4(send_queue_message                       , SEND_QUEUE_MESSAGE                       , i32, _messageQueueId, MessageBuffer*, _messageBuffer, s64, _messageSize, i32, _messageFlags)
    SYSCALL2(send_signal                              , SEND_SIGNAL                              , i32, _processId, i32, _signal)
    SYSCALL2(send_signal_to_thread                    , SEND_SIGNAL_TO_THREAD                    , i32, _threadId, i32, _signal)
    SYSCALL6(send_socket_data                         , SEND_SOCKET_DATA                         , i32, _fileDescriptor, void*, _buffer, s64, _length, u32, _flags, SocketAddress*, _address, i32, _addressLength)
    SYSCALL3(send_socket_message                      , SEND_SOCKET_MESSAGE                      , i32, _fileDescriptor, UserMessageHeader*, _message, u32, _flags)
    SYSCALL4(send_socket_messages                     , SEND_SOCKET_MESSAGES                     , i32, _fileDescriptor, MultiMessageHeader*, _messages, u32, _messageCount, u32, _flags)
    SYSCALL3(send_thread_signal                       , SEND_THREAD_SIGNAL                       , i32, _threadGroupId, i32, _threadId, i32, _signal)
    SYSCALL2(set_clock_time                           , SET_CLOCK_TIME                           , const i32, _clockId, const KernelTimeSpecification*, _time)
    SYSCALL3(set_cpu_affinity                         , SET_CPU_AFFINITY                         , i32, _processId, u32, _length, u64*, _cpuMask)
    SYSCALL5(set_extended_attribute                   , SET_EXTENDED_ATTRIBUTE                   , const c08*, _pathName, const c08*, _name, const void*, _value, s64, _size, i32, _flags)
    SYSCALL5(set_extended_attribute                   , SET_EXTENDED_ATTRIBUTE                   , i32, _fileDescriptor, const c08*, _name, const void*, _value, u64, _size, i32, _flags)
    SYSCALL6(set_extended_attribute_at                , SET_EXTENDED_ATTRIBUTE_AT                , i32, _directoryFileDescriptor, const c08*, _pathName, u32, _lookupFlags, const c08*, _name, const ExtendedAttributeArguments*, _arguments, s64, _size)
    SYSCALL5(set_extended_attribute_no_follow         , SET_EXTENDED_ATTRIBUTE_NO_FOLLOW         , const c08*, _pathName, const c08*, _name, const void*, _value, u64, _size, i32, _flags)
    SYSCALL1(set_file_creation_mask                   , SET_FILE_CREATION_MASK                   , i32, _mask)
    SYSCALL4(set_file_times_at                        , SET_FILE_TIMES_AT                        , i32, _directoryFileDescriptor, const c08*, _fileName, KernelTimeSpecification*, _times, i32, _flags)
    SYSCALL5(set_filesystem_file_attributes           , SET_FILESYSTEM_FILE_ATTRIBUTES           , i32, _directoryFileDescriptor, const c08*, _fileName, FileAttributes*, _fileAttributes, u64, _size, u32, _lookupFlags)
    SYSCALL1(set_filesystem_group_id                  , SET_FILESYSTEM_GROUP_ID                  , u32, _groupId)
    SYSCALL1(set_filesystem_user_id                   , SET_FILESYSTEM_USER_ID                   , u32, _userId)
    SYSCALL3(set_group_credentials                    , SET_GROUP_CREDENTIALS                    , u32, _realGroupId, u32, _effectiveGroupId, u32, _savedGroupId)
    SYSCALL1(set_group_id                             , SET_GROUP_ID                             , u32, _groupId)
    SYSCALL3(set_interval_timer                       , SET_INTERVAL_TIMER                       , i32, _timerType, LegacyIntervalTimerValue*, _newValue, LegacyIntervalTimerValue*, _oldValue)
    SYSCALL3(set_io_priority                          , SET_IO_PRIORITY                          , i32, _which, i32, _who, i32, _ioPriority)
    SYSCALL4(set_memory_home_node                     , SET_MEMORY_HOME_NODE                     , u64, _startAddress, u64, _length, u64, _homeNode, u64, _flags)
    SYSCALL3(set_memory_policy                        , SET_MEMORY_POLICY                        , i32, _mode, const u64*, _nodeMask, u64, _maximumNode)
    SYSCALL3(set_memory_protection                    , SET_MEMORY_PROTECTION                    , u64, _startAddress, s64, _length, u64, _protection)
    SYSCALL4(set_memory_protection_key                , SET_MEMORY_PROTECTION_KEY                , u64, _startAddress, s64, _length, u64, _protection, i32, _protectionKey)
    SYSCALL5(set_mount_attributes                     , SET_MOUNT_ATTRIBUTES                     , i32, _directoryFileDescriptor, const c08*, _path, u32, _flags, MountAttributes*, _attributes, s64, _size)
    SYSCALL3(set_nice_priority                        , SET_NICE_PRIORITY                        , i32, _which, i32, _who, i32, _niceValue)
    SYSCALL2(set_process_group                        , SET_PROCESS_GROUP                        , i32, _processId, i32, _processGroupId)
    SYSCALL4(set_process_timer                        , SET_PROCESS_TIMER                        , i32, _timerId, i32, _flags, const KernelIntervalTimerSpecification*, _newSetting, KernelIntervalTimerSpecification*, _oldSetting)
    SYSCALL2(set_real_effective_group_ids             , SET_REAL_EFFECTIVE_GROUP_IDS             , u32, _realGroupId, u32, _effectiveGroupId)
    SYSCALL2(set_real_effective_user_ids              , SET_REAL_EFFECTIVE_USER_IDS              , u32, _realUserId, u32, _effectiveUserId)
    SYSCALL2(set_resource_limit                       , SET_RESOURCE_LIMIT                       , u32, _resource, ResourceLimit*, _resourceLimit)
    SYSCALL3(set_scheduler_attributes                 , SET_SCHEDULER_ATTRIBUTES                 , i32, _processId, SchedulerAttributes*, _attributes, u32, _flags)
    SYSCALL2(set_scheduler_parameters                 , SET_SCHEDULER_PARAMETERS                 , i32, _processId, SchedulerParameters*, _parameters)
    SYSCALL3(set_scheduler_policy                     , SET_SCHEDULER_POLICY                     , i32, _processId, i32, _policy, SchedulerParameters*, _parameters)
    SYSCALL4(set_security_attribute                   , SET_SECURITY_ATTRIBUTE                   , u32, _attribute, SecurityModuleContext*, _context, u32, _size, u32, _flags)
    SYSCALL5(set_socket_option                        , SET_SOCKET_OPTION                        , i32, _fileDescriptor, i32, _level, i32, _optionName, c08*, _optionValue, i32, _optionLength)
    SYSCALL2(set_supplementary_groups                 , SET_SUPPLEMENTARY_GROUPS                 , i32, _groupSetSize, u32*, _groupList)
    SYSCALL2(set_system_domain_name                   , SET_SYSTEM_DOMAIN_NAME                   , c08*, _name, i32, _length)
    SYSCALL2(set_system_host_name                     , SET_SYSTEM_HOST_NAME                     , c08*, _name, i32, _length)
    SYSCALL2(set_thread_capabilities                  , SET_THREAD_CAPABILITIES                  , cap_user_header_t, _capabilityHeader, const cap_user_data_t, _capabilityData)
    SYSCALL1(set_thread_id_address                    , SET_THREAD_ID_ADDRESS                    , i32*, _threadIdAddress)
    SYSCALL2(set_thread_robust_futex_list             , SET_THREAD_ROBUST_FUTEX_LIST             , RobustFutexListHead*, _head, s64, _length)
    SYSCALL4(set_timer_descriptor                     , SET_TIMER_DESCRIPTOR                     , i32, _fileDescriptor, i32, _flags, const KernelIntervalTimerSpecification*, _newTimer, KernelIntervalTimerSpecification*, _oldTimer)
    SYSCALL3(set_user_credentials                     , SET_USER_CREDENTIALS                     , u32, _realUserId, u32, _effectiveUserId, u32, _savedUserId)
    SYSCALL1(set_user_id                              , SET_USER_ID                              , u32, _userId)
    SYSCALL2(set_wall_clock_time                      , SET_WALL_CLOCK_TIME                      , LegacyTimeValue*, _timeValue, TimezoneInformation*, _timezone)
    SYSCALL2(shutdown_socket                          , SHUTDOWN_SOCKET                          , i32, _fileDescriptor, i32, _how)
    SYSCALL4(signal_process                           , SIGNAL_PROCESS                           , i32, _processFileDescriptor, i32, _signal, SignalInformation*, _signalInfo, u32, _flags)
    SYSCALL2(sleep_for_duration                       , SLEEP_FOR_DURATION                       , KernelTimeSpecification*, _requestedTime, KernelTimeSpecification*, _remainingTime)
    SYSCALL4(sleep_on_clock                           , SLEEP_ON_CLOCK                           , const i32, _clockId, i32, _flags, const KernelTimeSpecification*, _requestedTime, KernelTimeSpecification*, _remainingTime)
    SYSCALL6(splice_data                              , SPLICE_DATA                              , i32, _inputFileDescriptor, i64*, _inputOffset, i32, _outputFileDescriptor, i64*, _outputOffset, s64, _length, u32, _flags)
    SYSCALL4(splice_memory_to_pipe                    , SPLICE_MEMORY_TO_PIPE                    , i32, _fileDescriptor, const IoVector*, _vectors, u64, _segmentCount, u32, _flags)
    SYSCALL3(submit_async_io                          , SUBMIT_ASYNC_IO                          , u64, _contextId, i64, _count, IoControlBlock**, _ioControlBlocks)
    SYSCALL2(suspend_until_signal                     , SUSPEND_UNTIL_SIGNAL                     , SignalSet*, _newSignalSet, s64, _signalSetSize)
    SYSCALL1(synchronize_file                         , SYNCHRONIZE_FILE                         , u32, _fileDescriptor)
    SYSCALL1(synchronize_file_data                    , SYNCHRONIZE_FILE_DATA                    , u32, _fileDescriptor)
    SYSCALL4(synchronize_file_range                   , SYNCHRONIZE_FILE_RANGE                   , i32, _fileDescriptor, i64, _offset, i64, _byteCount, u32, _flags)
    SYSCALL1(synchronize_filesystem                   , SYNCHRONIZE_FILESYSTEM                   , i32, _fileDescriptor)
    SYSCALL0(synchronize_filesystems                  , SYNCHRONIZE_FILESYSTEMS                  )
    SYSCALL3(synchronize_memory_mapping               , SYNCHRONIZE_MEMORY_MAPPING               , u64, _startAddress, s64, _length, i32, _flags)
    SYSCALL1(unlink_message_queue                     , UNLINK_MESSAGE_QUEUE                     , const c08*, _name)
    SYSCALL2(unload_kernel_module                     , UNLOAD_KERNEL_MODULE                     , const c08*, _moduleName, u32, _flags)
    SYSCALL2(unlock_memory                            , UNLOCK_MEMORY                            , u64, _startAddress, s64, _length)
    SYSCALL0(unlock_process_memory                    , UNLOCK_PROCESS_MEMORY                    )
    SYSCALL2(unmap_memory                             , UNMAP_MEMORY                             , u64, _address, s64, _length)
    SYSCALL2(unmount_filesystem                       , UNMOUNT_FILESYSTEM                       , c08*, _name, i32, _flags)
    SYSCALL1(unshare_process_resources                , UNSHARE_PROCESS_RESOURCES                , u64, _unshareFlags)
    SYSCALL4(wait_for_child                           , WAIT_FOR_CHILD                           , i32, _processId, i32*, _statusAddress, i32, _options, ResourceUsage*, _resourceUsage)
    SYSCALL5(wait_for_child_event                     , WAIT_FOR_CHILD_EVENT                     , i32, _which, i32, _processId, SignalInformation*, _signalInfo, i32, _options, ResourceUsage*, _resourceUsage)
    SYSCALL6(wait_for_descriptor_events               , WAIT_FOR_DESCRIPTOR_EVENTS               , i32, _descriptorRange, DescriptorSet*, _readFileDescriptors, DescriptorSet*, _writeFileDescriptors, DescriptorSet*, _exceptionFileDescriptors, KernelTimeSpecification*, _timeout, void*, _signalMaskData)
    SYSCALL6(wait_for_epoll_events                    , WAIT_FOR_EPOLL_EVENTS                    , i32, _epollFileDescriptor, EpollEventData*, _events, i32, _maximumEvents, i32, _timeout, const SignalSet*, _signalMask, u64, _signalSetSize)
    SYSCALL6(wait_for_epoll_events_precise            , WAIT_FOR_EPOLL_EVENTS_PRECISE            , i32, _epollFileDescriptor, EpollEventData*, _events, i32, _maximumEvents, const KernelTimeSpecification*, _timeout, const SignalSet*, _signalMask, u64, _signalSetSize)
    SYSCALL4(wait_for_signal                          , WAIT_FOR_SIGNAL                          , const SignalSet*, _signalSet, SignalInformation*, _signalInfo, const KernelTimeSpecification*, _timeout, s64, _signalSetSize)
    SYSCALL6(wait_on_futex                            , WAIT_ON_FUTEX                            , void*, _userAddress, u64, _value, u64, _mask, u32, _flags, KernelTimeSpecification*, _timeout, i32, _clockId)
    SYSCALL5(wait_on_futex_set                        , WAIT_ON_FUTEX_SET                        , FutexWaitRequest*, _waiters, u32, _futexCount, u32, _flags, KernelTimeSpecification*, _timeout, i32, _clockId)
    SYSCALL4(wake_futex_waiters                       , WAKE_FUTEX_WAITERS                       , void*, _userAddress, u64, _mask, i32, _wakeCount, u32, _flags)
    SYSCALL3(write_data                               , WRITE_DATA                               , u32, _fileDescriptor, const c08*, _buffer, s64, _count)
    SYSCALL3(write_data_vectors                       , WRITE_DATA_VECTORS                       , u64, _fileDescriptor, const IoVector*, _vectors, u64, _vectorCount)
    SYSCALL4(write_file_at_offset                     , WRITE_FILE_AT_OFFSET                     , u32, _fileDescriptor, const c08*, _buffer, s64, _count, i64, _position)
    SYSCALL5(write_file_vectors_at_offset             , WRITE_FILE_VECTORS_AT_OFFSET             , u64, _fileDescriptor, const IoVector*, _vectors, u64, _vectorCount, u64, _positionLow, u64, _positionHigh)
    SYSCALL6(write_file_vectors_at_offset_with_flags  , WRITE_FILE_VECTORS_AT_OFFSET_WITH_FLAGS  , u64, _fileDescriptor, const IoVector*, _vectors, u64, _vectorCount, u64, _positionLow, u64, _positionHigh, i32, _flags)
    SYSCALL6(write_process_memory                     , WRITE_PROCESS_MEMORY                     , i32, _processId, const IoVector*, _localVectors, u64, _localVectorCount, const IoVector*, _remoteVectors, u64, _remoteVectorCount, u64, _flags)
    SYSCALL0(yield_processor                          , YIELD_PROCESSOR                          )
}