#pragma once
#include "Type.hpp"

extern "C"
{
    struct _TEB * NtCurrentTeb();
    NTSTATUS NtCallbackReturn(PVOID OutputBuffer, ULONG OutputLength, NTSTATUS Status);
    NTSTATUS NtQueryDebugFilterState(ULONG ComponentId, ULONG Level);
    NTSTATUS NtSetDebugFilterState(ULONG ComponentId, ULONG Level, BOOLEAN State);
    NTSTATUS NtYieldExecution();
    NTSTATUS NtDelayExecution(BOOLEAN Alertable, PLARGE_INTEGER DelayInterval);
    NTSTATUS NtQuerySystemEnvironmentValue(PCUNICODE_STRING VariableName, PWSTR VariableValue, USHORT ValueLength, PUSHORT ReturnLength);
    NTSTATUS NtQuerySystemEnvironmentValueEx(PCUNICODE_STRING VariableName, PCGUID VendorGuid, PVOID Buffer, PULONG BufferLength, PULONG Attributes);
    NTSTATUS NtSetSystemEnvironmentValue(PCUNICODE_STRING VariableName, PCUNICODE_STRING VariableValue);
    NTSTATUS NtSetSystemEnvironmentValueEx(PCUNICODE_STRING VariableName, PCGUID VendorGuid, PVOID Buffer, ULONG BufferLength, ULONG Attributes);
    NTSTATUS NtEnumerateSystemEnvironmentValuesEx(ULONG InformationClass, PVOID Buffer, PULONG BufferLength);
    NTSTATUS NtAddBootEntry(PBOOT_ENTRY BootEntry, PULONG Id);
    NTSTATUS NtDeleteBootEntry(ULONG Id);
    NTSTATUS NtModifyBootEntry(PBOOT_ENTRY BootEntry);
    NTSTATUS NtEnumerateBootEntries(PVOID Buffer, PULONG BufferLength);
    NTSTATUS NtQueryBootEntryOrder(PULONG Ids, PULONG Count);
    NTSTATUS NtSetBootEntryOrder(PULONG Ids, ULONG Count);
    NTSTATUS NtQueryBootOptions(PBOOT_OPTIONS BootOptions, PULONG BootOptionsLength);
    NTSTATUS NtSetBootOptions(PBOOT_OPTIONS BootOptions, ULONG FieldsToChange);
    NTSTATUS NtTranslateFilePath(PFILE_PATH InputFilePath, ULONG OutputType, PFILE_PATH OutputFilePath, PULONG OutputFilePathLength);
    NTSTATUS NtAddDriverEntry(PEFI_DRIVER_ENTRY DriverEntry, PULONG Id);
    NTSTATUS NtDeleteDriverEntry(ULONG Id);
    NTSTATUS NtModifyDriverEntry(PEFI_DRIVER_ENTRY DriverEntry);
    NTSTATUS NtEnumerateDriverEntries(PVOID Buffer, PULONG BufferLength);
    NTSTATUS NtQueryDriverEntryOrder(PULONG Ids, PULONG Count);
    NTSTATUS NtSetDriverEntryOrder(PULONG Ids, ULONG Count);
    NTSTATUS NtFilterBootOption(FILTER_BOOT_OPTION_OPERATION FilterOperation, ULONG ObjectType, ULONG ElementType, PVOID Data, ULONG DataSize);
    NTSTATUS NtCreateEvent(PHANDLE EventHandle, ACCESS_MASK DesiredAccess, POBJECT_ATTRIBUTES ObjectAttributes, EVENT_TYPE EventType, BOOLEAN InitialState);
    NTSTATUS NtOpenEvent(PHANDLE EventHandle, ACCESS_MASK DesiredAccess, POBJECT_ATTRIBUTES ObjectAttributes);
    NTSTATUS NtSetEvent(HANDLE EventHandle, PLONG PreviousState);
    NTSTATUS NtSetEventEx(HANDLE ThreadId, PRTL_SRWLOCK Lock);
    NTSTATUS NtSetEventBoostPriority(HANDLE EventHandle);
    NTSTATUS NtClearEvent(HANDLE EventHandle);
    NTSTATUS NtResetEvent(HANDLE EventHandle, PLONG PreviousState);
    NTSTATUS NtPulseEvent(HANDLE EventHandle, PLONG PreviousState);
    NTSTATUS NtQueryEvent(HANDLE EventHandle, EVENT_INFORMATION_CLASS EventInformationClass, PVOID EventInformation, ULONG EventInformationLength, PULONG ReturnLength);
    NTSTATUS NtCreateEventPair(PHANDLE EventPairHandle, ACCESS_MASK DesiredAccess, PCOBJECT_ATTRIBUTES ObjectAttributes);
    NTSTATUS NtOpenEventPair(PHANDLE EventPairHandle, ACCESS_MASK DesiredAccess, PCOBJECT_ATTRIBUTES ObjectAttributes);
    NTSTATUS NtSetLowEventPair(HANDLE EventPairHandle);
    NTSTATUS NtSetHighEventPair(HANDLE EventPairHandle);
    NTSTATUS NtWaitLowEventPair(HANDLE EventPairHandle);
    NTSTATUS NtWaitHighEventPair(HANDLE EventPairHandle);
    NTSTATUS NtSetLowWaitHighEventPair(HANDLE EventPairHandle);
    NTSTATUS NtSetHighWaitLowEventPair(HANDLE EventPairHandle);
    NTSTATUS NtCreateMutant(PHANDLE MutantHandle, ACCESS_MASK DesiredAccess, PCOBJECT_ATTRIBUTES ObjectAttributes, BOOLEAN InitialOwner);
    NTSTATUS NtOpenMutant(PHANDLE MutantHandle, ACCESS_MASK DesiredAccess, PCOBJECT_ATTRIBUTES ObjectAttributes);
    NTSTATUS NtReleaseMutant(HANDLE MutantHandle, PLONG PreviousCount);
    NTSTATUS NtQueryMutant(HANDLE MutantHandle, MUTANT_INFORMATION_CLASS MutantInformationClass, PVOID MutantInformation, ULONG MutantInformationLength, PULONG ReturnLength);
    NTSTATUS NtCreateSemaphore(PHANDLE SemaphoreHandle, ACCESS_MASK DesiredAccess, PCOBJECT_ATTRIBUTES ObjectAttributes, LONG InitialCount, LONG MaximumCount);
    NTSTATUS NtOpenSemaphore(PHANDLE SemaphoreHandle, ACCESS_MASK DesiredAccess, PCOBJECT_ATTRIBUTES ObjectAttributes);
    NTSTATUS NtReleaseSemaphore(HANDLE SemaphoreHandle, LONG ReleaseCount, PLONG PreviousCount);
    NTSTATUS NtQuerySemaphore(HANDLE SemaphoreHandle, SEMAPHORE_INFORMATION_CLASS SemaphoreInformationClass, PVOID SemaphoreInformation, ULONG SemaphoreInformationLength, PULONG ReturnLength);
    NTSTATUS NtCreateTimer(PHANDLE TimerHandle, ACCESS_MASK DesiredAccess, PCOBJECT_ATTRIBUTES ObjectAttributes, TIMER_TYPE TimerType);
    NTSTATUS NtOpenTimer(PHANDLE TimerHandle, ACCESS_MASK DesiredAccess, PCOBJECT_ATTRIBUTES ObjectAttributes);
    NTSTATUS NtSetTimer(HANDLE TimerHandle, PLARGE_INTEGER DueTime, PTIMER_APC_ROUTINE TimerApcRoutine, PVOID TimerContext, BOOLEAN ResumeTimer, LONG Period, PBOOLEAN PreviousState);
    NTSTATUS NtSetTimerEx(HANDLE TimerHandle, TIMER_SET_INFORMATION_CLASS TimerSetInformationClass, PVOID TimerSetInformation, ULONG TimerSetInformationLength);
    NTSTATUS NtCancelTimer(HANDLE TimerHandle, PBOOLEAN CurrentState);
    NTSTATUS NtQueryTimer(HANDLE TimerHandle, TIMER_INFORMATION_CLASS TimerInformationClass, PVOID TimerInformation, ULONG TimerInformationLength, PULONG ReturnLength);
    NTSTATUS NtCreateIRTimer(PHANDLE TimerHandle, PULONG TimerId, ACCESS_MASK DesiredAccess);
    NTSTATUS NtSetIRTimer(HANDLE TimerHandle, PLARGE_INTEGER DueTime);
    NTSTATUS NtCreateTimer2(PHANDLE TimerHandle, PULONG TimerId, PCOBJECT_ATTRIBUTES ObjectAttributes, ULONG Attributes, ACCESS_MASK DesiredAccess);
    NTSTATUS NtSetTimer2(HANDLE TimerHandle, PLARGE_INTEGER DueTime, PLARGE_INTEGER Period, PT2_SET_PARAMETERS Parameters);
    NTSTATUS NtCancelTimer2(HANDLE TimerHandle, PT2_CANCEL_PARAMETERS Parameters);
    NTSTATUS NtCreateProfile(PHANDLE ProfileHandle, HANDLE Process, PVOID ProfileBase, SIZE_T ProfileSize, ULONG BucketSize, PULONG Buffer, ULONG BufferSize, KPROFILE_SOURCE ProfileSource, KAFFINITY Affinity);
    NTSTATUS NtCreateProfileEx(PHANDLE ProfileHandle, HANDLE Process, PVOID ProfileBase, SIZE_T ProfileSize, ULONG BucketSize, PULONG Buffer, ULONG BufferSize, KPROFILE_SOURCE ProfileSource, USHORT GroupCount, PGROUP_AFFINITY GroupAffinity);
    NTSTATUS NtStartProfile(HANDLE ProfileHandle);
    NTSTATUS NtStopProfile(HANDLE ProfileHandle);
    NTSTATUS NtQueryIntervalProfile(KPROFILE_SOURCE ProfileSource, PULONG Interval);
    NTSTATUS NtSetIntervalProfile(ULONG Interval, KPROFILE_SOURCE Source);
    NTSTATUS NtCreateKeyedEvent(PHANDLE KeyedEventHandle, ACCESS_MASK DesiredAccess, PCOBJECT_ATTRIBUTES ObjectAttributes, ULONG Flags);
    NTSTATUS NtOpenKeyedEvent(PHANDLE KeyedEventHandle, ACCESS_MASK DesiredAccess, PCOBJECT_ATTRIBUTES ObjectAttributes);
    NTSTATUS NtReleaseKeyedEvent(HANDLE KeyedEventHandle, PVOID KeyValue, BOOLEAN Alertable, PLARGE_INTEGER Timeout);
    NTSTATUS NtWaitForKeyedEvent(HANDLE KeyedEventHandle, PVOID KeyValue, BOOLEAN Alertable, PLARGE_INTEGER Timeout);
    NTSTATUS NtUmsThreadYield(PVOID SchedulerParam);
    NTSTATUS NtCreateWnfStateName(PWNF_STATE_NAME StateName, WNF_STATE_NAME_LIFETIME NameLifetime, WNF_DATA_SCOPE DataScope, BOOLEAN PersistData, PCWNF_TYPE_ID TypeId, ULONG MaximumStateSize, PSECURITY_DESCRIPTOR SecurityDescriptor);
    NTSTATUS NtDeleteWnfStateName(PCWNF_STATE_NAME StateName);
    NTSTATUS NtUpdateWnfStateData(PCWNF_STATE_NAME StateName, void *Buffer, ULONG Length, PCWNF_TYPE_ID TypeId, PCSID ExplicitScope, WNF_CHANGE_STAMP MatchingChangeStamp, LOGICAL CheckStamp);
    NTSTATUS NtDeleteWnfStateData(PCWNF_STATE_NAME StateName, PCSID ExplicitScope);
    NTSTATUS NtQueryWnfStateData(PCWNF_STATE_NAME StateName, PCWNF_TYPE_ID TypeId, PCSID ExplicitScope, PWNF_CHANGE_STAMP ChangeStamp, PVOID Buffer, PULONG BufferLength);
    NTSTATUS NtQueryWnfStateNameInformation(PCWNF_STATE_NAME StateName, WNF_STATE_NAME_INFORMATION NameInfoClass, PCSID ExplicitScope, PVOID Buffer, ULONG BufferLength);
    NTSTATUS NtSubscribeWnfStateChange(PCWNF_STATE_NAME StateName, WNF_CHANGE_STAMP ChangeStamp, ULONG EventMask, PULONG64 SubscriptionId);
    NTSTATUS NtUnsubscribeWnfStateChange(PCWNF_STATE_NAME StateName);
    NTSTATUS NtGetCompleteWnfStateSubscription(PWNF_STATE_NAME OldDescriptorStateName, ULONG64 *OldSubscriptionId, ULONG OldDescriptorEventMask, ULONG OldDescriptorStatus, PWNF_DELIVERY_DESCRIPTOR NewDeliveryDescriptor, ULONG DescriptorSize);
    NTSTATUS NtSetWnfProcessNotificationEvent(HANDLE NotificationEvent);
    NTSTATUS NtCreateWorkerFactory(PHANDLE WorkerFactoryHandleReturn, ACCESS_MASK DesiredAccess, PCOBJECT_ATTRIBUTES ObjectAttributes, HANDLE CompletionPortHandle, HANDLE WorkerProcessHandle, PVOID StartRoutine, PVOID StartParameter, ULONG MaxThreadCount, SIZE_T StackReserve, SIZE_T StackCommit);
    NTSTATUS NtQueryInformationWorkerFactory(HANDLE WorkerFactoryHandle, WORKERFACTORYINFOCLASS WorkerFactoryInformationClass, PVOID WorkerFactoryInformation, ULONG WorkerFactoryInformationLength, PULONG ReturnLength);
    NTSTATUS NtSetInformationWorkerFactory(HANDLE WorkerFactoryHandle, WORKERFACTORYINFOCLASS WorkerFactoryInformationClass, PVOID WorkerFactoryInformation, ULONG WorkerFactoryInformationLength);
    NTSTATUS NtShutdownWorkerFactory(HANDLE WorkerFactoryHandle, LONG *PendingWorkerCount);
    NTSTATUS NtReleaseWorkerFactoryWorker(HANDLE WorkerFactoryHandle);
    NTSTATUS NtWorkerFactoryWorkerReady(HANDLE WorkerFactoryHandle);
    NTSTATUS NtWaitForWorkViaWorkerFactory(HANDLE WorkerFactoryHandle, PFILE_IO_COMPLETION_INFORMATION MiniPackets, ULONG Count, PULONG PacketsReturned, PVOID DeferredWork);
    NTSTATUS NtQuerySystemTime(PLARGE_INTEGER SystemTime);
    NTSTATUS NtSetSystemTime(PLARGE_INTEGER SystemTime, PLARGE_INTEGER PreviousTime);
    NTSTATUS NtQueryTimerResolution(PULONG MaximumTime, PULONG MinimumTime, PULONG CurrentTime);
    NTSTATUS NtSetTimerResolution(ULONG DesiredTime, BOOLEAN SetResolution, PULONG ActualTime);
    NTSTATUS NtQueryPerformanceCounter(PLARGE_INTEGER PerformanceCounter, PLARGE_INTEGER PerformanceFrequency);
    NTSTATUS NtQueryAuxiliaryCounterFrequency(PULONG64 AuxiliaryCounterFrequency);
    NTSTATUS NtConvertBetweenAuxiliaryCounterAndPerformanceCounter(BOOLEAN ConvertAuxiliaryToPerformanceCounter, PULONG64 PerformanceOrAuxiliaryCounterValue, PULONG64 ConvertedValue, PULONG64 ConversionError);
    NTSTATUS NtAllocateLocallyUniqueId(PLUID Luid);
    NTSTATUS NtSetUuidSeed(PCHAR Seed);
    NTSTATUS NtAllocateUuids(PULARGE_INTEGER Time, PULONG Range, PULONG Sequence, PCHAR Seed);
    NTSTATUS NtQuerySystemInformation(SYSTEM_INFORMATION_CLASS SystemInformationClass, PVOID SystemInformation, ULONG SystemInformationLength, PULONG ReturnLength);
    NTSTATUS NtQuerySystemInformationEx(SYSTEM_INFORMATION_CLASS SystemInformationClass, PVOID InputBuffer, ULONG InputBufferLength, PVOID SystemInformation, ULONG SystemInformationLength, PULONG ReturnLength);
    NTSTATUS NtSetSystemInformation(SYSTEM_INFORMATION_CLASS SystemInformationClass, PVOID SystemInformation, ULONG SystemInformationLength);
    NTSTATUS NtSystemDebugControl(SYSDBG_COMMAND Command, PVOID InputBuffer, ULONG InputBufferLength, PVOID OutputBuffer, ULONG OutputBufferLength, PULONG ReturnLength);
    ULONGLONG NtGetTickCount64();
    ULONG NtGetTickCount();
    NTSTATUS NtQueryDefaultLocale(BOOLEAN UserProfile, PLCID DefaultLocaleId);
    NTSTATUS NtSetDefaultLocale(BOOLEAN UserProfile, LCID DefaultLocaleId);
    NTSTATUS NtQueryInstallUILanguage(LANGID *InstallUILanguageId);
    NTSTATUS NtFlushInstallUILanguage(LANGID InstallUILanguage, ULONG SetComittedFlag);
    NTSTATUS NtQueryDefaultUILanguage(LANGID *DefaultUILanguageId);
    NTSTATUS NtSetDefaultUILanguage(LANGID DefaultUILanguageId);
    NTSTATUS NtIsUILanguageComitted();
    NTSTATUS NtInitializeNlsFiles(PVOID *BaseAddress, PLCID DefaultLocaleId, PLARGE_INTEGER DefaultCasingTableSize, PULONG CurrentNLSVersion);
    NTSTATUS NtGetNlsSectionPtr(ULONG SectionType, ULONG SectionData, PVOID ContextData, PVOID *SectionPointer, PULONG SectionSize);
    NTSTATUS NtMapCMFModule(ULONG What, ULONG Index, PULONG CacheIndexOut, PULONG CacheFlagsOut, PULONG ViewSizeOut, PVOID *BaseAddress);
    NTSTATUS NtGetMUIRegistryInfo(ULONG Flags, PULONG DataSize, PVOID Data);
    NTSTATUS NtAddAtom(PCWSTR AtomName, ULONG Length, PRTL_ATOM Atom);
    NTSTATUS NtAddAtomEx(PCWSTR AtomName, ULONG Length, PRTL_ATOM Atom, ULONG Flags);
    NTSTATUS NtFindAtom(PCWSTR AtomName, ULONG Length, PRTL_ATOM Atom);
    NTSTATUS NtDeleteAtom(RTL_ATOM Atom);
    NTSTATUS NtQueryInformationAtom(RTL_ATOM Atom, ATOM_INFORMATION_CLASS AtomInformationClass, PVOID AtomInformation, ULONG AtomInformationLength, PULONG ReturnLength);
    NTSTATUS NtQueryLicenseValue(PCUNICODE_STRING ValueName, PULONG Type, PVOID Data, ULONG DataSize, PULONG ResultDataSize);
    NTSTATUS NtSetDefaultHardErrorPort(HANDLE DefaultHardErrorPort);
    NTSTATUS NtShutdownSystem(SHUTDOWN_ACTION Action);
    NTSTATUS NtDisplayString(PCUNICODE_STRING String);
    NTSTATUS NtDrawText(PCUNICODE_STRING Text);
    NTSTATUS NtManageHotPatch(HOT_PATCH_INFORMATION_CLASS HotPatchInformationClass, PVOID HotPatchInformation, ULONG HotPatchInformationLength, PULONG ReturnLength);
    NTSTATUS NtAllocateVirtualMemory(HANDLE ProcessHandle, PVOID *BaseAddress, ULONG_PTR ZeroBits, PSIZE_T RegionSize, ULONG AllocationType, ULONG PageProtection);
    NTSTATUS NtAllocateVirtualMemoryEx(HANDLE ProcessHandle, PVOID *BaseAddress, PSIZE_T RegionSize, ULONG AllocationType, ULONG PageProtection, PMEM_EXTENDED_PARAMETER ExtendedParameters, ULONG ExtendedParameterCount);
    NTSTATUS NtFreeVirtualMemory(HANDLE ProcessHandle, PVOID *BaseAddress, PSIZE_T RegionSize, ULONG FreeType);
    NTSTATUS NtReadVirtualMemory(HANDLE ProcessHandle, PVOID BaseAddress, PVOID Buffer, SIZE_T NumberOfBytesToRead, PSIZE_T NumberOfBytesRead);
    NTSTATUS NtWow64ReadVirtualMemory64(HANDLE ProcessHandle, ULONGLONG BaseAddress, PVOID Buffer, ULONGLONG NumberOfBytesToRead, PULONGLONG NumberOfBytesRead);
    NTSTATUS NtReadVirtualMemoryEx(HANDLE ProcessHandle, PVOID BaseAddress, PVOID Buffer, SIZE_T NumberOfBytesToRead, PSIZE_T NumberOfBytesRead, ULONG Flags);
    NTSTATUS NtWriteVirtualMemory(HANDLE ProcessHandle, PVOID BaseAddress, PVOID Buffer, SIZE_T NumberOfBytesToWrite, PSIZE_T NumberOfBytesWritten);
    NTSTATUS NtWow64WriteVirtualMemory64(HANDLE ProcessHandle, ULONGLONG BaseAddress, PVOID Buffer, ULONGLONG NumberOfBytesToWrite, PULONGLONG NumberOfBytesWritten);
    NTSTATUS NtProtectVirtualMemory(HANDLE ProcessHandle, PVOID *BaseAddress, PSIZE_T RegionSize, ULONG NewProtection, PULONG OldProtection);
    NTSTATUS NtQueryVirtualMemory(HANDLE ProcessHandle, PVOID BaseAddress, MEMORY_INFORMATION_CLASS MemoryInformationClass, PVOID MemoryInformation, SIZE_T MemoryInformationLength, PSIZE_T ReturnLength);
    NTSTATUS NtWow64QueryVirtualMemory64(HANDLE ProcessHandle, ULONGLONG BaseAddress, MEMORY_INFORMATION_CLASS MemoryInformationClass, PVOID MemoryInformation, ULONGLONG MemoryInformationLength, PULONGLONG ReturnLength);
    NTSTATUS NtFlushVirtualMemory(HANDLE ProcessHandle, PVOID *BaseAddress, PSIZE_T RegionSize, PIO_STATUS_BLOCK IoStatus);
    NTSTATUS NtSetInformationVirtualMemory(HANDLE ProcessHandle, VIRTUAL_MEMORY_INFORMATION_CLASS VmInformationClass, SIZE_T NumberOfEntries, PMEMORY_RANGE_ENTRY VirtualAddresses, PVOID VmInformation, ULONG VmInformationLength);
    NTSTATUS NtLockVirtualMemory(HANDLE ProcessHandle, PVOID *BaseAddress, PSIZE_T RegionSize, ULONG MapType);
    NTSTATUS NtUnlockVirtualMemory(HANDLE ProcessHandle, PVOID *BaseAddress, PSIZE_T RegionSize, ULONG MapType);
    NTSTATUS NtCreateSection(PHANDLE SectionHandle, ACCESS_MASK DesiredAccess, PCOBJECT_ATTRIBUTES ObjectAttributes, PLARGE_INTEGER MaximumSize, ULONG SectionPageProtection, ULONG AllocationAttributes, HANDLE FileHandle);
    NTSTATUS NtCreateSectionEx(PHANDLE SectionHandle, ACCESS_MASK DesiredAccess, PCOBJECT_ATTRIBUTES ObjectAttributes, PLARGE_INTEGER MaximumSize, ULONG SectionPageProtection, ULONG AllocationAttributes, HANDLE FileHandle, PMEM_EXTENDED_PARAMETER ExtendedParameters, ULONG ExtendedParameterCount);
    NTSTATUS NtOpenSection(PHANDLE SectionHandle, ACCESS_MASK DesiredAccess, PCOBJECT_ATTRIBUTES ObjectAttributes);
    NTSTATUS NtMapViewOfSection(HANDLE SectionHandle, HANDLE ProcessHandle, PVOID *BaseAddress, ULONG_PTR ZeroBits, SIZE_T CommitSize, PLARGE_INTEGER SectionOffset, PSIZE_T ViewSize, SECTION_INHERIT InheritDisposition, ULONG AllocationType, ULONG PageProtection);
    NTSTATUS NtMapViewOfSectionEx(HANDLE SectionHandle, HANDLE ProcessHandle, PVOID *BaseAddress, PLARGE_INTEGER SectionOffset, PSIZE_T ViewSize, ULONG AllocationType, ULONG PageProtection, PMEM_EXTENDED_PARAMETER ExtendedParameters, ULONG ExtendedParameterCount);
    NTSTATUS NtUnmapViewOfSection(HANDLE ProcessHandle, PVOID BaseAddress);
    NTSTATUS NtUnmapViewOfSectionEx(HANDLE ProcessHandle, PVOID BaseAddress, ULONG Flags);
    NTSTATUS NtExtendSection(HANDLE SectionHandle, PLARGE_INTEGER NewSectionSize);
    NTSTATUS NtQuerySection(HANDLE SectionHandle, SECTION_INFORMATION_CLASS SectionInformationClass, PVOID SectionInformation, SIZE_T SectionInformationLength, PSIZE_T ReturnLength);
    NTSTATUS NtAreMappedFilesTheSame(PVOID File1MappedAsAnImage, PVOID File2MappedAsFile);
    NTSTATUS NtCreatePartition(HANDLE ParentPartitionHandle, PHANDLE PartitionHandle, ACCESS_MASK DesiredAccess, PCOBJECT_ATTRIBUTES ObjectAttributes);
    NTSTATUS NtOpenPartition(PHANDLE PartitionHandle, ACCESS_MASK DesiredAccess, PCOBJECT_ATTRIBUTES ObjectAttributes);
    NTSTATUS NtManagePartition(HANDLE TargetHandle, HANDLE SourceHandle, PARTITION_INFORMATION_CLASS PartitionInformationClass, PVOID PartitionInformation, ULONG PartitionInformationLength);
    NTSTATUS NtMapUserPhysicalPages(PVOID VirtualAddress, SIZE_T NumberOfPages, PULONG_PTR UserPfnArray);
    NTSTATUS NtMapUserPhysicalPagesScatter(PVOID *VirtualAddresses, SIZE_T NumberOfPages, PULONG_PTR UserPfnArray);
    NTSTATUS NtAllocateUserPhysicalPages(HANDLE ProcessHandle, PSIZE_T NumberOfPages, PULONG_PTR UserPfnArray);
    NTSTATUS NtAllocateUserPhysicalPagesEx(HANDLE ProcessHandle, PULONG_PTR NumberOfPages, PULONG_PTR UserPfnArray, PMEM_EXTENDED_PARAMETER ExtendedParameters, ULONG ExtendedParameterCount);
    NTSTATUS NtFreeUserPhysicalPages(HANDLE ProcessHandle, PULONG_PTR NumberOfPages, PULONG_PTR UserPfnArray);
    NTSTATUS NtGetWriteWatch(HANDLE ProcessHandle, ULONG Flags, PVOID BaseAddress, SIZE_T RegionSize, PVOID *UserAddressArray, PULONG_PTR EntriesInUserAddressArray, PULONG Granularity);
    NTSTATUS NtResetWriteWatch(HANDLE ProcessHandle, PVOID BaseAddress, SIZE_T RegionSize);
    NTSTATUS NtCreatePagingFile(PCUNICODE_STRING PageFileName, PLARGE_INTEGER MinimumSize, PLARGE_INTEGER MaximumSize, ULONG Priority);
    NTSTATUS NtFlushInstructionCache(HANDLE ProcessHandle, PVOID BaseAddress, SIZE_T RegionSize);
    NTSTATUS NtFlushWriteBuffer();
    NTSTATUS NtFlushProcessWriteBuffers();
    NTSTATUS NtCreateEnclave(HANDLE ProcessHandle, PVOID *BaseAddress, ULONG_PTR ZeroBits, SIZE_T Size, SIZE_T InitialCommitment, ULONG EnclaveType, PVOID EnclaveInformation, ULONG EnclaveInformationLength, PULONG EnclaveError);
    NTSTATUS NtLoadEnclaveData(HANDLE ProcessHandle, PVOID BaseAddress, PVOID Buffer, SIZE_T BufferSize, ULONG Protect, PVOID PageInformation, ULONG PageInformationLength, PSIZE_T NumberOfBytesWritten, PULONG EnclaveError);
    NTSTATUS NtInitializeEnclave(HANDLE ProcessHandle, PVOID BaseAddress, PVOID EnclaveInformation, ULONG EnclaveInformationLength, PULONG EnclaveError);
    NTSTATUS NtTerminateEnclave(PVOID BaseAddress, ULONG Flags);
    NTSTATUS NtCallEnclave(PENCLAVE_ROUTINE Routine, PVOID Reserved, ULONG Flags, PVOID *RoutineParamReturn);
    NTSTATUS NtQueryObject(HANDLE Handle, OBJECT_INFORMATION_CLASS ObjectInformationClass, PVOID ObjectInformation, ULONG ObjectInformationLength, PULONG ReturnLength);
    NTSTATUS NtSetInformationObject(HANDLE Handle, OBJECT_INFORMATION_CLASS ObjectInformationClass, PVOID ObjectInformation, ULONG ObjectInformationLength);
    NTSTATUS NtDuplicateObject(HANDLE SourceProcessHandle, HANDLE SourceHandle, HANDLE TargetProcessHandle, PHANDLE TargetHandle, ACCESS_MASK DesiredAccess, ULONG HandleAttributes, ULONG Options);
    NTSTATUS NtMakeTemporaryObject(HANDLE Handle);
    NTSTATUS NtMakePermanentObject(HANDLE Handle);
    NTSTATUS NtSignalAndWaitForSingleObject(HANDLE SignalHandle, HANDLE WaitHandle, BOOLEAN Alertable, PLARGE_INTEGER Timeout);
    NTSTATUS NtWaitForSingleObject(HANDLE Handle, BOOLEAN Alertable, PLARGE_INTEGER Timeout);
    NTSTATUS NtWaitForMultipleObjects(ULONG Count, HANDLE Handles[], WAIT_TYPE WaitType, BOOLEAN Alertable, PLARGE_INTEGER Timeout);
    NTSTATUS NtWaitForMultipleObjects32(ULONG Count, LONG Handles[], WAIT_TYPE WaitType, BOOLEAN Alertable, PLARGE_INTEGER Timeout);
    NTSTATUS NtSetSecurityObject(HANDLE Handle, SECURITY_INFORMATION SecurityInformation, PSECURITY_DESCRIPTOR SecurityDescriptor);
    NTSTATUS NtQuerySecurityObject(HANDLE Handle, SECURITY_INFORMATION SecurityInformation, PSECURITY_DESCRIPTOR SecurityDescriptor, ULONG Length, PULONG LengthNeeded);
    NTSTATUS NtClose(HANDLE Handle);
    NTSTATUS NtCompareObjects(HANDLE FirstObjectHandle, HANDLE SecondObjectHandle);
    NTSTATUS NtCreateDirectoryObject(PHANDLE DirectoryHandle, ACCESS_MASK DesiredAccess, POBJECT_ATTRIBUTES ObjectAttributes);
    NTSTATUS NtCreateDirectoryObjectEx(PHANDLE DirectoryHandle, ACCESS_MASK DesiredAccess, POBJECT_ATTRIBUTES ObjectAttributes, HANDLE ShadowDirectoryHandle, ULONG Flags);
    NTSTATUS NtOpenDirectoryObject(PHANDLE DirectoryHandle, ACCESS_MASK DesiredAccess, POBJECT_ATTRIBUTES ObjectAttributes);
    NTSTATUS NtQueryDirectoryObject(HANDLE DirectoryHandle, PVOID Buffer, ULONG Length, BOOLEAN ReturnSingleEntry, BOOLEAN RestartScan, PULONG Context, PULONG ReturnLength);
    NTSTATUS NtCreatePrivateNamespace(PHANDLE NamespaceHandle, ACCESS_MASK DesiredAccess, POBJECT_ATTRIBUTES ObjectAttributes, POBJECT_BOUNDARY_DESCRIPTOR BoundaryDescriptor);
    NTSTATUS NtOpenPrivateNamespace(PHANDLE NamespaceHandle, ACCESS_MASK DesiredAccess, POBJECT_ATTRIBUTES ObjectAttributes, POBJECT_BOUNDARY_DESCRIPTOR BoundaryDescriptor);
    NTSTATUS NtDeletePrivateNamespace(HANDLE NamespaceHandle);
    NTSTATUS NtCreateSymbolicLinkObject(PHANDLE LinkHandle, ACCESS_MASK DesiredAccess, POBJECT_ATTRIBUTES ObjectAttributes, PCUNICODE_STRING LinkTarget);
    NTSTATUS NtOpenSymbolicLinkObject(PHANDLE LinkHandle, ACCESS_MASK DesiredAccess, POBJECT_ATTRIBUTES ObjectAttributes);
    NTSTATUS NtQuerySymbolicLinkObject(HANDLE LinkHandle, PUNICODE_STRING LinkTarget, PULONG ReturnedLength);
    NTSTATUS NtSetInformationSymbolicLink(HANDLE LinkHandle, SYMBOLIC_LINK_INFO_CLASS SymbolicLinkInformationClass, PVOID SymbolicLinkInformation, ULONG SymbolicLinkInformationLength);
    LOGICAL NtQueryPortInformationProcess();
    NTSTATUS NtCreateProcess(PHANDLE ProcessHandle, ACCESS_MASK DesiredAccess, PCOBJECT_ATTRIBUTES ObjectAttributes, HANDLE ParentProcess, BOOLEAN InheritObjectTable, HANDLE SectionHandle, HANDLE DebugPort, HANDLE TokenHandle);
    NTSTATUS NtCreateProcessEx(PHANDLE ProcessHandle, ACCESS_MASK DesiredAccess, PCOBJECT_ATTRIBUTES ObjectAttributes, HANDLE ParentProcess, ULONG Flags, HANDLE SectionHandle, HANDLE DebugPort, HANDLE TokenHandle, ULONG Reserved);
    NTSTATUS NtOpenProcess(PHANDLE ProcessHandle, ACCESS_MASK DesiredAccess, PCOBJECT_ATTRIBUTES ObjectAttributes, PCLIENT_ID ClientId);
    NTSTATUS NtTerminateProcess(HANDLE ProcessHandle, NTSTATUS ExitStatus);
    NTSTATUS NtSuspendProcess(HANDLE ProcessHandle);
    NTSTATUS NtResumeProcess(HANDLE ProcessHandle);
    NTSTATUS NtQueryInformationProcess(HANDLE ProcessHandle, PROCESSINFOCLASS ProcessInformationClass, PVOID ProcessInformation, ULONG ProcessInformationLength, PULONG ReturnLength);
    NTSTATUS NtWow64QueryInformationProcess64(HANDLE ProcessHandle, PROCESSINFOCLASS ProcessInformationClass, PVOID ProcessInformation, ULONG ProcessInformationLength, PULONG ReturnLength);
    NTSTATUS NtSetInformationProcess(HANDLE ProcessHandle, PROCESSINFOCLASS ProcessInformationClass, PVOID ProcessInformation, ULONG ProcessInformationLength);
    NTSTATUS NtGetNextProcess(HANDLE ProcessHandle, ACCESS_MASK DesiredAccess, ULONG HandleAttributes, ULONG Flags, PHANDLE NewProcessHandle);
    NTSTATUS NtGetNextThread(HANDLE ProcessHandle, HANDLE ThreadHandle, ACCESS_MASK DesiredAccess, ULONG HandleAttributes, ULONG Flags, PHANDLE NewThreadHandle);
    NTSTATUS NtCreateProcessStateChange(PHANDLE ProcessStateChangeHandle, ACCESS_MASK DesiredAccess, PCOBJECT_ATTRIBUTES ObjectAttributes, HANDLE ProcessHandle, ULONG Reserved);
    NTSTATUS NtChangeProcessState(HANDLE ProcessStateChangeHandle, HANDLE ProcessHandle, PROCESS_STATE_CHANGE_TYPE StateChangeType, PVOID ExtendedInformation, SIZE_T ExtendedInformationLength, ULONG Reserved);
    NTSTATUS NtCreateThreadStateChange(PHANDLE ThreadStateChangeHandle, ACCESS_MASK DesiredAccess, PCOBJECT_ATTRIBUTES ObjectAttributes, HANDLE ThreadHandle, ULONG Reserved);
    NTSTATUS NtChangeThreadState(HANDLE ThreadStateChangeHandle, HANDLE ThreadHandle, THREAD_STATE_CHANGE_TYPE StateChangeType, PVOID ExtendedInformation, SIZE_T ExtendedInformationLength, ULONG Reserved);
    NTSTATUS NtCreateThread(PHANDLE ThreadHandle, ACCESS_MASK DesiredAccess, PCOBJECT_ATTRIBUTES ObjectAttributes, HANDLE ProcessHandle, PCLIENT_ID ClientId, PCONTEXT ThreadContext, PINITIAL_TEB InitialTeb, BOOLEAN CreateSuspended);
    NTSTATUS NtOpenThread(PHANDLE ThreadHandle, ACCESS_MASK DesiredAccess, PCOBJECT_ATTRIBUTES ObjectAttributes, PCLIENT_ID ClientId);
    NTSTATUS NtTerminateThread(HANDLE ThreadHandle, NTSTATUS ExitStatus);
    NTSTATUS NtSuspendThread(HANDLE ThreadHandle, PULONG PreviousSuspendCount);
    NTSTATUS NtResumeThread(HANDLE ThreadHandle, PULONG PreviousSuspendCount);
    ULONG NtGetCurrentProcessorNumber();
    ULONG NtGetCurrentProcessorNumberEx(PPROCESSOR_NUMBER ProcessorNumber);
    NTSTATUS NtGetContextThread(HANDLE ThreadHandle, PCONTEXT ThreadContext);
    NTSTATUS NtSetContextThread(HANDLE ThreadHandle, PCONTEXT ThreadContext);
    NTSTATUS NtQueryInformationThread(HANDLE ThreadHandle, THREADINFOCLASS ThreadInformationClass, PVOID ThreadInformation, ULONG ThreadInformationLength, PULONG ReturnLength);
    NTSTATUS NtSetInformationThread(HANDLE ThreadHandle, THREADINFOCLASS ThreadInformationClass, PVOID ThreadInformation, ULONG ThreadInformationLength);
    NTSTATUS NtAlertThread(HANDLE ThreadHandle);
    NTSTATUS NtAlertResumeThread(HANDLE ThreadHandle, PULONG PreviousSuspendCount);
    NTSTATUS NtTestAlert();
    NTSTATUS NtAlertThreadByThreadId(HANDLE ThreadId);
    NTSTATUS NtAlertThreadByThreadIdEx(HANDLE ThreadId, PRTL_SRWLOCK Lock);
    NTSTATUS NtAlertMultipleThreadByThreadId(PHANDLE MultipleThreadId, ULONG Count, PPS_ALERT_THREAD_EXTENDED_PARAMETER ExtendedParameters, ULONG ExtendedParameterCount);
    NTSTATUS NtWaitForAlertByThreadId(PVOID Address, PLARGE_INTEGER Timeout);
    NTSTATUS NtImpersonateThread(HANDLE ServerThreadHandle, HANDLE ClientThreadHandle, PSECURITY_QUALITY_OF_SERVICE SecurityQos);
    NTSTATUS NtRegisterThreadTerminatePort(HANDLE PortHandle);
    NTSTATUS NtSetLdtEntries(ULONG Selector0, ULONG Entry0Low, ULONG Entry0Hi, ULONG Selector1, ULONG Entry1Low, ULONG Entry1Hi);
    NTSTATUS NtQueueApcThread(HANDLE ThreadHandle, PPS_APC_ROUTINE ApcRoutine, PVOID ApcArgument1, PVOID ApcArgument2, PVOID ApcArgument3);
    NTSTATUS NtQueueApcThreadEx(HANDLE ThreadHandle, HANDLE ReserveHandle, PPS_APC_ROUTINE ApcRoutine, PVOID ApcArgument1, PVOID ApcArgument2, PVOID ApcArgument3);
    NTSTATUS NtQueueApcThreadEx2(HANDLE ThreadHandle, HANDLE ReserveHandle, ULONG ApcFlags, PPS_APC_ROUTINE ApcRoutine, PVOID ApcArgument1, PVOID ApcArgument2, PVOID ApcArgument3);
    NTSTATUS NtCreateUserProcess(PHANDLE ProcessHandle, PHANDLE ThreadHandle, ACCESS_MASK ProcessDesiredAccess, ACCESS_MASK ThreadDesiredAccess, PCOBJECT_ATTRIBUTES ProcessObjectAttributes, PCOBJECT_ATTRIBUTES ThreadObjectAttributes, ULONG ProcessFlags, ULONG ThreadFlags, PRTL_USER_PROCESS_PARAMETERS ProcessParameters, PPS_CREATE_INFO CreateInfo, PPS_ATTRIBUTE_LIST AttributeList);
    NTSTATUS NtCreateThreadEx(PHANDLE ThreadHandle, ACCESS_MASK DesiredAccess, PCOBJECT_ATTRIBUTES ObjectAttributes, HANDLE ProcessHandle, PUSER_THREAD_START_ROUTINE StartRoutine, PVOID Argument, ULONG CreateFlags, SIZE_T ZeroBits, SIZE_T StackSize, SIZE_T MaximumStackSize, PPS_ATTRIBUTE_LIST AttributeList);
    NTSTATUS NtCreateJobObject(PHANDLE JobHandle, ACCESS_MASK DesiredAccess, PCOBJECT_ATTRIBUTES ObjectAttributes);
    NTSTATUS NtOpenJobObject(PHANDLE JobHandle, ACCESS_MASK DesiredAccess, PCOBJECT_ATTRIBUTES ObjectAttributes);
    NTSTATUS NtAssignProcessToJobObject(HANDLE JobHandle, HANDLE ProcessHandle);
    NTSTATUS NtTerminateJobObject(HANDLE JobHandle, NTSTATUS ExitStatus);
    NTSTATUS NtIsProcessInJob(HANDLE ProcessHandle, HANDLE JobHandle);
    NTSTATUS NtQueryInformationJobObject(HANDLE JobHandle, ULONG JobObjectInformationClass, PVOID JobObjectInformation, ULONG JobObjectInformationLength, PULONG ReturnLength);
    NTSTATUS NtSetInformationJobObject(HANDLE JobHandle, ULONG JobObjectInformationClass, PVOID JobObjectInformation, ULONG JobObjectInformationLength);
    NTSTATUS NtCreateJobSet(ULONG NumJob, PJOB_SET_ARRAY UserJobSet, ULONG Flags);
    NTSTATUS NtRevertContainerImpersonation();
    NTSTATUS NtAllocateReserveObject(PHANDLE MemoryReserveHandle, PCOBJECT_ATTRIBUTES ObjectAttributes, MEMORY_RESERVE_TYPE Type);
    NTSTATUS NtPssCaptureVaSpaceBulk(HANDLE ProcessHandle, PVOID BaseAddress, PNTPSS_MEMORY_BULK_INFORMATION BulkInformation, SIZE_T BulkInformationLength, PSIZE_T ReturnLength);
    NTSTATUS NtCreateDebugObject(PHANDLE DebugObjectHandle, ACCESS_MASK DesiredAccess, POBJECT_ATTRIBUTES ObjectAttributes, ULONG Flags);
    NTSTATUS NtDebugActiveProcess(HANDLE ProcessHandle, HANDLE DebugObjectHandle);
    NTSTATUS NtDebugContinue(HANDLE DebugObjectHandle, PCLIENT_ID ClientId, NTSTATUS ContinueStatus);
    NTSTATUS NtRemoveProcessDebug(HANDLE ProcessHandle, HANDLE DebugObjectHandle);
    NTSTATUS NtSetInformationDebugObject(HANDLE DebugObjectHandle, DEBUGOBJECTINFOCLASS DebugObjectInformationClass, PVOID DebugInformation, ULONG DebugInformationLength, PULONG ReturnLength);
    NTSTATUS NtWaitForDebugEvent(HANDLE DebugObjectHandle, BOOLEAN Alertable, PLARGE_INTEGER Timeout, PDBGUI_WAIT_STATE_CHANGE WaitStateChange);
    NTSTATUS NtCreateFile(PHANDLE FileHandle, ACCESS_MASK DesiredAccess, PCOBJECT_ATTRIBUTES ObjectAttributes, PIO_STATUS_BLOCK IoStatusBlock, PLARGE_INTEGER AllocationSize, ULONG FileAttributes, ULONG ShareAccess, ULONG CreateDisposition, ULONG CreateOptions, PVOID EaBuffer, ULONG EaLength);
    NTSTATUS NtCreateNamedPipeFile(PHANDLE FileHandle, ACCESS_MASK DesiredAccess, PCOBJECT_ATTRIBUTES ObjectAttributes, PIO_STATUS_BLOCK IoStatusBlock, ULONG ShareAccess, ULONG CreateDisposition, ULONG CreateOptions, ULONG NamedPipeType, ULONG ReadMode, ULONG CompletionMode, ULONG MaximumInstances, ULONG InboundQuota, ULONG OutboundQuota, PLARGE_INTEGER DefaultTimeout);
    NTSTATUS NtCreateMailslotFile(PHANDLE FileHandle, ACCESS_MASK DesiredAccess, PCOBJECT_ATTRIBUTES ObjectAttributes, PIO_STATUS_BLOCK IoStatusBlock, ULONG CreateOptions, ULONG MailslotQuota, ULONG MaximumMessageSize, PLARGE_INTEGER ReadTimeout);
    NTSTATUS NtOpenFile(PHANDLE FileHandle, ACCESS_MASK DesiredAccess, PCOBJECT_ATTRIBUTES ObjectAttributes, PIO_STATUS_BLOCK IoStatusBlock, ULONG ShareAccess, ULONG OpenOptions);
    NTSTATUS NtDeleteFile(PCOBJECT_ATTRIBUTES ObjectAttributes);
    NTSTATUS NtFlushBuffersFile(HANDLE FileHandle, PIO_STATUS_BLOCK IoStatusBlock);
    NTSTATUS NtFlushBuffersFileEx(HANDLE FileHandle, ULONG Flags, PVOID Parameters, ULONG ParametersSize, PIO_STATUS_BLOCK IoStatusBlock);
    NTSTATUS NtQueryInformationFile(HANDLE FileHandle, PIO_STATUS_BLOCK IoStatusBlock, PVOID FileInformation, ULONG Length, FILE_INFORMATION_CLASS FileInformationClass);
    NTSTATUS NtQueryInformationByName(PCOBJECT_ATTRIBUTES ObjectAttributes, PIO_STATUS_BLOCK IoStatusBlock, PVOID FileInformation, ULONG Length, FILE_INFORMATION_CLASS FileInformationClass);
    NTSTATUS NtSetInformationFile(HANDLE FileHandle, PIO_STATUS_BLOCK IoStatusBlock, PVOID FileInformation, ULONG Length, FILE_INFORMATION_CLASS FileInformationClass);
    NTSTATUS NtQueryDirectoryFile(HANDLE FileHandle, HANDLE Event, PIO_APC_ROUTINE ApcRoutine, PVOID ApcContext, PIO_STATUS_BLOCK IoStatusBlock, PVOID FileInformation, ULONG Length, FILE_INFORMATION_CLASS FileInformationClass, BOOLEAN ReturnSingleEntry, PCUNICODE_STRING FileName, BOOLEAN RestartScan);
    NTSTATUS NtQueryDirectoryFileEx(HANDLE FileHandle, HANDLE Event, PIO_APC_ROUTINE ApcRoutine, PVOID ApcContext, PIO_STATUS_BLOCK IoStatusBlock, PVOID FileInformation, ULONG Length, FILE_INFORMATION_CLASS FileInformationClass, ULONG QueryFlags, PCUNICODE_STRING FileName);
    NTSTATUS NtQueryEaFile(HANDLE FileHandle, PIO_STATUS_BLOCK IoStatusBlock, PVOID Buffer, ULONG Length, BOOLEAN ReturnSingleEntry, PVOID EaList, ULONG EaListLength, PULONG EaIndex, BOOLEAN RestartScan);
    NTSTATUS NtSetEaFile(HANDLE FileHandle, PIO_STATUS_BLOCK IoStatusBlock, PVOID Buffer, ULONG Length);
    NTSTATUS NtQueryQuotaInformationFile(HANDLE FileHandle, PIO_STATUS_BLOCK IoStatusBlock, PVOID Buffer, ULONG Length, BOOLEAN ReturnSingleEntry, PVOID SidList, ULONG SidListLength, PSID StartSid, BOOLEAN RestartScan);
    NTSTATUS NtSetQuotaInformationFile(HANDLE FileHandle, PIO_STATUS_BLOCK IoStatusBlock, PVOID Buffer, ULONG Length);
    NTSTATUS NtQueryVolumeInformationFile(HANDLE FileHandle, PIO_STATUS_BLOCK IoStatusBlock, PVOID FsInformation, ULONG Length, FSINFOCLASS FsInformationClass);
    NTSTATUS NtSetVolumeInformationFile(HANDLE FileHandle, PIO_STATUS_BLOCK IoStatusBlock, PVOID FsInformation, ULONG Length, FSINFOCLASS FsInformationClass);
    NTSTATUS NtCancelIoFile(HANDLE FileHandle, PIO_STATUS_BLOCK IoStatusBlock);
    NTSTATUS NtCancelIoFileEx(HANDLE FileHandle, PIO_STATUS_BLOCK IoRequestToCancel, PIO_STATUS_BLOCK IoStatusBlock);
    NTSTATUS NtCancelSynchronousIoFile(HANDLE ThreadHandle, PIO_STATUS_BLOCK IoRequestToCancel, PIO_STATUS_BLOCK IoStatusBlock);
    NTSTATUS NtDeviceIoControlFile(HANDLE FileHandle, HANDLE Event, PIO_APC_ROUTINE ApcRoutine, PVOID ApcContext, PIO_STATUS_BLOCK IoStatusBlock, ULONG IoControlCode, PVOID InputBuffer, ULONG InputBufferLength, PVOID OutputBuffer, ULONG OutputBufferLength);
    NTSTATUS NtFsControlFile(HANDLE FileHandle, HANDLE Event, PIO_APC_ROUTINE ApcRoutine, PVOID ApcContext, PIO_STATUS_BLOCK IoStatusBlock, ULONG FsControlCode, PVOID InputBuffer, ULONG InputBufferLength, PVOID OutputBuffer, ULONG OutputBufferLength);
    NTSTATUS NtReadFile(HANDLE FileHandle, HANDLE Event, PIO_APC_ROUTINE ApcRoutine, PVOID ApcContext, PIO_STATUS_BLOCK IoStatusBlock, PVOID Buffer, ULONG Length, PLARGE_INTEGER ByteOffset, PULONG Key);
    NTSTATUS NtWriteFile(HANDLE FileHandle, HANDLE Event, PIO_APC_ROUTINE ApcRoutine, PVOID ApcContext, PIO_STATUS_BLOCK IoStatusBlock, PVOID Buffer, ULONG Length, PLARGE_INTEGER ByteOffset, PULONG Key);
    NTSTATUS NtReadFileScatter(HANDLE FileHandle, HANDLE Event, PIO_APC_ROUTINE ApcRoutine, PVOID ApcContext, PIO_STATUS_BLOCK IoStatusBlock, PFILE_SEGMENT_ELEMENT SegmentArray, ULONG Length, PLARGE_INTEGER ByteOffset, PULONG Key);
    NTSTATUS NtWriteFileGather(HANDLE FileHandle, HANDLE Event, PIO_APC_ROUTINE ApcRoutine, PVOID ApcContext, PIO_STATUS_BLOCK IoStatusBlock, PFILE_SEGMENT_ELEMENT SegmentArray, ULONG Length, PLARGE_INTEGER ByteOffset, PULONG Key);
    NTSTATUS NtLockFile(HANDLE FileHandle, HANDLE Event, PIO_APC_ROUTINE ApcRoutine, PVOID ApcContext, PIO_STATUS_BLOCK IoStatusBlock, PLARGE_INTEGER ByteOffset, PLARGE_INTEGER Length, ULONG Key, BOOLEAN FailImmediately, BOOLEAN ExclusiveLock);
    NTSTATUS NtUnlockFile(HANDLE FileHandle, PIO_STATUS_BLOCK IoStatusBlock, PLARGE_INTEGER ByteOffset, PLARGE_INTEGER Length, ULONG Key);
    NTSTATUS NtQueryAttributesFile(PCOBJECT_ATTRIBUTES ObjectAttributes, PFILE_BASIC_INFORMATION FileInformation);
    NTSTATUS NtQueryFullAttributesFile(PCOBJECT_ATTRIBUTES ObjectAttributes, PFILE_NETWORK_OPEN_INFORMATION FileInformation);
    NTSTATUS NtNotifyChangeDirectoryFile(HANDLE FileHandle, HANDLE Event, PIO_APC_ROUTINE ApcRoutine, PVOID ApcContext, PIO_STATUS_BLOCK IoStatusBlock, PVOID Buffer, ULONG Length, ULONG CompletionFilter, BOOLEAN WatchTree);
    NTSTATUS NtNotifyChangeDirectoryFileEx(HANDLE FileHandle, HANDLE Event, PIO_APC_ROUTINE ApcRoutine, PVOID ApcContext, PIO_STATUS_BLOCK IoStatusBlock, PVOID Buffer, ULONG Length, ULONG CompletionFilter, BOOLEAN WatchTree, DIRECTORY_NOTIFY_INFORMATION_CLASS DirectoryNotifyInformationClass);
    NTSTATUS NtLoadDriver(PCUNICODE_STRING DriverServiceName);
    NTSTATUS NtUnloadDriver(PCUNICODE_STRING DriverServiceName);
    NTSTATUS NtCreateIoCompletion(PHANDLE IoCompletionHandle, ACCESS_MASK DesiredAccess, PCOBJECT_ATTRIBUTES ObjectAttributes, ULONG NumberOfConcurrentThreads);
    NTSTATUS NtOpenIoCompletion(PHANDLE IoCompletionHandle, ACCESS_MASK DesiredAccess, PCOBJECT_ATTRIBUTES ObjectAttributes);
    NTSTATUS NtQueryIoCompletion(HANDLE IoCompletionHandle, IO_COMPLETION_INFORMATION_CLASS IoCompletionInformationClass, PVOID IoCompletionInformation, ULONG IoCompletionInformationLength, PULONG ReturnLength);
    NTSTATUS NtSetIoCompletion(HANDLE IoCompletionHandle, PVOID KeyContext, PVOID ApcContext, NTSTATUS IoStatus, ULONG_PTR IoStatusInformation);
    NTSTATUS NtSetIoCompletionEx(HANDLE IoCompletionHandle, HANDLE IoCompletionPacketHandle, PVOID KeyContext, PVOID ApcContext, NTSTATUS IoStatus, ULONG_PTR IoStatusInformation);
    NTSTATUS NtRemoveIoCompletion(HANDLE IoCompletionHandle, PVOID *KeyContext, PVOID *ApcContext, PIO_STATUS_BLOCK IoStatusBlock, PLARGE_INTEGER Timeout);
    NTSTATUS NtRemoveIoCompletionEx(HANDLE IoCompletionHandle, PFILE_IO_COMPLETION_INFORMATION IoCompletionInformation, ULONG Count, PULONG NumEntriesRemoved, PLARGE_INTEGER Timeout, BOOLEAN Alertable);
    NTSTATUS NtCreateWaitCompletionPacket(PHANDLE WaitCompletionPacketHandle, ACCESS_MASK DesiredAccess, PCOBJECT_ATTRIBUTES ObjectAttributes);
    NTSTATUS NtAssociateWaitCompletionPacket(HANDLE WaitCompletionPacketHandle, HANDLE IoCompletionHandle, HANDLE TargetObjectHandle, PVOID KeyContext, PVOID ApcContext, NTSTATUS IoStatus, ULONG_PTR IoStatusInformation, PBOOLEAN AlreadySignaled);
    NTSTATUS NtCancelWaitCompletionPacket(HANDLE WaitCompletionPacketHandle, BOOLEAN RemoveSignaledPacket);
    NTSTATUS NtCopyFileChunk(HANDLE SourceHandle, HANDLE DestinationHandle, HANDLE EventHandle, PIO_STATUS_BLOCK IoStatusBlock, ULONG Length, PLARGE_INTEGER SourceOffset, PLARGE_INTEGER DestOffset, PULONG SourceKey, PULONG DestKey, ULONG Flags);
    NTSTATUS NtCreateIoRing(PHANDLE IoRingHandle, ULONG CreateParametersLength, PVOID CreateParameters, ULONG OutputParametersLength, PVOID OutputParameters);
    NTSTATUS NtSubmitIoRing(HANDLE IoRingHandle, ULONG Flags, ULONG WaitOperations, PLARGE_INTEGER Timeout);
    NTSTATUS NtQueryIoRingCapabilities(SIZE_T IoRingCapabilitiesLength, PVOID IoRingCapabilities);
    NTSTATUS NtSetInformationIoRing(HANDLE IoRingHandle, ULONG IoRingInformationClass, ULONG IoRingInformationLength, PVOID IoRingInformation);
    NTSTATUS NtCreatePort(PHANDLE PortHandle, POBJECT_ATTRIBUTES ObjectAttributes, ULONG MaxConnectionInfoLength, ULONG MaxMessageLength, ULONG MaxPoolUsage);
    NTSTATUS NtCreateWaitablePort(PHANDLE PortHandle, POBJECT_ATTRIBUTES ObjectAttributes, ULONG MaxConnectionInfoLength, ULONG MaxMessageLength, ULONG MaxPoolUsage);
    NTSTATUS NtConnectPort(PHANDLE PortHandle, PCUNICODE_STRING PortName, PSECURITY_QUALITY_OF_SERVICE SecurityQos, PPORT_VIEW ClientView, PREMOTE_PORT_VIEW ServerView, PULONG MaxMessageLength, PVOID ConnectionInformation, PULONG ConnectionInformationLength);
    NTSTATUS NtSecureConnectPort(PHANDLE PortHandle, PCUNICODE_STRING PortName, PSECURITY_QUALITY_OF_SERVICE SecurityQos, PPORT_VIEW ClientView, PSID RequiredServerSid, PREMOTE_PORT_VIEW ServerView, PULONG MaxMessageLength, PVOID ConnectionInformation, PULONG ConnectionInformationLength);
    NTSTATUS NtListenPort(HANDLE PortHandle, PPORT_MESSAGE ConnectionRequest);
    NTSTATUS NtAcceptConnectPort(PHANDLE PortHandle, PVOID PortContext, PPORT_MESSAGE ConnectionRequest, BOOLEAN AcceptConnection, PPORT_VIEW ServerView, PREMOTE_PORT_VIEW ClientView);
    NTSTATUS NtCompleteConnectPort(HANDLE PortHandle);
    NTSTATUS NtRequestPort(HANDLE PortHandle, PPORT_MESSAGE RequestMessage);
    NTSTATUS NtRequestWaitReplyPort(HANDLE PortHandle, PPORT_MESSAGE RequestMessage, PPORT_MESSAGE ReplyMessage);
    NTSTATUS NtReplyPort(HANDLE PortHandle, PPORT_MESSAGE ReplyMessage);
    NTSTATUS NtReplyWaitReplyPort(HANDLE PortHandle, PPORT_MESSAGE ReplyMessage);
    NTSTATUS NtReplyWaitReceivePort(HANDLE PortHandle, PVOID *PortContext, PPORT_MESSAGE ReplyMessage, PPORT_MESSAGE ReceiveMessage);
    NTSTATUS NtReplyWaitReceivePortEx(HANDLE PortHandle, PVOID *PortContext, PPORT_MESSAGE ReplyMessage, PPORT_MESSAGE ReceiveMessage, PLARGE_INTEGER Timeout);
    NTSTATUS NtImpersonateClientOfPort(HANDLE PortHandle, PPORT_MESSAGE Message);
    NTSTATUS NtReadRequestData(HANDLE PortHandle, PPORT_MESSAGE Message, ULONG DataEntryIndex, PVOID Buffer, SIZE_T BufferSize, PSIZE_T NumberOfBytesRead);
    NTSTATUS NtWriteRequestData(HANDLE PortHandle, PPORT_MESSAGE Message, ULONG DataEntryIndex, PVOID Buffer, SIZE_T BufferSize, PSIZE_T NumberOfBytesWritten);
    NTSTATUS NtQueryInformationPort(HANDLE PortHandle, PORT_INFORMATION_CLASS PortInformationClass, PVOID PortInformation, ULONG Length, PULONG ReturnLength);
    NTSTATUS NtAlpcCreatePort(PHANDLE PortHandle, POBJECT_ATTRIBUTES ObjectAttributes, PALPC_PORT_ATTRIBUTES PortAttributes);
    NTSTATUS NtAlpcDisconnectPort(HANDLE PortHandle, ULONG Flags);
    NTSTATUS NtAlpcQueryInformation(HANDLE PortHandle, ALPC_PORT_INFORMATION_CLASS PortInformationClass, PVOID PortInformation, ULONG Length, PULONG ReturnLength);
    NTSTATUS NtAlpcSetInformation(HANDLE PortHandle, ALPC_PORT_INFORMATION_CLASS PortInformationClass, PVOID PortInformation, ULONG Length);
    NTSTATUS NtAlpcCreatePortSection(HANDLE PortHandle, ULONG Flags, HANDLE SectionHandle, SIZE_T SectionSize, PALPC_HANDLE AlpcSectionHandle, PSIZE_T ActualSectionSize);
    NTSTATUS NtAlpcDeletePortSection(HANDLE PortHandle, ULONG Flags, ALPC_HANDLE SectionHandle);
    NTSTATUS NtAlpcCreateResourceReserve(HANDLE PortHandle, ULONG Flags, SIZE_T MessageSize, PULONG ResourceId);
    NTSTATUS NtAlpcDeleteResourceReserve(HANDLE PortHandle, ULONG Flags, ULONG ResourceId);
    NTSTATUS NtAlpcCreateSectionView(HANDLE PortHandle, ULONG Flags, PALPC_DATA_VIEW_ATTR ViewAttributes);
    NTSTATUS NtAlpcDeleteSectionView(HANDLE PortHandle, ULONG Flags, PVOID ViewBase);
    NTSTATUS NtAlpcCreateSecurityContext(HANDLE PortHandle, ULONG Flags, PALPC_SECURITY_ATTR SecurityAttribute);
    NTSTATUS NtAlpcDeleteSecurityContext(HANDLE PortHandle, ULONG Flags, ALPC_HANDLE ContextHandle);
    NTSTATUS NtAlpcRevokeSecurityContext(HANDLE PortHandle, ULONG Flags, ALPC_HANDLE ContextHandle);
    NTSTATUS NtAlpcQueryInformationMessage(HANDLE PortHandle, PPORT_MESSAGE PortMessage, ALPC_MESSAGE_INFORMATION_CLASS MessageInformationClass, PVOID MessageInformation, ULONG Length, PULONG ReturnLength);
    NTSTATUS NtAlpcConnectPort(PHANDLE PortHandle, PCUNICODE_STRING PortName, POBJECT_ATTRIBUTES ObjectAttributes, PALPC_PORT_ATTRIBUTES PortAttributes, ULONG Flags, PSID RequiredServerSid, PPORT_MESSAGE ConnectionMessage, PSIZE_T BufferLength, PALPC_MESSAGE_ATTRIBUTES OutMessageAttributes, PALPC_MESSAGE_ATTRIBUTES InMessageAttributes, PLARGE_INTEGER Timeout);
    NTSTATUS NtAlpcConnectPortEx(PHANDLE PortHandle, POBJECT_ATTRIBUTES ConnectionPortObjectAttributes, POBJECT_ATTRIBUTES ClientPortObjectAttributes, PALPC_PORT_ATTRIBUTES PortAttributes, ULONG Flags, PSECURITY_DESCRIPTOR ServerSecurityRequirements, PPORT_MESSAGE ConnectionMessage, PSIZE_T BufferLength, PALPC_MESSAGE_ATTRIBUTES OutMessageAttributes, PALPC_MESSAGE_ATTRIBUTES InMessageAttributes, PLARGE_INTEGER Timeout);
    NTSTATUS NtAlpcAcceptConnectPort(PHANDLE PortHandle, HANDLE ConnectionPortHandle, ULONG Flags, POBJECT_ATTRIBUTES ObjectAttributes, PALPC_PORT_ATTRIBUTES PortAttributes, PVOID PortContext, PPORT_MESSAGE ConnectionRequest, PALPC_MESSAGE_ATTRIBUTES ConnectionMessageAttributes, BOOLEAN AcceptConnection);
    NTSTATUS NtAlpcSendWaitReceivePort(HANDLE PortHandle, ULONG Flags, PPORT_MESSAGE SendMessageW, PALPC_MESSAGE_ATTRIBUTES SendMessageAttributes, PPORT_MESSAGE ReceiveMessage, PSIZE_T BufferLength, PALPC_MESSAGE_ATTRIBUTES ReceiveMessageAttributes, PLARGE_INTEGER Timeout);
    NTSTATUS NtAlpcCancelMessage(HANDLE PortHandle, ULONG Flags, PALPC_CONTEXT_ATTR MessageContext);
    NTSTATUS NtAlpcImpersonateClientOfPort(HANDLE PortHandle, PPORT_MESSAGE Message, PVOID Flags);
    NTSTATUS NtAlpcImpersonateClientContainerOfPort(HANDLE PortHandle, PPORT_MESSAGE Message, ULONG Flags);
    NTSTATUS NtAlpcOpenSenderProcess(PHANDLE ProcessHandle, HANDLE PortHandle, PPORT_MESSAGE PortMessage, ULONG Flags, ACCESS_MASK DesiredAccess, POBJECT_ATTRIBUTES ObjectAttributes);
    NTSTATUS NtAlpcOpenSenderThread(PHANDLE ThreadHandle, HANDLE PortHandle, PPORT_MESSAGE PortMessage, ULONG Flags, ACCESS_MASK DesiredAccess, POBJECT_ATTRIBUTES ObjectAttributes);
    NTSTATUS NtApphelpCacheControl(AHC_SERVICE_CLASS ServiceClass, PVOID ServiceContext);
    NTSTATUS NtVdmControl(VDMSERVICECLASS Service, PVOID ServiceData);
    NTSTATUS NtOpenSession(PHANDLE SessionHandle, ACCESS_MASK DesiredAccess, POBJECT_ATTRIBUTES ObjectAttributes);
    NTSTATUS NtNotifyChangeSession(HANDLE SessionHandle, ULONG ChangeSequenceNumber, PLARGE_INTEGER ChangeTimeStamp, IO_SESSION_EVENT Event, IO_SESSION_STATE NewState, IO_SESSION_STATE PreviousState, PVOID Payload, ULONG PayloadSize);
    NTSTATUS NtQuerySecurityPolicy(PCUNICODE_STRING Policy, PCUNICODE_STRING KeyName, PCUNICODE_STRING ValueName, SECURE_SETTING_VALUE_TYPE ValueType, PVOID Value, PULONG ValueSize);
    NTSTATUS NtCreateCrossVmEvent(PHANDLE CrossVmEvent, ACCESS_MASK DesiredAccess, POBJECT_ATTRIBUTES ObjectAttributes, ULONG CrossVmEventFlags, LPCGUID VMID, LPCGUID ServiceID);
    NTSTATUS NtCreateCrossVmMutant(PHANDLE EventHandle, ACCESS_MASK DesiredAccess, POBJECT_ATTRIBUTES ObjectAttributes, ULONG CrossVmEventFlags, LPCGUID VMID, LPCGUID ServiceID);
    NTSTATUS NtAcquireCrossVmMutant(HANDLE CrossVmMutant, PLARGE_INTEGER Timeout);
    NTSTATUS NtDirectGraphicsCall(ULONG InputBufferLength, PVOID InputBuffer, ULONG OutputBufferLength, PVOID OutputBuffer, PULONG ReturnLength);
    NTSTATUS NtOpenCpuPartition(PHANDLE CpuPartitionHandle, ACCESS_MASK DesiredAccess, POBJECT_ATTRIBUTES ObjectAttributes);
    NTSTATUS NtCreateCpuPartition(PHANDLE CpuPartitionHandle, ACCESS_MASK DesiredAccess, POBJECT_ATTRIBUTES ObjectAttributes);
    NTSTATUS NtSetInformationCpuPartition(HANDLE CpuPartitionHandle, ULONG CpuPartitionInformationClass, PVOID CpuPartitionInformation, ULONG CpuPartitionInformationLength, PVOID, ULONG, ULONG);
    NTSTATUS NtQueryInformationCpuPartition(HANDLE CpuPartitionHandle, ULONG CpuPartitionInformationClass, PVOID CpuPartitionInformation, ULONG CpuPartitionInformationLength, PULONG ReturnLength);
    NTSTATUS NtAcquireProcessActivityReference(PHANDLE ActivityReferenceHandle, HANDLE ParentProcessHandle, ULONG ProcessActivityType);
    NTSTATUS NtPlugPlayControl(PLUGPLAY_CONTROL_CLASS PnPControlClass, PVOID PnPControlData, ULONG PnPControlDataLength);
    NTSTATUS NtSerializeBoot();
    NTSTATUS NtEnableLastKnownGood();
    NTSTATUS NtDisableLastKnownGood();
    NTSTATUS NtReplacePartitionUnit(PCUNICODE_STRING TargetInstancePath, PCUNICODE_STRING SpareInstancePath, ULONG Flags);
    NTSTATUS NtPowerInformation(ULONG InformationLevel, PVOID InputBuffer, ULONG InputBufferLength, PVOID OutputBuffer, ULONG OutputBufferLength);
    NTSTATUS NtSetThreadExecutionState(EXECUTION_STATE NewFlags, EXECUTION_STATE *PreviousFlags);
    NTSTATUS NtInitiatePowerAction(POWER_ACTION SystemAction, SYSTEM_POWER_STATE LightestSystemState, ULONG Flags, BOOLEAN Asynchronous);
    NTSTATUS NtSetSystemPowerState(POWER_ACTION SystemAction, SYSTEM_POWER_STATE LightestSystemState, ULONG Flags);
    NTSTATUS NtGetDevicePowerState(HANDLE Device, PDEVICE_POWER_STATE State);
    BOOLEAN NtIsSystemResumeAutomatic();
    NTSTATUS NtCreateKey(PHANDLE KeyHandle, ACCESS_MASK DesiredAccess, POBJECT_ATTRIBUTES ObjectAttributes, ULONG TitleIndex, PCUNICODE_STRING Class, ULONG CreateOptions, PULONG Disposition);
    NTSTATUS NtCreateKeyTransacted(PHANDLE KeyHandle, ACCESS_MASK DesiredAccess, POBJECT_ATTRIBUTES ObjectAttributes, ULONG TitleIndex, PCUNICODE_STRING Class, ULONG CreateOptions, HANDLE TransactionHandle, PULONG Disposition);
    NTSTATUS NtOpenKey(PHANDLE KeyHandle, ACCESS_MASK DesiredAccess, POBJECT_ATTRIBUTES ObjectAttributes);
    NTSTATUS NtOpenKeyTransacted(PHANDLE KeyHandle, ACCESS_MASK DesiredAccess, POBJECT_ATTRIBUTES ObjectAttributes, HANDLE TransactionHandle);
    NTSTATUS NtOpenKeyEx(PHANDLE KeyHandle, ACCESS_MASK DesiredAccess, POBJECT_ATTRIBUTES ObjectAttributes, ULONG OpenOptions);
    NTSTATUS NtOpenKeyTransactedEx(PHANDLE KeyHandle, ACCESS_MASK DesiredAccess, POBJECT_ATTRIBUTES ObjectAttributes, ULONG OpenOptions, HANDLE TransactionHandle);
    NTSTATUS NtDeleteKey(HANDLE KeyHandle);
    NTSTATUS NtRenameKey(HANDLE KeyHandle, PCUNICODE_STRING NewName);
    NTSTATUS NtDeleteValueKey(HANDLE KeyHandle, PCUNICODE_STRING ValueName);
    NTSTATUS NtQueryKey(HANDLE KeyHandle, KEY_INFORMATION_CLASS KeyInformationClass, PVOID KeyInformation, ULONG Length, PULONG ResultLength);
    NTSTATUS NtSetInformationKey(HANDLE KeyHandle, KEY_SET_INFORMATION_CLASS KeySetInformationClass, PVOID KeySetInformation, ULONG KeySetInformationLength);
    NTSTATUS NtQueryValueKey(HANDLE KeyHandle, PCUNICODE_STRING ValueName, KEY_VALUE_INFORMATION_CLASS KeyValueInformationClass, PVOID KeyValueInformation, ULONG Length, PULONG ResultLength);
    NTSTATUS NtSetValueKey(HANDLE KeyHandle, PCUNICODE_STRING ValueName, ULONG TitleIndex, ULONG Type, PVOID Data, ULONG DataSize);
    NTSTATUS NtQueryMultipleValueKey(HANDLE KeyHandle, PKEY_VALUE_ENTRY ValueEntries, ULONG EntryCount, PVOID ValueBuffer, PULONG BufferLength, PULONG RequiredBufferLength);
    NTSTATUS NtEnumerateKey(HANDLE KeyHandle, ULONG Index, KEY_INFORMATION_CLASS KeyInformationClass, PVOID KeyInformation, ULONG Length, PULONG ResultLength);
    NTSTATUS NtEnumerateValueKey(HANDLE KeyHandle, ULONG Index, KEY_VALUE_INFORMATION_CLASS KeyValueInformationClass, PVOID KeyValueInformation, ULONG Length, PULONG ResultLength);
    NTSTATUS NtFlushKey(HANDLE KeyHandle);
    NTSTATUS NtCompactKeys(ULONG Count, HANDLE KeyArray[]);
    NTSTATUS NtCompressKey(HANDLE KeyHandle);
    NTSTATUS NtLoadKey(POBJECT_ATTRIBUTES TargetKey, POBJECT_ATTRIBUTES SourceFile);
    NTSTATUS NtLoadKey2(POBJECT_ATTRIBUTES TargetKey, POBJECT_ATTRIBUTES SourceFile, ULONG Flags);
    NTSTATUS NtLoadKeyEx(POBJECT_ATTRIBUTES TargetKey, POBJECT_ATTRIBUTES SourceFile, ULONG Flags, HANDLE TrustClassKey, HANDLE Event, ACCESS_MASK DesiredAccess, PHANDLE RootHandle, PVOID Reserved);
    NTSTATUS NtLoadKey3(POBJECT_ATTRIBUTES TargetKey, POBJECT_ATTRIBUTES SourceFile, ULONG Flags, PCM_EXTENDED_PARAMETER ExtendedParameters, ULONG ExtendedParameterCount, ACCESS_MASK DesiredAccess, PHANDLE RootHandle, PVOID Reserved);
    NTSTATUS NtReplaceKey(POBJECT_ATTRIBUTES NewFile, HANDLE TargetHandle, POBJECT_ATTRIBUTES OldFile);
    NTSTATUS NtSaveKey(HANDLE KeyHandle, HANDLE FileHandle);
    NTSTATUS NtSaveKeyEx(HANDLE KeyHandle, HANDLE FileHandle, ULONG Format);
    NTSTATUS NtSaveMergedKeys(HANDLE HighPrecedenceKeyHandle, HANDLE LowPrecedenceKeyHandle, HANDLE FileHandle);
    NTSTATUS NtRestoreKey(HANDLE KeyHandle, HANDLE FileHandle, ULONG Flags);
    NTSTATUS NtUnloadKey(POBJECT_ATTRIBUTES TargetKey);
    NTSTATUS NtUnloadKey2(POBJECT_ATTRIBUTES TargetKey, ULONG Flags);
    NTSTATUS NtUnloadKeyEx(POBJECT_ATTRIBUTES TargetKey, HANDLE Event);
    NTSTATUS NtNotifyChangeKey(HANDLE KeyHandle, HANDLE Event, PIO_APC_ROUTINE ApcRoutine, PVOID ApcContext, PIO_STATUS_BLOCK IoStatusBlock, ULONG CompletionFilter, BOOLEAN WatchTree, PVOID Buffer, ULONG BufferSize, BOOLEAN Asynchronous);
    NTSTATUS NtNotifyChangeMultipleKeys(HANDLE MasterKeyHandle, ULONG Count, OBJECT_ATTRIBUTES SubordinateObjects[], HANDLE Event, PIO_APC_ROUTINE ApcRoutine, PVOID ApcContext, PIO_STATUS_BLOCK IoStatusBlock, ULONG CompletionFilter, BOOLEAN WatchTree, PVOID Buffer, ULONG BufferSize, BOOLEAN Asynchronous);
    NTSTATUS NtQueryOpenSubKeys(POBJECT_ATTRIBUTES TargetKey, PULONG HandleCount);
    NTSTATUS NtQueryOpenSubKeysEx(POBJECT_ATTRIBUTES TargetKey, ULONG BufferLength, PVOID Buffer, PULONG RequiredSize);
    NTSTATUS NtInitializeRegistry(USHORT BootCondition);
    NTSTATUS NtLockRegistryKey(HANDLE KeyHandle);
    NTSTATUS NtLockProductActivationKeys(ULONG *pPrivateVer, ULONG *pSafeMode);
    NTSTATUS NtFreezeRegistry(ULONG TimeOutInSeconds);
    NTSTATUS NtThawRegistry();
    NTSTATUS NtCreateRegistryTransaction(HANDLE *RegistryTransactionHandle, ACCESS_MASK DesiredAccess, POBJECT_ATTRIBUTES ObjAttributes, ULONG CreateOptions);
    NTSTATUS NtOpenRegistryTransaction(HANDLE *RegistryTransactionHandle, ACCESS_MASK DesiredAccess, POBJECT_ATTRIBUTES ObjAttributes);
    NTSTATUS NtCommitRegistryTransaction(HANDLE RegistryTransactionHandle, ULONG Flags);
    NTSTATUS NtRollbackRegistryTransaction(HANDLE RegistryTransactionHandle, ULONG Flags);
    NTSTATUS NtWow64GetNativeSystemInformation(SYSTEM_INFORMATION_CLASS SystemInformationClass, PVOID NativeSystemInformation, ULONG InformationLength, PULONG ReturnLength);
    NTSTATUS NtCreateToken(PHANDLE TokenHandle, ACCESS_MASK DesiredAccess, POBJECT_ATTRIBUTES ObjectAttributes, TOKEN_TYPE Type, PLUID AuthenticationId, PLARGE_INTEGER ExpirationTime, PTOKEN_USER User, PTOKEN_GROUPS Groups, PTOKEN_PRIVILEGES Privileges, PTOKEN_OWNER Owner, PTOKEN_PRIMARY_GROUP PrimaryGroup, PTOKEN_DEFAULT_DACL DefaultDacl, PTOKEN_SOURCE Source);
    NTSTATUS NtCreateLowBoxToken(PHANDLE TokenHandle, HANDLE ExistingTokenHandle, ACCESS_MASK DesiredAccess, POBJECT_ATTRIBUTES ObjectAttributes, PSID PackageSid, ULONG CapabilityCount, PSID_AND_ATTRIBUTES Capabilities, ULONG HandleCount, HANDLE *Handles);
    NTSTATUS NtCreateTokenEx(PHANDLE TokenHandle, ACCESS_MASK DesiredAccess, POBJECT_ATTRIBUTES ObjectAttributes, TOKEN_TYPE Type, PLUID AuthenticationId, PLARGE_INTEGER ExpirationTime, PTOKEN_USER User, PTOKEN_GROUPS Groups, PTOKEN_PRIVILEGES Privileges, PTOKEN_SECURITY_ATTRIBUTES_INFORMATION UserAttributes, PTOKEN_SECURITY_ATTRIBUTES_INFORMATION DeviceAttributes, PTOKEN_GROUPS DeviceGroups, PTOKEN_MANDATORY_POLICY MandatoryPolicy, PTOKEN_OWNER Owner, PTOKEN_PRIMARY_GROUP PrimaryGroup, PTOKEN_DEFAULT_DACL DefaultDacl, PTOKEN_SOURCE Source);
    NTSTATUS NtOpenProcessToken(HANDLE ProcessHandle, ACCESS_MASK DesiredAccess, PHANDLE TokenHandle);
    NTSTATUS NtOpenProcessTokenEx(HANDLE ProcessHandle, ACCESS_MASK DesiredAccess, ULONG HandleAttributes, PHANDLE TokenHandle);
    NTSTATUS NtOpenThreadToken(HANDLE ThreadHandle, ACCESS_MASK DesiredAccess, BOOLEAN OpenAsSelf, PHANDLE TokenHandle);
    NTSTATUS NtOpenThreadTokenEx(HANDLE ThreadHandle, ACCESS_MASK DesiredAccess, BOOLEAN OpenAsSelf, ULONG HandleAttributes, PHANDLE TokenHandle);
    NTSTATUS NtDuplicateToken(HANDLE ExistingTokenHandle, ACCESS_MASK DesiredAccess, POBJECT_ATTRIBUTES ObjectAttributes, BOOLEAN EffectiveOnly, TOKEN_TYPE Type, PHANDLE NewTokenHandle);
    NTSTATUS NtQueryInformationToken(HANDLE TokenHandle, TOKEN_INFORMATION_CLASS TokenInformationClass, PVOID TokenInformation, ULONG TokenInformationLength, PULONG ReturnLength);
    NTSTATUS NtSetInformationToken(HANDLE TokenHandle, TOKEN_INFORMATION_CLASS TokenInformationClass, PVOID TokenInformation, ULONG TokenInformationLength);
    NTSTATUS NtAdjustPrivilegesToken(HANDLE TokenHandle, BOOLEAN DisableAllPrivileges, PTOKEN_PRIVILEGES NewState, ULONG BufferLength, PTOKEN_PRIVILEGES PreviousState, PULONG ReturnLength);
    NTSTATUS NtAdjustGroupsToken(HANDLE TokenHandle, BOOLEAN ResetToDefault, PTOKEN_GROUPS NewState, ULONG BufferLength, PTOKEN_GROUPS PreviousState, PULONG ReturnLength);
    NTSTATUS NtAdjustTokenClaimsAndDeviceGroups(HANDLE TokenHandle, BOOLEAN UserResetToDefault, BOOLEAN DeviceResetToDefault, BOOLEAN DeviceGroupsResetToDefault, PTOKEN_SECURITY_ATTRIBUTES_INFORMATION NewUserState, PTOKEN_SECURITY_ATTRIBUTES_INFORMATION NewDeviceState, PTOKEN_GROUPS NewDeviceGroupsState, ULONG UserBufferLength, PTOKEN_SECURITY_ATTRIBUTES_INFORMATION PreviousUserState, ULONG DeviceBufferLength, PTOKEN_SECURITY_ATTRIBUTES_INFORMATION PreviousDeviceState, ULONG DeviceGroupsBufferLength, PTOKEN_GROUPS PreviousDeviceGroups, PULONG UserReturnLength, PULONG DeviceReturnLength, PULONG DeviceGroupsReturnBufferLength);
    NTSTATUS NtFilterToken(HANDLE ExistingTokenHandle, ULONG Flags, PTOKEN_GROUPS SidsToDisable, PTOKEN_PRIVILEGES PrivilegesToDelete, PTOKEN_GROUPS RestrictedSids, PHANDLE NewTokenHandle);
    NTSTATUS NtFilterTokenEx(HANDLE ExistingTokenHandle, ULONG Flags, PTOKEN_GROUPS SidsToDisable, PTOKEN_PRIVILEGES PrivilegesToDelete, PTOKEN_GROUPS RestrictedSids, ULONG DisableUserClaimsCount, PCUNICODE_STRING UserClaimsToDisable, ULONG DisableDeviceClaimsCount, PCUNICODE_STRING DeviceClaimsToDisable, PTOKEN_GROUPS DeviceGroupsToDisable, PTOKEN_SECURITY_ATTRIBUTES_INFORMATION RestrictedUserAttributes, PTOKEN_SECURITY_ATTRIBUTES_INFORMATION RestrictedDeviceAttributes, PTOKEN_GROUPS RestrictedDeviceGroups, PHANDLE NewTokenHandle);
    NTSTATUS NtCompareTokens(HANDLE FirstTokenHandle, HANDLE SecondTokenHandle, PBOOLEAN Equal);
    NTSTATUS NtPrivilegeCheck(HANDLE ClientToken, PPRIVILEGE_SET RequiredPrivileges, PBOOLEAN Result);
    NTSTATUS NtImpersonateAnonymousToken(HANDLE ThreadHandle);
    NTSTATUS NtQuerySecurityAttributesToken(HANDLE TokenHandle, PCUNICODE_STRING Attributes, ULONG NumberOfAttributes, PVOID Buffer, ULONG Length, PULONG ReturnLength);
    NTSTATUS NtAccessCheck(PSECURITY_DESCRIPTOR SecurityDescriptor, HANDLE ClientToken, ACCESS_MASK DesiredAccess, PGENERIC_MAPPING GenericMapping, PPRIVILEGE_SET PrivilegeSet, PULONG PrivilegeSetLength, PACCESS_MASK GrantedAccess, PNTSTATUS AccessStatus);
    NTSTATUS NtAccessCheckByType(PSECURITY_DESCRIPTOR SecurityDescriptor, PSID PrincipalSelfSid, HANDLE ClientToken, ACCESS_MASK DesiredAccess, POBJECT_TYPE_LIST ObjectTypeList, ULONG ObjectTypeListLength, PGENERIC_MAPPING GenericMapping, PPRIVILEGE_SET PrivilegeSet, PULONG PrivilegeSetLength, PACCESS_MASK GrantedAccess, PNTSTATUS AccessStatus);
    NTSTATUS NtAccessCheckByTypeResultList(PSECURITY_DESCRIPTOR SecurityDescriptor, PSID PrincipalSelfSid, HANDLE ClientToken, ACCESS_MASK DesiredAccess, POBJECT_TYPE_LIST ObjectTypeList, ULONG ObjectTypeListLength, PGENERIC_MAPPING GenericMapping, PPRIVILEGE_SET PrivilegeSet, PULONG PrivilegeSetLength, PACCESS_MASK GrantedAccess, PNTSTATUS AccessStatus);
    NTSTATUS NtGetCachedSigningLevel(HANDLE File, PULONG Flags, PSE_SIGNING_LEVEL SigningLevel, PUCHAR Thumbprint, PULONG ThumbprintSize, PULONG ThumbprintAlgorithm);
    NTSTATUS NtSetCachedSigningLevel(ULONG Flags, SE_SIGNING_LEVEL InputSigningLevel, PHANDLE SourceFiles, ULONG SourceFileCount, HANDLE TargetFile);
    NTSTATUS NtSetCachedSigningLevel2(ULONG Flags, SE_SIGNING_LEVEL InputSigningLevel, PHANDLE SourceFiles, ULONG SourceFileCount, HANDLE TargetFile, SE_SET_FILE_CACHE_INFORMATION *CacheInformation);
    NTSTATUS NtCompareSigningLevels(SE_SIGNING_LEVEL FirstSigningLevel, SE_SIGNING_LEVEL SecondSigningLevel);
    NTSTATUS NtAccessCheckAndAuditAlarm(PCUNICODE_STRING SubsystemName, PVOID HandleId, PCUNICODE_STRING ObjectTypeName, PCUNICODE_STRING ObjectName, PSECURITY_DESCRIPTOR SecurityDescriptor, ACCESS_MASK DesiredAccess, PGENERIC_MAPPING GenericMapping, BOOLEAN ObjectCreation, PACCESS_MASK GrantedAccess, PNTSTATUS AccessStatus, PBOOLEAN GenerateOnClose);
    NTSTATUS NtAccessCheckByTypeAndAuditAlarm(PCUNICODE_STRING SubsystemName, PVOID HandleId, PCUNICODE_STRING ObjectTypeName, PCUNICODE_STRING ObjectName, PSECURITY_DESCRIPTOR SecurityDescriptor, PSID PrincipalSelfSid, ACCESS_MASK DesiredAccess, AUDIT_EVENT_TYPE AuditType, ULONG Flags, POBJECT_TYPE_LIST ObjectTypeList, ULONG ObjectTypeListLength, PGENERIC_MAPPING GenericMapping, BOOLEAN ObjectCreation, PACCESS_MASK GrantedAccess, PNTSTATUS AccessStatus, PBOOLEAN GenerateOnClose);
    NTSTATUS NtAccessCheckByTypeResultListAndAuditAlarm(PCUNICODE_STRING SubsystemName, PVOID HandleId, PCUNICODE_STRING ObjectTypeName, PCUNICODE_STRING ObjectName, PSECURITY_DESCRIPTOR SecurityDescriptor, PSID PrincipalSelfSid, ACCESS_MASK DesiredAccess, AUDIT_EVENT_TYPE AuditType, ULONG Flags, POBJECT_TYPE_LIST ObjectTypeList, ULONG ObjectTypeListLength, PGENERIC_MAPPING GenericMapping, BOOLEAN ObjectCreation, PACCESS_MASK GrantedAccess, PNTSTATUS AccessStatus, PBOOLEAN GenerateOnClose);
    NTSTATUS NtAccessCheckByTypeResultListAndAuditAlarmByHandle(PCUNICODE_STRING SubsystemName, PVOID HandleId, HANDLE ClientToken, PCUNICODE_STRING ObjectTypeName, PCUNICODE_STRING ObjectName, PSECURITY_DESCRIPTOR SecurityDescriptor, PSID PrincipalSelfSid, ACCESS_MASK DesiredAccess, AUDIT_EVENT_TYPE AuditType, ULONG Flags, POBJECT_TYPE_LIST ObjectTypeList, ULONG ObjectTypeListLength, PGENERIC_MAPPING GenericMapping, BOOLEAN ObjectCreation, PACCESS_MASK GrantedAccess, PNTSTATUS AccessStatus, PBOOLEAN GenerateOnClose);
    NTSTATUS NtOpenObjectAuditAlarm(PCUNICODE_STRING SubsystemName, PVOID HandleId, PCUNICODE_STRING ObjectTypeName, PCUNICODE_STRING ObjectName, PSECURITY_DESCRIPTOR SecurityDescriptor, HANDLE ClientToken, ACCESS_MASK DesiredAccess, ACCESS_MASK GrantedAccess, PPRIVILEGE_SET Privileges, BOOLEAN ObjectCreation, BOOLEAN AccessGranted, PBOOLEAN GenerateOnClose);
    NTSTATUS NtPrivilegeObjectAuditAlarm(PCUNICODE_STRING SubsystemName, PVOID HandleId, HANDLE ClientToken, ACCESS_MASK DesiredAccess, PPRIVILEGE_SET Privileges, BOOLEAN AccessGranted);
    NTSTATUS NtCloseObjectAuditAlarm(PCUNICODE_STRING SubsystemName, PVOID HandleId, BOOLEAN GenerateOnClose);
    NTSTATUS NtDeleteObjectAuditAlarm(PCUNICODE_STRING SubsystemName, PVOID HandleId, BOOLEAN GenerateOnClose);
    NTSTATUS NtPrivilegedServiceAuditAlarm(PCUNICODE_STRING SubsystemName, PCUNICODE_STRING ServiceName, HANDLE ClientToken, PPRIVILEGE_SET Privileges, BOOLEAN AccessGranted);
    NTSTATUS NtCreateTransactionManager(PHANDLE TmHandle, ACCESS_MASK DesiredAccess, POBJECT_ATTRIBUTES ObjectAttributes, PCUNICODE_STRING LogFileName, ULONG CreateOptions, ULONG CommitStrength);
    NTSTATUS NtOpenTransactionManager(PHANDLE TmHandle, ACCESS_MASK DesiredAccess, POBJECT_ATTRIBUTES ObjectAttributes, PCUNICODE_STRING LogFileName, LPGUID TmIdentity, ULONG OpenOptions);
    NTSTATUS NtRenameTransactionManager(PCUNICODE_STRING LogFileName, LPGUID ExistingTransactionManagerGuid);
    NTSTATUS NtRollforwardTransactionManager(HANDLE TransactionManagerHandle, PLARGE_INTEGER TmVirtualClock);
    NTSTATUS NtRecoverTransactionManager(HANDLE TransactionManagerHandle);
    NTSTATUS NtQueryInformationTransactionManager(HANDLE TransactionManagerHandle, TRANSACTIONMANAGER_INFORMATION_CLASS TransactionManagerInformationClass, PVOID TransactionManagerInformation, ULONG TransactionManagerInformationLength, PULONG ReturnLength);
    NTSTATUS NtSetInformationTransactionManager(HANDLE TmHandle, TRANSACTIONMANAGER_INFORMATION_CLASS TransactionManagerInformationClass, PVOID TransactionManagerInformation, ULONG TransactionManagerInformationLength);
    NTSTATUS NtEnumerateTransactionObject(HANDLE RootObjectHandle, KTMOBJECT_TYPE QueryType, PKTMOBJECT_CURSOR ObjectCursor, ULONG ObjectCursorLength, PULONG ReturnLength);
    NTSTATUS NtCreateTransaction(PHANDLE TransactionHandle, ACCESS_MASK DesiredAccess, POBJECT_ATTRIBUTES ObjectAttributes, LPGUID Uow, HANDLE TmHandle, ULONG CreateOptions, ULONG IsolationLevel, ULONG IsolationFlags, PLARGE_INTEGER Timeout, PCUNICODE_STRING Description);
    NTSTATUS NtOpenTransaction(PHANDLE TransactionHandle, ACCESS_MASK DesiredAccess, POBJECT_ATTRIBUTES ObjectAttributes, LPGUID Uow, HANDLE TmHandle);
    NTSTATUS NtQueryInformationTransaction(HANDLE TransactionHandle, TRANSACTION_INFORMATION_CLASS TransactionInformationClass, PVOID TransactionInformation, ULONG TransactionInformationLength, PULONG ReturnLength);
    NTSTATUS NtSetInformationTransaction(HANDLE TransactionHandle, TRANSACTION_INFORMATION_CLASS TransactionInformationClass, PVOID TransactionInformation, ULONG TransactionInformationLength);
    NTSTATUS NtCommitTransaction(HANDLE TransactionHandle, BOOLEAN Wait);
    NTSTATUS NtRollbackTransaction(HANDLE TransactionHandle, BOOLEAN Wait);
    NTSTATUS NtCreateEnlistment(PHANDLE EnlistmentHandle, ACCESS_MASK DesiredAccess, HANDLE ResourceManagerHandle, HANDLE TransactionHandle, POBJECT_ATTRIBUTES ObjectAttributes, ULONG CreateOptions, NOTIFICATION_MASK NotificationMask, PVOID EnlistmentKey);
    NTSTATUS NtOpenEnlistment(PHANDLE EnlistmentHandle, ACCESS_MASK DesiredAccess, HANDLE ResourceManagerHandle, LPGUID EnlistmentGuid, POBJECT_ATTRIBUTES ObjectAttributes);
    NTSTATUS NtQueryInformationEnlistment(HANDLE EnlistmentHandle, ENLISTMENT_INFORMATION_CLASS EnlistmentInformationClass, PVOID EnlistmentInformation, ULONG EnlistmentInformationLength, PULONG ReturnLength);
    NTSTATUS NtSetInformationEnlistment(HANDLE EnlistmentHandle, ENLISTMENT_INFORMATION_CLASS EnlistmentInformationClass, PVOID EnlistmentInformation, ULONG EnlistmentInformationLength);
    NTSTATUS NtRecoverEnlistment(HANDLE EnlistmentHandle, PVOID EnlistmentKey);
    NTSTATUS NtPrePrepareEnlistment(HANDLE EnlistmentHandle, PLARGE_INTEGER TmVirtualClock);
    NTSTATUS NtPrepareEnlistment(HANDLE EnlistmentHandle, PLARGE_INTEGER TmVirtualClock);
    NTSTATUS NtCommitEnlistment(HANDLE EnlistmentHandle, PLARGE_INTEGER TmVirtualClock);
    NTSTATUS NtRollbackEnlistment(HANDLE EnlistmentHandle, PLARGE_INTEGER TmVirtualClock);
    NTSTATUS NtPrePrepareComplete(HANDLE EnlistmentHandle, PLARGE_INTEGER TmVirtualClock);
    NTSTATUS NtPrepareComplete(HANDLE EnlistmentHandle, PLARGE_INTEGER TmVirtualClock);
    NTSTATUS NtCommitComplete(HANDLE EnlistmentHandle, PLARGE_INTEGER TmVirtualClock);
    NTSTATUS NtReadOnlyEnlistment(HANDLE EnlistmentHandle, PLARGE_INTEGER TmVirtualClock);
    NTSTATUS NtRollbackComplete(HANDLE EnlistmentHandle, PLARGE_INTEGER TmVirtualClock);
    NTSTATUS NtSinglePhaseReject(HANDLE EnlistmentHandle, PLARGE_INTEGER TmVirtualClock);
    NTSTATUS NtCreateResourceManager(PHANDLE ResourceManagerHandle, ACCESS_MASK DesiredAccess, HANDLE TmHandle, LPGUID RmGuid, POBJECT_ATTRIBUTES ObjectAttributes, ULONG CreateOptions, PCUNICODE_STRING Description);
    NTSTATUS NtOpenResourceManager(PHANDLE ResourceManagerHandle, ACCESS_MASK DesiredAccess, HANDLE TmHandle, LPGUID ResourceManagerGuid, POBJECT_ATTRIBUTES ObjectAttributes);
    NTSTATUS NtRecoverResourceManager(HANDLE ResourceManagerHandle);
    NTSTATUS NtGetNotificationResourceManager(HANDLE ResourceManagerHandle, PTRANSACTION_NOTIFICATION TransactionNotification, ULONG NotificationLength, PLARGE_INTEGER Timeout, PULONG ReturnLength, ULONG Asynchronous, ULONG_PTR AsynchronousContext);
    NTSTATUS NtQueryInformationResourceManager(HANDLE ResourceManagerHandle, RESOURCEMANAGER_INFORMATION_CLASS ResourceManagerInformationClass, PVOID ResourceManagerInformation, ULONG ResourceManagerInformationLength, PULONG ReturnLength);
    NTSTATUS NtSetInformationResourceManager(HANDLE ResourceManagerHandle, RESOURCEMANAGER_INFORMATION_CLASS ResourceManagerInformationClass, PVOID ResourceManagerInformation, ULONG ResourceManagerInformationLength);
    NTSTATUS NtRegisterProtocolAddressInformation(HANDLE ResourceManager, PCRM_PROTOCOL_ID ProtocolId, ULONG ProtocolInformationSize, PVOID ProtocolInformation, ULONG CreateOptions);
    NTSTATUS NtPropagationComplete(HANDLE ResourceManagerHandle, ULONG RequestCookie, ULONG BufferLength, PVOID Buffer);
    NTSTATUS NtPropagationFailed(HANDLE ResourceManagerHandle, ULONG RequestCookie, NTSTATUS PropStatus);
    NTSTATUS NtFreezeTransactions(PLARGE_INTEGER FreezeTimeout, PLARGE_INTEGER ThawTimeout);
    NTSTATUS NtThawTransactions();
    NTSTATUS NtUserAttachThreadInput(ULONG IdAttach, ULONG IdAttachTo, BOOL Attach);
    HDC NtUserBeginPaint(HWND WindowHandle, LPPAINTSTRUCT lpPaint);
    BOOL NtUserBlockInput(BOOL BlockInput);
    HWND NtUserFindWindowEx(HWND hwndParent, HWND hwndChild, PCUNICODE_STRING ClassName, PCUNICODE_STRING WindowName, ULONG Type);
    NTSTATUS NtUserBuildHwndList(HANDLE DesktopHandle, HWND ParentWindowHandle, BOOL IncludeChildren, BOOL ExcludeImmersive, ULONG ThreadId, ULONG HwndListInformationLength, PVOID HwndListInformation, PULONG ReturnLength);
    NTSTATUS NtUserBuildNameList(HWINSTA WindowStationHandle, ULONG NameListInformationLength, PVOID NameListInformation, PULONG ReturnLength);
    NTSTATUS NtUserBuildPropList(HWINSTA WindowStationHandle, ULONG PropListInformationLength, PVOID PropListInformation, PULONG ReturnLength);
    BOOL NtUserCanCurrentThreadChangeForeground();
    BOOL NtUserCalculatePopupWindowPosition(POINT *anchorPoint, SIZE *windowSize, ULONG flags, RECT *excludeRect, RECT *popupWindowPosition);
    NTSTATUS NtUserCheckAccessForIntegrityLevel(ULONG ProcessIdFirst, ULONG ProcessIdSecond, PBOOLEAN GrantedAccess);
    NTSTATUS NtUserCheckProcessForClipboardAccess(ULONG ProcessId, PULONG GrantedAccess);
    BOOL NtUserCloseWindowStation(HWINSTA WindowStationHandle);
    BOOL NtUserDisableProcessWindowFiltering();
    HANDLE NtUserGetProp(HWND WindowHandle, PCWSTR String);
    HANDLE NtUserGetProp2(HWND WindowHandle, PCUNICODE_STRING String);
    NTSTATUS NtUserCreateWindowStation(POBJECT_ATTRIBUTES ObjectAttributes, ACCESS_MASK DesiredAccess, HANDLE KeyboardLayoutHandle, PVOID KeyboardLayoutOffset, PVOID NlsTableOffset, PVOID KeyboardDescriptor, PCUNICODE_STRING LanguageIdString, ULONG KeyboardLocale);
    NTSTATUS NtUserConsoleControl(CONSOLECONTROL Command, PVOID ConsoleInformation, ULONG ConsoleInformationLength);
    ULONG NtUserGetClassName(HWND WindowHandle, BOOL RealClassName, PUNICODE_STRING ClassName);
    HWND NtUserGetForegroundWindow();
    BOOL NtUserGetIconInfo(HICON IconOrCursorHandle, PICONINFO Iconinfo, PUNICODE_STRING Name, PUNICODE_STRING ResourceId, PULONG ColorBits, LOGICAL IsCursorHandle);
    BOOL NtUserGetIconSize(HGDIOBJ IconOrCursorHandle, LOGICAL IsCursorHandle, PULONG XX, PULONG YY);
    HWINSTA NtUserGetProcessWindowStation();
    NTSTATUS NtUserGetProcessUIContextInformation(HANDLE ProcessHandle, PPROCESS_UICONTEXT_INFORMATION UIContext);
    ULONG_PTR NtUserGetThreadState(ULONG UserThreadState);
    HWND NtUserGhostWindowFromHungWindow(HWND WindowHandle);
    HWND NtUserHungWindowFromGhostWindow(HWND WindowHandle);
    ULONG NtUserInternalGetWindowText(HWND WindowHandle, LPWSTR pString, ULONG cchMaxCount);
    HICON NtUserInternalGetWindowIcon(HWND WindowHandle, ULONG IconType);
    HANDLE NtUserOpenDesktop(PCOBJECT_ATTRIBUTES ObjectAttributes, ULONG Flags, ACCESS_MASK DesiredAccess);
    HWINSTA NtUserOpenWindowStation(POBJECT_ATTRIBUTES ObjectAttributes, ACCESS_MASK DesiredAccess);
    ULONG_PTR NtUserQueryWindow(HWND WindowHandle, WINDOWINFOCLASS WindowInfo);
    HWND NtUserSetActiveWindow(HWND WindowHandle);
    NTSTATUS NtUserSetChildWindowNoActivate(HWND WindowHandle);
    HWND NtUserSetFocus(HWND WindowHandle);
    NTSTATUS NtUserSetInformationThread(HANDLE ThreadHandle, USERTHREADINFOCLASS ThreadInformationClass, PVOID ThreadInformation, ULONG ThreadInformationLength);
    BOOL NtUserSetProcessWindowStation(HWINSTA WindowStationHandle);
    NTSTATUS NtUserSetProcessWin32Capabilities(USER_PROCESS_CAP_ENTRY *Capabilities, ULONG Count);
    NTSTATUS NtUserSetProcessRestrictionExemption(BOOL EnableExemption);
    NTSTATUS NtUserSetProcessUIAccessZorder();
    BOOL NtUserSetWindowPlacement(HWND WindowHandle, WINDOWPLACEMENT *lpwndpl);
    BOOL NtUserSetWindowStationUser(HWINSTA WindowStationHandle, PLUID UserLogonId, PSID UserSid, ULONG UserSidLength);
    NTSTATUS NtUserTestForInteractiveUser(PLUID AuthenticationId);
    BOOL NtUserSwitchDesktop(HDESK DesktopHandle, ULONG Flags, ULONG FadeTime);
    BOOL NtUserSetThreadDesktop(HDESK DesktopHandle);
    HWND NtUserChildWindowFromPointEx(HWND WindowHandle, POINT pt, ULONG flags);
    BOOL NtUserClipCursor(RECT *lpRect);
    BOOL NtUserCloseDesktop(HDESK DesktopHandle);
    LONG NtUserCopyAcceleratorTable(HACCEL hAccelSrc, LPACCEL lpAccelDst, LONG cAccelEntries);
    HACCEL NtUserCreateAcceleratorTable(LPACCEL paccel, LONG cAccel);
    BOOL NtUserDeleteMenu(HMENU MenuHandle, ULONG Position, ULONG Flags);
    BOOL NtUserDestroyMenu(HMENU MenuHandle);
    BOOL NtUserDestroyWindow(HWND WindowHandle);
    BOOL NtUserDragDetect(HWND WindowHandle, POINT pt);
    ULONG NtUserDragObject(HWND WindowHandleParent, HWND WindowHandleFrom, ULONG fmt, ULONG_PTR data, HCURSOR hcur);
    BOOL NtUserDrawAnimatedRects(HWND WindowHandle, int idAni, RECT *lprcFrom, RECT *lprcTo);
    BOOL NtUserEndMenu();
    BOOL NtUserEndPaint(HWND WindowHandle, PAINTSTRUCT *lpPaint);
    BOOL NtUserEnumDisplayMonitors(HDC hdc, LPCRECT lprcClip, MONITORENUMPROC lpfnEnum, LPARAM dwData);
    HRGN NtUserExcludeUpdateRgn(HDC hDC, HWND WindowHandle);
    BOOL NtUserFlashWindowEx(PFLASHWINFO pfwi);
    HWND NtUserGetAncestor(HWND WindowHandle, ULONG gaFlags);
    ULONG NtUserGetCaretBlinkTime();
    BOOL NtUserGetCaretPos(LPPOINT lpPoint);
    BOOL NtUserGetClipCursor(LPRECT lpRect);
    BOOL NtUserGetComboBoxInfo(HWND WindowHandleCombo, PCOMBOBOXINFO pcbi);
    BOOL NtUserGetCurrentInputMessageSource(INPUT_MESSAGE_SOURCE *InputMessageSource);
    HCURSOR NtUserGetCursor();
    BOOL NtUserGetCursorInfo(PCURSORINFO pci);
    HDC NtUserGetDCEx(HWND WindowHandle, HRGN hrgnClip, ULONG flags);
    BOOL NtUserGetDisplayAutoRotationPreferences(ORIENTATION_PREFERENCE *pOrientation);
    ULONG NtUserGetDoubleClickTime();
    BOOL NtUserGetGUIThreadInfo(ULONG idThread, PGUITHREADINFO pgui);
    ULONG NtUserGetGuiResources(HANDLE ProcessHandle, ULONG Flags);
    BOOL NtUserGetLayeredWindowAttributes(HWND WindowHandle, COLORREF *Key, PBYTE Alpha, PULONG Flags);
    ULONG NtUserGetListBoxInfo(HWND WindowHandle);
    BOOL NtUserGetMenuBarInfo(HWND WindowHandle, LONG idObject, LONG idItem, PMENUBARINFO pmbi);
    BOOL NtUserGetMenuItemRect(HWND WindowHandle, HMENU MenuHandle, ULONG MenuIndex, PRECT MenuRect);
    LONG NtUserGetMouseMovePointsEx(ULONG MouseMovePointsSize, LPMOUSEMOVEPOINT InputBuffer, LPMOUSEMOVEPOINT OutputBuffer, LONG OutputBufferCount, ULONG Resolution);
    ULONG NtUserGetRawInputData(HRAWINPUT RawInputData, ULONG RawInputCommand, PVOID RawInputBuffer, PULONG RawInputBufferSize, ULONG RawInputHeaderSize);
    ULONG NtUserGetRawInputDeviceList(PRAWINPUTDEVICELIST RawInputDeviceList, PULONG RawInputDeviceCount, ULONG RawInputDeviceSize);
    ULONG NtUserGetRegisteredRawInputDevices(PRAWINPUTDEVICE RawInputDevices, PULONG RawInputDeviceCount, ULONG RawInputDeviceSize);
    HMENU NtUserGetSystemMenu(HWND WindowHandle, BOOL Revert);
    HDESK NtUserGetThreadDesktop(ULONG ThreadId);
    BOOL NtUserGetTitleBarInfo(HWND WindowHandle, PTITLEBARINFO pti);
    BOOL NtUserGetObjectInformation(HANDLE ObjectHandle, LONG Index, PVOID vInfo, ULONG Length, PULONG LengthNeeded);
    HDC NtUserGetWindowDC(HWND WindowHandle);
    BOOL NtUserGetWindowPlacement(HWND WindowHandle, PWINDOWPLACEMENT WindowPlacement);
    HANDLE NtUserGetWindowProcessHandle(HWND WindowHandle, ACCESS_MASK DesiredAccess);
    BOOL NtUserHiliteMenuItem(HWND WindowHandle, HMENU MenuHandle, ULONG IDHiliteItem, ULONG Hilite);
    BOOL NtUserInvalidateRect(HWND WindowHandle, RECT *Rect, BOOL Erase);
    BOOL NtUserInvalidateRgn(HWND WindowHandle, HRGN RgnHandle, BOOL Erase);
    BOOL NtUserIsTouchWindow(HWND WindowHandle, PULONG Flags);
    BOOL NtUserKillTimer(HWND WindowHandle, ULONG_PTR IDEvent);
    BOOL NtUserLockWorkStation();
    BOOL NtUserLogicalToPhysicalPoint(HWND WindowHandle, LPPOINT lpPoint);
    LONG NtUserMenuItemFromPoint(HWND WindowHandle, HMENU MenuHandle, POINT ptScreen);
    BOOL NtUserMoveWindow(HWND WindowHandle, LONG X, LONG Y, LONG Width, LONG Height, BOOL Repaint);
    HDESK NtUserOpenInputDesktop(ULONG Flags, BOOL Inherit, ACCESS_MASK DesiredAccess);
    BOOL NtUserPhysicalToLogicalPoint(HWND WindowHandle, LPPOINT Point);
    BOOL NtUserPrintWindow(HWND WindowHandle, HDC Hdc, ULONG Flags);
    NTSTATUS NtUserQueryInformationThread(HANDLE ThreadHandle, USERTHREADINFOCLASS ThreadInformationClass, PVOID ThreadInformation, PULONG ReturnLength);
    BOOL NtUserQuerySendMessage(PMSG Message);
    NTSTATUS NtUserRaiseLowerShellWindow(HWND WindowHandle, BOOLEAN SetWithOptions);
    BOOL NtUserRedrawWindow(HWND WindowHandle, PRECT lprcUpdate, HRGN hrgnUpdate, ULONG Flags);
    HWND NtUserRealChildWindowFromPoint(HWND WindowHandleParent, POINT ptParentClientCoords);
    BOOL NtUserRegisterHotKey(HWND WindowHandle, LONG Id, ULONG fsModifiers, ULONG vk);
    BOOL NtUserRemoveMenu(HMENU MenuHandle, ULONG Position, ULONG Flags);
    ULONG NtUserSendInput(ULONG Count, LPINPUT Inputs, LONG Size);
    HWND NtUserSetCapture(HWND WindowHandle);
    ULONG_PTR NtUserSetTimer(HWND WindowHandle, ULONG_PTR IDEvent, ULONG Elapse, TIMERPROC TimerFunc, ULONG ToleranceDelay);
    USHORT NtUserSetClassWord(HWND WindowHandle, LONG Index, USHORT NewWord);
    BOOL NtUserSetCursorPos(LONG X, LONG Y);
    BOOL NtUserSetLayeredWindowAttributes(HWND WindowHandle, COLORREF Key, BYTE Alpha, ULONG Flags);
    BOOL NtUserSetWindowPos(HWND WindowHandle, HWND WindowHandleInsertAfter, LONG X, LONG Y, LONG cx, LONG cy, ULONG Flags);
    BOOL NtUserBringWindowToTop(HWND WindowHandle);
    BOOL NtUserRegisterCloakedNotification(HWND WindowHandle, BOOL Register);
    USHORT NtUserSetWindowWord(HWND WindowHandle, LONG Index, USHORT NewWord);
    NTSTATUS NtUserSetForegroundWindowForApplication(HWND WindowHandle);
    HWND NtUserShellForegroundBoostProcess(HANDLE ProcessHandle, HWND WindowHandle);
    ULONG NtUserSetAdditionalForegroundBoostProcesses(HWND WindowHandle);
    ULONG NtUserSetAdditionalPowerThrottlingProcess(HWND WindowHandle, ULONG ProcessHandlesCount, PHANDLE ProcessHandles);
    LONG NtUserShowCursor(BOOL Show);
    BOOL NtUserShowWindow(HWND WindowHandle, LONG CmdShow);
    BOOL NtUserShowWindowAsync(HWND WindowHandle, LONG CmdShow);
    BOOL NtUserShutdownBlockReasonQuery(HWND WindowHandle, PWSTR Buffer, PULONG BufferCount);
    BOOL NtUserShutdownReasonDestroy(HWND WindowHandle);
    BOOL NtUserTrackMouseEvent(LPTRACKMOUSEEVENT EventTrack);
    BOOL NtUserTrackPopupMenuEx(HMENU MenuHandle, ULONG Flags, LONG x, LONG y, HWND WindowHandle, LPTPMPARAMS lptpm);
    BOOL NtUserUnhookWinEvent(HWINEVENTHOOK WinEventHookHandle);
    BOOL NtUserUnregisterHotKey(HWND WindowHandle, LONG Id);
    BOOL NtUserUserHandleGrantAccess(HANDLE UserHandle, HANDLE Job, BOOL Grant);
    BOOL NtUserValidateRect(HWND WindowHandle, RECT *Rect);
    HWND NtUserWindowFromDC(HDC Hdc);
    HWND NtUserWindowFromPhysicalPoint(POINT Point);
    HWND NtUserWindowFromPoint(POINT Point);
    ULONG_PTR NtUserCallNoParam(ULONG xpfnProc);
    ULONG_PTR NtUserCallOneParam(ULONG_PTR Param, ULONG xpfnProc);
    ULONG_PTR NtUserCallHwnd(HWND hwnd, ULONG xpfnProc);
    ULONG_PTR NtUserCallHwndSafe(HWND hwnd, ULONG xpfnProc);
    ULONG_PTR NtUserCallHwndOpt(HWND hwnd, ULONG xpfnProc);
    ULONG_PTR NtUserCallHwndParam(HWND hwnd, ULONG_PTR Param, ULONG xpfnProc);
    ULONG_PTR NtUserCallHwndLock(HWND hwnd, ULONG xpfnProc);
    ULONG_PTR NtUserCallHwndLockSafe(HWND hwnd, ULONG xpfnProc);
    ULONG_PTR NtUserCallHwndParamLock(HWND hwnd, ULONG_PTR Param, ULONG xpfnProc);
    ULONG_PTR NtUserCallHwndParamLockSafe(HWND hwnd, ULONG_PTR Param, ULONG xpfnProc);
    ULONG_PTR NtUserCallTwoParam(ULONG_PTR Param1, ULONG_PTR Param2, ULONG xpfnProc);
    HMENU NtUserCreateMenu();
    HMENU NtUserCreatePopupMenu();
    LOGICAL NtUserAllowForegroundActivation();
    LOGICAL NtUserCancelQueueEventCompletionPacket();
    LOGICAL NtUserClearWakeMask();
    LOGICAL NtUserCreateSystemThreads();
    LOGICAL NtUserDestroyCaret();
    LOGICAL NtUserDisableProcessWindowsGhosting();
    LOGICAL NtUserDrainThreadCoreMessagingCompletions();
    ULONG NtUserGetDeviceChangeInfo();
    LOGICAL NtUserGetIMEShowStatus();
    HDESK NtUserGetInputDesktop();
    ULONG NtUserGetMessagePos();
    ULONG_PTR NtUserGetQueueIocp();
    ULONG NtUserGetUnpredictedMessagePos();
    LOGICAL NtUserHandleSystemThreadCreationFailure();
    ULONG_PTR NtUserHideCursorNoCapture();
    LOGICAL NtUserIsQueueAttached();
    LOGICAL NtUserLoadCursorsAndIcons();
    LOGICAL NtUserLoadUserApiHook();
    LOGICAL NtUserPrepareForLogoff();
    LOGICAL NtUserReassociateQueueEventCompletionPacket();
    LOGICAL NtUserReleaseCapture();
    LOGICAL NtUserRemoveQueueCompletion();
    LOGICAL NtUserResetDblClk();
    LOGICAL NtUserZapActiveAndFocus();
    NTSTATUS NtUserRemoteConsoleShadowStop();
    NTSTATUS NtUserRemoteDisconnect();
    NTSTATUS NtUserRemoteShadowSetup();
    NTSTATUS NtUserRemoteShadowStop();
    NTSTATUS NtUserRemotePassthruEnable();
    NTSTATUS NtUserRemotePassthruDisable();
    ULONG NtUserRemoteConnectState();
    LOGICAL NtUserUpdatePerUserImmEnabling();
    LOGICAL NtUserUserPowerCalloutWorker();
    NTSTATUS NtUserWakeRITForShutdown();
    LOGICAL NtUserDoInitMessagePumpHook();
    LOGICAL NtUserDoUninitMessagePumpHook();
    LOGICAL NtUserEnableMouseInPointerForThread();
    ULONG_PTR NtUserDeferredDesktopRotation();
    LOGICAL NtUserEnablePerMonitorMenuScaling();
    HDWP NtUserBeginDeferWindowPos(ULONG NumWindowsHint);
    HWND NtUserGetSendMessageReceiver(ULONG ThreadIdSender);
    LOGICAL NtUserAllowSetForegroundWindow(ULONG ProcessId);
    LOGICAL NtUserCsDdeUninitialize(HANDLE hInst);
    ULONG NtUserEnumClipboardFormats(ULONG Format);
    HANDLE NtUserGetInputEvent(ULONG WakeMask);
    ULONG NtUserGetKeyboardType(ULONG TypeFlag);
    LOGICAL NtUserGetProcessDefaultLayout(PULONG DefaultLayout);
    LOGICAL NtUserGetWinStationInfo(PWSINFO WsInfo);
    LOGICAL NtUserLockSetForegroundWindow(ULONG LockCode);
    LOGICAL NtUserLW_LoadFonts(LOGICAL Remote);
    PVOID NtUserMapDesktopObject(HANDLE h);
    LOGICAL NtUserMessageBeep(ULONG Type);
    LOGICAL NtUserPlayEventSound(ULONG idSound);
    LOGICAL NtUserPostQuitMessage(LONG ExitCode);
    ULONG NtUserRealizePalette(HDC hdc);
    LOGICAL NtUserRegisterLPK(ULONG LpkEntryPoints);
    LOGICAL NtUserRegisterSystemThread(ULONG Flags);
    NTSTATUS NtUserRemoteReconnect(struct _DOCONNECTDATA *DoConnectData);
    NTSTATUS NtUserRemoteThinwireStats(struct CACHE_STATISTICS *Stats);
    NTSTATUS NtUserRemoteNotify(struct _DONOTIFYDATA *DoNotifyData);
    LOGICAL NtUserReplyMessage(LRESULT Result);
    LOGICAL NtUserSetCaretBlinkTime(ULONG Milliseconds);
    LOGICAL NtUserSetDoubleClickTime(ULONG Milliseconds);
    LPARAM NtUserSetMessageExtraInfo(LPARAM Param);
    LOGICAL NtUserSetProcessDefaultLayout(ULONG DefaultLayout);
    LOGICAL NtUserSetWatermarkStrings(PCUNICODE_STRING StringTable);
    LOGICAL NtUserShowStartGlass(ULONG Timeout);
    LOGICAL NtUserSwapMouseButton(LOGICAL SwapButtons);
    LOGICAL NtUserWOWModuleUnload(HANDLE Module);
    ULONG_PTR NtUserDwmLockScreenUpdates(LOGICAL LockUpdates);
    ULONG_PTR NtUserEnableSessionForMMCSS(LOGICAL Enable);
    LOGICAL NtUserSetWaitForQueueAttach(LOGICAL Waiting);
    LOGICAL NtUserThreadMessageQueueAttached(ULONG ThreadId);
    LOGICAL NtUserEnsureDpiDepSysMetCacheForPlateau(ULONG Dpi);
    UINT_PTR NtUserForceEnableNumpadTranslation(LOGICAL ForceNumlockTranslation);
    LOGICAL NtUserSetTSFEventState(ULONG StateFlags);
    LOGICAL NtUserSetShellChangeNotifyHWND(HWND hwnd);
    LOGICAL NtUserDeregisterShellHookWindow(HWND hwnd);
    ULONG_PTR NtUserDWP_GetEnabledPopupOffset(HWND hwnd);
    HWND NtUserGetModernAppWindow(HWND ShellFrame);
    ULONG NtUserGetWindowContextHelpId(HWND hwnd);
    LOGICAL NtUserRegisterShellHookWindow(HWND hwnd);
    LOGICAL NtUserSetMsgBox(HWND hwnd);
    ULONG_PTR NtUserInitThreadCoreMessagingIocp(HWND hwnd);
    LOGICAL NtUserScheduleDispatchNotification(HWND hwnd);
    LOGICAL NtUserSetProgmanWindow(HWND hwnd);
    LOGICAL NtUserSetTaskmanWindow(HWND hwnd);
    HCURSOR NtUserGetClassIcoCur(HWND hwnd, ULONG Index);
    LOGICAL NtUserClearWindowState(HWND hwnd, ULONG Flag);
    LOGICAL NtUserSetWindowState(HWND hwnd, ULONG Flag);
    LOGICAL NtUserKillSystemTimer(HWND hwnd, UINT_PTR IDEvent);
    LOGICAL NtUserNotifyOverlayWindow(HWND hwnd, LOGICAL Enable);
    LOGICAL NtUserSetDialogPointer(HWND hwnd, ULONG_PTR Ptr);
    LOGICAL NtUserSetVisible(HWND hwnd, ULONG Flags);
    LOGICAL NtUserSetWindowContextHelpId(HWND hwnd, ULONG ContextId);
    LOGICAL NtUserRegisterWindowArrangementCallout(HWND hwnd, LOGICAL Register);
    LOGICAL NtUserEnableModernAppWindowKeyboardIntercept(HWND hwnd, LOGICAL Enable);
    ULONG NtUserArrangeIconicWindows(HWND hwnd);
    LOGICAL NtUserDrawMenuBar(HWND hwnd);
    LOGICAL NtUserCheckImeShowStatusInThread(HWND Ime);
    ULONG_PTR NtUserGetSysMenuOffset(HWND hwnd);
    LOGICAL NtUserRedrawFrame(HWND hwnd);
    LOGICAL NtUserRedrawFrameAndHook(HWND hwnd);
    LOGICAL NtUserSetDialogSystemMenu(HWND hwnd);
    LOGICAL NtUserSetForegroundWindow(HWND hwnd);
    LOGICAL NtUserSetSysMenu(HWND hwnd);
    LOGICAL NtUserUpdateClientRect(HWND hwnd);
    LOGICAL NtUserUpdateWindow(HWND hwnd);
    LOGICAL NtUserSetCancelRotationDelayHintWindow(HWND hwnd);
    ULONG_PTR NtUserGetWindowTrackInfoAsync(HWND hwnd);
    LOGICAL NtUserBroadcastImeShowStatusChange(HWND Ime, LOGICAL Show);
    LOGICAL NtUserSetModernAppWindow(HWND ShellFrame, HWND App);
    LOGICAL NtUserRedrawTitle(HWND hwnd, ULONG Flags);
    LOGICAL NtUserShowOwnedPopups(HWND Owner, LOGICAL Show);
    LOGICAL NtUserSwitchToThisWindow(HWND hwnd, LOGICAL AltTab);
    LOGICAL NtUserUpdateWindows(HWND hwnd, HRGN hrgn);
    LOGICAL NtUserValidateRgn(HWND hwnd, HRGN hrgn);
    LOGICAL NtUserEnableWindow(HWND hwnd, LOGICAL Enable);
    LOGICAL NtUserChangeWindowMessageFilter(ULONG Message, ULONG Flag);
    LOGICAL NtUserGetCursorPos(PPOINT Point, ULONG CursorPosType);
    LOGICAL NtUserInitAnsiOem(PCHAR OemToCharA, PCHAR CharToOemA);
    LOGICAL NtUserNlsKbdSendIMENotification(ULONG ImeOpen, ULONG ImeConversion);
    LOGICAL NtUserRegisterGhostWindow(HWND Ghost, HWND Hung);
    LOGICAL NtUserRegisterLogonProcess(ULONG ProcessId, PLUID LuidConnect);
    LOGICAL NtUserRegisterSiblingFrostWindow(HWND hwndFrost, HWND hwnd);
    LOGICAL NtUserRegisterUserHungAppHandlers(PFNW32ET W32EndTask, HANDLE EventWowExec);
    NTSTATUS NtUserRemoteShadowCleanup(PVOID ThinwireData, ULONG ThinwireDataLength);
    NTSTATUS NtUserRemoteShadowStart(PVOID ThinwireData, ULONG ThinwireDataLength);
    LOGICAL NtUserSetCaretPos(LONG x, LONG y);
    LOGICAL NtUserSetThreadQueueMergeSetting(ULONG ThreadId, ULONG Flags);
    LOGICAL NtUserUnhookWindowsHook(LONG FilterType, HOOKPROC FilterProc);
    LOGICAL NtUserEnableShellWindowManagementBehavior(ULONG_PTR Param1, ULONG_PTR Param2);
    NTSTATUS NtUserCitSetInfo(ULONG_PTR InfoFlags, ULONG_PTR Info);
    ULONG_PTR NtUserScaleSystemMetricForDPIWithoutCache(ULONG Metric, ULONG ToDpi);
    NTSTATUS NtTraceControl(ETWTRACECONTROLCODE FunctionCode, PVOID InputBuffer, ULONG InputBufferLength, PVOID OutputBuffer, ULONG OutputBufferLength, PULONG ReturnLength);
    NTSTATUS NtTraceEvent(HANDLE TraceHandle, ULONG Flags, ULONG FieldSize, PVOID Fields);
    NTSTATUS NtContinue(PCONTEXT ContextRecord, BOOLEAN TestAlert);
    NTSTATUS NtContinueEx(PCONTEXT ContextRecord, PVOID ContinueArgument);
    NTSTATUS NtRaiseException(PEXCEPTION_RECORD ExceptionRecord, PCONTEXT ContextRecord, BOOLEAN FirstChance);
}