#pragma once

namespace cmn::syscall
{
    #define ACCEPT_CONNECTION                         288
    #define ACCEPT_CONNECTION_WITH_FLAGS               43
    #define ADD_INOTIFY_WATCH                         254
    #define ADD_KEY_TO_KEYRING                        248
    #define ADD_LANDLOCK_RULE                         445
    #define ADJUST_CLOCK                              305
    #define ADJUST_SYSTEM_CLOCK                       159
    #define ADVISE_MEMORY                              28
    #define ADVISE_PROCESS_MEMORY                     440
    #define ALLOCATE_FILE_SPACE                       285
    #define ALLOCATE_MEMORY_PROTECTION_KEY            330
    #define APPLY_LANDLOCK_RULESET                    446
    #define ATTACH_SHARED_MEMORY                       30
    #define BIND_MEMORY_POLICY                        237
    #define BIND_SOCKET                                49
    #define BRK                                        12
    #define CANCEL_ASYNC_IO                           210
    #define CHANGE_FILE_MODE                           91
    #define CHANGE_FILE_MODE_AT                       268
    #define CHANGE_FILE_MODE_AT_WITH_FLAGS            452
    #define CHANGE_FILE_OWNER                          93
    #define CHANGE_FILE_OWNER_AT                      260
    #define CHANGE_ROOT_DIRECTORY                     161
    #define CHANGE_ROOT_MOUNT                         155
    #define CHANGE_WORKING_DIRECTORY                   80
    #define CHANGE_WORKING_DIRECTORY_FROM_DESCRIPTOR   81
    #define CHECK_FILE_ACCESS_AT                      269
    #define CHECK_FILE_ACCESS_AT_WITH_FLAGS           439
    #define CLOSE_FILE_DESCRIPTOR                       3
    #define CLOSE_FILE_DESCRIPTOR_RANGE               436
    #define COMPARE_PROCESS_RESOURCES                 312
    #define CONFIGURE_EPOLL_WATCH                     233
    #define CONFIGURE_FILESYSTEM_CONTEXT              431
    #define CONFIGURE_IO_URING                        427
    #define CONFIGURE_MESSAGE_QUEUE_ATTRIBUTES        245
    #define CONFIGURE_MESSAGE_QUEUE_NOTIFICATION      244
    #define CONFIGURE_PROCESS_ACCOUNTING              163
    #define CONFIGURE_PROCESS_PERSONALITY             135
    #define CONFIGURE_PROCESS_RESOURCE_LIMIT          302
    #define CONFIGURE_RESTARTABLE_SEQUENCE            334
    #define CONFIGURE_SIGNAL_ACTION                    13
    #define CONFIGURE_SIGNAL_DESCRIPTOR               289
    #define CONFIGURE_SIGNAL_MASK                      14
    #define CONFIGURE_SIGNAL_STACK                    131
    #define CONFIGURE_SYSCALL_FILTERING               317
    #define CONNECT_SOCKET                             42
    #define CONTROL_FILE_DESCRIPTOR                    72
    #define CONTROL_FILESYSTEM_QUOTA                  179
    #define CONTROL_FILESYSTEM_QUOTA_BY_DESCRIPTOR    443
    #define CONTROL_KERNEL_KEYS                       250
    #define CONTROL_KERNEL_LOG                        103
    #define CONTROL_MESSAGE_QUEUE                      71
    #define CONTROL_PROCESS                           157
    #define CONTROL_PROCESS_TRACE                     101
    #define CONTROL_SEMAPHORE_SET                      66
    #define CONTROL_SHARED_MEMORY                      31
    #define CONTROL_SYSTEM_POWER                      169
    #define COPY_FILE_DATA                            326
    #define COPY_FILE_TO_DESCRIPTOR                    40
    #define CREATE_ASYNC_IO_CONTEXT                   206
    #define CREATE_CHILD_TASK                         435
    #define CREATE_CHILD_TASK_WITH_OPTIONS             56
    #define CREATE_DETACHED_MOUNT                     432
    #define CREATE_DIRECTORY_AT                       258
    #define CREATE_EPOLL                              291
    #define CREATE_EVENT_COUNTER                      290
    #define CREATE_FANOTIFY_GROUP                     300
    #define CREATE_FILESYSTEM_CONTEXT                 430
    #define CREATE_FILESYSTEM_NODE_AT                 259
    #define CREATE_HARD_LINK_AT                       265
    #define CREATE_INOTIFY                            294
    #define CREATE_IO_URING                           425
    #define CREATE_LANDLOCK_RULESET                   444
    #define CREATE_MEMORY_FILE                        319
    #define CREATE_PIPE                               293
    #define CREATE_PROCESS_SESSION                    112
    #define CREATE_PROCESS_TIMER                      222
    #define CREATE_SECRET_MEMORY                      447
    #define CREATE_SHADOW_STACK                       453
    #define CREATE_SOCKET                              41
    #define CREATE_SOCKET_PAIR                         53
    #define CREATE_SYMBOLIC_LINK_AT                   266
    #define CREATE_TIMER_DESCRIPTOR                   283
    #define CREATE_USER_FAULT_DESCRIPTOR              323
    #define DELETE_PROCESS_TIMER                      226
    #define DESTROY_ASYNC_IO_CONTEXT                  207
    #define DETACH_SHARED_MEMORY                       67
    #define DISABLE_SWAP                              168
    #define DUPLICATE_FILE_DESCRIPTOR                 292
    #define DUPLICATE_FILE_DESCRIPTOR_TO               32
    #define DUPLICATE_PIPE_DATA                       276
    #define DUPLICATE_PROCESS_DESCRIPTOR              438
    #define ENABLE_SWAP                               167
    #define EXECUTE_BPF_COMMAND                       321
    #define EXECUTE_PROGRAM                            59
    #define EXECUTE_PROGRAM_AT                        322
    #define EXIT_PROCESS                              231
    #define EXIT_THREAD                                60
    #define FREE_MEMORY_PROTECTION_KEY                331
    #define GET_ASYNC_IO_COMPLETIONS                  208
    #define GET_ASYNC_IO_COMPLETIONS_WITH_SIGNAL_MASK 333
    #define GET_CLOCK_RESOLUTION                      229
    #define GET_CLOCK_TIME                            228
    #define GET_CPU_AFFINITY                          204
    #define GET_CURRENT_CPU                           309
    #define GET_DESCRIPTOR_STATUS                       5
    #define GET_EFFECTIVE_GROUP_ID                    108
    #define GET_EFFECTIVE_USER_ID                     107
    #define GET_EXTENDED_ATTRIBUTE                    191
    #define GET_EXTENDED_ATTRIBUTE_AT                 464
    #define GET_EXTENDED_ATTRIBUTE_BY_DESCRIPTOR      193
    #define GET_EXTENDED_ATTRIBUTE_NO_FOLLOW          192
    #define GET_EXTENDED_FILE_STATUS                  332
    #define GET_FILE_HANDLE_AT                        303
    #define GET_FILESYSTEM_FILE_ATTRIBUTES            468
    #define GET_FILESYSTEM_STATISTICS                 137
    #define GET_FILESYSTEM_STATISTICS_BY_DESCRIPTOR   138
    #define GET_GROUP_CREDENTIALS                     120
    #define GET_INTERVAL_TIMER                         36
    #define GET_IO_PRIORITY                           252
    #define GET_LOCAL_SOCKET_ADDRESS                   51
    #define GET_MAXIMUM_SCHEDULER_PRIORITY            146
    #define GET_MEMORY_POLICY                         239
    #define GET_MESSAGE_QUEUE                          68
    #define GET_MINIMUM_SCHEDULER_PRIORITY            147
    #define GET_MOUNT_INFORMATION                     457
    #define GET_NICE_PRIORITY                         140
    #define GET_PARENT_PROCESS_ID                     110
    #define GET_PATH_STATUS_AT                        262
    #define GET_PEER_SOCKET_ADDRESS                    52
    #define GET_PENDING_SIGNALS                       127
    #define GET_PROCESS_GROUP_ID                      121
    #define GET_PROCESS_ID                             39
    #define GET_PROCESS_TIMER                         224
    #define GET_PROCESS_TIMES                         100
    #define GET_RANDOM_BYTES                          318
    #define GET_REAL_GROUP_ID                         104
    #define GET_REAL_USER_ID                          102
    #define GET_RESOURCE_LIMIT                         97
    #define GET_RESOURCE_USAGE                         98
    #define GET_ROUND_ROBIN_INTERVAL                  148
    #define GET_SCHEDULER_ATTRIBUTES                  315
    #define GET_SCHEDULER_PARAMETERS                  143
    #define GET_SCHEDULER_POLICY                      145
    #define GET_SECURITY_ATTRIBUTES                   459
    #define GET_SEMAPHORE_SET                          64
    #define GET_SESSION_ID                            124
    #define GET_SHARED_MEMORY                          29
    #define GET_SOCKET_OPTION                          55
    #define GET_SUPPLEMENTARY_GROUPS                  115
    #define GET_SYSTEM_IDENTIFICATION                  63
    #define GET_SYSTEM_INFORMATION                     99
    #define GET_THREAD_CAPABILITIES                   125
    #define GET_THREAD_ID                             186
    #define GET_THREAD_ROBUST_FUTEX_LIST              274
    #define GET_TIMER_DESCRIPTOR                      287
    #define GET_TIMER_OVERRUN_COUNT                   225
    #define GET_USER_CREDENTIALS                      118
    #define GET_WALL_CLOCK_TIME                        96
    #define GET_WORKING_DIRECTORY                      79
    #define HANGUP_VIRTUAL_TERMINAL                   153
    #define ISSUE_MEMORY_BARRIER                      324
    #define JOIN_NAMESPACE                            308
    #define LISTEN_FOR_CONNECTIONS                     50
    #define LIST_EXTENDED_ATTRIBUTES                  194
    #define LIST_EXTENDED_ATTRIBUTES_AT               465
    #define LIST_EXTENDED_ATTRIBUTES_BY_DESCRIPTOR    196
    #define LIST_EXTENDED_ATTRIBUTES_NO_FOLLOW        195
    #define LIST_MOUNT_IDS                            458
    #define LIST_SECURITY_MODULES                     461
    #define LOAD_KERNEL_IMAGE                         246
    #define LOAD_KERNEL_IMAGE_FROM_FILES              320
    #define LOAD_KERNEL_MODULE_FROM_DESCRIPTOR        313
    #define LOAD_KERNEL_MODULE_FROM_MEMORY            175
    #define LOCK_MEMORY                               325
    #define LOCK_MEMORY_WITH_FLAGS                    149
    #define LOCK_PROCESS_MEMORY                       151
    #define MANAGE_FILE_LOCK                           73
    #define MAP_MEMORY                                  9
    #define MIGRATE_PROCESS_PAGES                     256
    #define MODIFY_FANOTIFY_MARK                      301
    #define MOUNT_FILESYSTEM                          165
    #define MOVE_MOUNT                                429
    #define MOVE_PROCESS_PAGES                        279
    #define OPEN_FILE_AT                              257
    #define OPEN_FILE_AT_WITH_OPTIONS                 437
    #define OPEN_FILE_BY_HANDLE                       304
    #define OPEN_MESSAGE_QUEUE                        240
    #define OPEN_MOUNT_CONFIGURATION                  433
    #define OPEN_MOUNT_TREE                           428
    #define OPEN_MOUNT_TREE_WITH_ATTRIBUTES           467
    #define OPEN_PERFORMANCE_EVENT                    298
    #define OPEN_PROCESS_DESCRIPTOR                   434
    #define PERFORM_FUTEX_OPERATION                   202
    #define PERFORM_IO_CONTROL                         16
    #define PERFORM_SEMAPHORE_OPERATIONS               65
    #define PERFORM_SEMAPHORE_OPERATIONS_UNTIL        220
    #define POLL_FILE_DESCRIPTORS                     271
    #define PRELOAD_FILE_DATA                         187
    #define PROCESS_IO_URING_QUEUE                    426
    #define QUERY_MEMORY_RESIDENCY                     27
    #define QUERY_PAGE_CACHE                          451
    #define QUEUE_PROCESS_SIGNAL                      129
    #define QUEUE_THREAD_SIGNAL                       297
    #define READ_DATA                                   0
    #define READ_DATA_VECTORS                          19
    #define READ_DIRECTORY_ENTRIES                    217
    #define READ_FILE_AT_OFFSET                        17
    #define READ_FILE_VECTORS_AT_OFFSET               295
    #define READ_FILE_VECTORS_AT_OFFSET_WITH_FLAGS    327
    #define READ_PROCESS_MEMORY                       310
    #define READ_SYMBOLIC_LINK_AT                     267
    #define RECEIVE_MESSAGE_UNTIL                     243
    #define RECEIVE_QUEUE_MESSAGE                      70
    #define RECEIVE_SOCKET_DATA                        45
    #define RECEIVE_SOCKET_MESSAGE                     47
    #define RECEIVE_SOCKET_MESSAGES                   299
    #define RELEASE_PROCESS_MEMORY                    448
    #define REMAP_FILE_PAGES                          216
    #define REMAP_MEMORY                               25
    #define REMOVE_EXTENDED_ATTRIBUTE                 197
    #define REMOVE_EXTENDED_ATTRIBUTE_AT              466
    #define REMOVE_EXTENDED_ATTRIBUTE_BY_DESCRIPTOR   199
    #define REMOVE_EXTENDED_ATTRIBUTE_NO_FOLLOW       198
    #define REMOVE_INOTIFY_WATCH                      255
    #define REMOVE_PATH_AT                            263
    #define RENAME_PATH_AT                            264
    #define RENAME_PATH_AT_WITH_FLAGS                 316
    #define REQUEST_KERNEL_KEY                        249
    #define REQUEUE_FUTEX_WAITERS                     456
    #define RESIZE_FILE                                77
    #define RESIZE_FILE_AT_PATH                        76
    #define RESTART_INTERRUPTED_SYSCALL               219
    #define RETURN_FROM_SIGNAL_HANDLER                 15
    #define SEAL_MEMORY                               462
    #define SEEK_FILE                                   8
    #define SEND_MESSAGE_UNTIL                        242
    #define SEND_QUEUE_MESSAGE                         69
    #define SEND_SIGNAL                                62
    #define SEND_SIGNAL_TO_THREAD                     200
    #define SEND_SOCKET_DATA                           44
    #define SEND_SOCKET_MESSAGE                        46
    #define SEND_SOCKET_MESSAGES                      307
    #define SEND_THREAD_SIGNAL                        234
    #define SET_CLOCK_TIME                            227
    #define SET_CPU_AFFINITY                          203
    #define SET_EXTENDED_ATTRIBUTE                    188
    #define SET_EXTENDED_ATTRIBUTE_AT                 463
    #define SET_EXTENDED_ATTRIBUTE_BY_DESCRIPTOR      190
    #define SET_EXTENDED_ATTRIBUTE_NO_FOLLOW          189
    #define SET_FILE_CREATION_MASK                     95
    #define SET_FILESYSTEM_FILE_ATTRIBUTES            469
    #define SET_FILESYSTEM_GROUP_ID                   123
    #define SET_FILESYSTEM_USER_ID                    122
    #define SET_FILE_TIMES_AT                         280
    #define SET_GROUP_CREDENTIALS                     119
    #define SET_GROUP_ID                              106
    #define SET_INTERVAL_TIMER                         38
    #define SET_IO_PRIORITY                           251
    #define SET_MEMORY_HOME_NODE                      450
    #define SET_MEMORY_POLICY                         238
    #define SET_MEMORY_PROTECTION                      10
    #define SET_MEMORY_PROTECTION_KEY                 329
    #define SET_MOUNT_ATTRIBUTES                      442
    #define SET_NICE_PRIORITY                         141
    #define SET_PROCESS_GROUP                         109
    #define SET_PROCESS_TIMER                         223
    #define SET_REAL_EFFECTIVE_GROUP_IDS              114
    #define SET_REAL_EFFECTIVE_USER_IDS               113
    #define SET_RESOURCE_LIMIT                        160
    #define SET_SCHEDULER_ATTRIBUTES                  314
    #define SET_SCHEDULER_PARAMETERS                  142
    #define SET_SCHEDULER_POLICY                      144
    #define SET_SECURITY_ATTRIBUTE                    460
    #define SET_SOCKET_OPTION                          54
    #define SET_SUPPLEMENTARY_GROUPS                  116
    #define SET_SYSTEM_DOMAIN_NAME                    171
    #define SET_SYSTEM_HOST_NAME                      170
    #define SET_THREAD_CAPABILITIES                   126
    #define SET_THREAD_ID_ADDRESS                     218
    #define SET_THREAD_ROBUST_FUTEX_LIST              273
    #define SET_TIMER_DESCRIPTOR                      286
    #define SET_USER_CREDENTIALS                      117
    #define SET_USER_ID                               105
    #define SET_WALL_CLOCK_TIME                       164
    #define SHUTDOWN_SOCKET                            48
    #define SIGNAL_PROCESS                            424
    #define SLEEP_FOR_DURATION                         35
    #define SLEEP_ON_CLOCK                            230
    #define SPLICE_DATA                               275
    #define SPLICE_MEMORY_TO_PIPE                     278
    #define SUBMIT_ASYNC_IO                           209
    #define SUSPEND_UNTIL_SIGNAL                      130
    #define SYNCHRONIZE_FILE                           74
    #define SYNCHRONIZE_FILE_DATA                      75
    #define SYNCHRONIZE_FILE_RANGE                    277
    #define SYNCHRONIZE_FILESYSTEM                    306
    #define SYNCHRONIZE_FILESYSTEMS                   162
    #define SYNCHRONIZE_MEMORY_MAPPING                 26
    #define UNLINK_MESSAGE_QUEUE                      241
    #define UNLOAD_KERNEL_MODULE                      176
    #define UNLOCK_MEMORY                             150
    #define UNLOCK_PROCESS_MEMORY                     152
    #define UNMAP_MEMORY                               11
    #define UNMOUNT_FILESYSTEM                        166
    #define UNSHARE_PROCESS_RESOURCES                 272
    #define WAIT_FOR_CHILD                             61
    #define WAIT_FOR_CHILD_EVENT                      247
    #define WAIT_FOR_DESCRIPTOR_EVENTS                270
    #define WAIT_FOR_EPOLL_EVENTS                     441
    #define WAIT_FOR_EPOLL_EVENTS_PRECISE             281
    #define WAIT_FOR_SIGNAL                           128
    #define WAIT_ON_FUTEX                             455
    #define WAIT_ON_FUTEX_SET                         449
    #define WAKE_FUTEX_WAITERS                        454
    #define WRITE_DATA                                  1
    #define WRITE_DATA_VECTORS                         20
    #define WRITE_FILE_AT_OFFSET                       18
    #define WRITE_FILE_VECTORS_AT_OFFSET              296
    #define WRITE_FILE_VECTORS_AT_OFFSET_WITH_FLAGS   328
    #define WRITE_PROCESS_MEMORY                      311
    #define YIELD_PROCESSOR                            24
}