// AUTO-GENERATED SCRIPT
#pragma once
#include "sys/platform/Arch.hpp"

namespace cmn::sys::syscall
{
    #if CMN_SYS_ARCH_ARM64
        #define ACCEPT                   202
        #define ACCEPT4                  242
        #define ACCT                      89
        #define ADD_KEY                  217
        #define ADJTIMEX                 171
        #define BIND                     200
        #define BPF                      280
        #define BRK                      214
        #define CACHESTAT                451
        #define CAPGET                    90
        #define CAPSET                    91
        #define CHDIR                     49
        #define CHROOT                    51
        #define CLOCK_ADJTIME            266
        #define CLOCK_GETRES             114
        #define CLOCK_GETTIME            113
        #define CLOCK_NANOSLEEP          115
        #define CLOCK_SETTIME            112
        #define CLONE                    220
        #define CLONE3                   435
        #define CLOSE                     57
        #define CLOSE_RANGE              436
        #define CONNECT                  203
        #define COPY_FILE_RANGE          285
        #define DELETE_MODULE            106
        #define DUP                       23
        #define DUP3                      24
        #define EPOLL_CREATE1             20
        #define EPOLL_CTL                 21
        #define EPOLL_PWAIT               22
        #define EPOLL_PWAIT2             441
        #define EVENTFD2                  19
        #define EXECVE                   221
        #define EXECVEAT                 281
        #define EXIT                      93
        #define EXIT_GROUP                94
        #define FACCESSAT2               439
        #define FACCESSAT                 48
        #define FALLOCATE                 47
        #define FANOTIFY_INIT            262
        #define FANOTIFY_MARK            263
        #define FCHDIR                    50
        #define FCHMOD                    52
        #define FCHMODAT2                452
        #define FCHMODAT                  53
        #define FCHOWN                    55
        #define FCHOWNAT                  54
        #define FCNTL                     25
        #define FDATASYNC                 83
        #define FGETXATTR                 10
        #define FILE_GETATTR             468
        #define FILE_SETATTR             469
        #define FINIT_MODULE             273
        #define FLISTXATTR                13
        #define FLOCK                     32
        #define FREMOVEXATTR              16
        #define FSCONFIG                 431
        #define FSETXATTR                  7
        #define FSMOUNT                  432
        #define FSOPEN                   430
        #define FSPICK                   433
        #define FSTATFS                   44
        #define FSYNC                     82
        #define FTRUNCATE                 46
        #define FUTEX                     98
        #define FUTEX_REQUEUE            456
        #define FUTEX_WAIT               455
        #define FUTEX_WAITV              449
        #define FUTEX_WAKE               454
        #define GETCPU                   168
        #define GETCWD                    17
        #define GETDENTS64                61
        #define GETEGID                  177
        #define GETEUID                  175
        #define GETGID                   176
        #define GETGROUPS                158
        #define GETITIMER                102
        #define GET_MEMPOLICY            236
        #define GETPEERNAME              205
        #define GETPGID                  155
        #define GETPID                   172
        #define GETPPID                  173
        #define GETPRIORITY              141
        #define GETRANDOM                278
        #define GETRESGID                150
        #define GETRESUID                148
        #define GETRLIMIT                163
        #define GET_ROBUST_LIST          100
        #define GETRUSAGE                165
        #define GETSID                   156
        #define GETSOCKNAME              204
        #define GETSOCKOPT               209
        #define GETTID                   178
        #define GETTIMEOFDAY             169
        #define GETUID                   174
        #define GETXATTR                   8
        #define GETXATTRAT               464
        #define INIT_MODULE              105
        #define INOTIFY_ADD_WATCH         27
        #define INOTIFY_INIT1             26
        #define INOTIFY_RM_WATCH          28
        #define IO_CANCEL                  3
        #define IOCTL                     29
        #define IO_DESTROY                 1
        #define IO_GETEVENTS               4
        #define IO_PGETEVENTS            292
        #define IOPRIO_GET                31
        #define IOPRIO_SET                30
        #define IO_SETUP                   0
        #define IO_SUBMIT                  2
        #define IO_URING_ENTER           426
        #define IO_URING_REGISTER        427
        #define IO_URING_SETUP           425
        #define KCMP                     272
        #define KEXEC_FILE_LOAD          294
        #define KEXEC_LOAD               104
        #define KEYCTL                   219
        #define KILL                     129
        #define LANDLOCK_ADD_RULE        445
        #define LANDLOCK_CREATE_RULESET  444
        #define LANDLOCK_RESTRICT_SELF   446
        #define LGETXATTR                  9
        #define LINKAT                    37
        #define LISTEN                   201
        #define LISTMOUNT                458
        #define LISTXATTR                 11
        #define LISTXATTRAT              465
        #define LLISTXATTR                12
        #define LREMOVEXATTR              15
        #define LSEEK                     62
        #define LSETXATTR                  6
        #define LSM_GET_SELF_ATTR        459
        #define LSM_LIST_MODULES         461
        #define LSM_SET_SELF_ATTR        460
        #define MADVISE                  233
        #define MAP_SHADOW_STACK         453
        #define MBIND                    235
        #define MEMBARRIER               283
        #define MEMFD_CREATE             279
        #define MEMFD_SECRET             447
        #define MIGRATE_PAGES            238
        #define MINCORE                  232
        #define MKDIRAT                   34
        #define MKNODAT                   33
        #define MLOCK2                   284
        #define MLOCK                    228
        #define MLOCKALL                 230
        #define MMAP                     222
        #define MOUNT                     40
        #define MOUNT_SETATTR            442
        #define MOVE_MOUNT               429
        #define MOVE_PAGES               239
        #define MPROTECT                 226
        #define MQ_GETSETATTR            185
        #define MQ_NOTIFY                184
        #define MQ_OPEN                  180
        #define MQ_TIMEDRECEIVE          183
        #define MQ_TIMEDSEND             182
        #define MQ_UNLINK                181
        #define MREMAP                   216
        #define MSEAL                    462
        #define MSGCTL                   187
        #define MSGGET                   186
        #define MSGRCV                   188
        #define MSGSND                   189
        #define MSYNC                    227
        #define MUNLOCK                  229
        #define MUNLOCKALL               231
        #define MUNMAP                   215
        #define NAME_TO_HANDLE_AT        264
        #define NANOSLEEP                101
        #define NEWFSTAT                  80
        #define NEWFSTATAT                79
        #define NEWUNAME                 160
        #define OPENAT2                  437
        #define OPENAT                    56
        #define OPEN_BY_HANDLE_AT        265
        #define OPEN_TREE                428
        #define OPEN_TREE_ATTR           467
        #define PERF_EVENT_OPEN          241
        #define PERSONALITY               92
        #define PIDFD_GETFD              438
        #define PIDFD_OPEN               434
        #define PIDFD_SEND_SIGNAL        424
        #define PIPE2                     59
        #define PIVOT_ROOT                41
        #define PKEY_ALLOC               289
        #define PKEY_FREE                290
        #define PKEY_MPROTECT            288
        #define PPOLL                     73
        #define PRCTL                    167
        #define PREAD64                   67
        #define PREADV2                  286
        #define PREADV                    69
        #define PRLIMIT64                261
        #define PROCESS_MADVISE          440
        #define PROCESS_MRELEASE         448
        #define PROCESS_VM_READV         270
        #define PROCESS_VM_WRITEV        271
        #define PSELECT6                  72
        #define PTRACE                   117
        #define PWRITE64                  68
        #define PWRITEV2                 287
        #define PWRITEV                   70
        #define QUOTACTL                  60
        #define QUOTACTL_FD              443
        #define READ                      63
        #define READAHEAD                213
        #define READLINKAT                78
        #define READV                     65
        #define REBOOT                   142
        #define RECVFROM                 207
        #define RECVMMSG                 243
        #define RECVMSG                  212
        #define REMAP_FILE_PAGES         234
        #define REMOVEXATTR               14
        #define REMOVEXATTRAT            466
        #define RENAMEAT2                276
        #define RENAMEAT                  38
        #define REQUEST_KEY              218
        #define RESTART_SYSCALL          128
        #define RSEQ                     293
        #define RT_SIGACTION             134
        #define RT_SIGPENDING            136
        #define RT_SIGPROCMASK           135
        #define RT_SIGQUEUEINFO          138
        #define RT_SIGRETURN             139
        #define RT_SIGSUSPEND            133
        #define RT_SIGTIMEDWAIT          137
        #define RT_TGSIGQUEUEINFO        240
        #define SCHED_GETAFFINITY        123
        #define SCHED_GETATTR            275
        #define SCHED_GETPARAM           121
        #define SCHED_GET_PRIORITY_MAX   125
        #define SCHED_GET_PRIORITY_MIN   126
        #define SCHED_GETSCHEDULER       120
        #define SCHED_RR_GET_INTERVAL    127
        #define SCHED_SETAFFINITY        122
        #define SCHED_SETATTR            274
        #define SCHED_SETPARAM           118
        #define SCHED_SETSCHEDULER       119
        #define SCHED_YIELD              124
        #define SECCOMP                  277
        #define SEMCTL                   191
        #define SEMGET                   190
        #define SEMOP                    193
        #define SEMTIMEDOP               192
        #define SENDFILE64                71
        #define SENDMMSG                 269
        #define SENDMSG                  211
        #define SENDTO                   206
        #define SETDOMAINNAME            162
        #define SETFSGID                 152
        #define SETFSUID                 151
        #define SETGID                   144
        #define SETGROUPS                159
        #define SETHOSTNAME              161
        #define SETITIMER                103
        #define SET_MEMPOLICY            237
        #define SET_MEMPOLICY_HOME_NODE  450
        #define SETNS                    268
        #define SETPGID                  154
        #define SETPRIORITY              140
        #define SETREGID                 143
        #define SETRESGID                149
        #define SETRESUID                147
        #define SETREUID                 145
        #define SETRLIMIT                164
        #define SET_ROBUST_LIST           99
        #define SETSID                   157
        #define SETSOCKOPT               208
        #define SET_TID_ADDRESS           96
        #define SETTIMEOFDAY             170
        #define SETUID                   146
        #define SETXATTR                   5
        #define SETXATTRAT               463
        #define SHMAT                    196
        #define SHMCTL                   195
        #define SHMDT                    197
        #define SHMGET                   194
        #define SHUTDOWN                 210
        #define SIGALTSTACK              132
        #define SIGNALFD4                 74
        #define SOCKET                   198
        #define SOCKETPAIR               199
        #define SPLICE                    76
        #define STATFS                    43
        #define STATMOUNT                457
        #define STATX                    291
        #define SWAPOFF                  225
        #define SWAPON                   224
        #define SYMLINKAT                 36
        #define SYNC                      81
        #define SYNC_FILE_RANGE           84
        #define SYNCFS                   267
        #define SYSINFO                  179
        #define SYSLOG                   116
        #define TEE                       77
        #define TGKILL                   131
        #define TIMER_CREATE             107
        #define TIMER_DELETE             111
        #define TIMERFD_CREATE            85
        #define TIMERFD_GETTIME           87
        #define TIMERFD_SETTIME           86
        #define TIMER_GETOVERRUN         109
        #define TIMER_GETTIME            108
        #define TIMER_SETTIME            110
        #define TIMES                    153
        #define TKILL                    130
        #define TRUNCATE                  45
        #define UMASK                    166
        #define UMOUNT                    39
        #define UNLINKAT                  35
        #define UNSHARE                   97
        #define USERFAULTFD              282
        #define UTIMENSAT                 88
        #define VHANGUP                   58
        #define VMSPLICE                  75
        #define WAIT4                    260
        #define WAITID                    95
        #define WRITE                     64
        #define WRITEV                    66
    #elif CMN_SYS_ARCH_X64
        #define ACCEPT4                  288
        #define ACCEPT                    43
        #define ACCESS                    21
        #define ACCT                     163
        #define ADD_KEY                  248
        #define ADJTIMEX                 159
        #define BIND                      49
        #define BPF                      321
        #define BRK                       12
        #define CACHESTAT                451
        #define CAPGET                   125
        #define CAPSET                   126
        #define CHDIR                     80
        #define CHROOT                   161
        #define CLOCK_ADJTIME            305
        #define CLOCK_GETRES             229
        #define CLOCK_GETTIME            228
        #define CLOCK_NANOSLEEP          230
        #define CLOCK_SETTIME            227
        #define CLONE3                   435
        #define CLONE                     56
        #define CLOSE                      3
        #define CLOSE_RANGE              436
        #define CONNECT                   42
        #define COPY_FILE_RANGE          326
        #define DELETE_MODULE            176
        #define DUP3                     292
        #define DUP                       32
        #define EPOLL_CREATE1            291
        #define EPOLL_CTL                233
        #define EPOLL_PWAIT2             441
        #define EPOLL_PWAIT              281
        #define EVENTFD2                 290
        #define EXECVE                    59
        #define EXECVEAT                 322
        #define EXIT                      60
        #define EXIT_GROUP               231
        #define FACCESSAT2               439
        #define FACCESSAT                269
        #define FALLOCATE                285
        #define FANOTIFY_INIT            300
        #define FANOTIFY_MARK            301
        #define FCHDIR                    81
        #define FCHMOD                    91
        #define FCHMODAT2                452
        #define FCHMODAT                 268
        #define FCHOWN                    93
        #define FCHOWNAT                 260
        #define FCNTL                     72
        #define FDATASYNC                 75
        #define FGETXATTR                193
        #define FILE_GETATTR             468
        #define FILE_SETATTR             469
        #define FINIT_MODULE             313
        #define FLISTXATTR               196
        #define FLOCK                     73
        #define FREMOVEXATTR             199
        #define FSCONFIG                 431
        #define FSETXATTR                190
        #define FSMOUNT                  432
        #define FSOPEN                   430
        #define FSPICK                   433
        #define FSTATFS                  138
        #define FSYNC                     74
        #define FTRUNCATE                 77
        #define FUTEX                    202
        #define FUTEX_REQUEUE            456
        #define FUTEX_WAIT               455
        #define FUTEX_WAITV              449
        #define FUTEX_WAKE               454
        #define GETCPU                   309
        #define GETCWD                    79
        #define GETDENTS64               217
        #define GETEGID                  108
        #define GETEUID                  107
        #define GETGID                   104
        #define GETGROUPS                115
        #define GETITIMER                 36
        #define GET_MEMPOLICY            239
        #define GETPEERNAME               52
        #define GETPGID                  121
        #define GETPID                    39
        #define GETPPID                  110
        #define GETPRIORITY              140
        #define GETRANDOM                318
        #define GETRESGID                120
        #define GETRESUID                118
        #define GETRLIMIT                 97
        #define GET_ROBUST_LIST          274
        #define GETRUSAGE                 98
        #define GETSID                   124
        #define GETSOCKNAME               51
        #define GETSOCKOPT                55
        #define GETTID                   186
        #define GETTIMEOFDAY              96
        #define GETUID                   102
        #define GETXATTR                 191
        #define GETXATTRAT               464
        #define INIT_MODULE              175
        #define INOTIFY_ADD_WATCH        254
        #define INOTIFY_INIT1            294
        #define INOTIFY_RM_WATCH         255
        #define IO_CANCEL                210
        #define IOCTL                     16
        #define IO_DESTROY               207
        #define IO_GETEVENTS             208
        #define IO_PGETEVENTS            333
        #define IOPRIO_GET               252
        #define IOPRIO_SET               251
        #define IO_SETUP                 206
        #define IO_SUBMIT                209
        #define IO_URING_ENTER           426
        #define IO_URING_REGISTER        427
        #define IO_URING_SETUP           425
        #define KCMP                     312
        #define KEXEC_FILE_LOAD          320
        #define KEXEC_LOAD               246
        #define KEYCTL                   250
        #define KILL                      62
        #define LANDLOCK_ADD_RULE        445
        #define LANDLOCK_CREATE_RULESET  444
        #define LANDLOCK_RESTRICT_SELF   446
        #define LGETXATTR                192
        #define LINKAT                   265
        #define LISTEN                    50
        #define LISTMOUNT                458
        #define LISTXATTR                194
        #define LISTXATTRAT              465
        #define LLISTXATTR               195
        #define LREMOVEXATTR             198
        #define LSEEK                      8
        #define LSETXATTR                189
        #define LSM_GET_SELF_ATTR        459
        #define LSM_LIST_MODULES         461
        #define LSM_SET_SELF_ATTR        460
        #define MADVISE                   28
        #define MAP_SHADOW_STACK         453
        #define MBIND                    237
        #define MEMBARRIER               324
        #define MEMFD_CREATE             319
        #define MEMFD_SECRET             447
        #define MIGRATE_PAGES            256
        #define MINCORE                   27
        #define MKDIRAT                  258
        #define MKNODAT                  259
        #define MLOCK                    149
        #define MLOCK2                   325
        #define MLOCKALL                 151
        #define MMAP                       9
        #define MOUNT                    165
        #define MOUNT_SETATTR            442
        #define MOVE_MOUNT               429
        #define MOVE_PAGES               279
        #define MPROTECT                  10
        #define MQ_GETSETATTR            245
        #define MQ_NOTIFY                244
        #define MQ_OPEN                  240
        #define MQ_TIMEDRECEIVE          243
        #define MQ_TIMEDSEND             242
        #define MQ_UNLINK                241
        #define MREMAP                    25
        #define MSEAL                    462
        #define MSGCTL                    71
        #define MSGGET                    68
        #define MSGRCV                    70
        #define MSGSND                    69
        #define MSYNC                     26
        #define MUNLOCK                  150
        #define MUNLOCKALL               152
        #define MUNMAP                    11
        #define NAME_TO_HANDLE_AT        303
        #define NANOSLEEP                 35
        #define NEWFSTAT                   5
        #define NEWFSTATAT               262
        #define NEWUNAME                  63
        #define OPENAT2                  437
        #define OPENAT                   257
        #define OPEN_BY_HANDLE_AT        304
        #define OPEN_TREE                428
        #define OPEN_TREE_ATTR           467
        #define PERF_EVENT_OPEN          298
        #define PERSONALITY              135
        #define PIDFD_GETFD              438
        #define PIDFD_OPEN               434
        #define PIDFD_SEND_SIGNAL        424
        #define PIPE2                    293
        #define PIVOT_ROOT               155
        #define PKEY_ALLOC               330
        #define PKEY_FREE                331
        #define PKEY_MPROTECT            329
        #define PPOLL                    271
        #define PRCTL                    157
        #define PREAD64                   17
        #define PREADV2                  327
        #define PREADV                   295
        #define PRLIMIT64                302
        #define PROCESS_MADVISE          440
        #define PROCESS_MRELEASE         448
        #define PROCESS_VM_READV         310
        #define PROCESS_VM_WRITEV        311
        #define PSELECT6                 270
        #define PTRACE                   101
        #define PWRITE64                  18
        #define PWRITEV2                 328
        #define PWRITEV                  296
        #define QUOTACTL                 179
        #define QUOTACTL_FD              443
        #define READ                       0
        #define READAHEAD                187
        #define READLINKAT               267
        #define READV                     19
        #define REBOOT                   169
        #define RECVFROM                  45
        #define RECVMMSG                 299
        #define RECVMSG                   47
        #define REMAP_FILE_PAGES         216
        #define REMOVEXATTR              197
        #define REMOVEXATTRAT            466
        #define RENAMEAT2                316
        #define RENAMEAT                 264
        #define REQUEST_KEY              249
        #define RESTART_SYSCALL          219
        #define RSEQ                     334
        #define RT_SIGACTION              13
        #define RT_SIGPENDING            127
        #define RT_SIGPROCMASK            14
        #define RT_SIGQUEUEINFO          129
        #define RT_SIGRETURN              15
        #define RT_SIGSUSPEND            130
        #define RT_SIGTIMEDWAIT          128
        #define RT_TGSIGQUEUEINFO        297
        #define SCHED_GETAFFINITY        204
        #define SCHED_GETATTR            315
        #define SCHED_GETPARAM           143
        #define SCHED_GET_PRIORITY_MAX   146
        #define SCHED_GET_PRIORITY_MIN   147
        #define SCHED_GETSCHEDULER       145
        #define SCHED_RR_GET_INTERVAL    148
        #define SCHED_SETAFFINITY        203
        #define SCHED_SETATTR            314
        #define SCHED_SETPARAM           142
        #define SCHED_SETSCHEDULER       144
        #define SCHED_YIELD               24
        #define SECCOMP                  317
        #define SEMCTL                    66
        #define SEMGET                    64
        #define SEMOP                     65
        #define SEMTIMEDOP               220
        #define SENDFILE64                40
        #define SENDMMSG                 307
        #define SENDMSG                   46
        #define SENDTO                    44
        #define SETDOMAINNAME            171
        #define SETFSGID                 123
        #define SETFSUID                 122
        #define SETGID                   106
        #define SETGROUPS                116
        #define SETHOSTNAME              170
        #define SETITIMER                 38
        #define SET_MEMPOLICY            238
        #define SET_MEMPOLICY_HOME_NODE  450
        #define SETNS                    308
        #define SETPGID                  109
        #define SETPRIORITY              141
        #define SETREGID                 114
        #define SETRESGID                119
        #define SETRESUID                117
        #define SETREUID                 113
        #define SETRLIMIT                160
        #define SET_ROBUST_LIST          273
        #define SETSID                   112
        #define SETSOCKOPT                54
        #define SET_TID_ADDRESS          218
        #define SETTIMEOFDAY             164
        #define SETUID                   105
        #define SETXATTR                 188
        #define SETXATTRAT               463
        #define SHMAT                     30
        #define SHMCTL                    31
        #define SHMDT                     67
        #define SHMGET                    29
        #define SHUTDOWN                  48
        #define SIGALTSTACK              131
        #define SIGNALFD4                289
        #define SOCKET                    41
        #define SOCKETPAIR                53
        #define SPLICE                   275
        #define STATFS                   137
        #define STATMOUNT                457
        #define STATX                    332
        #define SWAPOFF                  168
        #define SWAPON                   167
        #define SYMLINKAT                266
        #define SYNC                     162
        #define SYNC_FILE_RANGE          277
        #define SYNCFS                   306
        #define SYSINFO                   99
        #define SYSLOG                   103
        #define TEE                      276
        #define TGKILL                   234
        #define TIMER_CREATE             222
        #define TIMER_DELETE             226
        #define TIMERFD_CREATE           283
        #define TIMERFD_GETTIME          287
        #define TIMERFD_SETTIME          286
        #define TIMER_GETOVERRUN         225
        #define TIMER_GETTIME            224
        #define TIMER_SETTIME            223
        #define TIMES                    100
        #define TKILL                    200
        #define TRUNCATE                  76
        #define UMASK                     95
        #define UMOUNT                   166
        #define UNLINKAT                 263
        #define UNSHARE                  272
        #define USERFAULTFD              323
        #define UTIMENSAT                280
        #define VFORK                     58
        #define VHANGUP                  153
        #define VMSPLICE                 278
        #define WAIT4                     61
        #define WAITID                   247
        #define WRITE                      1
        #define WRITEV                    20
    #endif
}