#pragma once
#include "sys/platform/Arch.hpp"

namespace cmn::syscall
{
    #if CMN_SYS_ARCH_ARM64
        #define ACCEPT_CONNECTION                         202
        #define ACCEPT_CONNECTION_WITH_FLAGS              242
        #define CONFIGURE_PROCESS_ACCOUNTING               89
        #define ADD_KEY_TO_KEYRING                        217
        #define ADJUST_SYSTEM_CLOCK                       171
        #define BIND_SOCKET                               200
        #define EXECUTE_BPF_COMMAND                       280
        #define BRK                                       214
        #define QUERY_PAGE_CACHE                          451
        #define GET_THREAD_CAPABILITIES                    90
        #define SET_THREAD_CAPABILITIES                    91
        #define CHANGE_WORKING_DIRECTORY                   49
        #define CHANGE_ROOT_DIRECTORY                      51
        #define ADJUST_CLOCK                              266
        #define GET_CLOCK_RESOLUTION                      114
        #define GET_CLOCK_TIME                            113
        #define SLEEP_ON_CLOCK                            115
        #define SET_CLOCK_TIME                            112
        #define CREATE_CHILD_TASK                         220
        #define CREATE_CHILD_TASK_WITH_OPTIONS            435
        #define CLOSE_FILE_DESCRIPTOR                      57
        #define CLOSE_FILE_DESCRIPTOR_RANGE               436
        #define CONNECT_SOCKET                            203
        #define COPY_FILE_DATA                            285
        #define UNLOAD_KERNEL_MODULE                      106
        #define DUPLICATE_FILE_DESCRIPTOR                  23
        #define DUPLICATE_FILE_DESCRIPTOR_TO               24
        #define CREATE_EPOLL                               20
        #define CONFIGURE_EPOLL_WATCH                      21
        #define WAIT_FOR_EPOLL_EVENTS                      22
        #define WAIT_FOR_EPOLL_EVENTS_PRECISE             441
        #define CREATE_EVENT_COUNTER                       19
        #define EXECUTE_PROGRAM                           221
        #define EXECUTE_PROGRAM_AT                        281
        #define EXIT_THREAD                                93
        #define EXIT_PROCESS                               94
        #define CHECK_FILE_ACCESS_AT_WITH_FLAGS           439
        #define CHECK_FILE_ACCESS_AT                       48
        #define ALLOCATE_FILE_SPACE                        47
        #define CREATE_FANOTIFY_GROUP                     262
        #define MODIFY_FANOTIFY_MARK                      263
        #define CHANGE_WORKING_DIRECTORY_FROM_DESCRIPTOR   50
        #define CHANGE_FILE_MODE                           52
        #define CHANGE_FILE_MODE_AT_WITH_FLAGS            452
        #define CHANGE_FILE_MODE_AT                        53
        #define CHANGE_FILE_OWNER                          55
        #define CHANGE_FILE_OWNER_AT                       54
        #define CONTROL_FILE_DESCRIPTOR                    25
        #define SYNCHRONIZE_FILE_DATA                      83
        #define GET_EXTENDED_ATTRIBUTE                     10
        #define GET_FILESYSTEM_FILE_ATTRIBUTES            468
        #define SET_FILESYSTEM_FILE_ATTRIBUTES            469
        #define LOAD_KERNEL_MODULE_FROM_DESCRIPTOR        273
        #define LIST_EXTENDED_ATTRIBUTES                   13
        #define MANAGE_FILE_LOCK                           32
        #define REMOVE_EXTENDED_ATTRIBUTE                  16
        #define CONFIGURE_FILESYSTEM_CONTEXT              431
        #define SET_EXTENDED_ATTRIBUTE                      7
        #define CREATE_DETACHED_MOUNT                     432
        #define CREATE_FILESYSTEM_CONTEXT                 430
        #define OPEN_MOUNT_CONFIGURATION                  433
        #define GET_FILESYSTEM_STATISTICS                  44
        #define SYNCHRONIZE_FILE                           82
        #define RESIZE_FILE                                46
        #define PERFORM_FUTEX_OPERATION                    98
        #define REQUEUE_FUTEX_WAITERS                     456
        #define WAIT_ON_FUTEX                             455
        #define WAIT_ON_FUTEX_SET                         449
        #define WAKE_FUTEX_WAITERS                        454
        #define GET_CURRENT_CPU                           168
        #define GET_WORKING_DIRECTORY                      17
        #define READ_DIRECTORY_ENTRIES                     61
        #define GET_EFFECTIVE_GROUP_ID                    177
        #define GET_EFFECTIVE_USER_ID                     175
        #define GET_REAL_GROUP_ID                         176
        #define GET_SUPPLEMENTARY_GROUPS                  158
        #define GET_INTERVAL_TIMER                        102
        #define GET_MEMORY_POLICY                         236
        #define GET_PEER_SOCKET_ADDRESS                   205
        #define GET_PROCESS_GROUP_ID                      155
        #define GET_PROCESS_ID                            172
        #define GET_PARENT_PROCESS_ID                     173
        #define GET_NICE_PRIORITY                         141
        #define GET_RANDOM_BYTES                          278
        #define GET_GROUP_CREDENTIALS                     150
        #define GET_USER_CREDENTIALS                      148
        #define GET_RESOURCE_LIMIT                        163
        #define GET_THREAD_ROBUST_FUTEX_LIST              100
        #define GET_RESOURCE_USAGE                        165
        #define GET_SESSION_ID                            156
        #define GET_LOCAL_SOCKET_ADDRESS                  204
        #define GET_SOCKET_OPTION                         209
        #define GET_THREAD_ID                             178
        #define GET_WALL_CLOCK_TIME                       169
        #define GET_REAL_USER_ID                          174
        #define GET_EXTENDED_ATTRIBUTE                      8
        #define GET_EXTENDED_ATTRIBUTE_AT                 464
        #define LOAD_KERNEL_MODULE_FROM_MEMORY            105
        #define ADD_INOTIFY_WATCH                          27
        #define CREATE_INOTIFY                             26
        #define REMOVE_INOTIFY_WATCH                       28
        #define CANCEL_ASYNC_IO                             3
        #define PERFORM_IO_CONTROL                         29
        #define DESTROY_ASYNC_IO_CONTEXT                    1
        #define GET_ASYNC_IO_COMPLETIONS                    4
        #define GET_ASYNC_IO_COMPLETIONS_WITH_SIGNAL_MASK 292
        #define GET_IO_PRIORITY                            31
        #define SET_IO_PRIORITY                            30
        #define CREATE_ASYNC_IO_CONTEXT                     0
        #define SUBMIT_ASYNC_IO                             2
        #define PROCESS_IO_URING_QUEUE                    426
        #define CONFIGURE_IO_URING                        427
        #define CREATE_IO_URING                           425
        #define COMPARE_PROCESS_RESOURCES                 272
        #define LOAD_KERNEL_IMAGE_FROM_FILES              294
        #define LOAD_KERNEL_IMAGE                         104
        #define CONTROL_KERNEL_KEYS                       219
        #define SEND_SIGNAL                               129
        #define ADD_LANDLOCK_RULE                         445
        #define CREATE_LANDLOCK_RULESET                   444
        #define APPLY_LANDLOCK_RULESET                    446
        #define GET_EXTENDED_ATTRIBUTE_NO_FOLLOW            9
        #define CREATE_HARD_LINK_AT                        37
        #define LISTEN_FOR_CONNECTIONS                    201
        #define LIST_MOUNT_IDS                            458
        #define LIST_EXTENDED_ATTRIBUTES                   11
        #define LIST_EXTENDED_ATTRIBUTES_AT               465
        #define LIST_EXTENDED_ATTRIBUTES_NO_FOLLOW         12
        #define REMOVE_EXTENDED_ATTRIBUTE_NO_FOLLOW        15
        #define SEEK_FILE                                  62
        #define SET_EXTENDED_ATTRIBUTE_NO_FOLLOW            6
        #define GET_SECURITY_ATTRIBUTES                   459
        #define LIST_SECURITY_MODULES                     461
        #define SET_SECURITY_ATTRIBUTE                    460
        #define ADVISE_MEMORY                             233
        #define CREATE_SHADOW_STACK                       453
        #define BIND_MEMORY_POLICY                        235
        #define ISSUE_MEMORY_BARRIER                      283
        #define CREATE_MEMORY_FILE                        279
        #define CREATE_SECRET_MEMORY                      447
        #define MIGRATE_PROCESS_PAGES                     238
        #define QUERY_MEMORY_RESIDENCY                    232
        #define CREATE_DIRECTORY_AT                        34
        #define CREATE_FILESYSTEM_NODE_AT                  33
        #define LOCK_MEMORY_WITH_FLAGS                    284
        #define LOCK_MEMORY                               228
        #define LOCK_PROCESS_MEMORY                       230
        #define MAP_MEMORY                                222
        #define MOUNT_FILESYSTEM                           40
        #define SET_MOUNT_ATTRIBUTES                      442
        #define MOVE_MOUNT                                429
        #define MOVE_PROCESS_PAGES                        239
        #define SET_MEMORY_PROTECTION                     226
        #define CONFIGURE_MESSAGE_QUEUE_ATTRIBUTES        185
        #define CONFIGURE_MESSAGE_QUEUE_NOTIFICATION      184
        #define OPEN_MESSAGE_QUEUE                        180
        #define RECEIVE_MESSAGE_UNTIL                     183
        #define SEND_MESSAGE_UNTIL                        182
        #define UNLINK_MESSAGE_QUEUE                      181
        #define REMAP_MEMORY                              216
        #define SEAL_MEMORY                               462
        #define CONTROL_MESSAGE_QUEUE                     187
        #define GET_MESSAGE_QUEUE                         186
        #define RECEIVE_QUEUE_MESSAGE                     188
        #define SEND_QUEUE_MESSAGE                        189
        #define SYNCHRONIZE_MEMORY_MAPPING                227
        #define UNLOCK_MEMORY                             229
        #define UNLOCK_PROCESS_MEMORY                     231
        #define UNMAP_MEMORY                              215
        #define GET_FILE_HANDLE_AT                        264
        #define SLEEP_FOR_DURATION                        101
        #define GET_DESCRIPTOR_STATUS                      80
        #define GET_PATH_STATUS_AT                         79
        #define GET_SYSTEM_IDENTIFICATION                 160
        #define OPEN_FILE_AT_WITH_OPTIONS                 437
        #define OPEN_FILE_AT                               56
        #define OPEN_FILE_BY_HANDLE                       265
        #define OPEN_MOUNT_TREE                           428
        #define OPEN_MOUNT_TREE_WITH_ATTRIBUTES           467
        #define OPEN_PERFORMANCE_EVENT                    241
        #define CONFIGURE_PROCESS_PERSONALITY              92
        #define DUPLICATE_PROCESS_DESCRIPTOR              438
        #define OPEN_PROCESS_DESCRIPTOR                   434
        #define SIGNAL_PROCESS                            424
        #define CREATE_PIPE                                59
        #define CHANGE_ROOT_MOUNT                          41
        #define ALLOCATE_MEMORY_PROTECTION_KEY            289
        #define FREE_MEMORY_PROTECTION_KEY                290
        #define SET_MEMORY_PROTECTION_KEY                 288
        #define POLL_FILE_DESCRIPTORS                      73
        #define CONTROL_PROCESS                           167
        #define READ_FILE_AT_OFFSET                        67
        #define READ_FILE_VECTORS_AT_OFFSET_WITH_FLAGS    286
        #define READ_FILE_VECTORS_AT_OFFSET                69
        #define CONFIGURE_PROCESS_RESOURCE_LIMIT          261
        #define ADVISE_PROCESS_MEMORY                     440
        #define RELEASE_PROCESS_MEMORY                    448
        #define READ_PROCESS_MEMORY                       270
        #define WRITE_PROCESS_MEMORY                      271
        #define WAIT_FOR_DESCRIPTOR_EVENTS                 72
        #define CONTROL_PROCESS_TRACE                     117
        #define WRITE_FILE_AT_OFFSET                       68
        #define WRITE_FILE_VECTORS_AT_OFFSET_WITH_FLAGS   287
        #define WRITE_FILE_VECTORS_AT_OFFSET               70
        #define CONTROL_FILESYSTEM_QUOTA                   60
        #define CONTROL_FILESYSTEM_QUOTA_BY_DESCRIPTOR    443
        #define READ_DATA                                  63
        #define PRELOAD_FILE_DATA                         213
        #define READ_SYMBOLIC_LINK_AT                      78
        #define READ_DATA_VECTORS                          65
        #define CONTROL_SYSTEM_POWER                      142
        #define RECEIVE_SOCKET_DATA                       207
        #define RECEIVE_SOCKET_MESSAGES                   243
        #define RECEIVE_SOCKET_MESSAGE                    212
        #define REMAP_FILE_PAGES                          234
        #define REMOVE_EXTENDED_ATTRIBUTE                  14
        #define REMOVE_EXTENDED_ATTRIBUTE_AT              466
        #define RENAME_PATH_AT_WITH_FLAGS                 276
        #define RENAME_PATH_AT                             38
        #define REQUEST_KERNEL_KEY                        218
        #define RESTART_INTERRUPTED_SYSCALL               128
        #define CONFIGURE_RESTARTABLE_SEQUENCE            293
        #define CONFIGURE_SIGNAL_ACTION                   134
        #define GET_PENDING_SIGNALS                       136
        #define CONFIGURE_SIGNAL_MASK                     135
        #define QUEUE_PROCESS_SIGNAL                      138
        #define RETURN_FROM_SIGNAL_HANDLER                139
        #define SUSPEND_UNTIL_SIGNAL                      133
        #define WAIT_FOR_SIGNAL                           137
        #define QUEUE_THREAD_SIGNAL                       240
        #define GET_CPU_AFFINITY                          123
        #define GET_SCHEDULER_ATTRIBUTES                  275
        #define GET_SCHEDULER_PARAMETERS                  121
        #define GET_MAXIMUM_SCHEDULER_PRIORITY            125
        #define GET_MINIMUM_SCHEDULER_PRIORITY            126
        #define GET_SCHEDULER_POLICY                      120
        #define GET_ROUND_ROBIN_INTERVAL                  127
        #define SET_CPU_AFFINITY                          122
        #define SET_SCHEDULER_ATTRIBUTES                  274
        #define SET_SCHEDULER_PARAMETERS                  118
        #define SET_SCHEDULER_POLICY                      119
        #define YIELD_PROCESSOR                           124
        #define CONFIGURE_SYSCALL_FILTERING               277
        #define CONTROL_SEMAPHORE_SET                     191
        #define GET_SEMAPHORE_SET                         190
        #define PERFORM_SEMAPHORE_OPERATIONS              193
        #define PERFORM_SEMAPHORE_OPERATIONS_UNTIL        192
        #define COPY_FILE_TO_DESCRIPTOR                    71
        #define SEND_SOCKET_MESSAGES                      269
        #define SEND_SOCKET_MESSAGE                       211
        #define SEND_SOCKET_DATA                          206
        #define SET_SYSTEM_DOMAIN_NAME                    162
        #define SET_FILESYSTEM_GROUP_ID                   152
        #define SET_FILESYSTEM_USER_ID                    151
        #define SET_GROUP_ID                              144
        #define SET_SUPPLEMENTARY_GROUPS                  159
        #define SET_SYSTEM_HOST_NAME                      161
        #define SET_INTERVAL_TIMER                        103
        #define SET_MEMORY_POLICY                         237
        #define SET_MEMORY_HOME_NODE                      450
        #define JOIN_NAMESPACE                            268
        #define SET_PROCESS_GROUP                         154
        #define SET_NICE_PRIORITY                         140
        #define SET_REAL_EFFECTIVE_GROUP_IDS              143
        #define SET_GROUP_CREDENTIALS                     149
        #define SET_USER_CREDENTIALS                      147
        #define SET_REAL_EFFECTIVE_USER_IDS               145
        #define SET_RESOURCE_LIMIT                        164
        #define SET_THREAD_ROBUST_FUTEX_LIST               99
        #define CREATE_PROCESS_SESSION                    157
        #define SET_SOCKET_OPTION                         208
        #define SET_THREAD_ID_ADDRESS                      96
        #define SET_WALL_CLOCK_TIME                       170
        #define SET_USER_ID                               146
        #define SET_EXTENDED_ATTRIBUTE                      5
        #define SET_EXTENDED_ATTRIBUTE_AT                 463
        #define ATTACH_SHARED_MEMORY                      196
        #define CONTROL_SHARED_MEMORY                     195
        #define DETACH_SHARED_MEMORY                      197
        #define GET_SHARED_MEMORY                         194
        #define SHUTDOWN_SOCKET                           210
        #define CONFIGURE_SIGNAL_STACK                    132
        #define CONFIGURE_SIGNAL_DESCRIPTOR                74
        #define CREATE_SOCKET                             198
        #define CREATE_SOCKET_PAIR                        199
        #define SPLICE_DATA                                76
        #define GET_FILESYSTEM_STATISTICS                  43
        #define GET_MOUNT_INFORMATION                     457
        #define GET_EXTENDED_FILE_STATUS                  291
        #define DISABLE_SWAP                              225
        #define ENABLE_SWAP                               224
        #define CREATE_SYMBOLIC_LINK_AT                    36
        #define SYNCHRONIZE_FILESYSTEMS                    81
        #define SYNCHRONIZE_FILE_RANGE                     84
        #define SYNCHRONIZE_FILESYSTEM                    267
        #define GET_SYSTEM_INFORMATION                    179
        #define CONTROL_KERNEL_LOG                        116
        #define DUPLICATE_PIPE_DATA                        77
        #define SEND_THREAD_SIGNAL                        131
        #define CREATE_PROCESS_TIMER                      107
        #define DELETE_PROCESS_TIMER                      111
        #define CREATE_TIMER_DESCRIPTOR                    85
        #define GET_TIMER_DESCRIPTOR                       87
        #define SET_TIMER_DESCRIPTOR                       86
        #define GET_TIMER_OVERRUN_COUNT                   109
        #define GET_PROCESS_TIMER                         108
        #define SET_PROCESS_TIMER                         110
        #define GET_PROCESS_TIMES                         153
        #define SEND_SIGNAL_TO_THREAD                     130
        #define RESIZE_FILE_AT_PATH                        45
        #define SET_FILE_CREATION_MASK                    166
        #define UNMOUNT_FILESYSTEM                         39
        #define REMOVE_PATH_AT                             35
        #define UNSHARE_PROCESS_RESOURCES                  97
        #define CREATE_USER_FAULT_DESCRIPTOR              282
        #define SET_FILE_TIMES_AT                          88
        #define HANGUP_VIRTUAL_TERMINAL                    58
        #define SPLICE_MEMORY_TO_PIPE                      75
        #define WAIT_FOR_CHILD                            260
        #define WAIT_FOR_CHILD_EVENT                       95
        #define WRITE_DATA                                 64
        #define WRITE_DATA_VECTORS                         66
    #endif
    #if CMN_SYS_ARCH_X64
        #define ACCEPT_CONNECTION                         288
        #define ACCEPT_CONNECTION_WITH_FLAGS               43
        #define CONFIGURE_PROCESS_ACCOUNTING              163
        #define ADD_KEY_TO_KEYRING                        248
        #define ADJUST_SYSTEM_CLOCK                       159
        #define BIND_SOCKET                                49
        #define EXECUTE_BPF_COMMAND                       321
        #define BRK                                        12
        #define QUERY_PAGE_CACHE                          451
        #define GET_THREAD_CAPABILITIES                   125
        #define SET_THREAD_CAPABILITIES                   126
        #define CHANGE_WORKING_DIRECTORY                   80
        #define CHANGE_ROOT_DIRECTORY                     161
        #define ADJUST_CLOCK                              305
        #define GET_CLOCK_RESOLUTION                      229
        #define GET_CLOCK_TIME                            228
        #define SLEEP_ON_CLOCK                            230
        #define SET_CLOCK_TIME                            227
        #define CREATE_CHILD_TASK                         435
        #define CREATE_CHILD_TASK_WITH_OPTIONS             56
        #define CLOSE_FILE_DESCRIPTOR                       3
        #define CLOSE_FILE_DESCRIPTOR_RANGE               436
        #define CONNECT_SOCKET                             42
        #define COPY_FILE_DATA                            326
        #define UNLOAD_KERNEL_MODULE                      176
        #define DUPLICATE_FILE_DESCRIPTOR                 292
        #define DUPLICATE_FILE_DESCRIPTOR_TO               32
        #define CREATE_EPOLL                              291
        #define CONFIGURE_EPOLL_WATCH                     233
        #define WAIT_FOR_EPOLL_EVENTS                     441
        #define WAIT_FOR_EPOLL_EVENTS_PRECISE             281
        #define CREATE_EVENT_COUNTER                      290
        #define EXECUTE_PROGRAM                            59
        #define EXECUTE_PROGRAM_AT                        322
        #define EXIT_THREAD                                60
        #define EXIT_PROCESS                              231
        #define CHECK_FILE_ACCESS_AT_WITH_FLAGS           439
        #define CHECK_FILE_ACCESS_AT                      269
        #define ALLOCATE_FILE_SPACE                       285
        #define CREATE_FANOTIFY_GROUP                     300
        #define MODIFY_FANOTIFY_MARK                      301
        #define CHANGE_WORKING_DIRECTORY_FROM_DESCRIPTOR   81
        #define CHANGE_FILE_MODE                           91
        #define CHANGE_FILE_MODE_AT_WITH_FLAGS            452
        #define CHANGE_FILE_MODE_AT                       268
        #define CHANGE_FILE_OWNER                          93
        #define CHANGE_FILE_OWNER_AT                      260
        #define CONTROL_FILE_DESCRIPTOR                    72
        #define SYNCHRONIZE_FILE_DATA                      75
        #define GET_EXTENDED_ATTRIBUTE                    193
        #define GET_FILESYSTEM_FILE_ATTRIBUTES            468
        #define SET_FILESYSTEM_FILE_ATTRIBUTES            469
        #define LOAD_KERNEL_MODULE_FROM_DESCRIPTOR        313
        #define LIST_EXTENDED_ATTRIBUTES                  196
        #define MANAGE_FILE_LOCK                           73
        #define REMOVE_EXTENDED_ATTRIBUTE                 199
        #define CONFIGURE_FILESYSTEM_CONTEXT              431
        #define SET_EXTENDED_ATTRIBUTE                    190
        #define CREATE_DETACHED_MOUNT                     432
        #define CREATE_FILESYSTEM_CONTEXT                 430
        #define OPEN_MOUNT_CONFIGURATION                  433
        #define GET_FILESYSTEM_STATISTICS                 138
        #define SYNCHRONIZE_FILE                           74
        #define RESIZE_FILE                                77
        #define PERFORM_FUTEX_OPERATION                   202
        #define REQUEUE_FUTEX_WAITERS                     456
        #define WAIT_ON_FUTEX                             455
        #define WAIT_ON_FUTEX_SET                         449
        #define WAKE_FUTEX_WAITERS                        454
        #define GET_CURRENT_CPU                           309
        #define GET_WORKING_DIRECTORY                      79
        #define READ_DIRECTORY_ENTRIES                    217
        #define GET_EFFECTIVE_GROUP_ID                    108
        #define GET_EFFECTIVE_USER_ID                     107
        #define GET_REAL_GROUP_ID                         104
        #define GET_SUPPLEMENTARY_GROUPS                  115
        #define GET_INTERVAL_TIMER                         36
        #define GET_MEMORY_POLICY                         239
        #define GET_PEER_SOCKET_ADDRESS                    52
        #define GET_PROCESS_GROUP_ID                      121
        #define GET_PROCESS_ID                             39
        #define GET_PARENT_PROCESS_ID                     110
        #define GET_NICE_PRIORITY                         140
        #define GET_RANDOM_BYTES                          318
        #define GET_GROUP_CREDENTIALS                     120
        #define GET_USER_CREDENTIALS                      118
        #define GET_RESOURCE_LIMIT                         97
        #define GET_THREAD_ROBUST_FUTEX_LIST              274
        #define GET_RESOURCE_USAGE                         98
        #define GET_SESSION_ID                            124
        #define GET_LOCAL_SOCKET_ADDRESS                   51
        #define GET_SOCKET_OPTION                          55
        #define GET_THREAD_ID                             186
        #define GET_WALL_CLOCK_TIME                        96
        #define GET_REAL_USER_ID                          102
        #define GET_EXTENDED_ATTRIBUTE                    191
        #define GET_EXTENDED_ATTRIBUTE_AT                 464
        #define LOAD_KERNEL_MODULE_FROM_MEMORY            175
        #define ADD_INOTIFY_WATCH                         254
        #define CREATE_INOTIFY                            294
        #define REMOVE_INOTIFY_WATCH                      255
        #define CANCEL_ASYNC_IO                           210
        #define PERFORM_IO_CONTROL                         16
        #define DESTROY_ASYNC_IO_CONTEXT                  207
        #define GET_ASYNC_IO_COMPLETIONS                  208
        #define GET_ASYNC_IO_COMPLETIONS_WITH_SIGNAL_MASK 333
        #define GET_IO_PRIORITY                           252
        #define SET_IO_PRIORITY                           251
        #define CREATE_ASYNC_IO_CONTEXT                   206
        #define SUBMIT_ASYNC_IO                           209
        #define PROCESS_IO_URING_QUEUE                    426
        #define CONFIGURE_IO_URING                        427
        #define CREATE_IO_URING                           425
        #define COMPARE_PROCESS_RESOURCES                 312
        #define LOAD_KERNEL_IMAGE_FROM_FILES              320
        #define LOAD_KERNEL_IMAGE                         246
        #define CONTROL_KERNEL_KEYS                       250
        #define SEND_SIGNAL                                62
        #define ADD_LANDLOCK_RULE                         445
        #define CREATE_LANDLOCK_RULESET                   444
        #define APPLY_LANDLOCK_RULESET                    446
        #define GET_EXTENDED_ATTRIBUTE_NO_FOLLOW          192
        #define CREATE_HARD_LINK_AT                       265
        #define LISTEN_FOR_CONNECTIONS                     50
        #define LIST_MOUNT_IDS                            458
        #define LIST_EXTENDED_ATTRIBUTES                  194
        #define LIST_EXTENDED_ATTRIBUTES_AT               465
        #define LIST_EXTENDED_ATTRIBUTES_NO_FOLLOW        195
        #define REMOVE_EXTENDED_ATTRIBUTE_NO_FOLLOW       198
        #define SEEK_FILE                                   8
        #define SET_EXTENDED_ATTRIBUTE_NO_FOLLOW          189
        #define GET_SECURITY_ATTRIBUTES                   459
        #define LIST_SECURITY_MODULES                     461
        #define SET_SECURITY_ATTRIBUTE                    460
        #define ADVISE_MEMORY                              28
        #define CREATE_SHADOW_STACK                       453
        #define BIND_MEMORY_POLICY                        237
        #define ISSUE_MEMORY_BARRIER                      324
        #define CREATE_MEMORY_FILE                        319
        #define CREATE_SECRET_MEMORY                      447
        #define MIGRATE_PROCESS_PAGES                     256
        #define QUERY_MEMORY_RESIDENCY                     27
        #define CREATE_DIRECTORY_AT                       258
        #define CREATE_FILESYSTEM_NODE_AT                 259
        #define LOCK_MEMORY_WITH_FLAGS                    149
        #define LOCK_MEMORY                               325
        #define LOCK_PROCESS_MEMORY                       151
        #define MAP_MEMORY                                  9
        #define MOUNT_FILESYSTEM                          165
        #define SET_MOUNT_ATTRIBUTES                      442
        #define MOVE_MOUNT                                429
        #define MOVE_PROCESS_PAGES                        279
        #define SET_MEMORY_PROTECTION                      10
        #define CONFIGURE_MESSAGE_QUEUE_ATTRIBUTES        245
        #define CONFIGURE_MESSAGE_QUEUE_NOTIFICATION      244
        #define OPEN_MESSAGE_QUEUE                        240
        #define RECEIVE_MESSAGE_UNTIL                     243
        #define SEND_MESSAGE_UNTIL                        242
        #define UNLINK_MESSAGE_QUEUE                      241
        #define REMAP_MEMORY                               25
        #define SEAL_MEMORY                               462
        #define CONTROL_MESSAGE_QUEUE                      71
        #define GET_MESSAGE_QUEUE                          68
        #define RECEIVE_QUEUE_MESSAGE                      70
        #define SEND_QUEUE_MESSAGE                         69
        #define SYNCHRONIZE_MEMORY_MAPPING                 26
        #define UNLOCK_MEMORY                             150
        #define UNLOCK_PROCESS_MEMORY                     152
        #define UNMAP_MEMORY                               11
        #define GET_FILE_HANDLE_AT                        303
        #define SLEEP_FOR_DURATION                         35
        #define GET_DESCRIPTOR_STATUS                       5
        #define GET_PATH_STATUS_AT                        262
        #define GET_SYSTEM_IDENTIFICATION                  63
        #define OPEN_FILE_AT_WITH_OPTIONS                 437
        #define OPEN_FILE_AT                              257
        #define OPEN_FILE_BY_HANDLE                       304
        #define OPEN_MOUNT_TREE                           428
        #define OPEN_MOUNT_TREE_WITH_ATTRIBUTES           467
        #define OPEN_PERFORMANCE_EVENT                    298
        #define CONFIGURE_PROCESS_PERSONALITY             135
        #define DUPLICATE_PROCESS_DESCRIPTOR              438
        #define OPEN_PROCESS_DESCRIPTOR                   434
        #define SIGNAL_PROCESS                            424
        #define CREATE_PIPE                               293
        #define CHANGE_ROOT_MOUNT                         155
        #define ALLOCATE_MEMORY_PROTECTION_KEY            330
        #define FREE_MEMORY_PROTECTION_KEY                331
        #define SET_MEMORY_PROTECTION_KEY                 329
        #define POLL_FILE_DESCRIPTORS                     271
        #define CONTROL_PROCESS                           157
        #define READ_FILE_AT_OFFSET                        17
        #define READ_FILE_VECTORS_AT_OFFSET_WITH_FLAGS    327
        #define READ_FILE_VECTORS_AT_OFFSET               295
        #define CONFIGURE_PROCESS_RESOURCE_LIMIT          302
        #define ADVISE_PROCESS_MEMORY                     440
        #define RELEASE_PROCESS_MEMORY                    448
        #define READ_PROCESS_MEMORY                       310
        #define WRITE_PROCESS_MEMORY                      311
        #define WAIT_FOR_DESCRIPTOR_EVENTS                270
        #define CONTROL_PROCESS_TRACE                     101
        #define WRITE_FILE_AT_OFFSET                       18
        #define WRITE_FILE_VECTORS_AT_OFFSET_WITH_FLAGS   328
        #define WRITE_FILE_VECTORS_AT_OFFSET              296
        #define CONTROL_FILESYSTEM_QUOTA                  179
        #define CONTROL_FILESYSTEM_QUOTA_BY_DESCRIPTOR    443
        #define READ_DATA                                   0
        #define PRELOAD_FILE_DATA                         187
        #define READ_SYMBOLIC_LINK_AT                     267
        #define READ_DATA_VECTORS                          19
        #define CONTROL_SYSTEM_POWER                      169
        #define RECEIVE_SOCKET_DATA                        45
        #define RECEIVE_SOCKET_MESSAGES                   299
        #define RECEIVE_SOCKET_MESSAGE                     47
        #define REMAP_FILE_PAGES                          216
        #define REMOVE_EXTENDED_ATTRIBUTE                 197
        #define REMOVE_EXTENDED_ATTRIBUTE_AT              466
        #define RENAME_PATH_AT_WITH_FLAGS                 316
        #define RENAME_PATH_AT                            264
        #define REQUEST_KERNEL_KEY                        249
        #define RESTART_INTERRUPTED_SYSCALL               219
        #define CONFIGURE_RESTARTABLE_SEQUENCE            334
        #define CONFIGURE_SIGNAL_ACTION                    13
        #define GET_PENDING_SIGNALS                       127
        #define CONFIGURE_SIGNAL_MASK                      14
        #define QUEUE_PROCESS_SIGNAL                      129
        #define RETURN_FROM_SIGNAL_HANDLER                 15
        #define SUSPEND_UNTIL_SIGNAL                      130
        #define WAIT_FOR_SIGNAL                           128
        #define QUEUE_THREAD_SIGNAL                       297
        #define GET_CPU_AFFINITY                          204
        #define GET_SCHEDULER_ATTRIBUTES                  315
        #define GET_SCHEDULER_PARAMETERS                  143
        #define GET_MAXIMUM_SCHEDULER_PRIORITY            146
        #define GET_MINIMUM_SCHEDULER_PRIORITY            147
        #define GET_SCHEDULER_POLICY                      145
        #define GET_ROUND_ROBIN_INTERVAL                  148
        #define SET_CPU_AFFINITY                          203
        #define SET_SCHEDULER_ATTRIBUTES                  314
        #define SET_SCHEDULER_PARAMETERS                  142
        #define SET_SCHEDULER_POLICY                      144
        #define YIELD_PROCESSOR                            24
        #define CONFIGURE_SYSCALL_FILTERING               317
        #define CONTROL_SEMAPHORE_SET                      66
        #define GET_SEMAPHORE_SET                          64
        #define PERFORM_SEMAPHORE_OPERATIONS               65
        #define PERFORM_SEMAPHORE_OPERATIONS_UNTIL        220
        #define COPY_FILE_TO_DESCRIPTOR                    40
        #define SEND_SOCKET_MESSAGES                      307
        #define SEND_SOCKET_MESSAGE                        46
        #define SEND_SOCKET_DATA                           44
        #define SET_SYSTEM_DOMAIN_NAME                    171
        #define SET_FILESYSTEM_GROUP_ID                   123
        #define SET_FILESYSTEM_USER_ID                    122
        #define SET_GROUP_ID                              106
        #define SET_SUPPLEMENTARY_GROUPS                  116
        #define SET_SYSTEM_HOST_NAME                      170
        #define SET_INTERVAL_TIMER                         38
        #define SET_MEMORY_POLICY                         238
        #define SET_MEMORY_HOME_NODE                      450
        #define JOIN_NAMESPACE                            308
        #define SET_PROCESS_GROUP                         109
        #define SET_NICE_PRIORITY                         141
        #define SET_REAL_EFFECTIVE_GROUP_IDS              114
        #define SET_GROUP_CREDENTIALS                     119
        #define SET_USER_CREDENTIALS                      117
        #define SET_REAL_EFFECTIVE_USER_IDS               113
        #define SET_RESOURCE_LIMIT                        160
        #define SET_THREAD_ROBUST_FUTEX_LIST              273
        #define CREATE_PROCESS_SESSION                    112
        #define SET_SOCKET_OPTION                          54
        #define SET_THREAD_ID_ADDRESS                     218
        #define SET_WALL_CLOCK_TIME                       164
        #define SET_USER_ID                               105
        #define SET_EXTENDED_ATTRIBUTE                    188
        #define SET_EXTENDED_ATTRIBUTE_AT                 463
        #define ATTACH_SHARED_MEMORY                       30
        #define CONTROL_SHARED_MEMORY                      31
        #define DETACH_SHARED_MEMORY                       67
        #define GET_SHARED_MEMORY                          29
        #define SHUTDOWN_SOCKET                            48
        #define CONFIGURE_SIGNAL_STACK                    131
        #define CONFIGURE_SIGNAL_DESCRIPTOR               289
        #define CREATE_SOCKET                              41
        #define CREATE_SOCKET_PAIR                         53
        #define SPLICE_DATA                               275
        #define GET_FILESYSTEM_STATISTICS                 137
        #define GET_MOUNT_INFORMATION                     457
        #define GET_EXTENDED_FILE_STATUS                  332
        #define DISABLE_SWAP                              168
        #define ENABLE_SWAP                               167
        #define CREATE_SYMBOLIC_LINK_AT                   266
        #define SYNCHRONIZE_FILESYSTEMS                   162
        #define SYNCHRONIZE_FILE_RANGE                    277
        #define SYNCHRONIZE_FILESYSTEM                    306
        #define GET_SYSTEM_INFORMATION                     99
        #define CONTROL_KERNEL_LOG                        103
        #define DUPLICATE_PIPE_DATA                       276
        #define SEND_THREAD_SIGNAL                        234
        #define CREATE_PROCESS_TIMER                      222
        #define DELETE_PROCESS_TIMER                      226
        #define CREATE_TIMER_DESCRIPTOR                   283
        #define GET_TIMER_DESCRIPTOR                      287
        #define SET_TIMER_DESCRIPTOR                      286
        #define GET_TIMER_OVERRUN_COUNT                   225
        #define GET_PROCESS_TIMER                         224
        #define SET_PROCESS_TIMER                         223
        #define GET_PROCESS_TIMES                         100
        #define SEND_SIGNAL_TO_THREAD                     200
        #define RESIZE_FILE_AT_PATH                        76
        #define SET_FILE_CREATION_MASK                     95
        #define UNMOUNT_FILESYSTEM                        166
        #define REMOVE_PATH_AT                            263
        #define UNSHARE_PROCESS_RESOURCES                 272
        #define CREATE_USER_FAULT_DESCRIPTOR              323
        #define SET_FILE_TIMES_AT                         280
        #define HANGUP_VIRTUAL_TERMINAL                   153
        #define SPLICE_MEMORY_TO_PIPE                     278
        #define WAIT_FOR_CHILD                             61
        #define WAIT_FOR_CHILD_EVENT                      247
        #define WRITE_DATA                                  1
        #define WRITE_DATA_VECTORS                         20
    #endif
}