// AUTO-GENERATED SCRIPT
#pragma once
#include "system/platform/OS.hpp"
#if CMN_SYSTEM_OS_LIN
#include "system/syscall/Func.hpp"
#include "system/syscall/ID.hpp"
#include "system/syscall/Type.hpp"

namespace cmn::system::syscall
{
    inline long accept                  (int fd, struct sockaddr *upeer_sockaddr, int *upeer_addrlen) {return syscall(ACCEPT, (long)fd, (long)upeer_sockaddr, (long)upeer_addrlen);};
    inline long accept4                 (int fd, struct sockaddr *upeer_sockaddr, int *upeer_addrlen, int flags) {return syscall(ACCEPT4, (long)fd, (long)upeer_sockaddr, (long)upeer_addrlen, (long)flags);};
    inline long acct                    (const char *name) {return syscall(ACCT, (long)name);};
    inline long add_key                 (const char *_type, const char *_description, const void *_payload, size_t plen, key_serial_t ringid) {return syscall(ADD_KEY, (long)_type, (long)_description, (long)_payload, (long)plen, (long)ringid);};
    inline long adjtimex                (struct __kernel_timex *txc_p) {return syscall(ADJTIMEX, (long)txc_p);};
    inline long bind                    (int fd, struct sockaddr *umyaddr, int addrlen) {return syscall(BIND, (long)fd, (long)umyaddr, (long)addrlen);};
    inline long bpf                     (int cmd, union bpf_attr *uattr, unsigned int size) {return syscall(BPF, (long)cmd, (long)uattr, (long)size);};
    inline long brk                     (unsigned long brk) {return syscall(BRK, (long)brk);};
    inline long cachestat               (unsigned int fd, struct cachestat_range *cstat_range, struct cachestat *cstat, unsigned int flags) {return syscall(CACHESTAT, (long)fd, (long)cstat_range, (long)cstat, (long)flags);};
    inline long capget                  (cap_user_header_t header, cap_user_data_t dataptr) {return syscall(CAPGET, (long)header, (long)dataptr);};
    inline long capset                  (cap_user_header_t header, const cap_user_data_t data) {return syscall(CAPSET, (long)header, (long)data);};
    inline long chdir                   (const char *filename) {return syscall(CHDIR, (long)filename);};
    inline long chroot                  (const char *filename) {return syscall(CHROOT, (long)filename);};
    inline long clock_adjtime           (const clockid_t which_clock, struct __kernel_timex *utx) {return syscall(CLOCK_ADJTIME, (long)which_clock, (long)utx);};
    inline long clock_getres            (const clockid_t which_clock, struct __kernel_timespec *tp) {return syscall(CLOCK_GETRES, (long)which_clock, (long)tp);};
    inline long clock_gettime           (const clockid_t which_clock, struct __kernel_timespec *tp) {return syscall(CLOCK_GETTIME, (long)which_clock, (long)tp);};
    inline long clock_nanosleep         (const clockid_t which_clock, int flags, const struct __kernel_timespec *rqtp, struct __kernel_timespec *rmtp) {return syscall(CLOCK_NANOSLEEP, (long)which_clock, (long)flags, (long)rqtp, (long)rmtp);};
    inline long clock_settime           (const clockid_t which_clock, const struct __kernel_timespec *tp) {return syscall(CLOCK_SETTIME, (long)which_clock, (long)tp);};
    inline long clone                   (unsigned long clone_flags, unsigned long newsp, int *parent_tidptr, unsigned long tls, int *child_tidptr) {return syscall(CLONE, (long)clone_flags, (long)newsp, (long)parent_tidptr, (long)tls, (long)child_tidptr);};
    inline long clone3                  (struct clone_args *uargs, size_t size) {return syscall(CLONE3, (long)uargs, (long)size);};
    inline long close                   (unsigned int fd) {return syscall(CLOSE, (long)fd);};
    inline long close_range             (unsigned int fd, unsigned int max_fd, unsigned int flags) {return syscall(CLOSE_RANGE, (long)fd, (long)max_fd, (long)flags);};
    inline long connect                 (int fd, struct sockaddr *uservaddr, int addrlen) {return syscall(CONNECT, (long)fd, (long)uservaddr, (long)addrlen);};
    inline long copy_file_range         (int fd_in, loff_t *off_in, int fd_out, loff_t *off_out, size_t len, unsigned int flags) {return syscall(COPY_FILE_RANGE, (long)fd_in, (long)off_in, (long)fd_out, (long)off_out, (long)len, (long)flags);};
    inline long delete_module           (const char *name_user, unsigned int flags) {return syscall(DELETE_MODULE, (long)name_user, (long)flags);};
    inline long dup                     (unsigned int fildes) {return syscall(DUP, (long)fildes);};
    inline long dup3                    (unsigned int oldfd, unsigned int newfd, int flags) {return syscall(DUP3, (long)oldfd, (long)newfd, (long)flags);};
    inline long epoll_create1           (int flags) {return syscall(EPOLL_CREATE1, (long)flags);};
    inline long epoll_ctl               (int epfd, int op, int fd, struct epoll_event *event) {return syscall(EPOLL_CTL, (long)epfd, (long)op, (long)fd, (long)event);};
    inline long epoll_pwait             (int epfd, struct epoll_event *events, int maxevents, int timeout, const sigset_t *sigmask, size_t sigsetsize) {return syscall(EPOLL_PWAIT, (long)epfd, (long)events, (long)maxevents, (long)timeout, (long)sigmask, (long)sigsetsize);};
    inline long epoll_pwait2            (int epfd, struct epoll_event *events, int maxevents, const struct __kernel_timespec *timeout, const sigset_t *sigmask, size_t sigsetsize) {return syscall(EPOLL_PWAIT2, (long)epfd, (long)events, (long)maxevents, (long)timeout, (long)sigmask, (long)sigsetsize);};
    inline long eventfd2                (unsigned int count, int flags) {return syscall(EVENTFD2, (long)count, (long)flags);};
    inline long execve                  (const char *filename, const char *const *argv, const char *const *envp) {return syscall(EXECVE, (long)filename, (long)argv, (long)envp);};
    inline long execveat                (int fd, const char *filename, const char *const *argv, const char *const *envp, int flags) {return syscall(EXECVEAT, (long)fd, (long)filename, (long)argv, (long)envp, (long)flags);};
    inline long exit                    (int error_code) {return syscall(EXIT, (long)error_code);};
    inline long exit_group              (int error_code) {return syscall(EXIT_GROUP, (long)error_code);};
    inline long faccessat2              (int dfd, const char *filename, int mode, int flags) {return syscall(FACCESSAT2, (long)dfd, (long)filename, (long)mode, (long)flags);};
    inline long faccessat               (int dfd, const char *filename, int mode) {return syscall(FACCESSAT, (long)dfd, (long)filename, (long)mode);};
    inline long fallocate               (int fd, int mode, loff_t offset, loff_t len) {return syscall(FALLOCATE, (long)fd, (long)mode, (long)offset, (long)len);};
    inline long fanotify_init           (unsigned int flags, unsigned int event_f_flags) {return syscall(FANOTIFY_INIT, (long)flags, (long)event_f_flags);};
    inline long fanotify_mark           (int fanotify_fd, unsigned int flags, __u64 mask, int dfd, const char *pathname) {return syscall(FANOTIFY_MARK, (long)fanotify_fd, (long)flags, (long)mask, (long)dfd, (long)pathname);};
    inline long fchdir                  (unsigned int fd) {return syscall(FCHDIR, (long)fd);};
    inline long fchmod                  (unsigned int fd, umode_t mode) {return syscall(FCHMOD, (long)fd, (long)mode);};
    inline long fchmodat2               (int dfd, const char *filename, umode_t mode, unsigned int flags) {return syscall(FCHMODAT2, (long)dfd, (long)filename, (long)mode, (long)flags);};
    inline long fchmodat                (int dfd, const char *filename, umode_t mode) {return syscall(FCHMODAT, (long)dfd, (long)filename, (long)mode);};
    inline long fchown                  (unsigned int fd, uid_t user, gid_t group) {return syscall(FCHOWN, (long)fd, (long)user, (long)group);};
    inline long fchownat                (int dfd, const char *filename, uid_t user, gid_t group, int flag) {return syscall(FCHOWNAT, (long)dfd, (long)filename, (long)user, (long)group, (long)flag);};
    inline long fcntl                   (unsigned int fd, unsigned int cmd, unsigned long arg) {return syscall(FCNTL, (long)fd, (long)cmd, (long)arg);};
    inline long fdatasync               (unsigned int fd) {return syscall(FDATASYNC, (long)fd);};
    inline long fgetxattr               (int fd, const char *name, void *value, size_t size) {return syscall(FGETXATTR, (long)fd, (long)name, (long)value, (long)size);};
    inline long file_getattr            (int dfd, const char *filename, struct file_attr *ufattr, size_t usize, unsigned int at_flags) {return syscall(FILE_GETATTR, (long)dfd, (long)filename, (long)ufattr, (long)usize, (long)at_flags);};
    inline long file_setattr            (int dfd, const char *filename, struct file_attr *ufattr, size_t usize, unsigned int at_flags) {return syscall(FILE_SETATTR, (long)dfd, (long)filename, (long)ufattr, (long)usize, (long)at_flags);};
    inline long finit_module            (int fd, const char *uargs, int flags) {return syscall(FINIT_MODULE, (long)fd, (long)uargs, (long)flags);};
    inline long flistxattr              (int fd, char *list, size_t size) {return syscall(FLISTXATTR, (long)fd, (long)list, (long)size);};
    inline long flock                   (unsigned int fd, unsigned int cmd) {return syscall(FLOCK, (long)fd, (long)cmd);};
    inline long fremovexattr            (int fd, const char *name) {return syscall(FREMOVEXATTR, (long)fd, (long)name);};
    inline long fsconfig                (int fd, unsigned int cmd, const char *_key, const void *_value, int aux) {return syscall(FSCONFIG, (long)fd, (long)cmd, (long)_key, (long)_value, (long)aux);};
    inline long fsetxattr               (int fd, const char *name, const void *value, size_t size, int flags) {return syscall(FSETXATTR, (long)fd, (long)name, (long)value, (long)size, (long)flags);};
    inline long fsmount                 (int fs_fd, unsigned int flags, unsigned int attr_flags) {return syscall(FSMOUNT, (long)fs_fd, (long)flags, (long)attr_flags);};
    inline long fsopen                  (const char *_fs_name, unsigned int flags) {return syscall(FSOPEN, (long)_fs_name, (long)flags);};
    inline long fspick                  (int dfd, const char *path, unsigned int flags) {return syscall(FSPICK, (long)dfd, (long)path, (long)flags);};
    inline long fstatfs                 (unsigned int fd, struct statfs *buf) {return syscall(FSTATFS, (long)fd, (long)buf);};
    inline long fsync                   (unsigned int fd) {return syscall(FSYNC, (long)fd);};
    inline long ftruncate               (unsigned int fd, off_t length) {return syscall(FTRUNCATE, (long)fd, (long)length);};
    inline long futex                   (u32 *uaddr, int op, u32 val, const struct __kernel_timespec *utime, u32 *uaddr2, u32 val3) {return syscall(FUTEX, (long)uaddr, (long)op, (long)val, (long)utime, (long)uaddr2, (long)val3);};
    inline long futex_requeue           (struct futex_waitv *waiters, unsigned int flags, int nr_wake, int nr_requeue) {return syscall(FUTEX_REQUEUE, (long)waiters, (long)flags, (long)nr_wake, (long)nr_requeue);};
    inline long futex_wait              (void *uaddr, unsigned long val, unsigned long mask, unsigned int flags, struct __kernel_timespec *timeout, clockid_t clockid) {return syscall(FUTEX_WAIT, (long)uaddr, (long)val, (long)mask, (long)flags, (long)timeout, (long)clockid);};
    inline long futex_waitv             (struct futex_waitv *waiters, unsigned int nr_futexes, unsigned int flags, struct __kernel_timespec *timeout, clockid_t clockid) {return syscall(FUTEX_WAITV, (long)waiters, (long)nr_futexes, (long)flags, (long)timeout, (long)clockid);};
    inline long futex_wake              (void *uaddr, unsigned long mask, int nr, unsigned int flags) {return syscall(FUTEX_WAKE, (long)uaddr, (long)mask, (long)nr, (long)flags);};
    inline long getcpu                  (unsigned *cpup, unsigned *nodep, struct getcpu_cache *unused) {return syscall(GETCPU, (long)cpup, (long)nodep, (long)unused);};
    inline long getcwd                  (char *buf, unsigned long size) {return syscall(GETCWD, (long)buf, (long)size);};
    inline long getdents64              (unsigned int fd, struct linux_dirent64 *dirent, unsigned int count) {return syscall(GETDENTS64, (long)fd, (long)dirent, (long)count);};
    inline long getegid                 () {return syscall(GETEGID);};
    inline long geteuid                 () {return syscall(GETEUID);};
    inline long getgid                  () {return syscall(GETGID);};
    inline long getgroups               (int gidsetsize, gid_t *grouplist) {return syscall(GETGROUPS, (long)gidsetsize, (long)grouplist);};
    inline long getitimer               (int which, struct __kernel_old_itimerval *value) {return syscall(GETITIMER, (long)which, (long)value);};
    inline long get_mempolicy           (int *policy, unsigned long *nmask, unsigned long maxnode, unsigned long addr, unsigned long flags) {return syscall(GET_MEMPOLICY, (long)policy, (long)nmask, (long)maxnode, (long)addr, (long)flags);};
    inline long getpeername             (int fd, struct sockaddr *usockaddr, int *usockaddr_len) {return syscall(GETPEERNAME, (long)fd, (long)usockaddr, (long)usockaddr_len);};
    inline long getpgid                 (pid_t pid) {return syscall(GETPGID, (long)pid);};
    inline long getpid                  () {return syscall(GETPID);};
    inline long getppid                 () {return syscall(GETPPID);};
    inline long getpriority             (int which, int who) {return syscall(GETPRIORITY, (long)which, (long)who);};
    inline long getrandom               (char *ubuf, size_t len, unsigned int flags) {return syscall(GETRANDOM, (long)ubuf, (long)len, (long)flags);};
    inline long getresgid               (gid_t *rgidp, gid_t *egidp, gid_t *sgidp) {return syscall(GETRESGID, (long)rgidp, (long)egidp, (long)sgidp);};
    inline long getresuid               (uid_t *ruidp, uid_t *euidp, uid_t *suidp) {return syscall(GETRESUID, (long)ruidp, (long)euidp, (long)suidp);};
    inline long getrlimit               (unsigned int resource, struct rlimit *rlim) {return syscall(GETRLIMIT, (long)resource, (long)rlim);};
    inline long get_robust_list         (int pid, struct robust_list_head **head_ptr, size_t *len_ptr) {return syscall(GET_ROBUST_LIST, (long)pid, (long)head_ptr, (long)len_ptr);};
    inline long getrusage               (int who, struct rusage *ru) {return syscall(GETRUSAGE, (long)who, (long)ru);};
    inline long getsid                  (pid_t pid) {return syscall(GETSID, (long)pid);};
    inline long getsockname             (int fd, struct sockaddr *usockaddr, int *usockaddr_len) {return syscall(GETSOCKNAME, (long)fd, (long)usockaddr, (long)usockaddr_len);};
    inline long getsockopt              (int fd, int level, int optname, char *optval, int *optlen) {return syscall(GETSOCKOPT, (long)fd, (long)level, (long)optname, (long)optval, (long)optlen);};
    inline long gettid                  () {return syscall(GETTID);};
    inline long gettimeofday            (struct __kernel_old_timeval *tv, struct timezone *tz) {return syscall(GETTIMEOFDAY, (long)tv, (long)tz);};
    inline long getuid                  () {return syscall(GETUID);};
    inline long getxattr                (const char *pathname, const char *name, void *value, size_t size) {return syscall(GETXATTR, (long)pathname, (long)name, (long)value, (long)size);};
    inline long getxattrat              (int dfd, const char *pathname, unsigned int at_flags, const char *name, struct xattr_args *uargs, size_t usize) {return syscall(GETXATTRAT, (long)dfd, (long)pathname, (long)at_flags, (long)name, (long)uargs, (long)usize);};
    inline long init_module             (void *umod, unsigned long len, const char *uargs) {return syscall(INIT_MODULE, (long)umod, (long)len, (long)uargs);};
    inline long inotify_add_watch       (int fd, const char *pathname, u32 mask) {return syscall(INOTIFY_ADD_WATCH, (long)fd, (long)pathname, (long)mask);};
    inline long inotify_init1           (int flags) {return syscall(INOTIFY_INIT1, (long)flags);};
    inline long inotify_rm_watch        (int fd, __s32 wd) {return syscall(INOTIFY_RM_WATCH, (long)fd, (long)wd);};
    inline long io_cancel               (aio_context_t ctx_id, struct iocb *iocb, struct io_event *result) {return syscall(IO_CANCEL, (long)ctx_id, (long)iocb, (long)result);};
    inline long ioctl                   (unsigned int fd, unsigned int cmd, unsigned long arg) {return syscall(IOCTL, (long)fd, (long)cmd, (long)arg);};
    inline long io_destroy              (aio_context_t ctx) {return syscall(IO_DESTROY, (long)ctx);};
    inline long io_getevents            (aio_context_t ctx_id, long min_nr, long nr, struct io_event *events, struct __kernel_timespec *timeout) {return syscall(IO_GETEVENTS, (long)ctx_id, (long)min_nr, (long)nr, (long)events, (long)timeout);};
    inline long io_pgetevents           (aio_context_t ctx_id, long min_nr, long nr, struct io_event *events, struct __kernel_timespec *timeout, const struct __aio_sigset *usig) {return syscall(IO_PGETEVENTS, (long)ctx_id, (long)min_nr, (long)nr, (long)events, (long)timeout, (long)usig);};
    inline long ioprio_get              (int which, int who) {return syscall(IOPRIO_GET, (long)which, (long)who);};
    inline long ioprio_set              (int which, int who, int ioprio) {return syscall(IOPRIO_SET, (long)which, (long)who, (long)ioprio);};
    inline long io_setup                (unsigned nr_events, aio_context_t *ctxp) {return syscall(IO_SETUP, (long)nr_events, (long)ctxp);};
    inline long io_submit               (aio_context_t ctx_id, long nr, struct iocb **iocbpp) {return syscall(IO_SUBMIT, (long)ctx_id, (long)nr, (long)iocbpp);};
    inline long io_uring_enter          (unsigned int fd, u32 to_submit, u32 min_complete, u32 flags, const void *argp, size_t argsz) {return syscall(IO_URING_ENTER, (long)fd, (long)to_submit, (long)min_complete, (long)flags, (long)argp, (long)argsz);};
    inline long io_uring_register       (unsigned int fd, unsigned int opcode, void *arg, unsigned int nr_args) {return syscall(IO_URING_REGISTER, (long)fd, (long)opcode, (long)arg, (long)nr_args);};
    inline long io_uring_setup          (u32 entries, struct io_uring_params *params) {return syscall(IO_URING_SETUP, (long)entries, (long)params);};
    inline long kcmp                    (pid_t pid1, pid_t pid2, int type, unsigned long idx1, unsigned long idx2) {return syscall(KCMP, (long)pid1, (long)pid2, (long)type, (long)idx1, (long)idx2);};
    inline long kexec_file_load         (int kernel_fd, int initrd_fd, unsigned long cmdline_len, const char *cmdline_ptr, unsigned long flags) {return syscall(KEXEC_FILE_LOAD, (long)kernel_fd, (long)initrd_fd, (long)cmdline_len, (long)cmdline_ptr, (long)flags);};
    inline long kexec_load              (unsigned long entry, unsigned long nr_segments, struct kexec_segment *segments, unsigned long flags) {return syscall(KEXEC_LOAD, (long)entry, (long)nr_segments, (long)segments, (long)flags);};
    inline long keyctl                  (int option, unsigned long arg2, unsigned long arg3, unsigned long arg4, unsigned long arg5) {return syscall(KEYCTL, (long)option, (long)arg2, (long)arg3, (long)arg4, (long)arg5);};
    inline long kill                    (pid_t pid, int sig) {return syscall(KILL, (long)pid, (long)sig);};
    inline long landlock_add_rule       (const int ruleset_fd, const enum landlock_rule_type rule_type, const void *const rule_attr, const __u32 flags) {return syscall(LANDLOCK_ADD_RULE, (long)ruleset_fd, (long)rule_type, (long)rule_attr, (long)flags);};
    inline long landlock_create_ruleset (const struct landlock_ruleset_attr *const attr, const size_t size, const __u32 flags) {return syscall(LANDLOCK_CREATE_RULESET, (long)attr, (long)size, (long)flags);};
    inline long landlock_restrict_self  (const int ruleset_fd, const __u32 flags) {return syscall(LANDLOCK_RESTRICT_SELF, (long)ruleset_fd, (long)flags);};
    inline long lgetxattr               (const char *pathname, const char *name, void *value, size_t size) {return syscall(LGETXATTR, (long)pathname, (long)name, (long)value, (long)size);};
    inline long linkat                  (int olddfd, const char *oldname, int newdfd, const char *newname, int flags) {return syscall(LINKAT, (long)olddfd, (long)oldname, (long)newdfd, (long)newname, (long)flags);};
    inline long listen                  (int fd, int backlog) {return syscall(LISTEN, (long)fd, (long)backlog);};
    inline long listmount               (const struct mnt_id_req *req, u64 *mnt_ids, size_t nr_mnt_ids, unsigned int flags) {return syscall(LISTMOUNT, (long)req, (long)mnt_ids, (long)nr_mnt_ids, (long)flags);};
    inline long listxattr               (const char *pathname, char *list, size_t size) {return syscall(LISTXATTR, (long)pathname, (long)list, (long)size);};
    inline long listxattrat             (int dfd, const char *pathname, unsigned int at_flags, char *list, size_t size) {return syscall(LISTXATTRAT, (long)dfd, (long)pathname, (long)at_flags, (long)list, (long)size);};
    inline long llistxattr              (const char *pathname, char *list, size_t size) {return syscall(LLISTXATTR, (long)pathname, (long)list, (long)size);};
    inline long lremovexattr            (const char *pathname, const char *name) {return syscall(LREMOVEXATTR, (long)pathname, (long)name);};
    inline long lseek                   (unsigned int fd, off_t offset, unsigned int whence) {return syscall(LSEEK, (long)fd, (long)offset, (long)whence);};
    inline long lsetxattr               (const char *pathname, const char *name, const void *value, size_t size, int flags) {return syscall(LSETXATTR, (long)pathname, (long)name, (long)value, (long)size, (long)flags);};
    inline long lsm_get_self_attr       (unsigned int attr, struct lsm_ctx *ctx, u32 *size, u32 flags) {return syscall(LSM_GET_SELF_ATTR, (long)attr, (long)ctx, (long)size, (long)flags);};
    inline long lsm_list_modules        (u64 *ids, u32 *size, u32 flags) {return syscall(LSM_LIST_MODULES, (long)ids, (long)size, (long)flags);};
    inline long lsm_set_self_attr       (unsigned int attr, struct lsm_ctx *ctx, u32 size, u32 flags) {return syscall(LSM_SET_SELF_ATTR, (long)attr, (long)ctx, (long)size, (long)flags);};
    inline long madvise                 (unsigned long start, size_t len_in, int behavior) {return syscall(MADVISE, (long)start, (long)len_in, (long)behavior);};
    inline long map_shadow_stack        (unsigned long addr, unsigned long size, unsigned int flags) {return syscall(MAP_SHADOW_STACK, (long)addr, (long)size, (long)flags);};
    inline long mbind                   (unsigned long start, unsigned long len, unsigned long mode, const unsigned long *nmask, unsigned long maxnode, unsigned int flags) {return syscall(MBIND, (long)start, (long)len, (long)mode, (long)nmask, (long)maxnode, (long)flags);};
    inline long membarrier              (int cmd, unsigned int flags, int cpu_id) {return syscall(MEMBARRIER, (long)cmd, (long)flags, (long)cpu_id);};
    inline long memfd_create            (const char *uname, unsigned int flags) {return syscall(MEMFD_CREATE, (long)uname, (long)flags);};
    inline long memfd_secret            (unsigned int flags) {return syscall(MEMFD_SECRET, (long)flags);};
    inline long migrate_pages           (pid_t pid, unsigned long maxnode, const unsigned long *old_nodes, const unsigned long *new_nodes) {return syscall(MIGRATE_PAGES, (long)pid, (long)maxnode, (long)old_nodes, (long)new_nodes);};
    inline long mincore                 (unsigned long start, size_t len, unsigned char *vec) {return syscall(MINCORE, (long)start, (long)len, (long)vec);};
    inline long mkdirat                 (int dfd, const char *pathname, umode_t mode) {return syscall(MKDIRAT, (long)dfd, (long)pathname, (long)mode);};
    inline long mknodat                 (int dfd, const char *filename, umode_t mode, unsigned int dev) {return syscall(MKNODAT, (long)dfd, (long)filename, (long)mode, (long)dev);};
    inline long mlock2                  (unsigned long start, size_t len, int flags) {return syscall(MLOCK2, (long)start, (long)len, (long)flags);};
    inline long mlock                   (unsigned long start, size_t len) {return syscall(MLOCK, (long)start, (long)len);};
    inline long mlockall                (int flags) {return syscall(MLOCKALL, (long)flags);};
    inline long mmap                    (unsigned long addr, unsigned long len, unsigned long prot, unsigned long flags, unsigned long fd, unsigned long off) {return syscall(MMAP, (long)addr, (long)len, (long)prot, (long)flags, (long)fd, (long)off);};
    inline long mount                   (char *dev_name, char *dir_name, char *type, unsigned long flags, void *data) {return syscall(MOUNT, (long)dev_name, (long)dir_name, (long)type, (long)flags, (long)data);};
    inline long mount_setattr           (int dfd, const char *path, unsigned int flags, struct mount_attr *uattr, size_t usize) {return syscall(MOUNT_SETATTR, (long)dfd, (long)path, (long)flags, (long)uattr, (long)usize);};
    inline long move_mount              (int from_dfd, const char *from_pathname, int to_dfd, const char *to_pathname, unsigned int flags) {return syscall(MOVE_MOUNT, (long)from_dfd, (long)from_pathname, (long)to_dfd, (long)to_pathname, (long)flags);};
    inline long move_pages              (pid_t pid, unsigned long nr_pages, const void **pages, const int *nodes, int *status, int flags) {return syscall(MOVE_PAGES, (long)pid, (long)nr_pages, (long)pages, (long)nodes, (long)status, (long)flags);};
    inline long mprotect                (unsigned long start, size_t len, unsigned long prot) {return syscall(MPROTECT, (long)start, (long)len, (long)prot);};
    inline long mq_getsetattr           (mqd_t mqdes, const struct mq_attr *u_mqstat, struct mq_attr *u_omqstat) {return syscall(MQ_GETSETATTR, (long)mqdes, (long)u_mqstat, (long)u_omqstat);};
    inline long mq_notify               (mqd_t mqdes, const struct sigevent *u_notification) {return syscall(MQ_NOTIFY, (long)mqdes, (long)u_notification);};
    inline long mq_open                 (const char *u_name, int oflag, umode_t mode, struct mq_attr *u_attr) {return syscall(MQ_OPEN, (long)u_name, (long)oflag, (long)mode, (long)u_attr);};
    inline long mq_timedreceive         (mqd_t mqdes, char *u_msg_ptr, size_t msg_len, unsigned int *u_msg_prio, const struct __kernel_timespec *u_abs_timeout) {return syscall(MQ_TIMEDRECEIVE, (long)mqdes, (long)u_msg_ptr, (long)msg_len, (long)u_msg_prio, (long)u_abs_timeout);};
    inline long mq_timedsend            (mqd_t mqdes, const char *u_msg_ptr, size_t msg_len, unsigned int msg_prio, const struct __kernel_timespec *u_abs_timeout) {return syscall(MQ_TIMEDSEND, (long)mqdes, (long)u_msg_ptr, (long)msg_len, (long)msg_prio, (long)u_abs_timeout);};
    inline long mq_unlink               (const char *u_name) {return syscall(MQ_UNLINK, (long)u_name);};
    inline long mremap                  (unsigned long addr, unsigned long old_len, unsigned long new_len, unsigned long flags, unsigned long new_addr) {return syscall(MREMAP, (long)addr, (long)old_len, (long)new_len, (long)flags, (long)new_addr);};
    inline long mseal                   (unsigned long start, size_t len, unsigned long flags) {return syscall(MSEAL, (long)start, (long)len, (long)flags);};
    inline long msgctl                  (int msqid, int cmd, struct msqid_ds *buf) {return syscall(MSGCTL, (long)msqid, (long)cmd, (long)buf);};
    inline long msgget                  (key_t key, int msgflg) {return syscall(MSGGET, (long)key, (long)msgflg);};
    inline long msgrcv                  (int msqid, struct msgbuf *msgp, size_t msgsz, long msgtyp, int msgflg) {return syscall(MSGRCV, (long)msqid, (long)msgp, (long)msgsz, (long)msgtyp, (long)msgflg);};
    inline long msgsnd                  (int msqid, struct msgbuf *msgp, size_t msgsz, int msgflg) {return syscall(MSGSND, (long)msqid, (long)msgp, (long)msgsz, (long)msgflg);};
    inline long msync                   (unsigned long start, size_t len, int flags) {return syscall(MSYNC, (long)start, (long)len, (long)flags);};
    inline long munlock                 (unsigned long start, size_t len) {return syscall(MUNLOCK, (long)start, (long)len);};
    inline long munlockall              () {return syscall(MUNLOCKALL);};
    inline long munmap                  (unsigned long addr, size_t len) {return syscall(MUNMAP, (long)addr, (long)len);};
    inline long name_to_handle_at       (int dfd, const char *name, struct file_handle *handle, void *mnt_id, int flag) {return syscall(NAME_TO_HANDLE_AT, (long)dfd, (long)name, (long)handle, (long)mnt_id, (long)flag);};
    inline long nanosleep               (struct __kernel_timespec *rqtp, struct __kernel_timespec *rmtp) {return syscall(NANOSLEEP, (long)rqtp, (long)rmtp);};
    inline long newfstat                (unsigned int fd, struct stat *statbuf) {return syscall(NEWFSTAT, (long)fd, (long)statbuf);};
    inline long newfstatat              (int dfd, const char *filename, struct stat *statbuf, int flag) {return syscall(NEWFSTATAT, (long)dfd, (long)filename, (long)statbuf, (long)flag);};
    inline long newuname                (struct new_utsname *name) {return syscall(NEWUNAME, (long)name);};
    inline long openat2                 (int dfd, const char *filename, struct open_how *how, size_t usize) {return syscall(OPENAT2, (long)dfd, (long)filename, (long)how, (long)usize);};
    inline long openat                  (int dfd, const char *filename, int flags, umode_t mode) {return syscall(OPENAT, (long)dfd, (long)filename, (long)flags, (long)mode);};
    inline long open_by_handle_at       (int mountdirfd, struct file_handle *handle, int flags) {return syscall(OPEN_BY_HANDLE_AT, (long)mountdirfd, (long)handle, (long)flags);};
    inline long open_tree               (int dfd, const char *filename, unsigned flags) {return syscall(OPEN_TREE, (long)dfd, (long)filename, (long)flags);};
    inline long open_tree_attr          (int dfd, const char *filename, unsigned flags, struct mount_attr *uattr, size_t usize) {return syscall(OPEN_TREE_ATTR, (long)dfd, (long)filename, (long)flags, (long)uattr, (long)usize);};
    inline long perf_event_open         (struct perf_event_attr *attr_uptr, pid_t pid, int cpu, int group_fd, unsigned long flags) {return syscall(PERF_EVENT_OPEN, (long)attr_uptr, (long)pid, (long)cpu, (long)group_fd, (long)flags);};
    inline long personality             (unsigned int personality) {return syscall(PERSONALITY, (long)personality);};
    inline long pidfd_getfd             (int pidfd, int fd, unsigned int flags) {return syscall(PIDFD_GETFD, (long)pidfd, (long)fd, (long)flags);};
    inline long pidfd_open              (pid_t pid, unsigned int flags) {return syscall(PIDFD_OPEN, (long)pid, (long)flags);};
    inline long pidfd_send_signal       (int pidfd, int sig, siginfo_t *info, unsigned int flags) {return syscall(PIDFD_SEND_SIGNAL, (long)pidfd, (long)sig, (long)info, (long)flags);};
    inline long pipe2                   (int *fildes, int flags) {return syscall(PIPE2, (long)fildes, (long)flags);};
    inline long pivot_root              (const char *new_root, const char *put_old) {return syscall(PIVOT_ROOT, (long)new_root, (long)put_old);};
    inline long pkey_alloc              (unsigned long flags, unsigned long init_val) {return syscall(PKEY_ALLOC, (long)flags, (long)init_val);};
    inline long pkey_free               (int pkey) {return syscall(PKEY_FREE, (long)pkey);};
    inline long pkey_mprotect           (unsigned long start, size_t len, unsigned long prot, int pkey) {return syscall(PKEY_MPROTECT, (long)start, (long)len, (long)prot, (long)pkey);};
    inline long ppoll                   (struct pollfd *ufds, unsigned int nfds, struct __kernel_timespec *tsp, const sigset_t *sigmask, size_t sigsetsize) {return syscall(PPOLL, (long)ufds, (long)nfds, (long)tsp, (long)sigmask, (long)sigsetsize);};
    inline long prctl                   (int option, unsigned long arg2, unsigned long arg3, unsigned long arg4, unsigned long arg5) {return syscall(PRCTL, (long)option, (long)arg2, (long)arg3, (long)arg4, (long)arg5);};
    inline long pread64                 (unsigned int fd, char *buf, size_t count, loff_t pos) {return syscall(PREAD64, (long)fd, (long)buf, (long)count, (long)pos);};
    inline long preadv2                 (unsigned long fd, const struct iovec *vec, unsigned long vlen, unsigned long pos_l, unsigned long pos_h, rwf_t flags) {return syscall(PREADV2, (long)fd, (long)vec, (long)vlen, (long)pos_l, (long)pos_h, (long)flags);};
    inline long preadv                  (unsigned long fd, const struct iovec *vec, unsigned long vlen, unsigned long pos_l, unsigned long pos_h) {return syscall(PREADV, (long)fd, (long)vec, (long)vlen, (long)pos_l, (long)pos_h);};
    inline long prlimit64               (pid_t pid, unsigned int resource, const struct rlimit64 *new_rlim, struct rlimit64 *old_rlim) {return syscall(PRLIMIT64, (long)pid, (long)resource, (long)new_rlim, (long)old_rlim);};
    inline long process_madvise         (int pidfd, const struct iovec *vec, size_t vlen, int behavior, unsigned int flags) {return syscall(PROCESS_MADVISE, (long)pidfd, (long)vec, (long)vlen, (long)behavior, (long)flags);};
    inline long process_mrelease        (int pidfd, unsigned int flags) {return syscall(PROCESS_MRELEASE, (long)pidfd, (long)flags);};
    inline long process_vm_readv        (pid_t pid, const struct iovec *lvec, unsigned long liovcnt, const struct iovec *rvec, unsigned long riovcnt, unsigned long flags) {return syscall(PROCESS_VM_READV, (long)pid, (long)lvec, (long)liovcnt, (long)rvec, (long)riovcnt, (long)flags);};
    inline long process_vm_writev       (pid_t pid, const struct iovec *lvec, unsigned long liovcnt, const struct iovec *rvec, unsigned long riovcnt, unsigned long flags) {return syscall(PROCESS_VM_WRITEV, (long)pid, (long)lvec, (long)liovcnt, (long)rvec, (long)riovcnt, (long)flags);};
    inline long pselect6                (int n, fd_set *inp, fd_set *outp, fd_set *exp, struct __kernel_timespec *tsp, void *sig) {return syscall(PSELECT6, (long)n, (long)inp, (long)outp, (long)exp, (long)tsp, (long)sig);};
    inline long ptrace                  (long request, long pid, unsigned long addr, unsigned long data) {return syscall(PTRACE, (long)request, (long)pid, (long)addr, (long)data);};
    inline long pwrite64                (unsigned int fd, const char *buf, size_t count, loff_t pos) {return syscall(PWRITE64, (long)fd, (long)buf, (long)count, (long)pos);};
    inline long pwritev2                (unsigned long fd, const struct iovec *vec, unsigned long vlen, unsigned long pos_l, unsigned long pos_h, rwf_t flags) {return syscall(PWRITEV2, (long)fd, (long)vec, (long)vlen, (long)pos_l, (long)pos_h, (long)flags);};
    inline long pwritev                 (unsigned long fd, const struct iovec *vec, unsigned long vlen, unsigned long pos_l, unsigned long pos_h) {return syscall(PWRITEV, (long)fd, (long)vec, (long)vlen, (long)pos_l, (long)pos_h);};
    inline long quotactl                (unsigned int cmd, const char *special, qid_t id, void *addr) {return syscall(QUOTACTL, (long)cmd, (long)special, (long)id, (long)addr);};
    inline long quotactl_fd             (unsigned int fd, unsigned int cmd, qid_t id, void *addr) {return syscall(QUOTACTL_FD, (long)fd, (long)cmd, (long)id, (long)addr);};
    inline long read                    (unsigned int fd, char *buf, size_t count) {return syscall(READ, (long)fd, (long)buf, (long)count);};
    inline long readahead               (int fd, loff_t offset, size_t count) {return syscall(READAHEAD, (long)fd, (long)offset, (long)count);};
    inline long readlinkat              (int dfd, const char *pathname, char *buf, int bufsiz) {return syscall(READLINKAT, (long)dfd, (long)pathname, (long)buf, (long)bufsiz);};
    inline long readv                   (unsigned long fd, const struct iovec *vec, unsigned long vlen) {return syscall(READV, (long)fd, (long)vec, (long)vlen);};
    inline long reboot                  (int magic1, int magic2, unsigned int cmd, void *arg) {return syscall(REBOOT, (long)magic1, (long)magic2, (long)cmd, (long)arg);};
    inline long recvfrom                (int fd, void *ubuf, size_t size, unsigned int flags, struct sockaddr *addr, int *addr_len) {return syscall(RECVFROM, (long)fd, (long)ubuf, (long)size, (long)flags, (long)addr, (long)addr_len);};
    inline long recvmmsg                (int fd, struct mmsghdr *mmsg, unsigned int vlen, unsigned int flags, struct __kernel_timespec *timeout) {return syscall(RECVMMSG, (long)fd, (long)mmsg, (long)vlen, (long)flags, (long)timeout);};
    inline long recvmsg                 (int fd, struct user_msghdr *msg, unsigned int flags) {return syscall(RECVMSG, (long)fd, (long)msg, (long)flags);};
    inline long remap_file_pages        (unsigned long start, unsigned long size, unsigned long prot, unsigned long pgoff, unsigned long flags) {return syscall(REMAP_FILE_PAGES, (long)start, (long)size, (long)prot, (long)pgoff, (long)flags);};
    inline long removexattr             (const char *pathname, const char *name) {return syscall(REMOVEXATTR, (long)pathname, (long)name);};
    inline long removexattrat           (int dfd, const char *pathname, unsigned int at_flags, const char *name) {return syscall(REMOVEXATTRAT, (long)dfd, (long)pathname, (long)at_flags, (long)name);};
    inline long renameat2               (int olddfd, const char *oldname, int newdfd, const char *newname, unsigned int flags) {return syscall(RENAMEAT2, (long)olddfd, (long)oldname, (long)newdfd, (long)newname, (long)flags);};
    inline long renameat                (int olddfd, const char *oldname, int newdfd, const char *newname) {return syscall(RENAMEAT, (long)olddfd, (long)oldname, (long)newdfd, (long)newname);};
    inline long request_key             (const char *_type, const char *_description, const char *_callout_info, key_serial_t destringid) {return syscall(REQUEST_KEY, (long)_type, (long)_description, (long)_callout_info, (long)destringid);};
    inline long restart_syscall         () {return syscall(RESTART_SYSCALL);};
    inline long rseq                    (struct rseq *rseq, u32 rseq_len, int flags, u32 sig) {return syscall(RSEQ, (long)rseq, (long)rseq_len, (long)flags, (long)sig);};
    inline long rt_sigaction            (int sig, const struct sigaction *act, struct sigaction *oact, size_t sigsetsize) {return syscall(RT_SIGACTION, (long)sig, (long)act, (long)oact, (long)sigsetsize);};
    inline long rt_sigpending           (sigset_t *uset, size_t sigsetsize) {return syscall(RT_SIGPENDING, (long)uset, (long)sigsetsize);};
    inline long rt_sigprocmask          (int how, sigset_t *nset, sigset_t *oset, size_t sigsetsize) {return syscall(RT_SIGPROCMASK, (long)how, (long)nset, (long)oset, (long)sigsetsize);};
    inline long rt_sigqueueinfo         (pid_t pid, int sig, siginfo_t *uinfo) {return syscall(RT_SIGQUEUEINFO, (long)pid, (long)sig, (long)uinfo);};
    inline long rt_sigreturn            () {return syscall(RT_SIGRETURN);};
    inline long rt_sigsuspend           (sigset_t *unewset, size_t sigsetsize) {return syscall(RT_SIGSUSPEND, (long)unewset, (long)sigsetsize);};
    inline long rt_sigtimedwait         (const sigset_t *uthese, siginfo_t *uinfo, const struct __kernel_timespec *uts, size_t sigsetsize) {return syscall(RT_SIGTIMEDWAIT, (long)uthese, (long)uinfo, (long)uts, (long)sigsetsize);};
    inline long rt_tgsigqueueinfo       (pid_t tgid, pid_t pid, int sig, siginfo_t *uinfo) {return syscall(RT_TGSIGQUEUEINFO, (long)tgid, (long)pid, (long)sig, (long)uinfo);};
    inline long sched_getaffinity       (pid_t pid, unsigned int len, unsigned long *user_mask_ptr) {return syscall(SCHED_GETAFFINITY, (long)pid, (long)len, (long)user_mask_ptr);};
    inline long sched_getattr           (pid_t pid, struct sched_attr *uattr, unsigned int usize, unsigned int flags) {return syscall(SCHED_GETATTR, (long)pid, (long)uattr, (long)usize, (long)flags);};
    inline long sched_getparam          (pid_t pid, struct sched_param *param) {return syscall(SCHED_GETPARAM, (long)pid, (long)param);};
    inline long sched_get_priority_max  (int policy) {return syscall(SCHED_GET_PRIORITY_MAX, (long)policy);};
    inline long sched_get_priority_min  (int policy) {return syscall(SCHED_GET_PRIORITY_MIN, (long)policy);};
    inline long sched_getscheduler      (pid_t pid) {return syscall(SCHED_GETSCHEDULER, (long)pid);};
    inline long sched_rr_get_interval   (pid_t pid, struct __kernel_timespec *interval) {return syscall(SCHED_RR_GET_INTERVAL, (long)pid, (long)interval);};
    inline long sched_setaffinity       (pid_t pid, unsigned int len, unsigned long *user_mask_ptr) {return syscall(SCHED_SETAFFINITY, (long)pid, (long)len, (long)user_mask_ptr);};
    inline long sched_setattr           (pid_t pid, struct sched_attr *uattr, unsigned int flags) {return syscall(SCHED_SETATTR, (long)pid, (long)uattr, (long)flags);};
    inline long sched_setparam          (pid_t pid, struct sched_param *param) {return syscall(SCHED_SETPARAM, (long)pid, (long)param);};
    inline long sched_setscheduler      (pid_t pid, int policy, struct sched_param *param) {return syscall(SCHED_SETSCHEDULER, (long)pid, (long)policy, (long)param);};
    inline long sched_yield             () {return syscall(SCHED_YIELD);};
    inline long seccomp                 (unsigned int op, unsigned int flags, void *uargs) {return syscall(SECCOMP, (long)op, (long)flags, (long)uargs);};
    inline long semctl                  (int semid, int semnum, int cmd, unsigned long arg) {return syscall(SEMCTL, (long)semid, (long)semnum, (long)cmd, (long)arg);};
    inline long semget                  (key_t key, int nsems, int semflg) {return syscall(SEMGET, (long)key, (long)nsems, (long)semflg);};
    inline long semop                   (int semid, struct sembuf *tsops, unsigned nsops) {return syscall(SEMOP, (long)semid, (long)tsops, (long)nsops);};
    inline long semtimedop              (int semid, struct sembuf *tsops, unsigned int nsops, const struct __kernel_timespec *timeout) {return syscall(SEMTIMEDOP, (long)semid, (long)tsops, (long)nsops, (long)timeout);};
    inline long sendfile64              (int out_fd, int in_fd, loff_t *offset, size_t count) {return syscall(SENDFILE64, (long)out_fd, (long)in_fd, (long)offset, (long)count);};
    inline long sendmmsg                (int fd, struct mmsghdr *mmsg, unsigned int vlen, unsigned int flags) {return syscall(SENDMMSG, (long)fd, (long)mmsg, (long)vlen, (long)flags);};
    inline long sendmsg                 (int fd, struct user_msghdr *msg, unsigned int flags) {return syscall(SENDMSG, (long)fd, (long)msg, (long)flags);};
    inline long sendto                  (int fd, void *buff, size_t len, unsigned int flags, struct sockaddr *addr, int addr_len) {return syscall(SENDTO, (long)fd, (long)buff, (long)len, (long)flags, (long)addr, (long)addr_len);};
    inline long setdomainname           (char *name, int len) {return syscall(SETDOMAINNAME, (long)name, (long)len);};
    inline long setfsgid                (gid_t gid) {return syscall(SETFSGID, (long)gid);};
    inline long setfsuid                (uid_t uid) {return syscall(SETFSUID, (long)uid);};
    inline long setgid                  (gid_t gid) {return syscall(SETGID, (long)gid);};
    inline long setgroups               (int gidsetsize, gid_t *grouplist) {return syscall(SETGROUPS, (long)gidsetsize, (long)grouplist);};
    inline long sethostname             (char *name, int len) {return syscall(SETHOSTNAME, (long)name, (long)len);};
    inline long setitimer               (int which, struct __kernel_old_itimerval *value, struct __kernel_old_itimerval *ovalue) {return syscall(SETITIMER, (long)which, (long)value, (long)ovalue);};
    inline long set_mempolicy           (int mode, const unsigned long *nmask, unsigned long maxnode) {return syscall(SET_MEMPOLICY, (long)mode, (long)nmask, (long)maxnode);};
    inline long set_mempolicy_home_node (unsigned long start, unsigned long len, unsigned long home_node, unsigned long flags) {return syscall(SET_MEMPOLICY_HOME_NODE, (long)start, (long)len, (long)home_node, (long)flags);};
    inline long setns                   (int fd, int flags) {return syscall(SETNS, (long)fd, (long)flags);};
    inline long setpgid                 (pid_t pid, pid_t pgid) {return syscall(SETPGID, (long)pid, (long)pgid);};
    inline long setpriority             (int which, int who, int niceval) {return syscall(SETPRIORITY, (long)which, (long)who, (long)niceval);};
    inline long setregid                (gid_t rgid, gid_t egid) {return syscall(SETREGID, (long)rgid, (long)egid);};
    inline long setresgid               (gid_t rgid, gid_t egid, gid_t sgid) {return syscall(SETRESGID, (long)rgid, (long)egid, (long)sgid);};
    inline long setresuid               (uid_t ruid, uid_t euid, uid_t suid) {return syscall(SETRESUID, (long)ruid, (long)euid, (long)suid);};
    inline long setreuid                (uid_t ruid, uid_t euid) {return syscall(SETREUID, (long)ruid, (long)euid);};
    inline long setrlimit               (unsigned int resource, struct rlimit *rlim) {return syscall(SETRLIMIT, (long)resource, (long)rlim);};
    inline long set_robust_list         (struct robust_list_head *head, size_t len) {return syscall(SET_ROBUST_LIST, (long)head, (long)len);};
    inline long setsid                  () {return syscall(SETSID);};
    inline long setsockopt              (int fd, int level, int optname, char *optval, int optlen) {return syscall(SETSOCKOPT, (long)fd, (long)level, (long)optname, (long)optval, (long)optlen);};
    inline long set_tid_address         (int *tidptr) {return syscall(SET_TID_ADDRESS, (long)tidptr);};
    inline long settimeofday            (struct __kernel_old_timeval *tv, struct timezone *tz) {return syscall(SETTIMEOFDAY, (long)tv, (long)tz);};
    inline long setuid                  (uid_t uid) {return syscall(SETUID, (long)uid);};
    inline long setxattr                (const char *pathname, const char *name, const void *value, size_t size, int flags) {return syscall(SETXATTR, (long)pathname, (long)name, (long)value, (long)size, (long)flags);};
    inline long setxattrat              (int dfd, const char *pathname, unsigned int at_flags, const char *name, const struct xattr_args *uargs, size_t usize) {return syscall(SETXATTRAT, (long)dfd, (long)pathname, (long)at_flags, (long)name, (long)uargs, (long)usize);};
    inline long shmat                   (int shmid, char *shmaddr, int shmflg) {return syscall(SHMAT, (long)shmid, (long)shmaddr, (long)shmflg);};
    inline long shmctl                  (int shmid, int cmd, struct shmid_ds *buf) {return syscall(SHMCTL, (long)shmid, (long)cmd, (long)buf);};
    inline long shmdt                   (char *shmaddr) {return syscall(SHMDT, (long)shmaddr);};
    inline long shmget                  (key_t key, size_t size, int shmflg) {return syscall(SHMGET, (long)key, (long)size, (long)shmflg);};
    inline long shutdown                (int fd, int how) {return syscall(SHUTDOWN, (long)fd, (long)how);};
    inline long sigaltstack             (const stack_t *uss, stack_t *uoss) {return syscall(SIGALTSTACK, (long)uss, (long)uoss);};
    inline long signalfd4               (int ufd, sigset_t *user_mask, size_t sizemask, int flags) {return syscall(SIGNALFD4, (long)ufd, (long)user_mask, (long)sizemask, (long)flags);};
    inline long socket                  (int family, int type, int protocol) {return syscall(SOCKET, (long)family, (long)type, (long)protocol);};
    inline long socketpair              (int family, int type, int protocol, int *usockvec) {return syscall(SOCKETPAIR, (long)family, (long)type, (long)protocol, (long)usockvec);};
    inline long splice                  (int fd_in, loff_t *off_in, int fd_out, loff_t *off_out, size_t len, unsigned int flags) {return syscall(SPLICE, (long)fd_in, (long)off_in, (long)fd_out, (long)off_out, (long)len, (long)flags);};
    inline long statfs                  (const char *pathname, struct statfs *buf) {return syscall(STATFS, (long)pathname, (long)buf);};
    inline long statmount               (const struct mnt_id_req *req, struct statmount *buf, size_t bufsize, unsigned int flags) {return syscall(STATMOUNT, (long)req, (long)buf, (long)bufsize, (long)flags);};
    inline long statx                   (int dfd, const char *filename, unsigned flags, unsigned int mask, struct statx *buffer) {return syscall(STATX, (long)dfd, (long)filename, (long)flags, (long)mask, (long)buffer);};
    inline long swapoff                 (const char *specialfile) {return syscall(SWAPOFF, (long)specialfile);};
    inline long swapon                  (const char *specialfile, int swap_flags) {return syscall(SWAPON, (long)specialfile, (long)swap_flags);};
    inline long symlinkat               (const char *oldname, int newdfd, const char *newname) {return syscall(SYMLINKAT, (long)oldname, (long)newdfd, (long)newname);};
    inline long sync                    () {return syscall(SYNC);};
    inline long sync_file_range         (int fd, loff_t offset, loff_t nbytes, unsigned int flags) {return syscall(SYNC_FILE_RANGE, (long)fd, (long)offset, (long)nbytes, (long)flags);};
    inline long syncfs                  (int fd) {return syscall(SYNCFS, (long)fd);};
    inline long sysinfo                 (struct sysinfo *info) {return syscall(SYSINFO, (long)info);};
    inline long syslog                  (int type, char *buf, int len) {return syscall(SYSLOG, (long)type, (long)buf, (long)len);};
    inline long tee                     (int fdin, int fdout, size_t len, unsigned int flags) {return syscall(TEE, (long)fdin, (long)fdout, (long)len, (long)flags);};
    inline long tgkill                  (pid_t tgid, pid_t pid, int sig) {return syscall(TGKILL, (long)tgid, (long)pid, (long)sig);};
    inline long timer_create            (const clockid_t which_clock, struct sigevent *timer_event_spec, timer_t *created_timer_id) {return syscall(TIMER_CREATE, (long)which_clock, (long)timer_event_spec, (long)created_timer_id);};
    inline long timer_delete            (timer_t timer_id) {return syscall(TIMER_DELETE, (long)timer_id);};
    inline long timerfd_create          (int clockid, int flags) {return syscall(TIMERFD_CREATE, (long)clockid, (long)flags);};
    inline long timerfd_gettime         (int ufd, struct __kernel_itimerspec *otmr) {return syscall(TIMERFD_GETTIME, (long)ufd, (long)otmr);};
    inline long timerfd_settime         (int ufd, int flags, const struct __kernel_itimerspec *utmr, struct __kernel_itimerspec *otmr) {return syscall(TIMERFD_SETTIME, (long)ufd, (long)flags, (long)utmr, (long)otmr);};
    inline long timer_getoverrun        (timer_t timer_id) {return syscall(TIMER_GETOVERRUN, (long)timer_id);};
    inline long timer_gettime           (timer_t timer_id, struct __kernel_itimerspec *setting) {return syscall(TIMER_GETTIME, (long)timer_id, (long)setting);};
    inline long timer_settime           (timer_t timer_id, int flags, const struct __kernel_itimerspec *new_setting, struct __kernel_itimerspec *old_setting) {return syscall(TIMER_SETTIME, (long)timer_id, (long)flags, (long)new_setting, (long)old_setting);};
    inline long times                   (struct tms *tbuf) {return syscall(TIMES, (long)tbuf);};
    inline long tkill                   (pid_t pid, int sig) {return syscall(TKILL, (long)pid, (long)sig);};
    inline long truncate                (const char *path, long length) {return syscall(TRUNCATE, (long)path, (long)length);};
    inline long umask                   (int mask) {return syscall(UMASK, (long)mask);};
    inline long umount                  (char *name, int flags) {return syscall(UMOUNT, (long)name, (long)flags);};
    inline long unlinkat                (int dfd, const char *pathname, int flag) {return syscall(UNLINKAT, (long)dfd, (long)pathname, (long)flag);};
    inline long unshare                 (unsigned long unshare_flags) {return syscall(UNSHARE, (long)unshare_flags);};
    inline long userfaultfd             (int flags) {return syscall(USERFAULTFD, (long)flags);};
    inline long utimensat               (int dfd, const char *filename, struct __kernel_timespec *utimes, int flags) {return syscall(UTIMENSAT, (long)dfd, (long)filename, (long)utimes, (long)flags);};
    inline long vhangup                 () {return syscall(VHANGUP);};
    inline long vmsplice                (int fd, const struct iovec *uiov, unsigned long nr_segs, unsigned int flags) {return syscall(VMSPLICE, (long)fd, (long)uiov, (long)nr_segs, (long)flags);};
    inline long wait4                   (pid_t upid, int *stat_addr, int options, struct rusage *ru) {return syscall(WAIT4, (long)upid, (long)stat_addr, (long)options, (long)ru);};
    inline long waitid                  (int which, pid_t upid, struct siginfo *infop, int options, struct rusage *ru) {return syscall(WAITID, (long)which, (long)upid, (long)infop, (long)options, (long)ru);};
    inline long write                   (unsigned int fd, const char *buf, size_t count) {return syscall(WRITE, (long)fd, (long)buf, (long)count);};
    inline long writev                  (unsigned long fd, const struct iovec *vec, unsigned long vlen) {return syscall(WRITEV, (long)fd, (long)vec, (long)vlen);};
}
#endif