name: Build

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            script: build/lin_gcc.sh

          - os: ubuntu-latest
            script: build/lin_clg.sh

          - os: windows-latest
            script: build/win_gcc.ps1

          - os: windows-latest
            script: build/win_clg.ps1

          - os: macos-latest
            script: build/mac_clg.sh

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v6

      - name: Make script executable
        if: runner.os != 'Windows'
        run: chmod +x ${{ matrix.script }}

      - name: Build
        run: ./${{ matrix.script }}